const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
if(!SUPABASE_URL||!SERVICE_KEY)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');
const H={apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json'};
const now=new Date(),nowIso=now.toISOString();
const enc=v=>encodeURIComponent(String(v??''));
async function sb(path,{method='GET',body,prefer}={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:{...H,...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||`Supabase ${r.status}: ${String(t).slice(0,220)}`);return d}
async function rpc(name,body={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:H,body:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||`RPC ${r.status}: ${String(t).slice(0,220)}`);return d}
function chicagoParts(d=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${parts.year}-${parts.month}-${parts.day}`,hour:Number(parts.hour),minute:Number(parts.minute)}}
async function users(){const [p,o]=await Promise.all([sb('marketplace_scan_profiles?select=user_id&limit=5000'),sb('seller_orders?select=user_id&order=order_date.desc&limit=5000')]);return [...new Set([...(p||[]),...(o||[])].map(x=>x.user_id).filter(Boolean))]}
async function existing(uid,key){const r=await sb(`collectish_alerts?select=*&user_id=eq.${enc(uid)}&alert_key=eq.${enc(key)}&limit=1`);return r?.[0]||null}
async function upsertAlert(uid,key,{category='operational',severity='warning',title,message,actionScreen='admin',metadata={}}){const old=await existing(uid,key);if(!old){await sb('collectish_alerts',{method:'POST',body:[{user_id:uid,alert_key:key,category,severity,title,message,action_screen:actionScreen,metadata_json:metadata,first_seen_at:nowIso,last_seen_at:nowIso,updated_at:nowIso,occurrence:1}],prefer:'return=minimal'});return 'opened'}const reopened=Boolean(old.resolved_at);await sb(`collectish_alerts?id=eq.${enc(old.id)}`,{method:'PATCH',body:{category,severity,title,message,action_screen:actionScreen,metadata_json:metadata,last_seen_at:nowIso,resolved_at:null,updated_at:nowIso,...(reopened?{first_seen_at:nowIso,occurrence:Number(old.occurrence||1)+1}:{})},prefer:'return=minimal'});return reopened?'reopened':'active'}
async function resolveAlert(uid,key){await sb(`collectish_alerts?user_id=eq.${enc(uid)}&alert_key=eq.${enc(key)}&resolved_at=is.null`,{method:'PATCH',body:{resolved_at:nowIso,updated_at:nowIso},prefer:'return=minimal'})}
async function state(uid,key){const r=await sb(`collectish_alert_state?select=value_json&user_id=eq.${enc(uid)}&state_key=eq.${enc(key)}&limit=1`);return r?.[0]?.value_json||null}
async function saveState(uid,key,value){await sb('collectish_alert_state?on_conflict=user_id,state_key',{method:'POST',body:[{user_id:uid,state_key:key,value_json:value,updated_at:nowIso}],prefer:'resolution=merge-duplicates,return=minimal'})}
async function marketplace(uid){const since=new Date(Date.now()-3*3600000).toISOString();const rows=await sb(`collector_jobs?select=status,error_message,completed_at,progress_json,payload_json&user_id=eq.${enc(uid)}&source=eq.marketplace&action=eq.scan_set&completed_at=gte.${enc(since)}&status=in.(completed,failed)&order=completed_at.desc&limit=250`);const all=rows||[];const canary=all.find(x=>x.status==='completed'&&(x.progress_json?.circuitBreakerCanary===true||x.payload_json?.circuitBreakerCanary===true));const boundary=canary?.completed_at?new Date(canary.completed_at).getTime():null;const term=boundary?all.filter(x=>new Date(x.completed_at||0).getTime()>=boundary):all;const failed=term.filter(x=>x.status==='failed'),completed=term.filter(x=>x.status==='completed');const mismatch=failed.filter(x=>/Set filter mismatch/i.test(String(x.error_message||x.progress_json?.detail||''))).length;const http500=failed.filter(x=>/HTTP\s+500/i.test(String(x.error_message||x.progress_json?.detail||''))).length;const rate=term.length?failed.length/term.length:0;const open=mismatch>=2||http500>=5||(term.length>=6&&rate>=.4);const key='ops:marketplace-circuit-breaker';if(open)await upsertAlert(uid,key,{severity:'critical',title:'Marketplace scans need attention',message:`Automatic Marketplace admission is paused: ${failed.length} failed / ${completed.length} completed in the active window (${mismatch} set-filter mismatches).`,metadata:{failed:failed.length,completed:completed.length,mismatch,http500,failureRate:rate,windowHours:3}});else await resolveAlert(uid,key);
 const queued=await sb(`collector_jobs?select=job_id&user_id=eq.${enc(uid)}&source=eq.marketplace&action=eq.scan_set&status=eq.queued&or=(available_at.is.null,available_at.lte.${enc(nowIso)})&limit=5`);const c=await sb(`collectors?select=last_seen_at,status,app_version&user_id=eq.${enc(uid)}&collector_id=eq.00000000-0000-4000-8000-000000000001&limit=1`);const last=c?.[0]?.last_seen_at?new Date(c[0].last_seen_at).getTime():0;const stalled=(queued||[]).length>0&&(!last||Date.now()-last>30*60000);const stallKey='ops:marketplace-worker-stalled';if(stalled)await upsertAlert(uid,stallKey,{severity:'critical',title:'Marketplace worker appears stalled',message:`${(queued||[]).length}+ runnable Marketplace jobs are waiting and the cloud worker has not checked in for more than 30 minutes.`,metadata:{lastSeenAt:c?.[0]?.last_seen_at||null,version:c?.[0]?.app_version||null}});else await resolveAlert(uid,stallKey)}
async function freshness(uid){const [syp,scout]=await Promise.all([sb(`syp_products?select=collected_at&user_id=eq.${enc(uid)}&order=collected_at.desc&limit=1`),sb(`scout_opportunities_v5_cache?select=v5_computed_at&user_id=eq.${enc(uid)}&order=v5_computed_at.desc&limit=1`)]);const sypAt=syp?.[0]?.collected_at?new Date(syp[0].collected_at).getTime():0,scoutAt=scout?.[0]?.v5_computed_at?new Date(scout[0].v5_computed_at).getTime():0;const sypKey='ops:syp-stale',scoutKey='ops:scout-rankings-stale';if(!sypAt||Date.now()-sypAt>36*3600000)await upsertAlert(uid,sypKey,{severity:'warning',title:'SYP data is stale',message:'SYP has not produced a fresh captured dataset in more than 36 hours.',actionScreen:'syp',metadata:{latestCollectedAt:syp?.[0]?.collected_at||null}});else await resolveAlert(uid,sypKey);if(!scoutAt||Date.now()-scoutAt>3*3600000)await upsertAlert(uid,scoutKey,{severity:'warning',title:'Scout rankings are stale',message:'Scout v5 rankings have not refreshed in more than 3 hours.',actionScreen:'scout',metadata:{latestComputedAt:scout?.[0]?.v5_computed_at||null}});else await resolveAlert(uid,scoutKey)}
async function syncFailures(uids){const since=new Date(Date.now()-24*3600000).toISOString();const bad=await sb(`mtgjson_sync_state?select=feed,status,last_started_at,last_completed_at,detail&status=eq.failed&last_started_at=gte.${enc(since)}&limit=20`);for(const uid of uids){const activeKeys=new Set();for(const r of bad||[]){const key=`ops:sync:${r.feed}`;activeKeys.add(key);await upsertAlert(uid,key,{severity:'warning',title:`${r.feed} sync failed`,message:`The ${r.feed} pipeline reported a failure and may require attention.`,metadata:{feed:r.feed,lastStartedAt:r.last_started_at,lastCompletedAt:r.last_completed_at,detail:r.detail||{}}})}const prior=await sb(`collectish_alerts?select=alert_key&user_id=eq.${enc(uid)}&category=eq.operational&alert_key=like.ops%3Async%3A*&resolved_at=is.null&limit=100`);for(const a of prior||[])if(!activeKeys.has(a.alert_key))await resolveAlert(uid,a.alert_key)}}
async function newOrders(uid){const local=chicagoParts();let slot=null;if(local.hour===8)slot='morning';else if(local.hour===17)slot='evening';if(!slot)return;const key='seller-order-check';const st=await state(uid,key)||{};if(st.date===local.date&&st.slot===slot)return;const latest=await sb(`seller_orders?select=order_date&user_id=eq.${enc(uid)}&order=order_date.desc&limit=1`);const latestAt=latest?.[0]?.order_date||null;if(!st.watermark){await saveState(uid,key,{date:local.date,slot,watermark:latestAt,checkedAt:nowIso});return}const rows=await sb(`seller_orders?select=order_number,order_date,gross_amount,order_fulfillment&user_id=eq.${enc(uid)}&order_date=gt.${enc(st.watermark)}&order=order_date.asc&limit=200`);const nextWatermark=rows?.length?rows[rows.length-1].order_date:(latestAt||st.watermark);await saveState(uid,key,{date:local.date,slot,watermark:nextWatermark,checkedAt:nowIso});if(!rows?.length)return;const gross=rows.reduce((n,x)=>n+Number(x.gross_amount||0),0);await upsertAlert(uid,`business:new-orders:${local.date}:${slot}`,{category:'business',severity:'info',title:`${rows.length} new Seller order${rows.length===1?'':'s'}`,message:`Collectish found ${rows.length} new normalized order${rows.length===1?'':'s'} since the previous check${gross?` totaling $${gross.toFixed(2)} gross`:''}.`,actionScreen:'seller',metadata:{count:rows.length,gross,firstOrderAt:rows[0].order_date,lastOrderAt:rows[rows.length-1].order_date}})}
async function expireBusiness(uid){const cutoff=new Date(Date.now()-48*3600000).toISOString();await sb(`collectish_alerts?user_id=eq.${enc(uid)}&category=eq.business&resolved_at=is.null&last_seen_at=lt.${enc(cutoff)}`,{method:'PATCH',body:{resolved_at:nowIso,updated_at:nowIso},prefer:'return=minimal'})}
async function delvinParity(uids){const health=await rpc('ask_delvin_surface_parity_health_v1',{p_minutes:60,p_pair_window_seconds:300}).catch(()=>null);if(!health)return{status:'UNAVAILABLE',mismatchCount:0};const status=String(health.status||''),mismatches=Array.isArray(health.mismatches)?health.mismatches:[],key='ops:delvin-web-discord-parity';if(status==='MISMATCH'){const sample=mismatches[0]||{};for(const uid of uids)await upsertAlert(uid,key,{severity:'critical',title:'Delvin web/Discord parity mismatch',message:`${Number(health.mismatch_count||mismatches.length)} paired Ask result${Number(health.mismatch_count||mismatches.length)===1?'':'s'} disagreed across web and Discord in the last ${Number(health.window_minutes||60)} minutes.`,metadata:{status,mismatchCount:Number(health.mismatch_count||mismatches.length),matchedCount:Number(health.matched_count||0),pairedCount:Number(health.paired_count||0),pairWindowSeconds:Number(health.pair_window_seconds||300),route:sample.route||null,questionHash:sample.question_hash||null,webResultId:sample.web_result_id||null,discordResultId:sample.discord_result_id||null,webRowCount:sample.web_row_count??null,discordRowCount:sample.discord_row_count??null}})}else if(status==='HEALTHY'){for(const uid of uids)await resolveAlert(uid,key)}return{status,mismatchCount:Number(health.mismatch_count||0),pairedCount:Number(health.paired_count||0)}}
const uids=await users();for(const uid of uids){await marketplace(uid);await freshness(uid);await newOrders(uid);await expireBusiness(uid)}await syncFailures(uids);const parity=await delvinParity(uids);console.log(JSON.stringify({checkedAt:nowIso,users:uids.length,chicago:chicagoParts(),delvinParity:parity},null,2));