const URL=process.env.SUPABASE_URL, KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const RECENT_SET_COUNT=Math.max(0,Math.min(20,Number(process.env.COLLECTISH_EDHREC_RECENT_SETS||8)));
if(!URL||!KEY)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
const H={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const BASE='https://edhrec.com';let build={id:null,at:0};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function sb(path,opt={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...opt,headers:{...H,...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null}
async function text(url,opt={}){const r=await fetch(url,{...opt,headers:{'User-Agent':'collectish/0.8 (+https://joe-nasti.github.io/marketplacescout/)','Accept':'application/json,text/html;q=0.9,*/*;q=0.8',...(opt.headers||{})}});if(!r.ok)throw new Error(`EDHREC HTTP ${r.status}: ${new URL(url).pathname}`);return r.text()}
async function json(url,opt={}){return JSON.parse(await text(url,opt))}
async function discover(force=false){if(!force&&build.id&&Date.now()-build.at<21600000)return build.id;const h=await text(`${BASE}/top`),m=h.match(/"buildId"\s*:\s*"([^"]+)"/)||h.match(/\/_next\/static\/([^/]+)\/_buildManifest\.js/);if(!m)throw new Error('Could not discover EDHREC build ID');build={id:m[1],at:Date.now()};return build.id}
async function next(path,q=''){let b=await discover();try{return await json(`${BASE}/_next/data/${b}${path}.json${q?`?${q}`:''}`)}catch{b=await discover(true);return json(`${BASE}/_next/data/${b}${path}.json${q?`?${q}`:''}`)}}
const lists=d=>d?.pageProps?.data?.container?.json_dict?.cardlists||[];
async function top(period){const d=await next(`/top/${period}`,`slug=${period}`);return (lists(d)[0]?.cardviews||[]).map((c,i)=>({...c,rank:Number(c.rank||i+1)}))}
async function commanders(period){const d=await next(`/commanders/${period}`,`slug=${period}`);return (lists(d)[0]?.cardviews||[]).map((c,i)=>({...c,rank:Number(c.rank||i+1)}))}
async function sets(){return (await next('/sets'))?.pageProps?.data?.data||[]}
async function setPage(code){const d=await next(`/sets/${code}`,`setCode=${code}`);return{header:d?.pageProps?.data?.header||code,cardlists:lists(d)}}
const norm=(name='')=>String(name).normalize('NFKD').replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/\s+/g,' ').trim().toLowerCase();
const suffixes=['borderless','showcase','extended art','retro frame','surge foil','galaxy foil','serialized','foil etched','etched','alternate art','halo foil'];
function baseName(name=''){let s=String(name).trim();for(;;){const m=s.match(/^(.*)\s+\(([^()]*)\)$/);if(!m||!suffixes.some(x=>m[2].toLowerCase().includes(x)))break;s=m[1].trim()}return s}
function role(header=''){const h=String(header).toLowerCase();if(h.startsWith('commanders')&&h.includes('reprint'))return'commander_reprint';if(h.startsWith('commanders'))return'commander';if(h.includes('reprints'))return'reprint';if(h.startsWith('cards'))return'card';return'set_card'}
function obs(sourceType,period,setCode,setName,roleName,rank,c){return{sourceType,period,setCode,setName,role:roleName,rank:Number(rank||0),cardKey:norm(c.name),name:c.name,numDecks:Number(c.num_decks||0),potentialDecks:Number(c.potential_decks||0),inclusionRate:Number(c.potential_decks||0)>0?Number(c.num_decks||0)/Number(c.potential_decks):null}}
function signals(cur,prev=[]){const pm=new Map(prev.map(x=>[`${x.sourceType}|${x.period||x.setCode}|${x.role}|${x.cardKey}`,x])),m=new Map();for(const o of cur){if(!m.has(o.cardKey))m.set(o.cardKey,{name:o.name,cardKey:o.cardKey,setRoles:[],reprintRisk:false});const c=m.get(o.cardKey);if(o.sourceType==='set'){c.setRoles.push({setCode:o.setCode,setName:o.setName,role:o.role,numDecks:o.numDecks});if(o.role.includes('reprint'))c.reprintRisk=true}if(o.sourceType==='top'&&o.period==='week'){c.weekRank=o.rank;c.weekDecks=o.numDecks;c.inclusionRate=o.inclusionRate;const p=pm.get(`top|week|card|${o.cardKey}`);if(p){c.rankChange=Number(p.rank)-Number(o.rank);c.deckChangePct=p.numDecks?(o.numDecks-p.numDecks)/p.numDecks:null}}if(o.sourceType==='top'&&o.period==='month'){c.monthRank=o.rank;c.monthDecks=o.numDecks}if(o.sourceType==='commander'&&o.period==='week'){c.commanderWeekRank=o.rank;c.commanderWeekDecks=o.numDecks;const p=pm.get(`commander|week|commander|${o.cardKey}`);if(p){c.commanderRankChange=Number(p.rank)-Number(o.rank);c.commanderDeckChangePct=p.numDecks?(o.numDecks-p.numDecks)/p.numDecks:null}}}for(const c of m.values()){let signal='Low EDH signal',score=0;if(c.reprintRisk){signal='Reprint risk';score=90}else if(c.commanderWeekRank<=25&&(c.commanderRankChange>=10||c.commanderDeckChangePct>=.15)){signal='Commander breakout';score=95}else if(c.weekRank&&(c.rankChange>=50||c.deckChangePct>=.25)){signal='Surging';score=90}else if(c.weekRank&&(c.rankChange>=20||c.deckChangePct>=.10)){signal='Rising';score=75}else if(c.weekRank<=100){signal='Popular / stable';score=55}else if(c.commanderWeekRank<=100){signal='Commander demand';score=60}c.signal=signal;c.signalScore=score}return Object.fromEntries(m)}
async function allRows(){const out=[];for(let off=0;off<50000;off+=5000){const x=await sb(`marketplace_scan_rows?select=id,user_id,product_name,scryfall_id&order=id.desc&limit=5000&offset=${off}`);out.push(...x);if(x.length<5000)break}return out}
async function patch(ids,body){for(let i=0;i<ids.length;i+=300){const chunk=ids.slice(i,i+300);await sb(`marketplace_scan_rows?id=in.(${chunk.join(',')})`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}}
const users=await sb('marketplace_scan_rows?select=user_id&limit=1');const userId=users?.[0]?.user_id;if(!userId)throw new Error('No marketplace user found');
const prevCap=await sb(`source_captures?select=payload_json,captured_at&user_id=eq.${userId}&source=eq.edhrec&capture_type=eq.commander_demand&order=captured_at.desc&limit=1`);const prevObs=prevCap?.[0]?.payload_json?.observations||[];
const rows=[];for(const p of['week','month']){for(const c of await top(p))rows.push(obs('top',p,null,null,'card',c.rank,c));await sleep(250)}for(const p of['week','month']){for(const c of await commanders(p))rows.push(obs('commander',p,null,null,'commander',c.rank,c));await sleep(250)}
const available=await sets(),selected=[];for(const s of available.slice(0,RECENT_SET_COUNT)){const page=await setPage(s.code);selected.push({code:s.code,name:page.header||s.name||s.code});for(const l of page.cardlists||[])for(const c of l.cardviews||[])rows.push(obs('set',null,s.code,page.header||s.name,role(l.header),c.rank,c));await sleep(300)}
const sig=signals(rows,prevObs),capturedAt=new Date().toISOString();
const market=await allRows(),byName=new Map();for(const r of market){const k=norm(baseName(r.product_name));if(!byName.has(k))byName.set(k,[]);byName.get(k).push(r.id)}
let cardsMatched=0,rowsUpdated=0;for(const s of Object.values(sig)){const ids=byName.get(s.cardKey)||[];if(!ids.length)continue;cardsMatched++;rowsUpdated+=ids.length;await patch(ids,{edhrec_rank:s.weekRank||null,commander_demand_score:s.signalScore,edhrec_signal:s.signal,edhrec_signal_score:s.signalScore,edhrec_observed_at:capturedAt})}
const payload={version:1,observations:rows,signals:sig,selectedSets:selected,counts:{observations:rows.length,cards:Object.keys(sig).length,sets:selected.length,cardsMatched,rowsUpdated}};
await sb('source_captures',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{user_id:userId,source:'edhrec',capture_type:'commander_demand',source_key:capturedAt,content_type:'application/json',payload_json:payload,metadata_json:{collector:'cloud',recentSetCount:RECENT_SET_COUNT}}])});
console.log(JSON.stringify({capturedAt,...payload.counts}));