import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const H=(t:string)=>({apikey:t===S&&S?S:A,Authorization:`Bearer ${t}`,'Content-Type':'application/json'});
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const endpoints=[
  {url:'https://api.mtgstocks.com/interests/market/regular',price_type:'market',finish:'regular'},
  {url:'https://api.mtgstocks.com/interests/market/foil',price_type:'market',finish:'foil'},
  {url:'https://api.mtgstocks.com/interests/average/regular',price_type:'average',finish:'regular'},
  {url:'https://api.mtgstocks.com/interests/average/foil',price_type:'average',finish:'foil'}
];
async function serviceAuth(t:string){if(!t)return false;if(S&&t===S)return true;try{const r=await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}});return r.ok}catch{return false}}
async function rest(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(S),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function sha(v:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getJson(url:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'CollectishSignals/1.0 (+MTG market discovery)','Accept':'application/json'}});if(!r.ok)throw Error(`MTGStocks API ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
async function getText(url:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'CollectishSignals/1.0 (+MTG market discovery)','Accept':'text/html'}});if(!r.ok)throw Error(`Source HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
function htmlText(s:string){return String(s||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').trim()}
async function owner(){const rows=await rest('source_captures?select=user_id&capture_type=eq.feed_subscription&source=eq.MTGStocks&limit=1');const id=String(rows?.[0]?.user_id||'');if(!UUID.test(id))throw Error('MTGStocks Signals owner not found');return id}
function normalizeInterest(x:any,e:any,date:string){const p=x?.print||{};return{print_id:String(p.id||''),card_name:String(p.name||'').trim(),set_name:p.set_name||null,set_code:p.abbreviation||null,set_id:p.set_id||null,foil:!!x.foil,interest_type:String(x.interest_type||'').toLowerCase(),pct_change:Number(x.percentage),new_price:Number(x.present_price),old_price:Number(x.past_price),price_type:e.price_type,finish:e.finish,date,url:p.id?`https://www.mtgstocks.com/prints/${p.id}`:'https://www.mtgstocks.com/interests',discovery_source:'api'}}
async function telegramFallback(){const html=await getText('https://t.me/s/mtgstocks'),blocks=[...html.matchAll(/<div class="tgme_widget_message_text[^>]*>([\s\S]*?)<\/div>/gi)].map(m=>htmlText(m[1])).filter(x=>/^Interests of /i.test(x));const recent=blocks.slice(-5),items:any[]=[];for(const block of recent){const lines=block.split(/\n+/).map(x=>x.trim()).filter(Boolean),date=(lines[0].match(/^Interests of (.+?) are online\.?$/i)||[])[1]||lines[0];for(const line of lines.slice(1)){const m=line.match(/^(.+?)\s+\(([^()]+)\)\s+\$([\d,.]+)\s+\(([▲▼])([\d,.]+)%\)$/);if(!m)continue;items.push({print_id:`telegram:${m[2]}:${m[1]}`,card_name:m[1].trim(),set_name:null,set_code:m[2],set_id:null,foil:null,interest_type:'daily_announced',pct_change:(m[4]==='▼'?-1:1)*Number(m[5].replace(/,/g,'')),new_price:Number(m[3].replace(/,/g,'')),old_price:null,price_type:'mtgstocks_default',finish:'unknown',date,url:'https://www.mtgstocks.com/interests',discovery_source:'telegram_announcement'})}}return items}
async function scout(ownerId:string,item:any){const names=[item.card_name,item.card_name.replace(/\s*\([^)]*\)\s*$/,'').trim()].filter(Boolean);for(const name of [...new Set(names)]){let rows=await rest(`scout_opportunities_v5_cache?select=sku_id,product_id,product_name,set_name,set_code,printing,condition,language,promoted_score,promoted_grade,opportunity_score,grade,direct_low,sku_market_price,avg_daily_qty_sold,sales_rank,scryfall_id&user_id=eq.${ownerId}&product_name=eq.${encodeURIComponent(name)}&order=promoted_score.desc.nullslast,opportunity_score.desc.nullslast&limit=12`).catch(()=>[]);if(item.set_code){const same=rows.filter((r:any)=>String(r.set_code||'').toLowerCase()===String(item.set_code||'').toLowerCase());if(same.length)rows=same}else if(item.set_name){const same=rows.filter((r:any)=>String(r.set_name||'').toLowerCase()===String(item.set_name||'').toLowerCase());if(same.length)rows=same}if(rows.length)return rows}return[]}
Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);
  const caller=bearer(req);if(!caller||!(await serviceAuth(caller)))return J({error:'Service authentication required'},401);if(!S)return J({error:'Service role unavailable'},500);
  try{
    const ownerId=await owner(),all:any[]=[],errors:any[]=[];
    for(const e of endpoints){try{const d=await getJson(e.url),date=String(d?.date||'');for(const x of Array.isArray(d?.interests)?d.interests:[]){const item=normalizeInterest(x,e,date);if(item.print_id&&item.card_name&&Number.isFinite(item.pct_change))all.push(item)}}catch(err){errors.push({source:e.url,error:(err as Error).message})}}
    let fallback=false;if(!all.length){try{all.push(...await telegramFallback());fallback=true}catch(err){errors.push({source:'https://t.me/s/mtgstocks',error:(err as Error).message})}}
    const dedupe=new Map<string,any>();for(const x of all){const k=`${x.price_type}:${x.finish}:${x.interest_type}:${x.print_id}`;if(!dedupe.has(k))dedupe.set(k,x)}const items=[...dedupe.values()].sort((a,b)=>Math.abs(b.pct_change)-Math.abs(a.pct_change)).slice(0,120);
    let inserted=0,unchanged=0,matched=0;const report:any[]=[];
    for(const item of items){const matches=await scout(ownerId,item);if(matches.length)matched++;const best=matches[0]||null;const payload={...item,scout_match_count:matches.length,scout_best:best?{sku_id:best.sku_id,product_id:best.product_id,product_name:best.product_name,set_name:best.set_name,set_code:best.set_code,printing:best.printing,condition:best.condition,grade:best.promoted_grade||best.grade,score:best.promoted_score??best.opportunity_score,direct_low:best.direct_low,market_price:best.sku_market_price,avg_daily_qty_sold:best.avg_daily_qty_sold,sales_rank:best.sales_rank,scryfall_id:best.scryfall_id}:null,scout_matches:matches.slice(0,5)};const hash=await sha(JSON.stringify(payload)),key=`${item.price_type}:${item.finish}:${item.interest_type}:${item.print_id}`;const prev=await rest(`source_captures?select=content_hash&user_id=eq.${ownerId}&source=eq.MTGStocks&capture_type=eq.discovery_candidate&source_key=eq.${encodeURIComponent(key)}&order=captured_at.desc&limit=1`).catch(()=>[]);if(prev?.[0]?.content_hash===hash){unchanged++;continue}await rest('source_captures',{method:'POST',prefer:'return=minimal',body:{user_id:ownerId,source:'MTGStocks',capture_type:'discovery_candidate',source_key:key,content_type:'application/mtgstocks-interest+json',payload_json:payload,payload_text:`${item.card_name} ${item.interest_type} ${item.pct_change}%`,content_hash:hash,metadata_json:{kind:'scout_candidate',signal_weight:'discovery_only',interest_type:item.interest_type,price_type:item.price_type,finish:item.finish,discovery_source:item.discovery_source,scout_matched:!!best,scout_grade:best?.promoted_grade||best?.grade||null,scout_score:best?.promoted_score??best?.opportunity_score??null}}});inserted++;if(report.length<25)report.push({card:item.card_name,set:item.set_code||item.set_name,type:item.interest_type,pct:item.pct_change,source:item.discovery_source,scout_grade:best?.promoted_grade||best?.grade||null,scout_score:best?.promoted_score??best?.opportunity_score??null})}
    return J({ok:true,api_rows:all.length,candidates:items.length,inserted,unchanged,scout_matched:matched,fallback,errors,report});
  }catch(e){return J({error:(e as Error).message},502)}
});
