import { markdown } from './markdown.js';
import { registerComponent } from '../../core/lifecycle.js';

// Ask Collectish — grounded cross-source assistant + non-destructive UI actions.
(() => {
  const cfg=window.COLLECTISH_CONFIG;
  const ENDPOINT=`${String(cfg?.supabaseUrl||'').replace(/\/$/,'')}/functions/v1/ask-collectish`;
  const CONV_KEY='askCollectishConversationId',FILTER_KEY='askCollectishUiFilters';
  let panel=null,messages=null,input=null,statusEl=null,contextEl=null,conversationId=localStorage.getItem(CONV_KEY)||null,busy=false,healthChecked=false,historyLoaded=false,lastEntity={};
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const money=n=>n==null?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
  function session(){try{return JSON.parse(localStorage.getItem('collectishSession')||'null')}catch{return null}}
  async function accessToken(){try{await window.rest?.('scout_opportunities_v5?select=sku_id&limit=1')}catch{}return session()?.token||null}
  async function api(body){const token=await accessToken();if(!token)throw Error('Sign in required');const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let d;try{d=t?JSON.parse(t):{}}catch{d={error:t||`HTTP ${r.status}`}}if(!r.ok)throw Error(d?.error||`Ask Collectish HTTP ${r.status}`);return d}
  async function rpc(name,body={}){return window.rest(`rpc/${name}`,{method:'POST',body})}
  function activeScreen(){const id=document.querySelector('.cx-page.active')?.id||'';return id.replace(/^cx/,'').toLowerCase()||'unknown'}
  function currentContext(){
    const screen=activeScreen(),out={screen};
    if(screen==='scout'){
      const card=document.querySelector('#cxParityCards .cx-scout-card.selected');
      const sku=card?.dataset?.sku||lastEntity.scout?.sku_id||null;
      const name=card?.querySelector('.cx-scout-card-body>strong')?.textContent?.trim()||document.querySelector('#cxParityDetail .cx-v5-title .cx-section-title')?.textContent?.trim()||lastEntity.scout?.product_name_hint||null;
      const href=document.querySelector('#cxParityDetail a[href*="tcgplayer.com/product/"]')?.getAttribute('href')||'';
      const product=(/\/product\/(\d+)/.exec(href)||[])[1]||lastEntity.scout?.product_id||null;
      return {...out,sku_id:sku,product_id:product,product_name_hint:name};
    }
    if(screen==='syp'&&lastEntity.syp)return {...out,...lastEntity.syp};
    if(screen==='seller'&&lastEntity.seller)return {...out,...lastEntity.seller};
    if(screen==='inventory'&&lastEntity.inventory)return {...out,...lastEntity.inventory};
    return out;
  }
  async function resolvedContext(){const c=currentContext();if(c.screen!=='scout'||c.product_id||!c.sku_id)return c;try{const rows=await rest(`scout_opportunities_v5?select=product_id,product_name&sku_id=eq.${encodeURIComponent(c.sku_id)}&limit=1`);if(rows?.[0])return {...c,product_id:rows[0].product_id,product_name_hint:rows[0].product_name||c.product_name_hint}}catch{}return c}
  function contextLabel(c=currentContext()){if(c.screen==='scout'&&c.product_name_hint)return `Scout · ${c.product_name_hint}`;if(c.screen==='syp'&&c.sku_id)return `SYP · SKU ${c.sku_id}`;if(c.screen==='seller'&&c.order_id)return `Seller · Order ${c.order_id}`;if(c.screen==='inventory'&&c.sku_id)return `Inventory · SKU ${c.sku_id}`;return `${c.screen[0]?.toUpperCase()||''}${c.screen.slice(1)} context`}
  function setStatus(t,k=''){if(statusEl){statusEl.textContent=t;statusEl.dataset.kind=k}}
  function syncContext(){if(contextEl){const c=currentContext();contextEl.textContent=contextLabel(c);contextEl.title=JSON.stringify(c)}}
  function bubble(role,text,meta=''){
    if(!messages)return null;
    const w=document.createElement('div');w.className=`cx-ask-msg cx-ask-${role}`;
    const b=document.createElement('div');b.className='cx-ask-msg-body';
    if(role==='assistant'){b.innerHTML=markdown(text);b.dataset.md='1'}else b.textContent=text;
    w.append(b);
    if(meta){const s=document.createElement('small');s.textContent=meta;w.append(s)}
    messages.append(w);messages.scrollTop=messages.scrollHeight;
    document.dispatchEvent(new CustomEvent('collectish:ask-message-rendered',{detail:{role,element:b}}));
    return w;
  }
  function thinking(){const b=bubble('assistant','Thinking with Collectish data…');b?.classList.add('cx-ask-thinking');return b}
  function starter(t){const b=document.createElement('button');b.type='button';b.className='cx-ask-starter';b.textContent=t;b.onclick=()=>send(t);return b}
  function starters(){const h=document.getElementById('cxAskStarters');if(!h)return;h.innerHTML='';const c=currentContext();let a=[];if(c.screen==='scout'&&c.sku_id)a=['Why this score?','Would you buy this?','Biggest risks?','What changed?'];else if(c.screen==='scout')a=['Best Scout opportunities today','Power search','Strong signals below 70','What changed today?'];else if(c.screen==='seller')a=['How much did I sell last month?','What did I net after fees?','Top revenue cards','Compare Direct vs non-Direct'];else if(c.screen==='syp')a=c.sku_id?['What changed for this SKU?','How long has it been active?','Show its history','Is it still eligible?']:['What changed on SYP today?','First seen this week','Active max quantity ≥ 20','Biggest changes since yesterday'];else if(c.screen==='inventory')a=['What inventory is stale?','What do I own that Scout likes?','What should I reprice?'];else a=['System freshness','Seller coverage','SYP coverage','AI diagnostics'];a.forEach(x=>h.append(starter(x)))}
  async function health(){if(healthChecked)return;healthChecked=true;setStatus('Checking AI…');try{const d=await api({action:'health'});setStatus(d.ok?`${d.model||'AI'} · ${d.version||'v2'}`:'AI unavailable',d.ok?'ok':'bad');if(!d.ok)bubble('system',d.error||'Health check failed')}catch(e){setStatus('AI unavailable','bad');bubble('system',e.message||String(e))}}
  function newConversation(){conversationId=null;historyLoaded=true;localStorage.removeItem(CONV_KEY);messages.innerHTML='<div class="cx-ask-welcome"><strong>New conversation.</strong><span>Current screen context attaches automatically. It will be saved to your Collectish account after your first message.</span></div>';starters();setStatus('New conversation')}
  async function touchConversation(){if(!conversationId)return;try{await window.rest(`ask_collectish_conversations?id=eq.${encodeURIComponent(conversationId)}`,{method:'PATCH',body:{updated_at:new Date().toISOString()}})}catch{}}
  async function loadConversation(id,{quiet=false}={}){if(!id)return false;const rows=await window.rest(`ask_collectish_messages?select=role,content,metadata,created_at&conversation_id=eq.${encodeURIComponent(id)}&order=created_at.asc&limit=250`);if(!Array.isArray(rows))return false;conversationId=id;localStorage.setItem(CONV_KEY,id);messages.innerHTML='';if(!rows.length)messages.innerHTML='<div class="cx-ask-welcome"><strong>Saved conversation.</strong><span>No messages were found yet.</span></div>';for(const m of rows){const tools=Array.isArray(m.metadata?.tools)&&m.metadata.tools.length?`Grounded with: ${m.metadata.tools.join(', ')}`:'';bubble(m.role==='assistant'?'assistant':m.role==='user'?'user':'system',m.content,tools)}if(!quiet)setStatus('Conversation resumed','ok');return true}
  async function restoreConversation(){if(historyLoaded)return;historyLoaded=true;try{if(conversationId){try{if(await loadConversation(conversationId,{quiet:true})){setStatus('Conversation restored','ok');return}}catch{}conversationId=null;localStorage.removeItem(CONV_KEY)}const rows=await window.rest('ask_collectish_conversations?select=id,title,updated_at,created_at&order=updated_at.desc&limit=1');if(rows?.[0]?.id){await loadConversation(rows[0].id,{quiet:true});setStatus('Latest conversation restored','ok')}}catch(e){console.warn('Ask conversation restore failed',e)}}
  async function showHistory(){build();setStatus('Loading conversations…');try{const rows=await window.rest('ask_collectish_conversations?select=id,title,updated_at,created_at&order=updated_at.desc&limit=30');messages.innerHTML='<div class="cx-ask-welcome"><strong>Recent Ask sessions</strong><span>Saved to your Collectish account and available after local site data is cleared.</span></div>';if(!rows?.length){bubble('system','No saved conversations yet.');setStatus('No saved conversations');return}for(const c of rows){const b=document.createElement('button');b.type='button';b.className='cx-ask-starter';const when=new Date(c.updated_at||c.created_at);b.textContent=`${c.title||'Untitled conversation'} · ${when.toLocaleString()}`;b.onclick=async()=>{setStatus('Restoring conversation…');try{await loadConversation(c.id)}catch(e){bubble('system',e.message||String(e));setStatus('Restore failed','bad')}};messages.append(b)}messages.scrollTop=0;setStatus(`${rows.length} saved conversation${rows.length===1?'':'s'}`,'ok')}catch(e){bubble('system',e.message||String(e));setStatus('History unavailable','bad')}}
  function build(){if(panel)return;const root=document.createElement('div');root.id='cxAskCollectish';root.className='cx-ask-root';root.hidden=true;root.innerHTML=`<div class="cx-ask-backdrop" data-ask-close></div><section class="cx-ask-panel" role="dialog" aria-modal="true"><header class="cx-ask-head"><div class="cx-ask-brand"><span class="cx-ask-mark">✦</span><div><strong>Ask Collectish</strong><small>Scout · Seller · SYP · Inventory · Vendors</small></div></div><div class="cx-ask-head-actions"><button class="cx-ask-history" type="button">History</button><button class="cx-ask-pref" type="button">Settings</button><button class="cx-ask-new" type="button">New</button><button class="cx-ask-close" type="button">×</button></div></header><div class="cx-ask-context-row"><span id="cxAskContext"></span><span id="cxAskStatus">Not checked</span></div><div id="cxAskStarters" class="cx-ask-starters"></div><div id="cxAskMessages" class="cx-ask-messages"><div class="cx-ask-welcome"><strong>Ask across Collectish.</strong><span>I’ll use controlled Collectish tools, state coverage, and keep UI actions separate from analysis.</span></div></div><div class="cx-ask-investigate-row"><button id="cxAskInvestigate" class="cx-ask-investigate" type="button">Investigate current card</button><span id="cxAskInvestigateState"></span></div><form id="cxAskForm" class="cx-ask-compose"><textarea id="cxAskInput" rows="1" placeholder="Ask Collectish or type a power search…"></textarea><button type="submit">↑</button></form></section>`;document.body.append(root);panel=root;messages=root.querySelector('#cxAskMessages');input=root.querySelector('#cxAskInput');statusEl=root.querySelector('#cxAskStatus');contextEl=root.querySelector('#cxAskContext');root.querySelectorAll('[data-ask-close],.cx-ask-close').forEach(x=>x.onclick=close);root.querySelector('.cx-ask-new').onclick=newConversation;root.querySelector('.cx-ask-history').onclick=showHistory;root.querySelector('.cx-ask-pref').onclick=preferences;root.querySelector('#cxAskForm').onsubmit=e=>{e.preventDefault();send(input.value)};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input.value)}};input.oninput=()=>{input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,110)}px`};root.querySelector('#cxAskInvestigate').onclick=investigate;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close()})}
  async function open(prefill=''){build();syncContext();starters();panel.hidden=false;document.body.classList.add('cx-ask-lock');const c=currentContext();panel.classList.toggle('cx-ask-has-card',Boolean(c.screen==='scout'&&c.sku_id));await restoreConversation();if(prefill)input.value=prefill;requestAnimationFrame(()=>input.focus());health()}
  function close(){if(panel){panel.hidden=true;document.body.classList.remove('cx-ask-lock')}}
  async function send(raw){const text=String(raw||'').trim();if(!text||busy)return;busy=true;input.value='';input.style.height='auto';bubble('user',text);const wait=thinking();setStatus('Using Collectish tools…');try{const context=await resolvedContext(),d=await api({action:'chat',message:text,conversation_id:conversationId,context});wait?.remove();conversationId=d.conversation_id||conversationId;if(conversationId)localStorage.setItem(CONV_KEY,conversationId);await touchConversation();const used=(d.tools||[]).filter(x=>x.ok&&!x.ui_action).map(x=>x.name.replace(':auto_context','')).join(', ');bubble('assistant',d.response||'No response.',used?`Grounded with: ${used}`:`Context: ${d.context_screen||context.screen}`);if(d.ui_actions?.length)await applyUiActions(d.ui_actions);setStatus(`${d.model||'AI'} · ${d.usage?.total_tokens||0} tokens`,'ok')}catch(e){wait?.remove();bubble('system',e.message||String(e));setStatus('Request failed','bad')}finally{busy=false}}
  async function preferences(){const wrap=bubble('system','Loading explicit AI preferences…');try{const p=await rpc('ask_collectish_get_preferences');wrap?.remove();const box=document.createElement('div');box.className='cx-ask-prefbox';box.innerHTML=`<strong>Ask Collectish settings</strong><label>Minimum net ROI %<input data-p="minimum_net_roi" type="number" step="1" value="${p.minimum_net_roi??''}"></label><label>Default condition<input data-p="default_condition" value="${esc(p.default_condition||'Near Mint')}"></label><label>Default language<input data-p="default_language" value="${esc(p.default_language||'English')}"></label><label>Preferred hold days<input data-p="preferred_hold_days" type="number" value="${p.preferred_hold_days??''}"></label><label>Low-value threshold $<input data-p="low_value_threshold" type="number" step="0.25" value="${p.low_value_threshold??2}"></label><label>Maximum position size<input data-p="maximum_position_size" type="number" value="${p.maximum_position_size??''}"></label><label>Fee assumption %<input data-p="fee_assumption_pct" type="number" step="0.5" value="${p.fee_assumption_pct??20}"></label><label>Scout risk tolerance<select data-p="scout_risk_tolerance"><option>conservative</option><option>balanced</option><option>aggressive</option></select></label><button type="button">Save explicit settings</button>`;box.querySelector('select').value=p.scout_risk_tolerance||'balanced';box.querySelector('button').onclick=async()=>{const v={};box.querySelectorAll('[data-p]').forEach(el=>{const val=el.value.trim();if(val!=='')v[el.dataset.p]=el.type==='number'?Number(val):val});try{await rpc('ask_collectish_save_preferences',{p_preferences:v});bubble('system','Preferences saved explicitly.');box.remove()}catch(e){bubble('system',e.message||String(e))}};messages.append(box);messages.scrollTop=messages.scrollHeight}catch(e){wrap?.remove();bubble('system',e.message||String(e))}}
  function filterState(){try{return JSON.parse(localStorage.getItem(FILTER_KEY)||'{}')}catch{return {}}}
  function saveFilterState(s){localStorage.setItem(FILTER_KEY,JSON.stringify(s))}
  async function applyUiActions(actions){for(const a of actions){try{if(a.type==='navigate'){navigate(a.screen);bubble('system',`UI action: opened ${a.screen}.`)}else if(a.type==='apply_filters'){navigate(a.screen);const s=filterState();s[a.screen]={filters:a.filters||{},sort:s[a.screen]?.sort||null};saveFilterState(s);await renderAiResults(a.screen);bubble('system',`UI action: applied Ask filters to ${a.screen}.`)}else if(a.type==='apply_sort'){const s=filterState();s[a.screen]={filters:s[a.screen]?.filters||{},sort:a.sort};saveFilterState(s);navigate(a.screen);await renderAiResults(a.screen);bubble('system',`UI action: sorted ${a.screen} by ${a.sort}.`)}else if(a.type==='open_card')await openCard(a.product_id);else if(a.type==='open_syp_item')await openSyp(a.sku_id);else if(a.type==='open_order')await openOrder(a.order_id)}catch(e){bubble('system',`UI action failed: ${e.message||e}`)}}}
  function navigate(screen){window.CollectishShell?.switchPage?.(screen)}
  async function openCard(product){navigate('scout');await sleep(0);let card=document.querySelector(`[data-product="${CSS.escape(String(product))}"]`);if(!card){try{const r=await rest(`scout_opportunities_v5?select=sku_id,product_name&product_id=eq.${encodeURIComponent(product)}&order=promoted_score.desc&limit=1`);if(r?.[0]){card=document.querySelector(`.cx-scout-card[data-sku="${CSS.escape(String(r[0].sku_id))}"]`);lastEntity.scout={product_id:String(product),sku_id:String(r[0].sku_id),product_name_hint:r[0].product_name}}}catch{}}card?.click();syncContext()}
  async function openSyp(sku){navigate('syp');lastEntity.syp={sku_id:String(sku)};await sleep(0);const q=document.getElementById('cxSypSearch');if(q){q.value=sku;q.dispatchEvent(new Event('input',{bubbles:true}));q.dispatchEvent(new Event('change',{bubbles:true}))}syncContext()}
  async function openOrder(id){navigate('seller');lastEntity.seller={order_id:String(id)};await sleep(0);const rows=[...document.querySelectorAll('#cxSeller tbody tr')],r=rows.find(x=>x.textContent.includes(String(id)));r?.click();syncContext()}
  function chipBar(screen,filters){return `<div class="cx-ai-filterbar"><span>Ask filters</span>${Object.entries(filters).map(([k,v])=>`<button data-ai-chip="${esc(k)}">${esc(k.replaceAll('_',' '))}: <b>${esc(v)}</b> ×</button>`).join('')}<button data-ai-clear>Clear</button></div>`}
  async function renderAiResults(screen){const host=document.getElementById(`cx${screen[0].toUpperCase()+screen.slice(1)}`);if(!host)return;let pane=host.querySelector('.cx-ai-filter-results');if(!pane){pane=document.createElement('section');pane.className='cx-ai-filter-results';const head=host.querySelector('.cx-page-head');head?.after(pane);if(!head)host.prepend(pane)}const st=filterState()[screen]||{filters:{}},f={...(st.filters||{})};if(st.sort&&!f.sort)f.sort=st.sort;pane.innerHTML=chipBar(screen,f)+'<div class="cx-empty">Loading Ask-filtered results…</div>';try{let d;if(screen==='scout')d=await rpc('ask_collectish_search_scout',{p_filters:f});else if(screen==='syp')d=await rpc('ask_collectish_search_syp',{p_filters:f});else if(screen==='seller')d=await rpc('ask_collectish_search_orders',{p_filters:f});else d=await rpc('ask_collectish_get_inventory_aging',{p_filters:f});renderAiRows(pane,screen,d,f)}catch(e){pane.innerHTML=chipBar(screen,f)+`<div class="cx-empty">${esc(e.message||e)}</div>`}pane.querySelectorAll('[data-ai-chip]').forEach(b=>b.onclick=()=>removeFilter(screen,b.dataset.aiChip));pane.querySelector('[data-ai-clear]')?.addEventListener('click',()=>clearFilters(screen))}
  function renderAiRows(pane,screen,d,f){const rows=d?.results||[];const coverage=d?.coverage_note||d?.coverage?.coverage_note||'';let html=chipBar(screen,f);if(coverage)html+=`<div class="cx-ai-coverage">${esc(coverage)}</div>`;if(!rows.length){html+='<div class="cx-empty">No matching rows.</div>';pane.innerHTML=html;return}html+=`<div class="cx-ai-result-count">${rows.length} Ask-filtered results</div><div class="cx-ai-result-list">${rows.slice(0,100).map(r=>{if(screen==='scout')return `<button data-open-card="${esc(r.product_id)}"><strong>${esc(r.product_name)}</strong><span>${esc(r.promoted_grade||'—')} ${r.promoted_score??'—'} · Market ${money(r.sku_market_price)} · Direct qty ${r.direct_available??'—'} · EDHREC ${r.edhrec_rank??'—'}</span></button>`;if(screen==='syp')return `<button data-open-syp="${esc(r.sku_id)}"><strong>${esc(r.product_name)}</strong><span>${esc(r.condition||'')} · ${esc(r.printing||'')} · ${esc(r.language||'')} · max ${r.current_max_quantity??r.max_quantity??'—'} · Market ${money(r.market_price)}</span></button>`;if(screen==='seller')return `<button data-open-order="${esc(r.order_number)}"><strong>Order ${esc(r.order_number)}</strong><span>${new Date(r.order_date).toLocaleDateString()} · ${esc(r.fulfillment||'')} · Gross ${money(r.gross)} · Fees ${money(r.fees)} · Net ${money(r.net)}</span></button>`;return `<button><strong>${esc(r.product_name||r.sku_id)}</strong><span>Qty ${r.quantity??'—'} · Scout ${r.scout_grade||'—'} ${r.scout_score??'—'}</span></button>`}).join('')}</div>`;pane.innerHTML=html;pane.querySelectorAll('[data-open-card]').forEach(b=>b.onclick=()=>openCard(b.dataset.openCard));pane.querySelectorAll('[data-open-syp]').forEach(b=>b.onclick=()=>openSyp(b.dataset.openSyp));pane.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.openOrder))}
  function removeFilter(screen,key){const s=filterState();if(s[screen]?.filters)delete s[screen].filters[key];if(key==='sort')s[screen].sort=null;saveFilterState(s);renderAiResults(screen)}
  function clearFilters(screen){const s=filterState();delete s[screen];saveFilterState(s);document.querySelector(`#cx${screen[0].toUpperCase()+screen.slice(1)} .cx-ai-filter-results`)?.remove()}
  async function investigate(){if(busy)return;const state=panel?.querySelector('#cxAskInvestigateState'),btn=panel?.querySelector('#cxAskInvestigate'),context=await resolvedContext();if(context.screen!=='scout'||!context.product_id){if(state)state.textContent='Open a Scout card first.';return}busy=true;btn.disabled=true;if(state)state.textContent='Queueing deeper sales check…';try{const d=await api({action:'investigate',context});if(!d.job_id)throw Error('No Investigate job returned');if(state)state.textContent='Queued';bubble('system','Investigate queued; I’ll re-analyze after the deeper sales cache refreshes.');for(let i=0;i<50;i++){await sleep(7000);const rows=await rest(`collector_jobs?select=status,progress_json,error_message&job_id=eq.${encodeURIComponent(d.job_id)}&limit=1`),j=rows?.[0];if(!j)continue;if(state)state.textContent=j.progress_json?.detail||j.status;if(j.status==='completed'){busy=false;btn.disabled=false;await send('Re-analyze this Scout card using the refreshed Investigate data.');return}if(j.status==='failed')throw Error(j.error_message||'Investigate failed')}}catch(e){bubble('system',`Investigate: ${e.message||e}`)}finally{busy=false;btn.disabled=false}}
  function trackSelection(e){const sr=e.target.closest('#cxSyp tr[data-sku]');if(sr){document.querySelectorAll('#cxSyp tr.cx-ai-selected').forEach(x=>x.classList.remove('cx-ai-selected'));sr.classList.add('cx-ai-selected');lastEntity.syp={sku_id:sr.dataset.sku};syncContext()}const ir=e.target.closest('#cxInventory tr[data-sku]');if(ir){lastEntity.inventory={sku_id:ir.dataset.sku,product_id:ir.dataset.product||null};syncContext()}const or=e.target.closest('#cxSeller tbody tr');if(or){const id=(or.querySelector('td')?.textContent||'').trim();if(id)lastEntity.seller={order_id:id};syncContext()}}
  function floating(){if(document.getElementById('cxAskFab'))return;const b=document.createElement('button');b.id='cxAskFab';b.type='button';b.className='cx-ask-fab';b.innerHTML='<span>✦</span><b>Ask</b>';b.onclick=()=>open();document.body.append(b)}
  function decorate(){document.querySelectorAll('#cxParityDetail,#cxSeller .cx-card,#cxSyp .cx-page-head,#cxInventory .cx-page-head,#cxAdmin .cx-page-head').forEach(d=>{if(d.querySelector('.cx-ask-inline'))return;const b=document.createElement('button');b.type='button';b.className='cx-ask-inline';b.innerHTML='<span>✦</span> Ask Collectish';b.onclick=()=>open();if(d.id==='cxParityDetail')d.querySelector('.cx-v5-badges')?.after(b);else d.append(b)})}
  async function diagnostics(){const h=document.getElementById('cxAdmin');if(!h||h.querySelector('.cx-ask-diagnostics'))return;const grid=h.querySelector('.cx-grid')||h,card=document.createElement('div');card.className='cx-card cx-span-12 cx-ask-diagnostics';card.innerHTML='<div class="cx-section-title">Ask Collectish · AI diagnostics</div><div class="cx-empty">Loading…</div>';grid.append(card);try{const d=await api({action:'diagnostics'});card.innerHTML=`<div class="cx-section-title">Ask Collectish ${esc(d.version||'v2')} · AI diagnostics</div><div class="cx-detail-list"><div class="cx-detail-stat"><span>Model</span><strong>${esc(d.model||'—')}</strong></div><div class="cx-detail-stat"><span>Requests today</span><strong>${Number(d.requests_today||0).toLocaleString()}</strong></div><div class="cx-detail-stat"><span>Tokens today</span><strong>${Number(d.total_tokens||0).toLocaleString()}</strong></div><div class="cx-detail-stat"><span>Approx. cost</span><strong>$${Number(d.approx_cost_usd||0).toFixed(4)}</strong></div><div class="cx-detail-stat"><span>Tool failures</span><strong>${Number(d.tool_failures||0)}</strong></div><div class="cx-detail-stat"><span>Avg latency</span><strong>${d.avg_latency_ms==null?'—':`${(Number(d.avg_latency_ms)/1000).toFixed(1)}s`}</strong></div></div>`}catch(e){card.querySelector('.cx-empty').textContent=e.message||String(e)}}
  function restoreAiFilters(){const s=filterState();Object.keys(s).forEach(screen=>{if(document.querySelector(`#cx${screen[0].toUpperCase()+screen.slice(1)}.active`))renderAiResults(screen)})}
  function mount(){floating();build();decorate();document.addEventListener('click',trackSelection,true)}
  function onPage(page){syncContext();starters();decorate();restoreAiFilters();if(page==='admin')diagnostics()}
  function unmount(){document.removeEventListener('click',trackSelection,true);panel?.remove();panel=null;messages=null;input=null;document.getElementById('cxAskFab')?.remove()}
  registerComponent('ask',{mount,unmount,onPage});
  window.AskCollectish={open,send,showHistory,loadConversation,applyUiActions,renderAiResults};
})();
