import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});const t=(v:any)=>String(v??'').trim();
async function rpc(n:string,b:any={}){const r=await fetch(`${U}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(b)}),raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`${n} ${r.status}`);return d}
const money=(v:any)=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:'—',num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—',pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(1)}%`:'—';
function sets(q:string){return [...new Set((q.toUpperCase().match(/\b[A-Z0-9]{3,4}\b/g)||[]).filter(x=>!['WHAT','WITH','TODAY','SHOW','CARD','FOIL','FOILS','FROM','THIS','THAT','MOVE','REAL'].includes(x)))].slice(0,8)}
function treatment(q:string){const s=q.toLowerCase();for(const [re,label] of [[/raised\s+foils?/,'Raised Foil'],[/textured\s+foils?/,'Textured Foil'],[/fracture\s+foils?/,'Fracture Foil'],[/galaxy\s+foils?/,'Galaxy Foil'],[/surge\s+foils?/,'Surge Foil'],[/rainbow\s+foils?/,'Rainbow Foil'],[/halo\s+foils?/,'Halo Foil'],[/confetti\s+foils?/,'Confetti Foil'],[/neon\s+ink/,'Neon Ink'],[/serialized/,'Serialized'],[/gilded\s+foils?/,'Gilded Foil'],[/retro(?:\s+frame)?\s+foils?/,'Retro Frame Foil'],[/etched\s+foils?/,'Etched Foil'],[/borderless\s+foils?/,'Borderless Foil'],[/showcase\s+foils?/,'Showcase Foil']] as any[]){if(re.test(s))return label}return null}
function cardAlias(q:string){return t(q).replace(/^(?:why is|why did|is|analyze|analyse|compare all printings of|compare printings of|which printing of|am i late on|how liquid is|can i buy \d+ copies of)\s+/i,'').replace(/\s+(?:moving|spiking|real or noise|move real|should i buy|sustainable)\??$/i,'').replace(/[?]+$/,'').trim()}
function sourceName(v:any){return({direct_pressure:'Direct pressure',sales_acceleration:'Sales acceleration',cross_market:'Cross-market',tcgplayer_climbing:'TCGplayer climbing',mtgstocks:'MTGStocks',syp:'SYP',edh_demand:'EDH demand',creator_catalyst:'Creator catalyst'})[v]||v}
function radarText(c:any){const rows=c?.payload?.rows||[];if(!rows.length)return'No warm market signals are strong enough to surface right now.';const out=['## Delvin market radar'];for(const tier of ['Confirmed','Converging','Watch','Single-source']){const g=rows.filter((r:any)=>(r.evidence_tier||'Single-source')===tier).slice(0,tier==='Single-source'?5:6);if(!g.length)continue;out.push(`\n### ${tier}`);g.forEach((r:any,i:number)=>out.push(`${i+1}. **${r.card_name}** · ${r.set_code||'SET?'} · radar **${num(r.radar_score)}** · ${(r.sources||[]).map(sourceName).join(' + ')}`))}out.push('\n*Single-source = investigate, not confirmation.*');return out.join('\n')}
function rowsText(title:string,d:any,score='score'){const rows=d?.rows||d||[];if(!Array.isArray(rows)||!rows.length)return`${title}: no qualifying rows right now.`;return [`## ${title}`,...rows.slice(0,12).map((r:any,i:number)=>`${i+1}. **${r.card_name||r.product_name||r.treatment||r.set_code||'Item'}**${r.set_code?` · ${r.set_code}`:''}${r[score]!=null?` · ${score.replaceAll('_',' ')} ${num(r[score])}`:''}${r.sku_market_price!=null?` · Market ${money(r.sku_market_price)}`:r.market_price!=null?` · Market ${money(r.market_price)}`:''}${r.avg_daily_qty_sold!=null?` · ${num(r.avg_daily_qty_sold,1)}/day`:''}`)].join('\n')}
function cohortText(d:any){const s=d?.summary||d?.basket||d;const rows=d?.rows||[];let out=['## Collectible cohort thesis'];if(s?.treatment)out.push(`**${s.treatment}**${Array.isArray(s.set_codes)?` · ${s.set_codes.join(' + ')}`:''}`);if(s?.basket_current!=null||s?.current_value!=null)out.push(`Current one-of-each basket: **${money(s.basket_current??s.current_value)}**`);if(s?.basket_change_pct!=null||s?.change_pct!=null)out.push(`Cumulative change: **${pct(s.basket_change_pct??s.change_pct)}**`);if(s?.median_change_pct!=null)out.push(`Median printing: **${pct(s.median_change_pct)}**`);if(s?.history_start)out.push(`History starts ${String(s.history_start).slice(0,10)}.`);if(rows.length)out.push('\nTop contributors:',...rows.slice(0,8).map((r:any,i:number)=>`${i+1}. ${r.card_name||r.product_name} · ${r.set_code||''} · ${pct(r.change_pct??r.market_change_pct)}`));return out.join('\n')}
async function cache(key:string){return rpc('get_delvin_query_cache_v1',{p_query_key:key})}
async function resolve(q:string){const s=q.toLowerCase().replace(/[’]/g,"'");
 if(/\btop movers(?: today)?\b|\bbiggest movers today\b|\bwhat moved today\b|\bwhat(?:'s| is) moving today\b|\bwhat should i look at(?: right now)?\b|\bmarket radar\b|\bbest opportunities right now\b|\bwhat is moving right now\b/.test(s)){const c=await cache('market_radar');return{handled:true,route:'market_radar',response:radarText(c),data:c}}
 if(/\bedh\b.*\b(?:demand|movers?|gaining|week)\b|\bcommander demand\b/.test(s)){const c=await cache('edh_demand_7d');return{handled:true,route:'edh_demand_7d',response:rowsText('EDH demand movers',c?.payload,'demand_score'),data:c}}
 if(/\bcreator(?:-driven)?\b.*\b(?:moving|movers?|catalyst|cards?)\b|\bcreator catalysts?\b/.test(s)){const c=await cache('creator_catalysts_7d');return{handled:true,route:'creator_catalysts_7d',response:rowsText('Creator / catalyst movers',c?.payload,'catalyst_score'),data:c}}
 if(/\bwhat changed (?:in delvin )?since yesterday\b|\bmarket changes\b/.test(s)){const d=await rpc('ask_delvin_market_changes_v1',{p_limit:30});return{handled:true,route:'market_changes',response:rowsText('What changed in Delvin',d,'score_delta'),data:d}}
 if(/\bwhich delvin signals followed through\b|\bsignal follow.?through\b/.test(s)){const d=await rpc('ask_delvin_signal_followthrough_v1',{p_limit:30});return{handled:true,route:'signal_followthrough',response:rowsText('Delvin signal follow-through',d,'signal_score'),data:d}}
 const tr=treatment(q),ss=sets(q);
 if(tr&&/\b(?:growth|runway|upside|room left|long.?term|thesis|still have|more upside)\b/.test(s)){const d=await rpc('ask_delvin_collectible_cohort_thesis_v1',{p_treatment:tr,p_set_codes:ss.length?ss:null,p_days:730});return{handled:true,route:'collectible_cohort_thesis',response:cohortText(d),data:d}}
 if(tr&&ss.length===1){const d=await rpc('ask_delvin_treatment_intelligence_v1',{p_set_code:ss[0],p_treatment:tr,p_limit:40});return{handled:true,route:'treatment_intelligence',response:rowsText(`${ss[0]} ${tr}`,d,'opportunity_score'),data:d}}
 if(tr&&/\b(?:across sets|which .* strongest|compare .* foils|how are .* doing)\b/.test(s)){const d=await rpc('ask_delvin_collectible_family_index_v1',{p_treatment:tr,p_limit:30});return{handled:true,route:'collectible_family_index',response:rowsText(`${tr} across sets`,d,'cohort_score'),data:d}}
 if(ss.length===1&&/\b(?:what'?s moving|what is moving|set intelligence|collectibles|premium treatments|what .* matter|top cards|show me)\b/.test(s)){const d=await rpc('ask_delvin_set_intelligence_v1',{p_set_code:ss[0],p_limit:30});return{handled:true,route:'set_intelligence',response:rowsText(`${ss[0]} set intelligence`,d,'opportunity_score'),data:d}}
 if(/\bcompare all printings of\b|\bcompare printings of\b|\bwhich printing of\b/.test(s)){const name=cardAlias(q),d=await rpc('ask_delvin_printing_family_v1',{p_card_name:name,p_limit:40});return{handled:true,route:'printing_family',response:rowsText(`${name} printing family`,d,'opportunity_score'),data:d}}
 if(/\bwhy is .+ moving\b|\bis .+ real or noise\b|\bam i late on\b|\banaly[sz]e\s+.+/.test(s)){const name=cardAlias(q),d=await rpc('ask_delvin_card_investigation_v1',{p_card_name:name});return{handled:true,route:'card_investigation',response:rowsText(`${name} investigation`,d,'opportunity_score'),data:d}}
 const starters=await rpc('list_delvin_query_starters_v1',{p_prefix:t(q),p_limit:20}).catch(()=>[]);const exact=(starters||[]).find((x:any)=>String(x.prompt||'').toLowerCase()===s||(x.aliases||[]).some((a:any)=>String(a).toLowerCase()===s));if(exact){const c=await cache(exact.query_key);return{handled:true,route:exact.query_key,response:exact.query_key==='market_radar'?radarText(c):rowsText(exact.prompt,c?.payload,'score'),data:c}}
 return{handled:false};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({handled:false},405);if(!S)return js({handled:false,error:'service role unavailable'},500);const b=await req.json().catch(()=>({})),q=t(b?.question||b?.message);if(!q)return js({handled:false});try{return js(await resolve(q))}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});
