import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const t=(v:any)=>String(v??'').trim();

async function rpc(n:string,b:any={}){const r=await fetch(`${U}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(b)}),raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`${n} ${r.status}`);return d}
async function rest(path:string){const r=await fetch(`${U}/rest/v1/${path}`,{headers:{apikey:S,Authorization:`Bearer ${S}`}}),raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
const money=(v:any)=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:'—',num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—',pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(1)}%`:'—';

function sets(q:string){return [...new Set((q.toUpperCase().match(/\b[A-Z0-9]{3,4}\b/g)||[]).filter(x=>!['WHAT','WITH','TODAY','SHOW','CARD','FOIL','FOILS','FROM','THIS','THAT','MOVE','REAL'].includes(x)))].slice(0,8)}
function treatment(q:string){const s=q.toLowerCase();for(const [re,label] of [[/raised\s+foils?/,'Raised Foil'],[/textured\s+foils?/,'Textured Foil'],[/fracture\s+foils?/,'Fracture Foil'],[/galaxy\s+foils?/,'Galaxy Foil'],[/surge\s+foils?/,'Surge Foil'],[/rainbow\s+foils?/,'Rainbow Foil'],[/halo\s+foils?/,'Halo Foil'],[/confetti\s+foils?/,'Confetti Foil'],[/neon\s+ink/,'Neon Ink'],[/serialized/,'Serialized'],[/gilded\s+foils?/,'Gilded Foil'],[/retro(?:\s+frame)?\s+foils?/,'Retro Frame Foil'],[/etched\s+foils?/,'Etched Foil'],[/borderless\s+foils?/,'Borderless Foil'],[/showcase\s+foils?/,'Showcase Foil']] as any[]){if(re.test(s))return label}return null}
function cardAlias(q:string){return t(q).replace(/^(?:why is|why did|is|analyze|analyse|compare all printings of|compare printings of|which printing of|am i late on|how liquid is|can i buy \d+ copies of)\s+/i,'').replace(/\s+(?:moving|spiking|real or noise|move real|should i buy|sustainable)\??$/i,'').replace(/[?]+$/,'').trim()}
function sourceName(v:any){return({direct_pressure:'Direct pressure',sales_acceleration:'Sales acceleration',cross_market:'Cross-market',tcgplayer_climbing:'TCGplayer climbing',mtgstocks:'MTGStocks',syp:'SYP',edh_demand:'EDH demand',creator_catalyst:'Creator catalyst'})[v]||v}
function radarText(c:any){const rows=c?.payload?.rows||[];if(!rows.length)return'No warm market signals are strong enough to surface right now.';const out=['## Delvin market radar'];for(const tier of ['Confirmed','Converging','Watch','Single-source']){const g=rows.filter((r:any)=>(r.evidence_tier||'Single-source')===tier).slice(0,tier==='Single-source'?5:6);if(!g.length)continue;out.push(`\n### ${tier}`);g.forEach((r:any,i:number)=>out.push(`${i+1}. **${r.card_name}** · ${r.set_code||'SET?'} · radar **${num(r.radar_score)}** · ${(r.sources||[]).map(sourceName).join(' + ')}`))}out.push('\n*Single-source = investigate, not confirmation.*');return out.join('\n')}
function rowsText(title:string,d:any,score='score'){const rows=d?.rows||d||[];if(!Array.isArray(rows)||!rows.length)return`${title}: no qualifying rows right now.`;return [`## ${title}`,...rows.slice(0,12).map((r:any,i:number)=>`${i+1}. **${r.card_name||r.product_name||r.treatment||r.set_code||'Item'}**${r.set_code?` · ${r.set_code}`:''}${r[score]!=null?` · ${score.replaceAll('_',' ')} ${num(r[score])}`:''}${r.sku_market_price!=null?` · Market ${money(r.sku_market_price)}`:r.market_price!=null?` · Market ${money(r.market_price)}`:''}${r.avg_daily_qty_sold!=null?` · ${num(r.avg_daily_qty_sold,1)}/day`:''}`)].join('\n')}
function cohortText(d:any){const s=d?.summary||d?.basket||d;const rows=d?.rows||[];let out=['## Collectible cohort thesis'];if(s?.treatment)out.push(`**${s.treatment}**${Array.isArray(s.set_codes)?` · ${s.set_codes.join(' + ')}`:''}`);if(s?.basket_current!=null||s?.current_value!=null)out.push(`Current one-of-each basket: **${money(s.basket_current??s.current_value)}**`);if(s?.basket_change_pct!=null||s?.change_pct!=null)out.push(`Cumulative change: **${pct(s.basket_change_pct??s.change_pct)}**`);if(s?.median_change_pct!=null)out.push(`Median printing: **${pct(s.median_change_pct)}**`);if(s?.history_start)out.push(`History starts ${String(s.history_start).slice(0,10)}.`);if(rows.length)out.push('\nTop contributors:',...rows.slice(0,8).map((r:any,i:number)=>`${i+1}. ${r.card_name||r.product_name} · ${r.set_code||''} · ${pct(r.change_pct??r.market_change_pct)}`));return out.join('\n')}

const MONTH_NAMES=['january','february','march','april','may','june','july','august','september','october','november','december'];
function historicalVelocityIntent(q:string){const s=q.toLowerCase();return MONTH_NAMES.some(m=>new RegExp(`\\b${m}\\b`,'i').test(s))&&/\b(?:best|top|biggest|fastest|moving|movers?|selling|sold|velocity|demand|liquid|liquidity)\b/.test(s)&&/\b(?:cards?|singles?|mtg|tcgplayer|moving|movers?|selling|sold)\b/.test(s)}
function monthParts(q:string){const s=q.toLowerCase(),mi=MONTH_NAMES.findIndex(m=>new RegExp(`\\b${m}\\b`,'i').test(s));if(mi<0)return null;const ym=s.match(/\b(20\d{2})\b/);return{month:mi+1,year:ym?Number(ym[1]):null}}
async function topSellingMonth(q:string){const p=monthParts(q);if(!p)return null;const now=new Date(),years=p.year?[p.year]:[now.getUTCFullYear(),now.getUTCFullYear()-1,now.getUTCFullYear()-2];let rows:any[]=[];let usedYear:number|null=null;for(const y of years){const month=`${y}-${String(p.month).padStart(2,'0')}-01`;const d=await rpc('ask_delvin_tcgplayer_top_selling_month_v1',{p_month:month,p_limit:8}).catch(()=>[]);if(Array.isArray(d)&&d.length){rows=d;usedYear=y;break}}if(!rows.length)return{handled:true,route:'tcgplayer_top_selling_month',response:`I don't have a TCGplayer Top Selling report for ${MONTH_NAMES[p.month-1][0].toUpperCase()+MONTH_NAMES[p.month-1].slice(1)}${p.year?` ${p.year}`:''} yet.`,data:{rows:[]}};const start=rows[0].sales_window_start,end=rows[0].sales_window_end,label=new Date(`${usedYear}-${String(p.month).padStart(2,'0')}-01T00:00:00Z`).toLocaleString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});const groups=['$50+','$1-$49.99'];const out=[`## TCGplayer sales velocity — ${label}`,`Measured **${start} → ${end}**. TCGplayer ranks each price cohort by total copies sold.`];for(const bucket of groups){const g=rows.filter((r:any)=>r.price_bucket===bucket);if(!g.length)continue;out.push(`\n### ${bucket} cohort`,'| Rank | Card | Set | Avg sale |','|---:|---|---|---:|',...g.map((r:any)=>`| ${r.rank} | ${String(r.card_name||'').replaceAll('|','\\|')} | ${String(r.set_name||'').replaceAll('|','\\|')} | ${money(r.average_sale_price)} |`))}out.push('\n*TCGplayer does not publish the copies-sold counts in these CSVs, only the rank. Ranks are within each price cohort, so #1 in one cohort is not directly comparable to #1 in the other.*');return{handled:true,route:'tcgplayer_top_selling_month',response:out.join('\n'),data:{month:`${usedYear}-${String(p.month).padStart(2,'0')}`,sales_window_start:start,sales_window_end:end,rows},sources:[...new Set(rows.map((r:any)=>r.source_url).filter(Boolean))]}}

const ZETA_TCGPLAYER_PRODUCT_ID='714891';
function zetaIntent(q:string){const s=q.toLowerCase();return /\bzeta\b/.test(s)&&/\b(?:booster|boosters|pack|packs|aftermarket|secondary|buy|bought|missed out|missed)\b/.test(s)}
async function zetaMarket(){try{const r=await fetch(`https://infinite-api.tcgplayer.com/price/history/${ZETA_TCGPLAYER_PRODUCT_ID}/detailed?range=quarter`,{headers:{Accept:'application/json','User-Agent':'Collectish/1.0 sealed market decision'}});if(!r.ok)return null;const d=await r.json(),row=(d?.result||[]).find((x:any)=>String(x?.condition||'').toLowerCase()==='unopened')||d?.result?.[0],b=(row?.buckets||[]).find((x:any)=>Number(x?.quantitySold)>0||Number(x?.marketPrice)>0);return row&&b?{product_id:ZETA_TCGPLAYER_PRODUCT_ID,market_price:Number(b.marketPrice)||null,low_sale:Number(b.lowSalePriceWithShipping??b.lowSalePrice)||null,high_sale:Number(b.highSalePriceWithShipping??b.highSalePrice)||null,units_sold:Number(row.totalQuantitySold??b.quantitySold)||0,transactions:Number(row.totalTransactionCount??b.transactionCount)||0,bucket_start:b.bucketStartDate||null,source_url:`https://www.tcgplayer.com/product/${ZETA_TCGPLAYER_PRODUCT_ID}`} :null}catch{return null}}
async function zetaDecision(){
 const products=await rest('secret_lair_randomized_products?product_name=eq.Zeta%20Booster&select=randomized_product_id,release_id,product_name,pack_msrp,cards_per_pack,total_distinct_cards,print_run_known,official_url&limit=1').catch(()=>[]),p=products?.[0];if(!p)return null;
 const id=encodeURIComponent(String(p.randomized_product_id)),release=encodeURIComponent(String(p.release_id));
 const [evs,offers,values,assets,market]=await Promise.all([rest(`secret_lair_randomized_pack_ev_snapshots?randomized_product_id=eq.${id}&select=gross_mean_ev,gross_median_ev,net_mean_ev_after_fees,break_even_probability,top10_ev_share,observed_at,model_version,metadata&order=observed_at.desc&limit=1`).catch(()=>[]),rest(`secret_lair_randomized_product_offers?randomized_product_id=eq.${id}&select=region,price,watch_last_state,watch_last_checked_at,metadata&order=region.asc`).catch(()=>[]),rest(`secret_lair_randomized_market_values?randomized_product_id=eq.${id}&select=value_source`).catch(()=>[]),rest(`secret_lair_assets?release_id=eq.${release}&download_status=eq.downloaded&select=public_url,asset_type,is_primary,sort_order&order=is_primary.desc,sort_order.asc&limit=1`).catch(()=>[]),zetaMarket()]);
 const ev=evs?.[0]||null,imageUrl=assets?.[0]?.public_url||`https://tcgplayer-cdn.tcgplayer.com/product/${ZETA_TCGPLAYER_PRODUCT_ID}_in_1000x1000.jpg`,observed=(values||[]).filter((x:any)=>x.value_source==='slz_market').length,total=(values||[]).length,msrp=Number(p.pack_msrp),mp=Number(market?.market_price),mean=Number(ev?.gross_mean_ev),median=Number(ev?.gross_median_ev),net=Number(ev?.net_mean_ev_after_fees),multiple=msrp>0&&mp>0?mp/msrp:null,evMultiple=mean>0&&mp>0?mp/mean:null,verdict=mp>0&&mean>0?(mp>mean*1.25?'PASS':mp>median?'WATCH':'BUY'):'WATCH';
 const action=verdict==='PASS'?'Do not chase at current pricing.':verdict==='WATCH'?'Wait for a better entry or stronger exact-treatment pricing.':'A small position is supported at this price.';
 const why=[...(evMultiple?[`Market is ${num(evMultiple,1)}× modeled gross EV.`]:[]),`${observed}/${total||363} exact Zeta treatments have established prices.`,`Current listings start above $90.`];
 const changes=['Negative and Color Banding singles establish materially higher prices.','Supply remains scarce after fulfilled orders reach buyers.'];
 const buyZone=verdict==='PASS'?'Around $30 all-in or less.':verdict==='WATCH'?'High-$20s or below.':'At or below the modeled median.';
 const recheck='After fulfilled orders broaden supply and exact-treatment sales develop.';
 const response=`Zeta Booster — ${verdict}. ${action}`;
 const surface={type:'sealed_purchase_decision',domain:'collectish',title:'Zeta Booster',subtitle:'Aftermarket decision',verdict,action,market_price:mp||null,msrp:msrp||null,gross_mean_ev:mean||null,gross_median_ev:median||null,net_mean_ev_after_fees:net||null,units_sold:market?.units_sold||0,transactions:market?.transactions||0,low_sale:market?.low_sale||null,high_sale:market?.high_sale||null,price_multiple_vs_msrp:multiple,why,changes,buy_zone:buyZone,recheck,image_url:imageUrl,response,source_urls:[p.official_url,market?.source_url].filter(Boolean)};
 return{handled:true,route:'sealed_aftermarket_decision',response,surfaces:[surface],data:{product:p,official_offers:offers,pack_ev:ev,market,image_url:imageUrl,exact_treatment_market_coverage:{observed,total},verdict,price_multiple_vs_msrp:multiple,price_multiple_vs_modeled_gross_mean:evMultiple},sources:surface.source_urls};
}

async function cache(key:string){return rpc('get_delvin_query_cache_v1',{p_query_key:key})}
async function resolve(q:string){const s=q.toLowerCase().replace(/[’]/g,"'");
 if(zetaIntent(q)){const d=await zetaDecision();if(d)return d}
 if(historicalVelocityIntent(q)){const d=await topSellingMonth(q);if(d)return d}
 if(/\btop movers(?: today)?\b|\bbiggest movers today\b|\bwhat moved today\b|\bwhat(?:'s| is) moving today\b|\bwhat should i look at(?: right now)?\b|\bmarket radar\b|\bbest opportunities right now\b|\bwhat is moving right now\b/.test(s)){const c=await cache('market_radar');return{handled:true,route:'market_radar',response:radarText(c),data:c}}
 if(/\bedh\b.*\b(?:demand|movers?|gaining|week)\b|\bcommander demand\b/.test(s)){const c=await cache('edh_demand_7d');return{handled:true,route:'edh_demand_7d',response:rowsText('EDH demand movers',c?.payload,'demand_score'),data:c}}
 if(/\bcreator(?:-driven)?\b.*\b(?:moving|movers?|catalyst|cards?)\b|\bcreator catalysts?\b/.test(s)){const c=await cache('creator_catalysts_7d');return{handled:true,route:'creator_catalysts_7d',response:rowsText('Creator / catalyst movers',c?.payload,'catalyst_score'),data:c}}
 if(/\bwhat changed (?:in delvin )?since yesterday\b|\bmarket changes\b/.test(s)){const d=await rpc('ask_delvin_market_changes_v1',{p_limit:30});return{handled:true,route:'market_changes',response:rowsText('What changed in Delvin',d,'score_delta'),data:d}}
 if(/\bwhich delvin signals followed through\b|\bsignal follow.?through\b/.test(s)){const d=await rpc('ask_delvin_signal_followthrough_v1',{p_limit:30});return{handled:true,route:'signal_followthrough',response:rowsText('Delvin signal follow-through',d,'signal_score'),data:d}}
 const tr=treatment(q),ss=sets(q);
 if(tr&&/\b(?:growth|runway|upside|room left|long.?term|thesis|still have|more upside)\b/.test(s)){const d=await rpc('ask_delvin_collectible_cohort_thesis_v1',{p_treatment:tr,p_set_codes:ss.length?ss:null,p_days:730});return{handled:true,route:'collectible_cohort_thesis',response:cohortText(d),data:d}}
 if(tr&&ss.length===1){const d=await rpc('ask_delvin_treatment_intelligence_v1',{p_set_code:ss[0],p_treatment:tr,p_limit:40});return{handled:true,route:'treatment_intelligence',response:rowsText(`${ss[0]} ${tr}`,d,'opportunity_score'),data:d}}
 if(tr&&/\b(?:across sets|which .* strongest|compare .* foils|how are .* doing)\b/.test(s)){const d=await rpc('ask_delvin_collectible_family_index_v1',{p_treatment:tr,p_limit:30});return{handled:true,route:'collectible_family_index',response:rowsText(`${tr} across sets`,d,'cohort_score'),data:d}}
 if(ss.length===1&&/\b(?:what'?s moving|what is moving|set intelligence|collectibles|premium treatments|what .* matter|top cards|show me)\b/.test(s)){const d=await rpc('ask_delvin_set_intelligence_v1',{p_set_code:ss[0],p_limit:30});return{handled:true,route:'set_intelligence',response:rowsText(`${ss[0]} set intelligence`,d,'opportunity_score'),data:d}}
 if(/\bcompare all printings of\b|\bcompare printings of\b|\bwhich printing of\b/.test(s)){const name=cardAlias(q),d=await rpc('ask_delvin_printing_family_v1',{p_card_name:name,p_limit:40});return{handled:true,route:'printing_family',response:rowsText(`${name} printing family`,d,'opportunity_score'),data:d}}
 if(/\bwhy is .+ moving\b|\bis .+ real or noise\b|\bam i late on\b|\banaly[sz]e\s+.+/.test(s)){const name=cardAlias(q),d=await rpc('ask_delvin_card_investigation_v1',{p_card_name:name});return{handled:true,route:'card_investigation',response:rowsText(`${name} investigation`,d,'opportunity_score'),data:d}}
 const starters=await rpc('list_delvin_query_starters_v1',{p_prefix:t(q),p_limit:20}).catch(()=>[]);const exact=(starters||[]).find((x:any)=>String(x.prompt||'').toLowerCase()===s||(x.aliases||[]).some((a:any)=>String(a).toLowerCase()===s));if(exact){const c=await cache(exact.query_key);return{handled:true,route:exact.query_key,response:exact.query_key==='market_radar'?radarText(c):rowsText(exact.prompt,c?.payload,'score'),data:c}}
 return{handled:false};
}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({handled:false},405);if(!S)return js({handled:false,error:'service role unavailable'},500);const b=await req.json().catch(()=>({})),q=t(b?.question||b?.message);if(!q)return js({handled:false});try{return js(await resolve(q))}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});
