import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {articleLinks,climbing,csvLink,isMtg,parseArticle,reportRows,reportWindow,rssLinks,safeDownload,subtype} from './parser.ts';
import {csvLinks,priceBucket,salesReportRows,topSelling} from './report-utils.ts';

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const H=(t:string)=>({apikey:t===S&&S?S:A,Authorization:`Bearer ${t}`,'Content-Type':'application/json'});
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SOURCE='TCGplayer Seller Blog',TAG='https://seller.tcgplayer.com/blog/tag/mtg',RSS='https://seller.tcgplayer.com/blog/rss.xml';
const FAILED_COOLDOWN_MS=6*60*60*1000,DEFAULT_BACKFILL_DAYS=240;

async function auth(t:string){const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('Unauthorized');const u=await r.json();if(!u?.id)throw Error('Unauthorized');return u}
async function serviceAuth(t:string){if(!t)return false;if(S&&t===S)return true;try{const r=await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}});return r.ok}catch{return false}}
async function rest(t:string,path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(t),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function getText(url:string,accept='text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.5'){const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'User-Agent':'MarketplaceScout/0.8 (+TCGplayer Seller Blog MTG collector)','Accept':accept}});if(!r.ok)throw Error(`HTTP ${r.status}`);return{text:await r.text(),url:r.url}}finally{clearTimeout(timer)}}
async function sha(v:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function failedRecently(row:any){if(row?.metadata_json?.status!=='failed')return false;const at=Date.parse(String(row?.metadata_json?.last_attempt_at||''));return Number.isFinite(at)&&Date.now()-at<FAILED_COOLDOWN_MS}
function completed(row:any){if(row?.metadata_json?.status!=='saved')return false;if(row?.metadata_json?.source_subtype==='first_party_market_sales'&&!Array.isArray(row?.metadata_json?.sales_reports))return false;return true}
async function callIngest(t:string,body:any){const r=await fetch(`${U}/functions/v1/market-intel-ingest`,{method:'POST',headers:H(t),body:JSON.stringify(body)}),raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):{}}catch{d={error:raw}}if(!r.ok)throw Error(d?.error||`Ingest ${r.status}`);return d}
async function ingestArticle(t:string,a:any,owner:string,scheduler:boolean){const b:any={url:a.url,rendered_title:a.title,rendered_text:a.rendered_text,author:a.author,published_at:a.published_at,source_type:'article',source_name:SOURCE,source_profile:'marketplace_editorial',source_subtype:subtype(a.title)};if(scheduler)b._scheduler_user_id=owner;return callIngest(t,b)}
async function ingestReport(t:string,a:any,url:string,rows:any[],window:any,owner:string,scheduler:boolean){let saved=0,duplicates=0;for(let i=0;i<rows.length;i+=20){const signals=rows.slice(i,i+20).map((r:any)=>{const bits=[r.previous_market!==null?`from $${r.previous_market.toFixed(2)}`:'',r.current_market!==null?`to $${r.current_market.toFixed(2)}`:'',r.percent_change!==null?`(${r.percent_change}% change)`:'' ].filter(Boolean).join(' ');return{entity_name:r.card,entity_type:'card',claim_type:'price',direction:'bullish',signal_stage:'confirming',confidence:0.99,summary:`TCGplayer first-party Market Price report identifies ${r.card}${r.set?` [${r.set}]`:''} as climbing in price${bits?`: ${bits}`:''}. Measurement window: ${window?.start||'unknown'} through ${window?.end||'unknown'}; Near Mint copies with at least ten sales.`}});const b:any={url,source_type:'article',source_name:'TCGplayer Price Trends Report',source_profile:'marketplace_editorial',source_subtype:'first_party_market_price',published_at:a.published_at,analysis:{url,title:`${a.title} — downloadable TCGplayer report`,author:a.author,published_at:a.published_at,source_summary:`TCGplayer first-party Market Price report. ${window?.note||''}`,signals}};if(scheduler)b._scheduler_user_id=owner;const d=await callIngest(t,b);saved+=Number(d?.saved||0);duplicates+=Number(d?.duplicates||0)}return{saved,duplicates}}
async function ingestSalesReport(t:string,a:any,url:string,rows:any[],window:any,bucket:string|null,owner:string,scheduler:boolean){let saved=0,duplicates=0;for(let i=0;i<rows.length;i+=20){const signals=rows.slice(i,i+20).map((r:any)=>{const facts=[`rank #${r.rank}`,r.copies_sold!==null?`${r.copies_sold} copies sold`:'',r.average_sale_price!==null?`average sale price $${r.average_sale_price.toFixed(2)}`:'',bucket?`July price bucket ${bucket}`:''].filter(Boolean).join('; ');return{entity_name:r.card,entity_type:'card',claim_type:'demand',direction:'bullish',signal_stage:'confirming',confidence:0.99,summary:`TCGplayer first-party sales report ranks ${r.card}${r.set?` [${r.set}]`:''} among its top-selling MTG cards (${facts}). Sales window: ${window?.start||'unknown'} through ${window?.end||'unknown'}. Rankings aggregate conditions and printing/finish variants within the named card/set entry.`}});const b:any={url,source_type:'article',source_name:'TCGplayer Top Selling Report',source_profile:'marketplace_editorial',source_subtype:'first_party_market_sales',published_at:a.published_at,analysis:{url,title:`${a.title} — downloadable TCGplayer top-selling report${bucket?` (${bucket})`:''}`,author:a.author,published_at:a.published_at,source_summary:`TCGplayer first-party Marketplace sales-velocity report ranked by total copies sold. Sales window ${window?.start||'unknown'} through ${window?.end||'unknown'}; condition and printing/finish are not distinguished.${bucket?` Prior-month average-sale-price bucket: ${bucket}.`:''}`,signals}};if(scheduler)b._scheduler_user_id=owner;const d=await callIngest(t,b);saved+=Number(d?.saved||0);duplicates+=Number(d?.duplicates||0)}return{saved,duplicates}}
async function discover(){const out:string[]=[];for(let p=1;p<=15;p++){const variants=p===1?[TAG]:[`${TAG}/page/${p}`,`${TAG}?page=${p}`];let found:string[]=[];for(const u of variants){try{found=articleLinks((await getText(u)).text,u);if(found.length)break}catch{}}if(!found.length)break;for(const u of found)if(!out.includes(u))out.push(u)}if(out.length)return out;try{return rssLinks((await getText(RSS,'application/rss+xml,application/xml,text/xml;q=0.9,*/*;q=0.5')).text,RSS)}catch{return[]}}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);
 const caller=bearer(req);if(!caller)return J({error:'Authentication required'},401);let b:any={};try{b=await req.json()}catch{}
 const scheduler=await serviceAuth(caller);let user:any=null;if(!scheduler){try{user=await auth(caller)}catch{return J({error:'Authentication required'},401)}}if(scheduler&&!S)return J({error:'Service role unavailable'},500);const t=scheduler?S:caller;
 try{
  const select=scheduler?'capture_id,user_id,source,source_key,payload_json':'capture_id,source,source_key,payload_json';const subs=await rest(t,`source_captures?select=${select}&capture_type=eq.content_subscription&payload_json->>discovery=eq.tcgplayer_seller_blog_mtg&order=captured_at.asc&limit=20`).catch(()=>[]);const enabled=(subs||[]).filter((x:any)=>x?.payload_json?.enabled!==false);const maxNew=Math.max(1,Math.min(Number(b?.max_new)||3,scheduler?8:4));let attempted=0,saved=0,duplicates=0,failed=0,reportRowsSeen=0,reportRowsSaved=0,salesReportRowsSeen=0,salesReportRowsSaved=0,morePending=false;const reports:any[]=[];
  for(const sub of enabled){const owner=scheduler?String(sub.user_id||''):String(user.id||'');if(!UUID.test(owner))continue;const days=Math.max(30,Math.min(Number(sub?.payload_json?.backfill_days)||DEFAULT_BACKFILL_DAYS,730)),cutoff=Date.now()-days*86400000,backfillComplete=!!sub?.payload_json?.backfill_complete;const existingRows=await rest(t,`source_captures?select=capture_id,source_key,metadata_json&user_id=eq.${encodeURIComponent(owner)}&source=eq.${encodeURIComponent(SOURCE)}&capture_type=eq.content_item&order=captured_at.desc&limit=2000`).catch(()=>[]),existing=new Map((existingRows||[]).map((x:any)=>[String(x.source_key||''),x]));const candidates=await discover();const out:any={source:SOURCE,tag:TAG,backfill_days:days,candidates:candidates.length,attempted:0,saved:0,duplicates:0,price_reports:0,sales_reports:0,report_rows:0,sales_report_rows:0,failed:0,errors:[]};let reachedCutoff=false;
   for(const url of candidates){const prior=existing.get(url);if(completed(prior)||failedRecently(prior))continue;if(attempted>=maxNew){morePending=true;break}let a:any;try{const got=await getText(url);if(!isMtg(got.text))continue;a=parseArticle(got.text,url);const pm=Date.parse(String(a.published_at||''));if(Number.isFinite(pm)&&pm<cutoff){reachedCutoff=true;break}if(!a.title||a.rendered_text.length<200)continue}catch(e){failed++;out.failed++;out.errors.push(`${url}: ${(e as Error).message}`);continue}attempted++;out.attempted++;const st=subtype(a.title);let captureId=prior?.capture_id||null;if(!captureId){const ins=await rest(t,'source_captures',{method:'POST',prefer:'return=representation',body:{user_id:owner,source:SOURCE,capture_type:'content_item',source_key:url,content_type:'text/html',payload_json:{title:a.title,published_at:a.published_at,author:a.author,tag:'mtg',index_url:TAG,source_profile:'marketplace_editorial',source_subtype:st},content_hash:await sha(`${url}|${a.title}|${a.published_at||''}`),metadata_json:{status:'pending',tag:'mtg',index_url:TAG,source_subtype:st}}});captureId=(Array.isArray(ins)?ins[0]:ins)?.capture_id||null}
    try{
     const ar=await ingestArticle(t,a,owner,scheduler);saved+=Number(ar?.saved||0);duplicates+=Number(ar?.duplicates||0);out.saved+=Number(ar?.saved||0);out.duplicates+=Number(ar?.duplicates||0);
     let priceReport:any=null;const salesReports:any[]=[];
     if(climbing(a.title)){
      const window=reportWindow(a.html),link=csvLink(a.html,a.url);if(!window)throw Error('Climbing-in-price article is missing an explicit report date window');
      if(link){const dl=await getText(safeDownload(link,a.url),'text/csv,text/plain,application/csv,application/octet-stream;q=0.8,*/*;q=0.2');if(dl.text.length>5_000_000)throw Error('CSV report exceeds 5 MB safety limit');const finalUrl=safeDownload(dl.url||link,a.url),rows=reportRows(dl.text);if(!rows.length)throw Error('CSV report contained no recognizable card rows');reportRowsSeen+=rows.length;out.report_rows+=rows.length;const ir=await ingestReport(t,a,finalUrl,rows,window,owner,scheduler);reportRowsSaved+=ir.saved;saved+=ir.saved;duplicates+=ir.duplicates;out.saved+=ir.saved;out.duplicates+=ir.duplicates;out.price_reports++;await rest(t,'source_captures',{method:'POST',prefer:'return=minimal',body:{user_id:owner,source:'TCGplayer Price Trends Report',capture_type:'data_report',source_key:finalUrl,content_type:'text/csv',payload_json:{parent_article_url:a.url,parent_article_title:a.title,published_at:a.published_at,report_window_start:window.start,report_window_end:window.end,report_window_note:window.note,criteria:{condition:'Near Mint',minimum_sales:10},rows:rows.length,download_url:link,final_url:finalUrl},payload_text:dl.text.slice(0,200000),content_hash:await sha(dl.text),metadata_json:{status:'saved',source_profile:'marketplace_editorial',source_subtype:'first_party_market_price',retrieved_at:new Date().toISOString()}}});priceReport={download_url:link,final_url:finalUrl,report_window_start:window.start,report_window_end:window.end,report_window_note:window.note,rows:rows.length}}
     }
     if(topSelling(a.title)){
      const window=reportWindow(a.html),links=csvLinks(a.html,a.url);if(!window)throw Error('Top-selling article is missing an explicit report date window');if(!links.length)throw Error('Top-selling article has no supported downloadable report links');
      for(const link of links){const dl=await getText(safeDownload(link.url,a.url),'text/csv,text/plain,application/csv,application/octet-stream;q=0.8,*/*;q=0.2');if(dl.text.length>5_000_000)throw Error('CSV report exceeds 5 MB safety limit');const finalUrl=safeDownload(dl.url||link.url,a.url),rows=salesReportRows(dl.text);if(!rows.length)throw Error(`Top-selling CSV contained no recognizable card rows: ${link.label||link.url}`);const bucket=priceBucket(link.label,finalUrl);salesReportRowsSeen+=rows.length;out.sales_report_rows+=rows.length;const ir=await ingestSalesReport(t,a,finalUrl,rows,window,bucket,owner,scheduler);salesReportRowsSaved+=ir.saved;saved+=ir.saved;duplicates+=ir.duplicates;out.saved+=ir.saved;out.duplicates+=ir.duplicates;out.sales_reports++;const reportMeta={download_url:link.url,final_url:finalUrl,label:link.label||null,price_bucket:bucket,report_window_start:window.start,report_window_end:window.end,rows:rows.length};salesReports.push(reportMeta);await rest(t,'source_captures',{method:'POST',prefer:'return=minimal',body:{user_id:owner,source:'TCGplayer Top Selling Report',capture_type:'data_report',source_key:finalUrl,content_type:'text/csv',payload_json:{parent_article_url:a.url,parent_article_title:a.title,published_at:a.published_at,report_window_start:window.start,report_window_end:window.end,report_window_note:window.note,criteria:{ranking:'total copies sold',condition:'all',printing_finish:'all',prior_month_average_sale_price_bucket:bucket},rows:rows.length,download_url:link.url,final_url:finalUrl,label:link.label||null},payload_text:dl.text.slice(0,200000),content_hash:await sha(dl.text),metadata_json:{status:'saved',source_profile:'marketplace_editorial',source_subtype:'first_party_market_sales',retrieved_at:new Date().toISOString()}}})}
     }
     const meta:any={status:'saved',tag:'mtg',index_url:TAG,source_profile:'marketplace_editorial',source_subtype:st,ingested_at:new Date().toISOString(),saved:Number(ar?.saved||0),duplicates:Number(ar?.duplicates||0),price_report:priceReport};if(topSelling(a.title))meta.sales_reports=salesReports;
     if(captureId)await rest(t,`source_captures?capture_id=eq.${encodeURIComponent(captureId)}&user_id=eq.${encodeURIComponent(owner)}`,{method:'PATCH',prefer:'return=minimal',body:{metadata_json:meta}});existing.set(url,{capture_id:captureId,metadata_json:meta});
    }catch(e){failed++;out.failed++;out.errors.push(`${a.title}: ${(e as Error).message}`);if(captureId)await rest(t,`source_captures?capture_id=eq.${encodeURIComponent(captureId)}&user_id=eq.${encodeURIComponent(owner)}`,{method:'PATCH',prefer:'return=minimal',body:{metadata_json:{status:'failed',tag:'mtg',source_subtype:st,last_error:(e as Error).message,last_attempt_at:new Date().toISOString()}}}).catch(()=>null)}
   }
   if(reachedCutoff&&!morePending&&!backfillComplete&&sub.capture_id){const payload={...(sub.payload_json||{}),backfill_complete:true,backfill_completed_at:new Date().toISOString()};await rest(t,`source_captures?capture_id=eq.${encodeURIComponent(sub.capture_id)}&user_id=eq.${encodeURIComponent(owner)}`,{method:'PATCH',prefer:'return=minimal',body:{payload_json:payload}}).catch(()=>null);out.backfill_complete=true}reports.push(out);if(attempted>=maxNew)break;
  }
  return J({ok:true,mode:scheduler?'scheduled':'user',configured:enabled.length,attempted,saved,duplicates,failed,report_rows_seen:reportRowsSeen,report_rows_saved:reportRowsSaved,sales_report_rows_seen:salesReportRowsSeen,sales_report_rows_saved:salesReportRowsSaved,more_pending:morePending,report:reports});
 }catch(e){return J({error:(e as Error).message},502)}
});
