export function dec(s:string){return String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
export function text(s:string){return dec(s).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
export function safeArticle(v:string,base='https://seller.tcgplayer.com/blog/tag/mtg'){const u=new URL(v,base);if(u.protocol!=='https:'||u.hostname.toLowerCase()!=='seller.tcgplayer.com')throw Error('Unsupported TCGplayer article URL');u.hash='';return u.toString()}
export function safeDownload(v:string,base='https://seller.tcgplayer.com/blog/tag/mtg'){const u=new URL(v,base);if(u.protocol!=='https:')throw Error('CSV download must use https');const h=u.hostname.toLowerCase();if(!(h==='bit.ly'||h.includes('hubspotusercontent')))throw Error(`Unsupported report host: ${h}`);return u.toString()}
export function meta(html:string,name:string){const e=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)`,'i'));const b=html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,'i'));return dec((a||b||[])[1]||'').trim()}
export function articleLinks(html:string,base:string){const out:string[]=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/gi)){let u='';try{u=safeArticle(dec(m[1]),base)}catch{continue}if(!/^\/blog\/[a-z0-9][a-z0-9-]+\/?$/i.test(new URL(u).pathname))continue;if(!out.includes(u))out.push(u)}return out}
export function rssLinks(xml:string,base:string){const out:string[]=[];for(const m of xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)){const b=m[1],raw=(b.match(/<link[^>]*>([\s\S]*?)<\/link>/i)||b.match(/<guid[^>]*>([\s\S]*?)<\/guid>/i)||[])[1]||'';try{const u=safeArticle(text(raw),base);if(!out.includes(u))out.push(u)}catch{}}return out}
export function isMtg(html:string){return /href=["'][^"']*\/blog\/tag\/mtg(?:[\/?#"'])/i.test(html)||/(?:^|[>\s])#mtg(?:[<\s]|$)/i.test(html)}
export function parseArticle(html:string,url:string){const title=(meta(html,'og:title')||text((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'')).replace(/\s*[|–-]\s*TCGplayer.*$/i,'').trim();const published=meta(html,'article:published_time')||meta(html,'datePublished')||dec((html.match(/<time\b[^>]*datetime=["']([^"']+)["']/i)||[])[1]||'')||dec((html.match(/["']datePublished["']\s*:\s*["']([^"']+)["']/i)||[])[1]||'')||null;const author=meta(html,'author')||dec((html.match(/["']author["']\s*:\s*\{[^}]*["']name["']\s*:\s*["']([^"']+)/i)||[])[1]||'')||null;const body=(html.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)||html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)||[])[1]||html;return{url,title,author,published_at:published,rendered_text:text(body).slice(0,70000),html}}
export function climbing(title:string){return /(?:price trends?.*)?climbing in price/i.test(title)||/cards climbing in price/i.test(title)}
const MONTHS=['january','february','march','april','may','june','july','august','september','october','november','december'];
function monthNum(s:string){return MONTHS.indexOf(s.toLowerCase())+1}
function isoDate(month:string,day:string,year:number){const m=monthNum(month),d=Number(day);return m&&d&&year?`${year}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:null}
export function reportWindow(body:string){const t=text(body);const m=t.match(/between\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})(?:,?\s+(\d{4}))?\s+and\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),?\s+(\d{4})/i);if(!m)return null;let sy=Number(m[3]||m[6]),ey=Number(m[6]);if(!m[3]&&monthNum(m[1])>monthNum(m[4]))sy=ey-1;const start=isoDate(m[1],m[2],sy),end=isoDate(m[4],m[5],ey);if(!start||!end)return null;const note=(t.match(/Note:\s*This report only considers[^.]{0,500}/i)||[])[0]||m[0];return{start,end,note:note.trim()}}
export function csvLink(html:string,url:string){let fallback='';for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const label=text(m[2]).toLowerCase(),href=dec(m[1]);let u='';try{u=safeDownload(href,url)}catch{continue}if(/csv|download|price trends? report/.test(label)||/\.csv(?:$|\?)/i.test(u))return u;if(!fallback&&/bit\.ly/i.test(u))fallback=u}return fallback||null}
function parseCsv(raw:string){const rows:string[][]=[];let row:string[]=[],field='',q=false;for(let i=0;i<raw.length;i++){const c=raw[i];if(q){if(c==='"'&&raw[i+1]==='"'){field+='"';i++}else if(c==='"')q=false;else field+=c}else if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}if(field.length||row.length){row.push(field.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(x=>x.trim()))}
function key(s:string){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function first(o:any,names:string[]){for(const n of names){const v=o[key(n)];if(v!==undefined&&String(v).trim())return String(v).trim()}return''}
function num(v:string){const n=Number(String(v||'').replace(/[$,%\s]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:null}
export function reportRows(raw:string){const rows=parseCsv(raw);if(rows.length<2)return[];const h=rows[0].map(key);return rows.slice(1).map(vals=>Object.fromEntries(h.map((x,i)=>[x,String(vals[i]??'').trim()]))).map((r:any)=>({card:first(r,['product name','card name','name']),set:first(r,['set name','set']),product_id:first(r,['product id','tcgplayer product id'])||null,printing:first(r,['printing','printing type','finish'])||null,current_market:num(first(r,['current market price','market price','new market price'])),previous_market:num(first(r,['previous market price','old market price','starting market price','market price 30 days ago'])),percent_change:num(first(r,['percent increase','percentage increase','percent change','price change percent','% increase','% change'])),sales:num(first(r,['sales','number of sales','sale count','units sold','total sales'])),raw:r})).filter((r:any)=>r.card)}
export function subtype(title:string){const h=title.toLowerCase();if(/climbing in price|price trends|market price/.test(h))return'first_party_market_price';if(/top[- ]?selling|best[- ]?selling|copies sold/.test(h))return'first_party_market_sales';if(/direct|seller|policy|fee|shipping|store your products/.test(h))return'marketplace_operations';return'marketplace_editorial'}
