import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const H=()=>({apikey:S||A,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const norm=(s:any)=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const trim=(x:any,n=1200)=>String(x??'').trim().slice(0,n);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const NEVER_SIGNAL=new Set(['plains','island','swamp','mountain','forest']);
const ALIASES=new Map<string,string>([
 ['fomo','Fear of Missing Out'],['fear of missing out','Fear of Missing Out'],['gsz',"Green Sun's Zenith"],['green sun zenith',"Green Sun's Zenith"],['green suns zenith',"Green Sun's Zenith"],
 ['aurora boroid','Ouroboroid'],['aurora borid','Ouroboroid'],['aurora boy','Ouroboroid'],['ouro boroid','Ouroboroid'],['space snake','Ouroboroid'],
 ['badger cup','Badgermole Cub'],['badger cub','Badgermole Cub'],['the cub','Badgermole Cub'],
 ['vexing bobble','Vexing Bauble'],['vexing bubble','Vexing Bauble'],['vexing bubbles','Vexing Bauble'],['vexing bobbles','Vexing Bauble'],
 ['mistress bobbles',"Mishra's Bauble"],['mishras bobble',"Mishra's Bauble"],['mishra bobble',"Mishra's Bauble"],
 ['street rays','Street Wraith'],['street ray','Street Wraith'],['wraith','Street Wraith'],['collector oof','Collector Ouphe'],['collector oofe','Collector Ouphe'],['oof','Collector Ouphe'],
 ['rumble','Malevolent Rumble'],['rumbles','Malevolent Rumble'],['fly trap','Omnivorous Flytrap'],['flight trap','Omnivorous Flytrap'],['omnivorous fly trap','Omnivorous Flytrap']
]);
const POSITIVE=[
 {re:/\bmandatory\b|\bhave to play\b|\bperfect (?:tool|card|fit)\b/i,p:.94,label:'strong recommendation'},
 {re:/\bhad success with\b|\bwe.ve been liking\b|\breally really powerful\b|\breally good with\b/i,p:.86,label:'positive testing'},
 {re:/\bgo(?:es)? (?:so )?crazy\b|\binsane board states?\b|\bbig part of what we.re trying to do\b/i,p:.84,label:'high-impact synergy'},
 {re:/\bmakes? a lot of sense\b|\bfits? (?:it|really well|a good spot)\b/i,p:.76,label:'positive deck fit'},
 {re:/\bwanted? to play more\b|\bplay more copies\b|\blike the look\b/i,p:.68,label:'copy-count preference'}
];
const NEGATIVE=/\bcut\b|\bget rid of\b|\bgo down\b|\bnot a huge fan\b|\bunderperform|\bweak\b|\bdon.t like\b/i;

async function serviceAuth(t:string){if(!t)return false;if(S&&t===S)return true;try{const r=await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}});return r.ok}catch{return false}}
async function rest(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function rpc(name:string,args:any={}){return rest(`rpc/${name}`,{method:'POST',body:args})}
function deckId(url:string){return (String(url||'').match(/moxfield\.com\/decks\/([A-Za-z0-9_-]+)/i)||[])[1]||''}
function boardNames(board:any){if(!board)return[];if(Array.isArray(board?.cards))return board.cards.map((x:any)=>x?.card?.name||x?.name).filter(Boolean);if(board?.cards&&typeof board.cards==='object')return Object.values(board.cards).map((x:any)=>x?.card?.name||x?.name).filter(Boolean);if(typeof board==='object')return Object.entries(board).map(([k,v]:any)=>v?.card?.name||v?.name||k).filter(Boolean);return[]}
async function deckCards(url:string){const id=deckId(url);if(!id)return[];for(const endpoint of [`https://api2.moxfield.com/v3/decks/all/${id}`,`https://api2.moxfield.com/v2/decks/all/${id}`,`https://api.moxfield.com/v2/decks/all/${id}`]){try{const r=await fetch(endpoint,{headers:{'User-Agent':'Mozilla/5.0 Collectish/1.0','Accept':'application/json','Origin':'https://www.moxfield.com','Referer':url}});if(!r.ok)continue;const d=await r.json();return [...new Set([...boardNames(d?.boards?.mainboard||d?.mainboard),...boardNames(d?.boards?.sideboard||d?.sideboard),...boardNames(d?.boards?.commanders||d?.commanders),...boardNames(d?.boards?.companions||d?.companions)].map(String))]}catch{}}return[]}
function mentions(text:string,cards:string[]){const t=norm(text),deck=new Map(cards.map(c=>[norm(c),c])),out=new Map<string,{raw:string,method:string,score:number,pos:number}>();for(const [alias,canonical] of ALIASES){const a=norm(alias),pos=t.indexOf(a);if(pos>=0&&deck.has(norm(canonical))&&!NEVER_SIGNAL.has(norm(canonical)))out.set(norm(canonical),{raw:alias,method:'deck_alias',score:.995,pos})}for(const card of cards){const c=norm(card),pos=t.indexOf(c);if(c&&pos>=0&&!NEVER_SIGNAL.has(c))out.set(c,{raw:card,method:'deck_exact',score:1,pos})}return [...out.entries()].map(([k,v])=>({card:deck.get(k)!,...v}))}
function evaluationNear(text:string,pos:number,raw:string){const t=norm(text),needle=norm(raw),start=Math.max(0,pos-180),end=Math.min(t.length,pos+needle.length+180),local=t.slice(start,end);if(NEGATIVE.test(local))return null;let best:any=null;for(const x of POSITIVE)if(x.re.test(local)&&(!best||x.p>best.p))best=x;return best}
async function scryfall(name:string){try{const r=await fetch(`https://api.scryfall.com/cards/named?exact=${encodeURIComponent(name)}`,{headers:{'User-Agent':'MarketplaceScout/0.8 (+deterministic creator video fallback)'}});if(!r.ok)return null;const c=await r.json();return c?.id?{name:String(c.name),id:String(c.id),set:String(c.set||'')}:null}catch{return null}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);const token=bearer(req);if(!token||!(await serviceAuth(token)))return J({error:'Service authentication required'},401);if(!S)return J({error:'Service role unavailable'},500);let body:any={};try{body=await req.json()}catch{}const target=String(body?.video_id||'').trim();try{
 const rows=await rest('source_captures?select=capture_id,user_id,source,payload_json,metadata_json&capture_type=eq.video_transcript&order=captured_at.desc&limit=50');let capture:any=null;for(const r of rows||[]){if(!UUID.test(String(r.user_id||''))||r?.metadata_json?.status!=='saved')continue;const p=r.payload_json||{};if(target&&p.video_id!==target)continue;if(!p.deck_url||!Array.isArray(p.segments)||!p.segments.length)continue;const count=Number(r?.metadata_json?.events_saved||0);if(count>0&&!body?.force)continue;capture=r;break}if(!capture)return J({ok:true,processed:0,events_saved:0,reason:'no_eligible_cached_video'});
 const p=capture.payload_json,owner=String(capture.user_id),cards=await deckCards(String(p.deck_url));if(!cards.length)return J({ok:true,processed:1,events_saved:0,reason:'deck_unavailable',video_id:p.video_id});
 const candidates:any[]=[];for(const seg of p.segments){const text=String(seg?.text||'');for(const m of mentions(text,cards)){const ev=evaluationNear(text,m.pos,m.raw);if(!ev)continue;candidates.push({card:m.card,raw:m.raw,method:m.method,resolution:m.score,start_ms:Math.max(0,Math.round(Number(seg?.offset)||0)),prominence:ev.p,evidence:trim(text,420),label:ev.label})}}
 candidates.sort((a,b)=>b.prominence-a.prominence||a.start_ms-b.start_ms);const selected:any[]=[];const seen=new Map<string,number>();for(const x of candidates){const key=norm(x.card),prior=seen.get(key);if(prior!=null&&Math.abs(x.start_ms-prior)<240000)continue;seen.set(key,x.start_ms);selected.push(x);if(selected.length>=12)break}
 let saved=0;const output:any[]=[];for(const x of selected){const card=await scryfall(x.card);if(!card)continue;const eventKey=`${p.video_id}|competitive_test|${x.start_ms}|${norm(card.name)}`;const existing=await rest(`market_intel_items?select=intel_id,metadata_json&user_id=eq.${encodeURIComponent(owner)}&source_url=eq.${encodeURIComponent(p.url)}&limit=100`).catch(()=>[]);let intelId=(existing||[]).find((q:any)=>String(q?.metadata_json?.video_event_key||'')===eventKey)?.intel_id||null;if(!intelId){const inserted=await rest('market_intel_items',{method:'POST',prefer:'return=representation',body:{user_id:owner,source_type:'youtube',source_name:capture.source||'YouTube',source_url:p.url,title:p.title||card.name,author:capture.source||null,summary:`${card.name}: ${x.label} in competitive deck testing.`,claim_type:'competitive',direction:'bullish',signal_stage:'leading',confidence:Math.min(.95,x.resolution),published_at:p.published_at||null,source_profile:'creator_competitive',source_subtype:'competitive_test',metadata_json:{platform:'youtube',video_id:p.video_id,channel_id:p.channel_id||null,creator_lane:p.creator_lane||'competitive',deck_url:p.deck_url,deck_context_status:'ok',transcript_provider:'supadata',transcript_mode:'native',timestamped:true,video_event_key:eventKey,event_type:'competitive_test',start_ms:x.start_ms,prominence:x.prominence,raw_mention:x.raw,resolution_method:x.method,resolution_confidence:x.resolution,deterministic_fallback:true,deterministic_version:3}}});intelId=Array.isArray(inserted)?inserted[0]?.intel_id:null;if(!intelId)continue;await rest('market_intel_entities',{method:'POST',prefer:'return=minimal',body:{intel_id:intelId,user_id:owner,entity_type:'card',entity_name:card.name,scryfall_id:card.id,set_code:card.set,confidence:x.resolution}})}await rest('market_intel_video_events',{method:'POST',prefer:'resolution=ignore-duplicates,return=minimal',body:{intel_id:intelId,user_id:owner,video_id:p.video_id,channel_id:p.channel_id||null,channel_name:capture.source||null,creator_lane:p.creator_lane||'competitive',event_type:'competitive_test',start_ms:x.start_ms,end_ms:null,prominence:x.prominence,evidence:x.evidence,transcript_provider:'supadata',transcript_mode:'native'}}).catch(()=>null);saved++;output.push({...x,entity_name:card.name,intel_id:intelId})}
 if(saved){await rpc('refresh_market_intel_entity_links',{}).catch(()=>null);await rpc('refresh_market_intel_evaluations',{}).catch(()=>null)}await rest(`source_captures?capture_id=eq.${encodeURIComponent(capture.capture_id)}&user_id=eq.${encodeURIComponent(owner)}`,{method:'PATCH',body:{metadata_json:{...(capture.metadata_json||{}),events_saved:saved,deterministic_events_saved:saved,deterministic_processed_at:new Date().toISOString(),deterministic_candidate_count:candidates.length,deterministic_version:3}}}).catch(()=>null);return J({ok:true,processed:1,video_id:p.video_id,deck_url:p.deck_url,deck_card_count:cards.length,candidates:candidates.length,events_saved:saved,events:output})
 }catch(e){return J({error:(e as Error).message},502)}});
