const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const age=t=>{if(!t)return'—';const ms=Math.max(0,Date.now()-new Date(t).getTime()),m=Math.round(ms/60000);if(m<2)return'now';if(m<60)return`${m}m`;const h=Math.round(m/60);return h<48?`${h}h`:`${Math.round(h/24)}d`};
let opsLoading=null,opsLoadedAt=0;

function stateClass(status){const s=String(status||'').toLowerCase();return s==='failed'?'danger':s==='completed'?'success':s==='running'||s==='queued'||s==='claimed'?'accent':'muted'}
function jobLabel(j){const p=j.progress_json||{};return p.set_slug||p.setSlug||p.feed||p.stage||j.action||'operation'}
function detail(j){if(j.error_message)return String(j.error_message);const p=j.progress_json||{};return [j.source,j.action,p.status,p.message,p.pausedBy].filter(Boolean).join(' · ')||'No additional detail'}
function opRow(j){return `<div class="cx-adminv-op-row"><span class="cx-ui-status ${stateClass(j.status)}">${esc(j.status||'unknown')}</span><span class="cx-adminv-op-main"><strong>${esc(jobLabel(j))}</strong><small>${esc(detail(j))}</small></span><span class="cx-adminv-op-age"><strong>${esc(age(j.created_at))}</strong><small>created</small></span></div>`}

function overview(){return document.querySelector('#cxAdminConsole [data-admin-panel="overview"]')}
function singles(){return document.querySelector('#cxAdminConsole [data-admin-panel="singles"]')}
function sealed(){return document.querySelector('#cxAdminConsole [data-admin-panel="sealed"]')}
function system(){return document.querySelector('#cxAdminConsole [data-admin-panel="system"]')}

function moveAlerts(){const panel=overview(),alerts=document.getElementById('cxAdminAlerts'),cards=document.getElementById('cxAdminOverviewCards');if(!panel||!alerts)return;if(alerts.parentElement!==panel){cards?.insertAdjacentElement('afterend',alerts);if(!cards)panel.prepend(alerts)}}
function moveMarketplaceHealth(){const panel=singles(),health=document.querySelector('.cx-marketplace-health'),summary=document.getElementById('cxAdminSinglesSummary');if(!panel||!health)return;health.classList.add('cx-adminv-scan-health');if(health.parentElement!==panel){summary?.insertAdjacentElement('afterend',health);if(!summary)panel.prepend(health)}}
function adoptPrimitives(){document.querySelectorAll('#cxAdminConsole .cx-admin-tabs').forEach(x=>x.classList.add('cx-ui-tabs'));document.querySelectorAll('#cxAdminConsole .cx-admin-summary-grid').forEach(x=>x.classList.add('cx-ui-metrics'));document.querySelectorAll('#cxAdminConsole .cx-admin-summary-card').forEach(x=>x.classList.add('cx-ui-metric'));document.querySelectorAll('#cxAdminConsole .cx-admin-status').forEach(x=>x.classList.add('cx-ui-status'))}

function wrapRuntime(){const panel=system(),runtime=panel?.querySelector('.cx-runtime-health');if(!panel||!runtime||runtime.closest('.cx-adminv-runtime'))return;const d=document.createElement('details');d.className='cx-adminv-runtime';d.innerHTML='<summary><span><strong>Runtime diagnostics</strong><small>Performance, transport, retries and endpoint cost</small></span><b>Show</b></summary><div class="cx-adminv-runtime-body"></div>';runtime.insertAdjacentElement('beforebegin',d);d.querySelector('.cx-adminv-runtime-body').appendChild(runtime);d.addEventListener('toggle',()=>{d.querySelector('summary b').textContent=d.open?'Hide':'Show'})}
function compactSealed(){const panel=sealed(),catalog=panel?.querySelector('#cxAdminSealedCatalog');if(!panel||!catalog)return;catalog.classList.add('cx-adminv-sealed-catalog');const sources=document.getElementById('cxAdminSealedSources');sources?.classList.add('cx-ui-list')}

async function loadOps(force=false){const panel=overview();if(!panel)return;let host=panel.querySelector('#cxAdminOpsVnext');if(!host){host=document.createElement('section');host.id='cxAdminOpsVnext';host.className='cx-adminv-ops';const modules=panel.querySelector('#cxAdminOverviewModules');modules?.insertAdjacentElement('beforebegin',host);if(!modules)panel.appendChild(host)}const fresh=Date.now()-opsLoadedAt<60000;if((fresh&&!force)||opsLoading)return opsLoading;if(!host.dataset.ready)host.innerHTML='<div class="cx-admin-loading">Loading recent operations…</div>';else host.classList.add('refreshing');opsLoading=rest('collector_jobs?select=source,action,status,error_message,created_at,available_at,progress_json&order=created_at.desc&limit=30').then(rows=>{const jobs=Array.isArray(rows)?rows:[],failed=jobs.filter(x=>x.status==='failed').length,running=jobs.filter(x=>['running','queued','claimed'].includes(x.status)).length;host.innerHTML=`<div class="cx-adminv-ops-head"><div><strong>Recent operations</strong><small>${jobs.length} latest · ${failed} failed · ${running} active/queued</small></div><button type="button" class="cx-secondary" data-adminv-system>System</button></div><div class="cx-adminv-op-list cx-ui-list">${jobs.length?jobs.map(opRow).join(''):'<div class="cx-empty">No recent jobs.</div>'}</div>`;host.dataset.ready='1';host.querySelector('[data-adminv-system]')?.addEventListener('click',()=>window.CollectishAdminConsole?.show?.('system'));opsLoadedAt=Date.now()}).catch(e=>{if(!host.dataset.ready)host.innerHTML=`<div class="cx-admin-error">Recent operations unavailable: ${esc(e?.message||e)}</div>`}).finally(()=>{host.classList.remove('refreshing');opsLoading=null});return opsLoading}

function reconcile(){const admin=document.getElementById('cxAdmin');if(!admin?.classList.contains('active'))return;moveAlerts();moveMarketplaceHealth();adoptPrimitives();wrapRuntime();compactSealed();const section=document.getElementById('cxAdminConsole')?.dataset.activeSection;if(section==='overview')void loadOps(false)}
function schedule(){for(const ms of [0,80,240])setTimeout(reconcile,ms)}

document.addEventListener('collectish:admin-modules-ready',schedule);document.addEventListener('collectish:admin-section-change',e=>{schedule();if(e.detail?.section==='overview')void loadOps(false)});document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='admin')schedule()});document.addEventListener('collectish:admin-marketplace-health',schedule);document.addEventListener('collectish:runtime-health',()=>setTimeout(()=>{wrapRuntime();adoptPrimitives()},40));document.addEventListener('collectish:ready',schedule);queueMicrotask(schedule);
window.CollectishAdminVnext={reconcile,refreshOperations:()=>loadOps(true)};
