// CardTrader sealed operational health in Admin > Sealed.
(() => {
  let loading=false;
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const age=t=>{if(!t)return'Never';const ms=Math.max(0,Date.now()-new Date(t).getTime()),m=Math.round(ms/6e4);if(m<60)return m<=1?'just now':`${m}m ago`;const h=Math.round(m/60);return h<24?`${h}h ago`:`${Math.round(h/24)}d ago`};
  const metric=(label,value,sub,state='neutral')=>`<div class="cx-admin-summary-card ${esc(state)}"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`;
  function ensure(){const host=document.getElementById('cxAdminSealedSources');if(!host)return null;let box=document.getElementById('cxAdminCardTraderHealth');if(!box){box=document.createElement('section');box.id='cxAdminCardTraderHealth';box.className='cx-card';box.innerHTML='<div class="cx-section-title">CardTrader / Zero</div><div class="cx-admin-summary-grid" data-ct-health-cards><div class="cx-admin-loading">Loading CardTrader health…</div></div><div data-ct-health-detail class="cx-admin-source-list"></div>';host.prepend(box)}return box}
  async function load(){if(loading)return;const active=document.getElementById('cxAdminConsole')?.dataset.activeSection==='sealed';if(!active)return;const box=ensure();if(!box)return;loading=true;try{
    const [sync,maps,prices]=await Promise.all([
      rest('mtgjson_sync_state?select=feed,status,last_completed_at,row_count,detail&feed=in.(cardtrader_catalog,cardtrader_sealed_map,cardtrader_sealed_prices,cardtrader_landed_model,cardtrader_zero_trends,cardtrader_zero_opportunities,cardtrader_zero_shadow_score)'),
      rest('cardtrader_sealed_map?select=sealed_uuid,cardtrader_blueprint_id,match_method,identity_conflict,conflict_detail&limit=5000'),
      rest('sealed_product_price_current?select=sealed_uuid,captured_at,raw_json&source=eq.cardtrader&limit=1000')
    ]);
    const sm=new Map((sync||[]).map(x=>[x.feed,x]));const mapped=(maps||[]).filter(x=>!x.identity_conflict).length,conflicts=(maps||[]).filter(x=>x.identity_conflict).length;
    const ct=(prices||[]),zero=ct.filter(x=>Number(x.raw_json?.ct_zero?.quantity||0)>0).length,opps=ct.filter(x=>x.raw_json?.ct_zero_opportunity?.eligible===true).length,strong=ct.filter(x=>x.raw_json?.ct_zero_opportunity?.tier==='strong').length,tight=ct.filter(x=>['tightening','strong_tightening'].includes(x.raw_json?.ct_zero_trend?.signal)).length;
    const last=ct.map(x=>x.captured_at).filter(Boolean).sort().at(-1)||null;const priceState=last&&Date.now()-new Date(last).getTime()<12*36e5?'good':'warn';
    box.querySelector('[data-ct-health-cards]').innerHTML=[metric('Exact mappings',String(mapped),`${conflicts} quarantined conflicts`,conflicts?'warn':'good'),metric('Current CT rows',String(ct.length),last?`synced ${age(last)}`:'no observations',priceState),metric('CT0 stocked',String(zero),`${opps} opportunities · ${strong} strong`,'good'),metric('Tightening',String(tight),tight?'supply pressure detected':'history building / stable',tight?'warn':'neutral')].join('');
    const feeds=['cardtrader_catalog','cardtrader_sealed_map','cardtrader_sealed_prices','cardtrader_landed_model','cardtrader_zero_trends','cardtrader_zero_opportunities','cardtrader_zero_shadow_score'];
    box.querySelector('[data-ct-health-detail]').innerHTML=feeds.map(feed=>{const s=sm.get(feed),state=s?.status==='complete'?'good':s?.status==='complete_with_warnings'?'warn':s?.status?'bad':'neutral';return `<div class="cx-admin-source-row"><div><strong>${esc(feed.replace(/^cardtrader_/, '').replaceAll('_',' '))}</strong><small>${esc(s?.detail?.version||'')}</small></div><div class="cx-admin-source-meta"><span class="cx-admin-status ${state}">${esc((s?.status||'unknown').toUpperCase())}</span><b>${esc(age(s?.last_completed_at))}</b><small>${esc(s?.row_count==null?'':`${s.row_count} rows`)}</small></div></div>`}).join('')+(conflicts?`<div class="cx-sealed-summary"><strong>${conflicts} identity conflicts remain quarantined.</strong> CardTrader pricing is not consumed for those rows until the Cardmarket/TCGplayer disagreement is resolved.</div>`:'');
  }catch(e){box.querySelector('[data-ct-health-cards]').innerHTML=`<div class="cx-admin-error">CardTrader health unavailable: ${esc(e.message||e)}</div>`}finally{loading=false}}
  document.addEventListener('collectish:admin-section-change',e=>{if(e.detail?.section==='sealed')setTimeout(load,80)});document.addEventListener('click',e=>{if(e.target.closest?.('[data-cx-page="admin"]'))setTimeout(load,350)},true);window.CollectishAdminCardTraderHealth={refresh:load};
})();