const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const age=t=>{if(!t)return'—';const ms=Math.max(0,Date.now()-new Date(t).getTime()),m=Math.round(ms/60000);if(m<2)return'now';if(m<60)return`${m}m`;const h=Math.round(m/60);return h<48?`${h}h`:`${Math.round(h/24)}d`};
let loading=null;

function installStyle(){if(document.getElementById('cxAdminOpsVnextStyle'))return;const s=document.createElement('style');s.id='cxAdminOpsVnextStyle';s.textContent=`
#cxAdminOpsVnext{margin-top:12px}.cx-admin-ops-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:7px}.cx-admin-ops-head>div{display:grid;gap:2px}.cx-admin-ops-head strong{font-size:13px}.cx-admin-ops-head small{font-size:9px;color:var(--color-text-secondary)}.cx-admin-ops-list{border:1px solid var(--color-border);border-radius:10px;overflow:hidden;background:var(--color-bg-surface)}.cx-admin-ops-row{display:grid;grid-template-columns:88px minmax(180px,1.2fr) minmax(220px,1.4fr) 80px;gap:8px;align-items:center;padding:7px 10px;border-top:1px solid var(--color-border);min-height:44px}.cx-admin-ops-row:first-child{border-top:0}.cx-admin-ops-row strong,.cx-admin-ops-row small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cx-admin-ops-row strong{font-size:10.5px}.cx-admin-ops-row small{font-size:8.5px;color:var(--color-text-secondary)}.cx-admin-ops-status{display:inline-flex;width:max-content;border-radius:999px;padding:3px 6px;font-size:8px;font-weight:850;text-transform:uppercase}.cx-admin-ops-status.completed{color:var(--color-success);background:color-mix(in srgb,var(--color-success) 14%,transparent)}.cx-admin-ops-status.failed{color:var(--color-danger);background:color-mix(in srgb,var(--color-danger) 14%,transparent)}.cx-admin-ops-status.queued,.cx-admin-ops-status.running{color:var(--color-accent);background:color-mix(in srgb,var(--color-accent) 14%,transparent)}.cx-admin-ops-status.other{color:var(--color-text-secondary);background:color-mix(in srgb,var(--color-text-secondary) 12%,transparent)}.cx-admin-ops-age{text-align:right;font-variant-numeric:tabular-nums}.cx-admin-overview-vnext #cxAdminAlerts{margin:0 0 12px!important}.cx-admin-overview-vnext #cxAdminAlerts .cx-admin-alert-list{display:grid;gap:6px}.cx-admin-overview-vnext #cxAdminAlerts .cx-admin-alert{padding:9px 10px!important}
@media(max-width:760px){.cx-admin-ops-row{grid-template-columns:78px minmax(0,1fr) 52px;grid-template-areas:'status task age' 'status detail detail';row-gap:2px}.cx-admin-ops-row>.cx-admin-ops-status{grid-area:status}.cx-admin-ops-task{grid-area:task}.cx-admin-ops-detail{grid-area:detail}.cx-admin-ops-age{grid-area:age}.cx-admin-ops-row{min-height:48px;padding:6px 8px}}
`;document.head.appendChild(s)}
function jobLabel(j){const p=j.progress_json||{};return p.set_slug||p.setSlug||p.feed||p.stage||j.action||'operation'}
function detail(j){if(j.error_message)return String(j.error_message);const p=j.progress_json||{};const bits=[j.source,j.action,p.status,p.message,p.pausedBy].filter(Boolean);return bits.join(' · ')||'No additional detail'}
function row(j){const state=['completed','failed','queued','running'].includes(String(j.status))?String(j.status):'other';return `<div class="cx-admin-ops-row"><span class="cx-admin-ops-status ${state}">${esc(j.status||'unknown')}</span><span class="cx-admin-ops-task"><strong>${esc(jobLabel(j))}</strong><small>${esc([j.source,j.action].filter(Boolean).join(' · '))}</small></span><span class="cx-admin-ops-detail"><strong>${esc(detail(j))}</strong><small>${j.available_at?`available ${esc(age(j.available_at))}`:''}</small></span><span class="cx-admin-ops-age"><strong>${esc(age(j.created_at))}</strong><small>created</small></span></div>`}
function moveAlerts(){const shell=document.getElementById('cxAdminConsole'),overview=shell?.querySelector('[data-admin-panel="overview"]'),alerts=document.getElementById('cxAdminAlerts');if(!overview||!alerts)return;overview.classList.add('cx-admin-overview-vnext');const cards=overview.querySelector('#cxAdminOverviewCards');if(alerts.parentElement!==overview){if(cards)cards.insertAdjacentElement('afterend',alerts);else overview.prepend(alerts)}}
async function render(){installStyle();moveAlerts();const shell=document.getElementById('cxAdminConsole'),overview=shell?.querySelector('[data-admin-panel="overview"]');if(!overview)return;let host=overview.querySelector('#cxAdminOpsVnext');if(!host){host=document.createElement('section');host.id='cxAdminOpsVnext';const modules=overview.querySelector('#cxAdminOverviewModules');if(modules)overview.insertBefore(host,modules);else overview.appendChild(host)}if(loading)return;host.innerHTML='<div class="cx-empty">Loading recent operations…</div>';loading=rest('collector_jobs?select=source,action,status,error_message,created_at,available_at,progress_json&order=created_at.desc&limit=30').then(rows=>{const jobs=Array.isArray(rows)?rows:[];const failed=jobs.filter(x=>x.status==='failed').length,running=jobs.filter(x=>x.status==='running'||x.status==='queued').length;host.innerHTML=`<div class="cx-admin-ops-head"><div><strong>Recent operations</strong><small>${jobs.length} latest jobs · ${failed} failed · ${running} queued/running</small></div><button type="button" class="cx-refresh" data-admin-ops-system>System</button></div><div class="cx-admin-ops-list">${jobs.length?jobs.map(row).join(''):'<div class="cx-empty">No recent jobs.</div>'}</div>`;host.querySelector('[data-admin-ops-system]')?.addEventListener('click',()=>window.CollectishAdminConsole?.show?.('system'))}).catch(e=>{host.innerHTML=`<div class="cx-empty">Recent operations unavailable: ${esc(e?.message||e)}</div>`}).finally(()=>{loading=null;moveAlerts()});return loading}
function schedule(){setTimeout(()=>{moveAlerts();void render()},40)}
document.addEventListener('collectish:admin-modules-ready',schedule);document.addEventListener('collectish:admin-section-change',e=>{if(e.detail?.section==='overview')schedule()});document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='admin')schedule()});document.addEventListener('collectish:ready',()=>{if(document.getElementById('cxAdmin')?.classList.contains('active'))schedule()});queueMicrotask(schedule);
