import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:any)=>String(v??'').trim();
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const money=(v:any)=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:'—';
const pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(1)}%`:'—';
const sourceLabel=(v:any)=>({direct_pressure:'Direct pressure',sales_acceleration:'Sales acceleration',cross_market:'Cross-market',tcgplayer_climbing:'TCGplayer climbing',mtgstocks:'MTGStocks',syp:'SYP',edh_demand:'EDH demand',creator_catalyst:'Creator catalyst'})[String(v)]||String(v||'');
async function callRoute(name:string,body:any,auth:string){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:{apikey:S,Authorization:auth||`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.error||`${name} ${r.status}`);return d}
async function upstream(body:any,auth:string){const deterministic=await callRoute('ask-collectish-route-intents',body,auth);return deterministic?.handled?deterministic:callRoute('ask-collectish-delvin-route',body,auth)}
const itemLabel=(r:any)=>text(r?.card_name||r?.product_name||r?.treatment||r?.set_code||r?.name||'Item');
function standardRow(r:any){return {title:itemLabel(r),subtitle:[r?.set_code,r?.printing,r?.collectible_tier].filter(Boolean).join(' · '),metrics:[['Market',r?.sku_market_price??r?.market_price,'money'],['Score',r?.radar_score??r?.opportunity_score??r?.demand_score??r?.catalyst_score??r?.cohort_score??r?.signal_score,'number'],['Sales/day',r?.avg_daily_qty_sold??r?.sales_day,'number1'],['Direct',r?.direct_available,'number']].filter(x=>x[1]!=null).map(([label,value,kind])=>({label,value,display:kind==='money'?money(value):kind==='number1'?num(value,1):num(value)})),raw:r}}
function radarPresentation(d:any){const rows=Array.isArray(d?.data?.payload?.rows)?d.data.payload.rows:[];const sections=['Confirmed','Converging','Watch','Single-source'].map(tier=>({heading:tier,kind:'ranked_rows',rows:rows.filter((r:any)=>(r.evidence_tier||'Single-source')===tier).slice(0,tier==='Single-source'?5:6).map((r:any)=>({title:itemLabel(r),subtitle:[r.set_code,`${num(r.radar_score)} radar`,`${r.source_count||1} signal${Number(r.source_count||1)===1?'':'s'}`].filter(Boolean).join(' · '),badges:(r.sources||[]).map(sourceLabel),note:(r.evidence||[]).slice(0,2).map((e:any)=>sourceLabel(e.source)).join(' + '),raw:r}))})).filter((s:any)=>s.rows.length);return{version:1,type:'market_radar',title:'Delvin market radar',summary:'Current cross-source candidates ranked by convergence and radar score.',sections,footnote:'Single-source = investigate, not confirmation.',actions:[{type:'ask',label:'Sales acceleration',prompt:'What cards suddenly started selling faster?'},{type:'ask',label:'Direct pressure',prompt:'What Direct cards are getting tight?'},{type:'ask',label:'SYP pressure',prompt:'What SYP changes look most meaningful this week?'}]}}
function cohortPresentation(d:any){const x=d?.data||{},s=x?.summary||x?.basket||x,rows=Array.isArray(x?.rows)?x.rows:[];const metrics=[];if(s?.basket_current!=null||s?.current_value!=null)metrics.push({label:'Current basket',value:s.basket_current??s.current_value,display:money(s.basket_current??s.current_value)});if(s?.basket_change_pct!=null||s?.change_pct!=null)metrics.push({label:'Cumulative',value:s.basket_change_pct??s.change_pct,display:pct(s.basket_change_pct??s.change_pct)});if(s?.median_change_pct!=null)metrics.push({label:'Median printing',value:s.median_change_pct,display:pct(s.median_change_pct)});if(s?.history_start)metrics.push({label:'History starts',value:s.history_start,display:String(s.history_start).slice(0,10)});return{version:1,type:'collectible_cohort_thesis',title:`${s?.treatment||'Collectible'} cohort thesis`,summary:Array.isArray(s?.set_codes)&&s.set_codes.length?`One-of-each collection across ${s.set_codes.join(' + ')}.`:'One-of-each collectible cohort.',metrics,sections:rows.length?[{heading:'Top contributors',kind:'ranked_rows',rows:rows.slice(0,10).map((r:any)=>({title:itemLabel(r),subtitle:[r.set_code,r.printing].filter(Boolean).join(' · '),metrics:[{label:'Change',value:r.change_pct??r.market_change_pct,display:pct(r.change_pct??r.market_change_pct)}],raw:r}))}]:[],footnote:s?.history_start?'Uses available stored/backfilled price history; slower collectible liquidity should be interpreted separately from price trend.':null,actions:[]}}
function rowsPresentation(d:any){const x=d?.data||{},rows=Array.isArray(x?.rows)?x.rows:Array.isArray(x)?x:[];const title=({edh_demand_7d:'EDH demand movers',creator_catalysts_7d:'Creator / catalyst movers',market_changes:'What changed in Delvin',signal_followthrough:'Delvin signal follow-through',collectible_family_index:'Collectible family across sets',set_intelligence:'Set intelligence',treatment_intelligence:'Treatment intelligence',printing_family:'Printing family',card_investigation:'Card investigation'} as any)[d.route]||String(d.route||'Delvin intelligence').replaceAll('_',' ');return{version:1,type:d.route||'delvin_report',title,summary:rows.length?`${rows.length} qualifying result${rows.length===1?'':'s'}.`:'No qualifying rows right now.',sections:rows.length?[{heading:'Results',kind:'ranked_rows',rows:rows.slice(0,20).map(standardRow)}]:[],footnote:null,actions:[]}}
function sealedPresentation(d:any){const s=(d?.surfaces||[]).find((x:any)=>x?.type==='sealed_purchase_decision');if(!s)return rowsPresentation(d);return{version:1,type:'sealed_purchase_decision',title:`${s.title||'Sealed decision'} — ${s.verdict||'WATCH'}`,summary:s.action||d.response||'',badges:[],metrics:[{label:'Market',value:s.market_price,display:money(s.market_price)},{label:'MSRP',value:s.msrp,display:money(s.msrp)},{label:'Modeled EV',value:s.gross_mean_ev,display:`${money(s.gross_mean_ev)} gross\n${money(s.net_mean_ev_after_fees)} net`}].filter(x=>x.value!=null),sections:[...(s.why?.length?[{heading:`Why ${s.verdict}`,kind:'bullets',items:s.why}]:[]),...(s.changes?.length?[{heading:'What could change it',kind:'bullets',items:s.changes}]:[]),...(s.buy_zone?[{heading:'Buy zone',kind:'text',text:s.buy_zone}]:[]),...(s.recheck?[{heading:'Recheck',kind:'text',text:s.recheck}]:[])],footnote:null,actions:[],image_url:s.image_url||null}}
function sealedCrackPresentation(d:any){const s=(d?.surfaces||[]).find((x:any)=>x?.type==='sealed_crack_ranking'),rows=Array.isArray(s?.rows)?s.rows:[];return{version:1,type:'sealed_crack_ranking',title:s?.title||'Sealed → Direct crack candidates',summary:d.response||'',metrics:[{label:'True buys',value:rows.filter((r:any)=>r.verdict==='BUY & CRACK').length,display:String(rows.filter((r:any)=>r.verdict==='BUY & CRACK').length)},{label:'Watch',value:rows.filter((r:any)=>String(r.verdict).startsWith('WATCH')).length,display:String(rows.filter((r:any)=>String(r.verdict).startsWith('WATCH')).length)},{label:'Modeled',value:rows.length,display:String(rows.length)}],sections:rows.length?[{heading:'Ranked products',kind:'ranked_rows',rows:rows.map((r:any)=>({title:r.product_name,subtitle:[r.set_code,r.verdict].filter(Boolean).join(' · '),metrics:[{label:'Buy',value:r.acquisition_price,display:money(r.acquisition_price)},{label:'Direct net',value:r.direct_first_net_ev,display:money(r.direct_first_net_ev)},{label:'Direct ROI',value:r.direct_roi_pct,display:pct(r.direct_roi_pct)},{label:'Practical ROI',value:r.practical_roi_pct,display:pct(r.practical_roi_pct)}],raw:r}))}]:[],footnote:'Direct-first net is modeled outlet value. BUY & CRACK still requires positive practical EV after liquidity and execution discounts.',actions:s?.actions||[]}}
function presentation(d:any){if(d?.route==='market_radar')return radarPresentation(d);if(d?.route==='collectible_cohort_thesis')return cohortPresentation(d);if(d?.route==='sealed_aftermarket_decision')return sealedPresentation(d);if(d?.route==='sealed_direct_crack_ranking')return sealedCrackPresentation(d);return rowsPresentation(d)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);const body=await req.json().catch(()=>({}));const q=text(body?.question||body?.message);if(!q)return js({handled:false});try{const auth=req.headers.get('authorization')||`Bearer ${S}`,d=await upstream({...body,question:q},auth);if(!d?.handled)return js(d||{handled:false});const p=presentation(d);return js({...d,presentation:p,presentation_version:1,surfaces:[...(Array.isArray(d.surfaces)?d.surfaces:[]),{type:'delvin_shared_report',domain:'collectish',...p}]})}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});
