import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const OPENAI=Deno.env.get('OPENAI_API_KEY')||'';
const MODEL=Deno.env.get('MARKET_INTEL_MODEL')||Deno.env.get('ASK_COLLECTISH_MODEL')||'gpt-5-mini';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const H=()=>({apikey:S||A,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const trim=(x:any,n=2000)=>String(x??'').trim().slice(0,n);
const clamp=(x:any)=>Number.isFinite(Number(x))?Math.max(0,Math.min(1,Number(x))):0.5;
const norm=(s:any)=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TYPES=new Set(['commander_showcase','commander_recommendation','precon_reveal','reprint_reveal','new_commander_synergy','precon_upgrade','precon_cut','spoiler_reaction','other']);

async function serviceAuth(t:string){if(!t)return false;if(S&&t===S)return true;try{const r=await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}});return r.ok}catch{return false}}
async function rest(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function rpc(name:string,args:any={}){return rest(`rpc/${name}`,{method:'POST',body:args})}
function mmss(ms:number){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function parseJson(raw:string){const s=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),z=s.lastIndexOf('}');if(a>=0&&z>a){const x=s.slice(a,z+1);try{return JSON.parse(x)}catch{}try{return JSON.parse(x.replace(/,\s*([}\]])/g,'$1'))}catch{}}throw Error('invalid JSON')}
async function oa(prompt:string,max=2200){if(!OPENAI)throw Error('OPENAI_API_KEY not configured');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,store:false,input:prompt,max_output_tokens:max})});const raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{d={error:{message:raw}}}if(!r.ok)throw Error(d?.error?.message||`OpenAI ${r.status}`);let out='';for(const x of d?.output||[])if(x.type==='message')for(const c of x.content||[])if(c.type==='output_text')out+=c.text;return out}
async function parsed(prompt:string){try{return parseJson(await oa(prompt))}catch{try{return parseJson(await oa(`Repair into valid JSON {"events":[]}. Keep only complete event objects. INPUT:\n${(await oa(prompt,1800)).slice(0,15000)}`,1200))}catch{return{events:[]}}}}
function windows(segments:any[]){const clean=segments.map(x=>({text:trim(x?.text,1200),offset:Number(x?.offset)||0})).filter(x=>x.text);const chars=clean.reduce((n,x)=>n+x.text.length,0),count=Math.max(1,Math.min(5,Math.ceil(chars/12000))),per=Math.ceil(clean.length/count),out:any[]=[];for(let i=0;i<count;i++){const a=Math.max(0,i*per-(i?2:0)),b=Math.min(clean.length,(i+1)*per+(i<count-1?2:0)),s=clean.slice(a,b);if(s.length)out.push(s.map(x=>`[${mmss(x.offset)}] ${x.text}`).join('\n'))}return out}
function prompt(text:string,channel:string,title:string){return `Extract actionable Magic: The Gathering Commander/product video card signals. Return ONLY JSON {"events":[{"raw_mention":string,"canonical_name":string,"event_type":"commander_showcase"|"commander_recommendation"|"precon_reveal"|"reprint_reveal"|"new_commander_synergy"|"precon_upgrade"|"precon_cut"|"spoiler_reaction"|"other","direction":"bullish"|"bearish"|"neutral","start_ms":integer,"prominence":number,"confidence":number,"evidence":string,"summary":string}]}. Return at most 8 strongest events in this window. IMPORTANT: explicit Commander judgments ARE actionable. Phrases such as 'obvious include', 'perfect', 'this card is busted', 'really powerful', 'a lot more powerful than it looks', 'works really well', 'you will want', 'I would combine this with', 'great in this deck', or a memorable showcased interaction qualify. For a NEW commander/card being evaluated positively, use spoiler_reaction. For an EXISTING card specifically recommended because of a new commander, use new_commander_synergy. Use commander_recommendation for general EDH recommendations, commander_showcase for a defining gameplay/display moment, reprint_reveal only for an explicitly confirmed reprint, and precon_upgrade/precon_cut only for explicit add/cut advice. Routine rules explanation or merely reading a card does NOT qualify. prominence >= .55. Preserve the spoken phrase in raw_mention but canonical_name should be the likely printed MTG card name. Use exact timestamp markers: [08:59] = 539000 ms. Channel=${channel}. Video=${title}. Transcript:\n${text}`}
function edit(a:string,b:string){const x=norm(a),y=norm(b);let p=Array.from({length:y.length+1},(_,i)=>i);for(let i=1;i<=x.length;i++){const c=[i];for(let j=1;j<=y.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(x[i-1]===y[j-1]?0:1));p=c}return p[y.length]}
function sim(a:string,b:string){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x===y)return 1;return 1-edit(x,y)/Math.max(x.length,y.length)}
async function card(name:string){for(const mode of ['exact','fuzzy'] as const){try{const r=await fetch(`https://api.scryfall.com/cards/named?${mode}=${encodeURIComponent(name)}`,{headers:{'User-Agent':'MarketplaceScout/0.9 (+commander video signals)'}});if(!r.ok)continue;const c=await r.json();if(c?.id&&(mode==='exact'||sim(name,c.name)>=.72))return{name:String(c.name),id:String(c.id),set:String(c.set||'')}}catch{}}return null}
function claim(type:string){return type==='reprint_reveal'?'reprint':(['precon_reveal','new_commander_synergy','precon_upgrade','precon_cut','spoiler_reaction'].includes(type)?'product':'demand')}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);
 const t=bearer(req);if(!t||!(await serviceAuth(t)))return J({error:'Service authentication required'},401);if(!S)return J({error:'Service role unavailable'},500);
 let b:any={};try{b=await req.json()}catch{}const target=trim(b?.video_id,100),force=!!b?.force;
 try{
  const rows=await rest('source_captures?select=capture_id,user_id,source,payload_json,metadata_json&capture_type=eq.video_transcript&order=captured_at.desc&limit=100');let cap:any=null;
  for(const r of rows||[]){const p=r.payload_json||{};if(!UUID.test(String(r.user_id||''))||r?.metadata_json?.status!=='saved')continue;if(p.creator_lane!=='commander_product'&&p.creator_lane!=='commander_gameplay')continue;if(target&&p.video_id!==target)continue;if(!Array.isArray(p.segments)||!p.segments.length)continue;if(!force&&Number(r?.metadata_json?.commander_events_saved||0)>0)continue;cap=r;break}
  if(!cap)return J({ok:true,processed:0,events_saved:0,reason:'no_eligible_cached_commander_video'});
  const p=cap.payload_json,owner=String(cap.user_id),ws=windows(p.segments),batches=await Promise.all(ws.map(async w=>{const d=await parsed(prompt(w,String(cap.source||'YouTube'),String(p.title||'')));return Array.isArray(d?.events)?d.events.slice(0,8):[]}));
  const candidates:any[]=[],seen=new Set<string>();for(const x of batches.flat()){const name=trim(x?.canonical_name||x?.raw_mention,300),start=Math.max(0,Math.round(Number(x?.start_ms)||0)),type=TYPES.has(String(x?.event_type))?String(x.event_type):'other',k=`${norm(name)}|${type}|${start}`;if(!name||seen.has(k)||clamp(x?.prominence)<.55)continue;seen.add(k);candidates.push({...x,canonical_name:name,start_ms:start,event_type:type})}
  candidates.sort((a,b)=>clamp(b.prominence)-clamp(a.prominence)||a.start_ms-b.start_ms);
  let saved=0,rejected=0,duplicates=0;const output:any[]=[];
  for(const x of candidates.slice(0,20)){const resolved=await card(x.canonical_name);if(!resolved){rejected++;continue}const key=`${p.video_id}|${x.event_type}|${x.start_ms}|${norm(resolved.name)}`,url=p.url||`https://www.youtube.com/watch?v=${p.video_id}`;const existing=await rest(`market_intel_items?select=intel_id,metadata_json&user_id=eq.${encodeURIComponent(owner)}&source_url=eq.${encodeURIComponent(url)}&limit=100`).catch(()=>[]);let intelId=(existing||[]).find((q:any)=>String(q?.metadata_json?.video_event_key||'')===key)?.intel_id||null;if(intelId)duplicates++;
   if(!intelId){const direction=['bullish','bearish','neutral'].includes(String(x.direction))?String(x.direction):(x.event_type==='reprint_reveal'?'bearish':'bullish'),inserted=await rest('market_intel_items',{method:'POST',prefer:'return=representation',body:{user_id:owner,source_type:'youtube',source_name:cap.source||'YouTube',source_url:url,title:p.title||resolved.name,author:cap.source||null,summary:trim(x.summary||x.evidence,1200)||`${resolved.name}: ${x.event_type.replace(/_/g,' ')}`,claim_type:claim(x.event_type),direction,signal_stage:x.event_type==='reprint_reveal'?'confirming':'leading',confidence:clamp(x.confidence),published_at:p.published_at||null,source_profile:'creator_commander',source_subtype:x.event_type,metadata_json:{platform:'youtube',video_id:p.video_id,channel_id:p.channel_id||null,creator_lane:p.creator_lane||'commander_product',transcript_provider:'supadata',transcript_mode:'native',timestamped:true,video_event_key:key,event_type:x.event_type,start_ms:x.start_ms,prominence:clamp(x.prominence),raw_mention:trim(x.raw_mention,300),resolution_method:'commander_fallback_scryfall',resolution_confidence:.92,commander_fallback:true}}});intelId=Array.isArray(inserted)?inserted[0]?.intel_id:null;if(!intelId)continue;await rest('market_intel_entities',{method:'POST',prefer:'return=minimal',body:{intel_id:intelId,user_id:owner,entity_type:'card',entity_name:resolved.name,scryfall_id:resolved.id,set_code:resolved.set,confidence:.92}})}
   await rest('market_intel_video_events',{method:'POST',prefer:'resolution=ignore-duplicates,return=minimal',body:{intel_id:intelId,user_id:owner,video_id:p.video_id,channel_id:p.channel_id||null,channel_name:cap.source||null,creator_lane:p.creator_lane||'commander_product',event_type:x.event_type,start_ms:x.start_ms,end_ms:null,prominence:clamp(x.prominence),evidence:trim(x.evidence,900)||null,transcript_provider:'supadata',transcript_mode:'native'}}).catch(()=>null);saved++;output.push({entity_name:resolved.name,event_type:x.event_type,start_ms:x.start_ms,prominence:clamp(x.prominence),evidence:trim(x.evidence,240),summary:trim(x.summary,300)})}
  if(saved){await rpc('refresh_market_intel_entity_links',{}).catch(()=>null);await rpc('refresh_market_intel_evaluations',{}).catch(()=>null)}
  await rest(`source_captures?capture_id=eq.${encodeURIComponent(cap.capture_id)}&user_id=eq.${encodeURIComponent(owner)}`,{method:'PATCH',body:{metadata_json:{...(cap.metadata_json||{}),events_saved:Math.max(Number(cap?.metadata_json?.events_saved||0),saved),commander_events_saved:saved,commander_processed_at:new Date().toISOString(),commander_candidates:candidates.length,commander_rejected:rejected,commander_model:MODEL}}}).catch(()=>null);
  return J({ok:true,processed:1,video_id:p.video_id,title:p.title,channel:cap.source,window_count:ws.length,candidates:candidates.length,rejected_cards:rejected,duplicates,events_saved:saved,events:output,transcript_credits_used:0});
 }catch(e){return J({error:(e as Error).message},502)}
});
