import store from '../../state/store.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
const spread=r=>{const low=Number(r?.tcg_low||r?.low_with_shipping||0),direct=Number(r?.direct_low||0);return low>0&&direct>0?direct/low:null};
let installed=false,syncingUrl=false;

function params(){return new URL(location.href).searchParams}
function readFilters(){const p=params();return {min:p.get('min')||'',max:p.get('max')||'',spread:p.get('spread')||'',foil:p.get('foil')||''}}
function writeUrl(extra={}){if(syncingUrl)return;const p=params();p.set('tab','scout');const q=document.getElementById('cxParitySearch')?.value?.trim()||'',grade=document.getElementById('cxParityGrade')?.value||'',set=document.getElementById('cxParitySet')?.value||'',merged={...readFilters(),...extra};const setOrDelete=(k,v)=>v?p.set(k,v):p.delete(k);setOrDelete('q',q);setOrDelete('grade',grade);setOrDelete('set',set);setOrDelete('min',merged.min);setOrDelete('max',merged.max);setOrDelete('spread',merged.spread);setOrDelete('foil',merged.foil);history.replaceState({collectish:true},'',`${location.pathname}?${p.toString()}${location.hash}`)}
function rowMatchesAdvanced(r){const f=readFilters(),min=Number(f.min),max=Number(f.max),minSpread=Number(f.spread),price=Number(r?.direct_low||r?.tcg_low||0),sp=spread(r),printing=String(r?.printing||'').toLowerCase();if(f.min&&Number.isFinite(min)&&price<min)return false;if(f.max&&Number.isFinite(max)&&price>max)return false;if(f.spread&&Number.isFinite(minSpread)&&(sp==null||sp<minSpread))return false;if(f.foil==='true'&&!printing.includes('foil'))return false;if(f.foil==='false'&&printing.includes('foil'))return false;return true}
function rowsForAdvanced(){const s=store.get().scout||{},base=(s.visible?.length?s.visible:s.rows)||[];return base.filter(rowMatchesAdvanced)}
function applyVisibility(){const host=document.getElementById('cxParityCards');if(!host)return;const allowed=new Set(rowsForAdvanced().map(r=>String(r.sku_id||'')));for(const card of host.querySelectorAll(':scope > .cx-scout-card'))card.dataset.cxAdvancedMatch=allowed.has(String(card.dataset.sku||''))?'1':'0';document.dispatchEvent(new CustomEvent('collectish:scout-advanced-filters-changed'))}
function ensureControls(){const toolbar=document.querySelector('#cxScout .cx-scout-toolbar');if(!toolbar||toolbar.querySelector('[data-cx-compact-filters]'))return;const f=readFilters(),wrap=document.createElement('div');wrap.dataset.cxCompactFilters='1';wrap.className='cx-scout-compact-filters';wrap.innerHTML=`<input id="cxScoutMin" inputmode="decimal" placeholder="Min $" value="${esc(f.min)}"><input id="cxScoutMax" inputmode="decimal" placeholder="Max $" value="${esc(f.max)}"><input id="cxScoutSpread" inputmode="decimal" placeholder="Min spread" value="${esc(f.spread)}"><select id="cxScoutFoil"><option value="">All finishes</option><option value="false">Nonfoil</option><option value="true">Foil</option></select><button type="button" id="cxScoutShare" class="cx-refresh">Share</button>`;toolbar.appendChild(wrap);wrap.querySelector('#cxScoutFoil').value=f.foil||'';const update=()=>{writeUrl({min:wrap.querySelector('#cxScoutMin').value.trim(),max:wrap.querySelector('#cxScoutMax').value.trim(),spread:wrap.querySelector('#cxScoutSpread').value.trim(),foil:wrap.querySelector('#cxScoutFoil').value});applyVisibility()};wrap.querySelectorAll('input').forEach(el=>el.addEventListener('input',update));wrap.querySelector('#cxScoutFoil').addEventListener('change',update);wrap.querySelector('#cxScoutShare').addEventListener('click',shareTargets)}
function hydrateBaseFiltersFromUrl(){const p=params(),mapping=[['q','cxParitySearch','input'],['grade','cxParityGrade','change'],['set','cxParitySet','change']];syncingUrl=true;for(const [param,id,eventName] of mapping){const v=p.get(param),el=document.getElementById(id);if(v!=null&&el&&el.value!==v){el.value=v;el.dispatchEvent(new Event(eventName,{bubbles:true}))}}syncingUrl=false}
async function shareTargets(){const rows=rowsForAdvanced().slice(0,30),text=rows.map(r=>`${r.product_name} — ${spread(r)?.toFixed(2)||'—'}x — Direct ${money(r.direct_low)} — Low ${money(r.tcg_low)}`).join('\n'),url=location.href;try{if(navigator.share){await navigator.share({title:'Collectish Scout targets',text,url});return}}catch(e){if(e?.name==='AbortError')return}try{await navigator.clipboard.writeText(`${text}\n\n${url}`);document.dispatchEvent(new CustomEvent('collectish:toast',{detail:{message:'Scout targets copied'}}))}catch{}}
function sync(){hydrateBaseFiltersFromUrl();ensureControls();writeUrl();applyVisibility()}
function install(){if(installed)return;installed=true;document.addEventListener('collectish:scout-v5-ready',sync);document.addEventListener('collectish:scout-list-rendered',()=>{ensureControls();writeUrl();applyVisibility()});addEventListener('popstate',()=>{if(params().get('tab')==='scout')sync()});queueMicrotask(()=>{if(document.getElementById('cxScout'))sync()})}
install();window.CollectishScoutCompact={render:applyVisibility,share:shareTargets,matches:rowMatchesAdvanced};
