import { rest } from '../../core/rest.js';

const WARN_MIN=90;
const BAD_MIN=120;
let timer=0;
let last=null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const ageMin=t=>t?Math.max(0,(Date.now()-new Date(t).getTime())/60000):Infinity;
const rel=t=>{if(!t)return'Never';const m=Math.round(ageMin(t));return m<60?`${Math.max(1,m)}m ago`:`${Math.round(m/60)}h ago`};
const secs=ms=>ms==null?'—':`${(Number(ms)/1000).toFixed(1)}s`;
export async function readScoutHealth(){const [cacheRows,stateRows]=await Promise.all([rest('scout_opportunities_v5_cache?select=v5_computed_at&order=v5_computed_at.desc.nullslast&limit=1').catch(()=>[]),rest('mtgjson_sync_state?select=feed,status,last_started_at,last_completed_at,detail&feed=in.(scout_rankings,scout_rankings_watchdog)').catch(()=>[])]);const cacheAt=cacheRows?.[0]?.v5_computed_at||null;const primary=(stateRows||[]).find(x=>x.feed==='scout_rankings')||{};const watchdog=(stateRows||[]).find(x=>x.feed==='scout_rankings_watchdog')||{};const mins=ageMin(cacheAt);const state=primary.status==='failed'||!cacheAt||mins>BAD_MIN?'bad':mins>WARN_MIN?'warn':'good';return{cacheAt,mins,state,primary,watchdog}}
function renderScoutBanner(x){const host=document.getElementById('cxScout');if(!host)return;let banner=document.getElementById('cxScoutFreshnessAlert');if(x.state==='good'){banner?.remove();return}if(!banner){banner=document.createElement('div');banner.id='cxScoutFreshnessAlert';banner.style.cssText='margin:8px 0 12px;padding:10px 12px;border-radius:12px;font-size:12px;font-weight:700';host.querySelector('.cx-page-head')?.insertAdjacentElement('afterend',banner)}banner.style.background=x.state==='bad'?'#fff1f0':'#fff8e6';banner.style.border=`1px solid ${x.state==='bad'?'#ef9a9a':'#e7b85a'}`;banner.style.color='#5b3a16';const phase=x.primary?.detail?.failed_phase||x.primary?.detail?.phase||'';banner.textContent=x.state==='bad'?`Scout rankings stale — promoted cache ${rel(x.cacheAt)}${phase?` · ${phase}`:''}`:`Scout rankings aging — promoted cache ${rel(x.cacheAt)}`}
function renderAdminCard(x){const grid=document.getElementById('cxAdminOverviewCards');if(!grid)return;let card=document.getElementById('cxAdminScoutHealth');if(!card){card=document.createElement('div');card.id='cxAdminScoutHealth';grid.prepend(card)}card.className=`cx-admin-summary-card ${x.state}`;const detail=x.primary?.detail||{},durations=detail.durations_ms||{},failed=detail.failed_phase?` · failed ${detail.failed_phase}`:'';card.innerHTML=`<span>Scout rankings</span><strong>${x.state==='good'?'Healthy':x.state==='warn'?'Aging':'STALE'}</strong><small>Cache ${esc(rel(x.cacheAt))}${esc(failed)}<br>agg ${esc(secs(durations['24h_aggregation']))} · v5 ${esc(secs(durations['v5_shadow']))} · cache ${esc(secs(durations['promoted_cache']))}</small>`;const overall=document.getElementById('cxAdminOverallState');if(overall&&x.state==='bad'){overall.textContent='ATTENTION';overall.className='cx-admin-console-state attention'}}
export function renderScoutHealth(x=last){if(!x)return;renderScoutBanner(x);renderAdminCard(x)}
export async function checkScoutHealth(){try{last=await readScoutHealth();renderScoutHealth(last);document.dispatchEvent(new CustomEvent('collectish:scout-health',{detail:last}));return last}catch(error){console.warn('Scout health monitor',error);return null}}
function schedule(){clearTimeout(timer);if(document.hidden)return;timer=setTimeout(async()=>{await checkScoutHealth();schedule()},60000)}
export function installScoutHealthMonitor(){document.addEventListener('collectish:ready',()=>{setTimeout(checkScoutHealth,400);schedule()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(timer);return}checkScoutHealth();schedule()});document.addEventListener('click',e=>{if(e.target.closest?.('[data-cx-page="scout"],[data-cx-page="admin"],#cxScoutRefresh'))setTimeout(checkScoutHealth,350)},true);document.addEventListener('collectish:admin-section-change',()=>setTimeout(()=>renderScoutHealth(last),0))}
installScoutHealthMonitor();
