import { rest } from '../../core/rest.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let timer=null,seq=0,installed=false;

function ageLabel(ts){if(!ts)return'Never evaluated';const ms=Date.now()-new Date(ts).getTime(),d=Math.floor(ms/86400000);if(d<1)return'Evaluated today';if(d===1)return'Evaluated 1d ago';return`Evaluated ${d}d ago`}
function stateOf(r){if(!r.last_evaluated_at)return{key:'catalog',label:'Catalog-only'};const d=(Date.now()-new Date(r.last_evaluated_at).getTime())/86400000;if(d<=7)return{key:'current',label:'Current'};return{key:'dormant',label:'Dormant'}}
function needsWake(r){const s=stateOf(r);return s.key!=='current'}
function ensureStyle(){if(document.getElementById('cxScoutUniversalStyle'))return;const s=document.createElement('style');s.id='cxScoutUniversalStyle';s.textContent=`
.cx-scout-search-row{position:relative}.cx-universal-results{position:absolute;z-index:50;left:0;right:0;top:calc(100% + 6px);background:var(--cx-surface,#111820);border:1px solid var(--cx-border,#2a3440);border-radius:14px;box-shadow:0 18px 45px rgba(0,0,0,.35);max-height:min(60vh,560px);overflow:auto;padding:6px}.cx-universal-results[hidden]{display:none}.cx-universal-head{padding:8px 10px 6px;font-size:12px;opacity:.7;display:flex;justify-content:space-between;gap:12px}.cx-universal-row{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;text-align:left;background:transparent;color:inherit;border:0;border-radius:10px;padding:10px;cursor:pointer}.cx-universal-row:hover,.cx-universal-row:focus{background:rgba(127,127,127,.12);outline:none}.cx-universal-row strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cx-universal-row small{display:block;opacity:.72;margin-top:2px}.cx-universal-state{font-size:11px;font-weight:700;padding:4px 7px;border-radius:999px;border:1px solid currentColor;white-space:nowrap}.cx-universal-state.current{color:#71d59a}.cx-universal-state.dormant{color:#e4b860}.cx-universal-state.catalog{color:#8ea6bd}.cx-universal-detail{margin:10px 0 14px;border:1px solid var(--cx-border,#2a3440);border-radius:16px;background:var(--cx-surface,#111820);padding:14px;display:grid;grid-template-columns:92px minmax(0,1fr);gap:14px}.cx-universal-detail img{width:92px;border-radius:8px;display:block}.cx-universal-detail h3{margin:0 0 4px;font-size:18px}.cx-universal-meta{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin:8px 0}.cx-universal-chip{font-size:11px;padding:4px 7px;border-radius:999px;background:rgba(127,127,127,.12)}.cx-universal-grade{font-weight:800}.cx-universal-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.cx-universal-actions button,.cx-universal-actions a{border:1px solid var(--cx-border,#2a3440);background:transparent;color:inherit;border-radius:9px;padding:7px 10px;text-decoration:none;font-weight:700}.cx-universal-actions button.primary{background:var(--cx-accent,#2d7ff9);color:white;border-color:transparent}.cx-universal-note{font-size:12px;opacity:.72;margin-top:7px}.cx-universal-empty{padding:12px;opacity:.7}@media(max-width:650px){.cx-universal-results{position:fixed;left:8px;right:8px;top:116px;max-height:58vh}.cx-universal-detail{grid-template-columns:68px minmax(0,1fr);padding:12px}.cx-universal-detail img{width:68px}.cx-universal-detail h3{font-size:16px}}
`;document.head.appendChild(s)}
function host(){return document.getElementById('cxScout')}
function input(){return document.getElementById('cxParitySearch')}
function resultsHost(){const row=input()?.closest('.cx-scout-search-row');if(!row)return null;let h=row.querySelector('#cxUniversalResults');if(!h){h=document.createElement('div');h.id='cxUniversalResults';h.className='cx-universal-results';h.hidden=true;row.appendChild(h)}return h}
function detailHost(){const h=host();if(!h)return null;let d=h.querySelector('#cxUniversalDetail');if(!d){d=document.createElement('div');d.id='cxUniversalDetail';const toolbar=h.querySelector('.cx-scout-toolbar');toolbar?.insertAdjacentElement('afterend',d)}return d}
function resultRow(r){const s=stateOf(r),grade=r.last_grade?`${r.last_grade} ${r.last_score??''}`.trim():'No grade';return `<button type="button" class="cx-universal-row" data-universal-sku="${esc(r.sku_id)}"><span><strong>${esc(r.card_name)}</strong><small>${esc(r.set_code)} · #${esc(r.collector_number||'—')} · ${esc(r.printing||r.finish||'Normal')} · ${esc(grade)}</small></span><span class="cx-universal-state ${s.key}">${esc(s.label)}</span></button>`}
async function search(q){const n=++seq,h=resultsHost();if(!h)return;if(q.trim().length<2){h.hidden=true;h.innerHTML='';return}h.hidden=false;h.innerHTML='<div class="cx-universal-empty">Searching the full Scout catalog…</div>';try{const data=await rest('rpc/scout_catalog_search',{method:'POST',body:{p_query:q.trim(),p_limit:28}});if(n!==seq)return;h.innerHTML=`<div class="cx-universal-head"><span>All Scout printings</span><span>${(data||[]).length} shown</span></div>${(data||[]).length?(data||[]).map(resultRow).join(''):'<div class="cx-universal-empty">No catalog matches.</div>'}`;h._rows=new Map((data||[]).map(r=>[String(r.sku_id),r]))}catch(e){if(n!==seq)return;h.innerHTML=`<div class="cx-universal-empty">Catalog search unavailable: ${esc(e.message||e)}</div>`}}
async function wake(r){try{const out=await rest('rpc/request_scout_refresh',{method:'POST',body:{p_sku_id:r.sku_id,p_reason:'user_open',p_priority:85}});r.refresh_requested_at=new Date().toISOString();return out?.[0]||null}catch(e){return{error:e.message||String(e)}}}
async function open(r){resultsHost().hidden=true;const d=detailHost(),s=stateOf(r),shouldWake=needsWake(r);d.innerHTML='<div class="cx-universal-detail"><div></div><div>Opening Scout printing…</div></div>';const wakeResult=shouldWake?await wake(r):null;const tcg=r.product_id?`https://www.tcgplayer.com/product/${encodeURIComponent(r.product_id)}`:'';const img=r.scryfall_id?`https://api.scryfall.com/cards/${encodeURIComponent(r.scryfall_id)}?format=image&version=normal`:'';const grade=r.last_grade?`${r.last_grade} · ${r.last_score??'—'}/100`:'No Scout grade yet';d.innerHTML=`<section class="cx-universal-detail"><div>${img?`<img src="${esc(img)}" alt="${esc(r.card_name)}">`:''}</div><div><h3>${esc(r.card_name)}</h3><div>${esc(r.set_code)} · #${esc(r.collector_number||'—')} · ${esc(r.printing||r.finish||'Normal')} · ${esc(r.condition||'Near Mint')}</div><div class="cx-universal-meta"><span class="cx-universal-state ${s.key}">${esc(s.label)}</span><span class="cx-universal-chip cx-universal-grade">${esc(grade)}</span><span class="cx-universal-chip">${esc(ageLabel(r.last_evaluated_at))}</span></div><div class="cx-universal-note">${shouldWake?(wakeResult?.error?`Refresh request failed: ${esc(wakeResult.error)}`:wakeResult?.already_open?'A fresh Scout evaluation is already queued.':'A fresh Scout evaluation was queued automatically because this printing is dormant or catalog-only.'):'This printing has a recent Scout evaluation, so opening it did not enqueue another scan.'}</div><div class="cx-universal-actions">${shouldWake?`<button type="button" class="primary" data-universal-refresh="${esc(r.sku_id)}">${wakeResult?.already_open?'Refresh queued':'Refresh queued'}</button>`:''}${tcg?`<a href="${esc(tcg)}" target="_blank" rel="noopener">TCGplayer ↗</a>`:''}<button type="button" data-universal-close>Close</button></div></div></section>`;d._row=r;d.scrollIntoView({behavior:'smooth',block:'nearest'})}
function bind(){ensureStyle();const i=input();if(!i||i.dataset.universalBound)return;i.dataset.universalBound='1';i.placeholder='Search all Magic cards and printings…';i.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(i.value),220)});i.addEventListener('focus',()=>{if(i.value.trim().length>=2)search(i.value)});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-universal-sku]');if(b){const r=resultsHost()?._rows?.get(String(b.dataset.universalSku));if(r)void open(r);return}if(e.target.closest?.('[data-universal-close]')){const d=detailHost();if(d)d.innerHTML='';return}if(!e.target.closest?.('#cxUniversalResults')&&!e.target.closest?.('#cxParitySearch')){const h=resultsHost();if(h)h.hidden=true}},true)}
export function installUniversalScoutSearch(){if(installed)return;installed=true;bind();document.addEventListener('collectish:scout-structure-ready',()=>setTimeout(bind,0));document.addEventListener('collectish:page-change',()=>setTimeout(bind,0))}

installUniversalScoutSearch();
