import { registerComponent } from '../../core/lifecycle.js';
import { loadResource } from '../../state/resources.js';
import { rest } from '../../core/rest.js';

const money=n=>n==null||n===''?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
const pct=n=>n==null||!Number.isFinite(Number(n))?'—':`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`;
const slug=s=>String(s||'').normalize('NFKD').replace(/[’']/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase();
let running=false,lastSignature='';

function productId(article){const href=article.querySelector('a[href*="tcgplayer.com/product/"]')?.href||'';return(href.match(/\/product\/(\d+)/)||[])[1]||''}
function meta(article){const s=article.querySelector('.cx-global-print-title small')?.textContent||'',parts=s.split('·').map(x=>x.trim());return{setCode:(parts[0]||'').toUpperCase(),collector:(parts[1]||'').replace(/^#/,'').trim()}}
function finishFor(v){return /etched/i.test(v||'')?'etched':/foil/i.test(v||'')?'foil':'normal'}
async function batches(pathPrefix,values,size=70){const out=[];for(let i=0;i<values.length;i+=size){const batch=values.slice(i,i+size),rows=await rest(`${pathPrefix}in.(${batch.map(encodeURIComponent).join(',')})`);out.push(...(rows||[]))}return out}
function collapsePrices(rows){const byUuid=new Map();for(const r of rows||[]){const u=String(r.uuid||''),f=String(r.finish||'normal').toLowerCase();if(!u)continue;if(!byUuid.has(u))byUuid.set(u,{});const byFinish=byUuid.get(u);if(!byFinish[f])byFinish[f]={observed_on:r.observed_on};const p=byFinish[f],provider=String(r.provider||'').toLowerCase(),type=String(r.price_type||'').toLowerCase();if(provider==='cardkingdom'&&type==='retail')p.cardkingdom_retail=Number(r.price);if(provider==='cardkingdom'&&type==='buylist')p.cardkingdom_buylist=Number(r.price);if(provider==='manapool'&&type==='retail')p.manapool_retail=Number(r.price);if(provider==='cardmarket'&&type==='retail')p.cardmarket_retail=Number(r.price)}return byUuid}
function links(id,pid){const name=id.name||'',nameSlug=slug(name),q=encodeURIComponent(name),set=String(id.set_code||'').toLowerCase(),collector=encodeURIComponent(id.collector_number||'');return{tcg:pid?`https://www.tcgplayer.com/product/${encodeURIComponent(pid)}`:'',ck:`https://www.cardkingdom.com/catalog/search?search=header&filter%5Bname%5D=${q}&filter%5Btab%5D=mtg_card`,ckBuy:`https://www.cardkingdom.com/purchasing/mtg_singles?search=header&filter%5Bname%5D=${q}`,mana:nameSlug?(set&&collector?`https://manapool.com/card/${encodeURIComponent(set)}/${collector}/${nameSlug}`:`https://manapool.com/card/${nameSlug}`):'',mkm:nameSlug?`https://www.cardmarket.com/en/Magic/Cards/${nameSlug}`:''}}
const ext=(url,label)=>url?`<a class="cx-gv-link" href="${url}" target="_blank" rel="noopener">${label} ↗</a>`:'';
function cell(label,price,url,sub='',cls=''){return `<div class="${cls}"><span>${label}</span><b>${money(price)}</b>${sub?`<small>${sub}</small>`:''}${ext(url,`Open ${label}`)}</div>`}
function actionability(p,s){const sources=[];const low=Number(s?.tcg_low)>0?Number(s.tcg_low):null;if(low)sources.push({name:'TCG Low',price:low,key:'tcg'});if(Number(s?.direct_low)>0)sources.push({name:'TCG Direct Low',price:Number(s.direct_low),key:'tcg'});if(Number(p.cardkingdom_retail)>0)sources.push({name:'Card Kingdom',price:Number(p.cardkingdom_retail),key:'ck'});if(Number(p.manapool_retail)>0)sources.push({name:'Mana Pool',price:Number(p.manapool_retail),key:'mana'});sources.sort((a,b)=>a.price-b.price);const cheapest=sources[0]||null,buylist=Number(p.cardkingdom_buylist)>0?Number(p.cardkingdom_buylist):null;if(!cheapest||!buylist)return{cheapest,buylist,backed:false};const spread=buylist-cheapest.price,roi=spread/cheapest.price*100;return{cheapest,buylist,spread,roi,backed:spread>0}}
function block(id,pid,prices,scout){const L=links(id,pid);return Object.entries(prices).map(([finish,p])=>{const s=scout.find(r=>finishFor(r.printing)===finish)||scout[0]||{},a=actionability(p,s),action=a.backed?`<div class="cx-gv-action backed"><span>BUYLIST BACKED</span><b>Buy ${a.cheapest.name} ${money(a.cheapest.price)} → CK ${money(a.buylist)}</b><small>Gross ${money(a.spread)} · ${pct(a.roi)} before outbound shipping</small></div>`:`<div class="cx-gv-action"><span>${a.cheapest&&a.buylist?'NO BUYLIST ARB':'NO BUYLIST TEST'}</span><small>${a.cheapest&&a.buylist?`${a.cheapest.name} ${money(a.cheapest.price)} → CK ${money(a.buylist)}`:'Insufficient US buy or cash buylist data.'}</small></div>`;return `<div class="cx-global-vendor-finish-block"><div class="cx-global-vendor-finish-head"><b>${finish[0].toUpperCase()+finish.slice(1)}</b><small>${p.observed_on||'latest'}</small></div>${action}<div class="cx-global-vendor-row">${cell('TCG Market',s.sku_market_price,L.tcg,'index / reference')}${cell('TCG Low',s.tcg_low,L.tcg,'US retail acquisition')}${cell('TCG Direct Low',s.direct_low,L.tcg,'Direct benchmark / modeled exit')}${cell('CK retail',p.cardkingdom_retail,L.ck,'US buy candidate')}${cell('CK buylist',p.cardkingdom_buylist,L.ckBuy,'cash exit','exit')}${cell('Mana Pool',p.manapool_retail,L.mana,'US buy candidate')}${cell('MKM',p.cardmarket_retail,L.mkm,'International only · excluded','intl')}</div></div>`}).join('')}

export async function enrichGlobalVendors(force=false){
  const panel=document.getElementById('cxGlobalScoutSearch');if(!panel||panel.hidden||running)return;
  const articles=[...panel.querySelectorAll('.cx-global-print')];if(!articles.length)return;
  const signature=articles.map(a=>`${productId(a)}|${meta(a).setCode}|${meta(a).collector}`).join(';');if(!force&&signature&&signature===lastSignature&&articles.every(a=>a.dataset.vendorLoaded==='1'))return;
  running=true;
  try{
    const pids=[...new Set(articles.map(productId).filter(Boolean))];if(!pids.length)return;
    const data=await loadResource(`scout.global-vendors:${signature}`,async()=>{
      const [identities,scoutRows]=await Promise.all([batches('mtgjson_cards?select=uuid,name,tcgplayer_product_id,set_code,collector_number,cardmarket_id&tcgplayer_product_id=',pids),batches('scout_opportunities_24h?select=product_id,set_code,collector_number,printing,tcg_low,direct_low,sku_market_price&product_id=',pids)]);
      const uuids=[...new Set(identities.map(r=>String(r.uuid||'')).filter(Boolean))],priceRows=uuids.length?await batches('mtgjson_vendor_prices?select=uuid,provider,price_type,finish,price,observed_on&uuid=',uuids):[];
      return{identities,scoutRows,prices:collapsePrices(priceRows)};
    },{force,ttl:5*60*1000});
    const byProduct=new Map();for(const r of data.identities||[]){const k=String(r.tcgplayer_product_id||'');if(!byProduct.has(k))byProduct.set(k,[]);byProduct.get(k).push(r)}
    for(const article of articles){const pid=productId(article),m=meta(article),cand=byProduct.get(pid)||[],id=cand.find(r=>String(r.set_code||'').toUpperCase()===m.setCode&&String(r.collector_number||'')===m.collector)||cand[0]||null;let host=article.querySelector('.cx-global-vendor');if(!host){host=document.createElement('div');host.className='cx-global-vendor';article.querySelector('.cx-global-print-main')?.appendChild(host)}const prices=id?data.prices.get(String(id.uuid)):null,scout=(data.scoutRows||[]).filter(r=>String(r.product_id)===pid);host.innerHTML=id&&prices?block(id,pid,prices,scout):'<div class="cx-global-vendor-empty">No MTGJSON vendor identity/pricing match.</div>';article.dataset.vendorLoaded='1'}
    lastSignature=signature;
    document.dispatchEvent(new CustomEvent('collectish:scout-global-vendors-rendered',{detail:{signature}}));
  }catch(error){console.warn('Global Scout vendor enrichment failed',error)}finally{running=false}
}

const style=document.createElement('style');style.textContent=`.cx-global-vendor{margin-top:10px;border-top:1px solid var(--cx-line);padding-top:9px}.cx-global-vendor-finish-block{border:1px solid var(--cx-line);border-radius:11px;padding:8px;margin-top:8px}.cx-global-vendor-finish-head{display:flex;justify-content:space-between;gap:8px}.cx-global-vendor-finish-head small{color:var(--cx-muted)}.cx-gv-action{margin:7px 0;border-radius:9px;padding:7px;background:var(--cx-bg)}.cx-gv-action.backed{background:#e8f7ee;border:1px solid #b7e1c6}.cx-gv-action>span{display:block;font-size:9px;font-weight:900;letter-spacing:.04em}.cx-gv-action b,.cx-gv-action small{display:block}.cx-gv-action small{font-size:9px;color:var(--cx-muted)}.cx-global-vendor-row{display:grid;grid-template-columns:repeat(7,minmax(88px,1fr));gap:6px}.cx-global-vendor-row>div{border:1px solid var(--cx-line);border-radius:8px;padding:6px;background:var(--cx-bg)}.cx-global-vendor-row span,.cx-global-vendor-row small{display:block;font-size:9px;color:var(--cx-muted)}.cx-global-vendor-row b{display:block;font-size:12px;margin-top:2px}.cx-global-vendor-row .exit{border-color:#b7e1c6}.cx-global-vendor-row .intl{opacity:.7;border-style:dashed}.cx-gv-link{display:inline-block;margin-top:4px;font-size:9px;font-weight:800;text-decoration:none;color:var(--cx-accent)}.cx-global-vendor-empty{color:var(--cx-muted);font-size:9px}@media(max-width:900px){.cx-global-vendor-row{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(style);

function onGlobalRendered(){enrichGlobalVendors().catch(()=>{})}
registerComponent('scout-global-vendors',{
  mount(){document.addEventListener('collectish:scout-global-rendered',onGlobalRendered)},
  unmount(){document.removeEventListener('collectish:scout-global-rendered',onGlobalRendered)},
  onPage(page){if(page==='scout'&&document.querySelector('#cxGlobalScoutSearch .cx-global-print'))enrichGlobalVendors().catch(()=>{})}
});
window.CollectishScoutGlobalVendors={refresh:()=>enrichGlobalVendors(true)};
