import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const t=(v:any)=>String(v??'').trim();
const H={apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'};
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function authorized(req:Request){const h=req.headers.get('authorization')||'',tok=h.replace(/^Bearer\s+/i,'');if(!tok)return false;if(tok===S)return true;const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:S,Authorization:`Bearer ${tok}`}});return r.ok}
async function rest(path:string,o:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:o.method||'GET',headers:{...H,...(o.prefer?{Prefer:o.prefer}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function fetchSet(code:string){const r=await fetch(`https://mtgjson.com/api/v5/${encodeURIComponent(code)}.json.gz`,{headers:{'User-Agent':'Collectish-MTGJSON-OnDemand/1.1'}});if(!r.ok)throw Error(`MTGJSON ${code} HTTP ${r.status}`);const bytes=new Uint8Array(await r.arrayBuffer());let raw=bytes;try{const ds=new DecompressionStream('gzip');raw=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).arrayBuffer())}catch{}const doc=JSON.parse(new TextDecoder().decode(raw)),data=doc?.data||{};return{cards:Array.isArray(data.cards)?data.cards:[],booster:data.booster&&typeof data.booster==='object'?data.booster:{}}}
function cardRow(code:string,c:any){const uuid=t(c?.uuid);if(uuid.length!==36)return null;return{uuid,name:t(c?.name)||'(unknown)',set_code:t(c?.setCode||code).toUpperCase(),type_line:c?.type||null,supertypes:Array.isArray(c?.supertypes)?c.supertypes:[],types:Array.isArray(c?.types)?c.types:[],subtypes:Array.isArray(c?.subtypes)?c.subtypes:[],frame_effects:Array.isArray(c?.frameEffects)?c.frameEffects:[],border_color:c?.borderColor||null,promo_types:Array.isArray(c?.promoTypes)?c.promoTypes:[],is_full_art:c?.isFullArt??null,is_textless:c?.isTextless??null,source_updated_at:new Date().toISOString()}}
async function mark(code:string,status:string,cards:number,boosters:number,error_text:string|null=null){await rest('mtgjson_set_scan_state?on_conflict=set_code',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:[{set_code:code,scanned_at:new Date().toISOString(),status,card_count:cards,booster_config_count:boosters,error_text}]})}
async function hydrate(code:string){try{const {cards,booster}=await fetchSet(code),now=new Date().toISOString(),cardRows=cards.map((c:any)=>cardRow(code,c)).filter(Boolean),boostRows=Object.entries(booster).filter(([,v])=>v&&typeof v==='object').map(([k,v])=>({set_code:code,booster_code:k,booster_config:v,source_updated_at:now}));for(let i=0;i<cardRows.length;i+=200)await rest('mtgjson_cards?on_conflict=uuid',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:cardRows.slice(i,i+200)});if(boostRows.length)await rest('mtgjson_set_booster_configs?on_conflict=set_code,booster_code',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:boostRows});await mark(code,'complete',cardRows.length,boostRows.length);return{set_code:code,cards:cardRows.length,booster_configs:boostRows.length,status:'complete'}}catch(e){const msg=String((e as Error)?.message||e).slice(0,500);await mark(code,'failed',0,0,msg).catch(()=>null);return{set_code:code,status:'failed',error:msg}}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);if(!(await authorized(req)))return js({error:'Signed-in user required'},401);const b=await req.json().catch(()=>({})),codes=[...new Set((Array.isArray(b?.set_codes)?b.set_codes:[b?.set_code]).map((x:any)=>t(x).toUpperCase()).filter((x:string)=>/^[A-Z0-9]{2,8}$/.test(x)))].slice(0,8);if(!codes.length)return js({error:'set_code or set_codes required'},400);const work=Promise.all(codes.map(hydrate));if((globalThis as any).EdgeRuntime?.waitUntil){(globalThis as any).EdgeRuntime.waitUntil(work);return js({ok:true,queued:true,set_codes:codes,note:'Targeted MTGJSON set scan started; results should be available on the next query.'},202)}return js({ok:true,queued:false,result:await work})});