import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const O=Deno.env.get('OPENAI_API_KEY')||'';
const M=Deno.env.get('MARKET_INTEL_MODEL')||'gpt-5-mini';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const H=()=>({apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
const norm=(s:any)=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const trim=(s:any,n=6000)=>String(s||'').trim().slice(0,n);
const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i;
const TRIGGERS=[[/\bthis card is busted\b/i,.97,'busted'],[/\bone of the best cards? in the deck\b|\bone of the better cards? in the deck\b/i,.96,'best in deck'],[/\bmight be the best\b|\bprobably the best\b/i,.95,'might be best'],[/\bthe perfect card\b|\bexactly what the doctor ordered\b/i,.93,'perfect fit'],[/\bfinally playable\b|\bis insane\b/i,.92,'exceptional'],[/\breally powerful\b/i,.90,'powerful'],[/\breally good in this deck\b|\bonly if you have\b/i,.87,'strong synergy'],[/\bmost obvious include\b|\bobvious include\b/i,.86,'include'],[/\bone of the better cards?\b/i,.82,'recommendation'],[/\bvery good\b/i,.78,'positive']];
async function rest(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function auth(t:string){if(!t)return false;if(S&&t===S)return true;try{return (await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}})).ok}catch{return false}}
function parse(raw:string){const s=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),z=s.lastIndexOf('}');if(a>=0&&z>a)try{return JSON.parse(s.slice(a,z+1))}catch{}return{}}
async function ask(prompt:string,max=700){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${O}`,'Content-Type':'application/json'},body:JSON.stringify({model:M,store:false,input:prompt,reasoning:{effort:'minimal'},max_output_tokens:max})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`OpenAI ${r.status}`);let out='';for(const x of d.output||[])if(x.type==='message')for(const c of x.content||[])if(c.type==='output_text')out+=c.text;return parse(out)}
async function canonical(name:string){for(const m of ['exact','fuzzy'])try{const r=await fetch(`https://api.scryfall.com/cards/named?${m}=${encodeURIComponent(name)}`,{headers:{'User-Agent':'MarketplaceScout/1.5'}});if(r.ok){const c=await r.json();if(c?.id)return{name:String(c.name),id:String(c.id),set:String(c.set||''),released_at:String(c.released_at||'')}}}catch{}return null}
function trigger(t:string){for(const [re,p,label] of TRIGGERS as any[]){const m=String(t||'').match(re);if(m)return{p,label,phrase:m[0]}}return null}
function anchored(anchor:any,text:string){const a=norm(anchor),h=norm(text);return a.length>=3&&h.includes(a)}
async function resolve(hit:any,title:string){
 const targetWindow=`PREVIOUS CAPTION: ${hit.prev}\nCURRENT CAPTION: ${hit.text}`;
 const sourceWindow=`SECTION CONTEXT: ${hit.context}\nCURRENT CAPTION: ${hit.text}`;
 const target=await ask(`From this MTG Commander review excerpt, identify ONLY the card that the exact evaluation phrase refers to. Return JSON {"target_anchor":string|null,"target_card":string|null,"relationship_type":"new_card_synergy"|"upgrade_for"|"combo_with"|"enabler_for"|"payoff_for"|"other","confidence":number,"summary":string}. Evaluation phrase: "${hit.phrase}". target_anchor MUST be copied verbatim from PREVIOUS CAPTION or CURRENT CAPTION. Prefer the nearest named card immediately before or containing that evaluation phrase. Do not choose an earlier unrelated recommendation and do not choose a card introduced after the evaluation. If the phrase is negative or the referent is ambiguous, return null. Video: ${title}\n${targetWindow}`);
 if(!target?.target_anchor||!target?.target_card||!anchored(target.target_anchor,targetWindow))return null;
 const tgt=await canonical(target.target_card);if(!tgt)return null;
 const source=await ask(`Identify the NEW commander/card whose deck section is being discussed in this local MTG review excerpt. Return JSON {"source_anchor":string|null,"source_card":string|null}. source_anchor MUST be copied verbatim from SECTION CONTEXT or CURRENT CAPTION. Use the most recent commander section introduction; do not return the praised existing card ${tgt.name}. If no new reviewed card can be grounded, return null. ${sourceWindow}`,500);
 if(!source?.source_anchor||!source?.source_card||!anchored(source.source_anchor,sourceWindow))return null;
 const src=await canonical(source.source_card);if(!src||src.id===tgt.id)return null;
 return{src,tgt,type:String(target.relationship_type||'new_card_synergy'),confidence:Math.max(.65,Math.min(.98,Number(target.confidence)||hit.prominence)),summary:trim(target.summary,400),hit};
}
async function resolveAll(hits:any[],title:string){let i=0;const out:any[]=[];async function w(){while(true){const x=i++;if(x>=hits.length)return;try{const r=await resolve(hits[x],title);if(r)out.push(r)}catch{}}}await Promise.all(Array.from({length:Math.min(6,hits.length)},()=>w()));return out}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);
 const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!S||!(await auth(token)))return J({error:'Service authentication required'},401);
 let body:any={};try{body=await req.json()}catch{}
 try{
  const caps=await rest('source_captures?select=capture_id,user_id,source,payload_json,metadata_json&capture_type=eq.video_transcript&order=captured_at.desc&limit=120');let cap:any=null;
  for(const c of caps||[]){const p=c.payload_json||{};if(!UUID.test(String(c.user_id||''))||c?.metadata_json?.status!=='saved'||p.creator_lane!=='commander_product'||!Array.isArray(p.segments))continue;if(body.video_id&&p.video_id!==body.video_id)continue;cap=c;break}
  if(!cap)return J({ok:true,processed:0,reason:'no_cached_commander_product',transcript_credits_used:0});
  const p=cap.payload_json,s=p.segments,date=String(p.published_at||new Date().toISOString()).slice(0,10),hits:any[]=[];
  for(let x=0;x<s.length;x++){const h=trigger(String(s[x]?.text||''));if(!h)continue;const pre=[];for(let k=Math.max(0,x-12);k<x;k++)pre.push(String(s[k]?.text||''));hits.push({idx:x,start_ms:Math.max(0,Math.round(Number(s[x]?.offset)||0)),text:trim(s[x]?.text,1800),prev:x>0?trim(s[x-1]?.text,1800):'',context:trim(pre.join(' '),7200),prominence:h.p,label:h.label,phrase:h.phrase})}
  const rels=await resolveAll(hits,String(p.title||''));const seen=new Set<string>();const saved:any[]=[];let rejected=0;
  for(const r of rels){const sourceFuture=!!r.src.released_at&&r.src.released_at>date,targetExisting=!r.tgt.released_at||r.tgt.released_at<=date;if(!sourceFuture||!targetExisting){rejected++;continue}const key=`${norm(r.src.name)}|${norm(r.tgt.name)}`;if(seen.has(key))continue;seen.add(key);
   const catalog=await rest(`scout_card_catalog?select=sku_id&scryfall_id=eq.${encodeURIComponent(r.tgt.id)}&limit=1`).catch(()=>[]);const actionable=!!catalog?.length;const url=p.url||`https://www.youtube.com/watch?v=${p.video_id}`;const eventKey=`grounded-recall|${p.video_id}|${r.hit.start_ms}|${norm(r.tgt.name)}|${norm(r.src.name)}`;
   let intel:any=null;const old=await rest(`market_intel_items?select=intel_id,metadata_json&user_id=eq.${cap.user_id}&source_url=eq.${encodeURIComponent(url)}&limit=500`).catch(()=>[]);intel=(old||[]).find((q:any)=>q?.metadata_json?.video_event_key===eventKey)?.intel_id||null;
   if(!intel){const ins=await rest('market_intel_items',{method:'POST',prefer:'return=representation',body:{user_id:cap.user_id,source_type:'youtube',source_name:cap.source||'YouTube',source_url:url,title:p.title||r.tgt.name,summary:r.summary||`${r.tgt.name} recommended for ${r.src.name}`,claim_type:'product',direction:'bullish',signal_stage:'leading',confidence:r.confidence,published_at:p.published_at||null,source_profile:'creator_commander',source_subtype:'new_commander_synergy',metadata_json:{platform:'youtube',video_id:p.video_id,video_event_key:eventKey,event_type:'new_commander_synergy',start_ms:r.hit.start_ms,prominence:r.hit.prominence,relationship_source_card:r.src.name,relationship_target_card:r.tgt.name,relationship_type:r.type,source_is_unreleased:true,target_is_actionable:actionable,resolution_method:'two_stage_local_target_anchor+scryfall'}}});intel=ins?.[0]?.intel_id||null;if(intel)await rest('market_intel_entities',{method:'POST',prefer:'return=minimal',body:{intel_id:intel,user_id:cap.user_id,entity_type:'card',entity_name:r.tgt.name,scryfall_id:r.tgt.id,set_code:r.tgt.set,confidence:.97}}).catch(()=>null)}
   if(!intel)continue;await rest('market_intel_card_relationships',{method:'POST',prefer:'resolution=ignore-duplicates,return=minimal',body:{user_id:cap.user_id,source_intel_id:intel,source_video_id:p.video_id,source_name:cap.source||'YouTube',source_url:url,source_card_name:r.src.name,source_scryfall_id:r.src.id,source_release_date:r.src.released_at||null,target_card_name:r.tgt.name,target_scryfall_id:r.tgt.id,target_release_date:r.tgt.released_at||null,relationship_type:r.type,direction:'bullish',conviction:Math.max(r.hit.prominence,r.confidence),start_ms:r.hit.start_ms,evidence:r.hit.text,summary:r.summary,source_is_unreleased:true,target_is_actionable:actionable}}).catch(()=>null);saved.push({source_card:r.src.name,target_card:r.tgt.name,conviction:Math.max(r.hit.prominence,r.confidence),target_actionable:actionable,start_ms:r.hit.start_ms})
  }
  if(saved.length){await rest('rpc/refresh_market_intel_entity_links',{method:'POST',body:{}}).catch(()=>null);await rest('rpc/refresh_market_intel_evaluations',{method:'POST',body:{}}).catch(()=>null)}
  return J({ok:true,processed:1,video_id:p.video_id,trigger_hits:hits.length,relationships_saved:saved.length,rejected,relationships:saved,transcript_credits_used:0});
 }catch(e){return J({error:(e as Error).message},502)}
});
