import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:any)=>String(v??'').trim();
const sh=()=>({apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
async function rest(path:string,o:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:o.method||'GET',headers:{...sh(),...(o.prefer?{Prefer:o.prefer}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function sync(pid:string,sku:string){const r=await fetch(`${U}/functions/v1/market-supply-sync`,{method:'POST',headers:sh(),body:JSON.stringify({product_id:pid,sku_id:sku})});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}return r.ok?d:{ok:false,error:text(d?.error||raw)}}
const norm=(v:any)=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function alias(q:string){for(const p of[/^how(?:'s| is)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^(?:what(?:'s| is)|show(?: me)?|give me)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/\b(?:stock|supply|inventory|liquidity)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i]){const m=text(q).match(p);if(m?.[1])return m[1].trim()}return''}
const ageMin=(v:any)=>{const t=Date.parse(text(v));return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):null};
const nfmt=(v:any)=>Number(v||0).toLocaleString('en-US');
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);
 const body=await req.json().catch(()=>({})),q=text(body?.question||body?.message),name=alias(q);if(!name)return js({handled:false,reason:'not_supply_question'});
 const rows=await rest(`scout_card_catalog?card_name=ilike.${encodeURIComponent(name)}&language=ilike.ENGLISH&condition=in.(NEAR%20MINT,LIGHTLY%20PLAYED)&select=card_name,product_id,sku_id,set_code,collector_number,printing,condition,language&limit=50`).catch(()=>[]);
 const exact=(rows||[]).filter((r:any)=>norm(r.card_name)===norm(name)&&/^\d+$/.test(text(r.product_id))&&/^\d+$/.test(text(r.sku_id)));
 if(!exact.length)return js({handled:false,reason:'no_exact_card_family'});
 const seen=new Set<string>(),family=exact.filter((r:any)=>{const k=text(r.sku_id);if(seen.has(k))return false;seen.add(k);return true}).slice(0,20);
 const refresh=await Promise.all(family.map((r:any)=>sync(text(r.product_id),text(r.sku_id)).catch(e=>({ok:false,error:String(e?.message||e)}))));
 const skus=family.map((r:any)=>text(r.sku_id));
 const snapshots=await rest(`market_supply_snapshots?source=eq.tcgplayer_marketplace&sku_id=in.(${skus.join(',')})&select=sku_id,observed_at,coverage_state,unit_count,listing_count,direct_unit_count,non_direct_unit_count,lowest_price_with_shipping&order=observed_at.desc`).catch(()=>[]);
 const latest=new Map<string,any>();for(const r of snapshots||[]){const k=text(r.sku_id);if(!latest.has(k))latest.set(k,r)}
 async function vendor(source:string){const ids=await rest(`vendor_item_identities?source=eq.${source}&tcgplayer_sku_id=in.(${skus.join(',')})&select=source_item_key,tcgplayer_sku_id`).catch(()=>[]);if(!ids?.length)return new Map();const keyToSku=new Map(ids.map((x:any)=>[text(x.source_item_key),text(x.tcgplayer_sku_id)]));const keys=[...keyToSku.keys()];const ds=await rest(`vendor_depth_current?source=eq.${source}&lane=eq.retail_supply&source_item_key=in.(${keys.map(k=>encodeURIComponent(k)).join(',')})&select=source_item_key,quantity,price,observed_at,condition,finish`).catch(()=>[]);const out=new Map<string,any[]>();for(const d of ds||[]){const sku=keyToSku.get(text(d.source_item_key));if(!sku)continue;out.set(sku,[...(out.get(sku)||[]),d])}return out}
 const [mp,ck]=await Promise.all([vendor('manapool'),vendor('cardkingdom')]);
 let tcg=0,listings=0,direct=0,nonDirect=0,mpQty=0,ckQty=0;const variants:any[]=[];let newest:string|null=null;
 for(const r of family){const sku=text(r.sku_id),s=latest.get(sku),mps=mp.get(sku)||[],cks=ck.get(sku)||[];if(s?.coverage_state==='COMPLETE'){tcg+=Number(s.unit_count||0);listings+=Number(s.listing_count||0);direct+=Number(s.direct_unit_count||0);nonDirect+=Number(s.non_direct_unit_count||0);if(!newest||Date.parse(s.observed_at)>Date.parse(newest))newest=s.observed_at}mpQty+=mps.reduce((n:number,x:any)=>n+Number(x.quantity||0),0);ckQty+=cks.reduce((n:number,x:any)=>n+Number(x.quantity||0),0);variants.push({title:`${r.set_code||''} #${r.collector_number||''} ${String(r.printing||'').replace('NON FOIL','nonfoil').replace('FOIL','foil')}`.trim(),sku_id:sku,condition:r.condition,tcgplayer_units:Number(s?.unit_count||0),tcgplayer_listings:Number(s?.listing_count||0),direct_units:Number(s?.direct_unit_count||0),manapool_units:mps.reduce((n:number,x:any)=>n+Number(x.quantity||0),0),cardkingdom_units:cks.reduce((n:number,x:any)=>n+Number(x.quantity||0),0),observed_at:s?.observed_at||null})}
 variants.sort((a,b)=>b.tcgplayer_units-a.tcgplayer_units);const label=tcg>=100?'DEEP':tcg>=30?'MODERATE':tcg>0?'THIN':'UNPROVEN',age=newest?ageMin(newest):null,cacheHits=refresh.filter((x:any)=>x?.cached===true||x?.cache?.tcgplayer?.hit===true).length;
 const summary=label==='DEEP'?'Plenty available across the currently covered printings.':label==='MODERATE'?'Supply looks healthy overall, but some printings are tighter.':label==='THIN'?'Supply is limited across the currently covered printings.':'Current family depth is incomplete.';
 const response=`**${family[0].card_name} — Stock**\n**${label}** · ${summary}\n\nTCGplayer: **${nfmt(tcg)}** units across **${nfmt(listings)}** listings\n↳ Direct **${nfmt(direct)}** · Non-Direct **${nfmt(nonDirect)}**\nManaPool: **${nfmt(mpQty)}** copies\nCard Kingdom: **${nfmt(ckQty)}** copies\n\n${variants.slice(0,6).map(v=>`• ${v.title}: ${nfmt(v.tcgplayer_units)} TCG`).join('\n')}`;
 const presentation={version:1,type:'card_family_supply',title:`${family[0].card_name} — Stock`,summary:`${label} · ${summary}`,badges:[label],metrics:[{label:'TCGplayer',value:tcg,display:`${nfmt(tcg)} units · ${nfmt(listings)} listings`},{label:'Direct',value:direct,display:nfmt(direct)},{label:'Non-Direct',value:nonDirect,display:nfmt(nonDirect)},{label:'ManaPool',value:mpQty,display:nfmt(mpQty)},{label:'Card Kingdom',value:ckQty,display:nfmt(ckQty)}],sections:[{heading:'Printing depth',kind:'ranked_rows',rows:variants.slice(0,10).map(v=>({title:v.title,subtitle:v.condition,metrics:[{label:'TCG',value:v.tcgplayer_units,display:nfmt(v.tcgplayer_units)},{label:'Direct',value:v.direct_units,display:nfmt(v.direct_units)},{label:'MP',value:v.manapool_units,display:nfmt(v.manapool_units)},{label:'CK',value:v.cardkingdom_units,display:nfmt(v.cardkingdom_units)}]}))}],footnote:`English NM/LP family scope · TCGplayer/ManaPool cache 30m · CK baseline refresh 12h${age!=null?` · TCG data ${age<1?'under 1m':Math.round(age)+'m'} old`:''}${cacheHits?` · ${cacheHits}/${family.length} SKU refreshes reused`:''}`,actions:[]};
 return js({handled:true,route:'card_family_supply',response,presentation,data:{card_name:family[0].card_name,scope:'CARD_NAME_NM_LP_ENGLISH',variant_count:family.length,tcgplayer_total_units:tcg,tcgplayer_total_listings:listings,direct_units:direct,non_direct_units:nonDirect,manapool_quantity:mpQty,cardkingdom_quantity:ckQty,cache_reused_skus:cacheHits,variants}});
});
