import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const WEB=(Deno.env.get('COLLECTISH_WEB_URL')||'https://joe-nasti.github.io/marketplacescout/').replace(/\/?$/,'/');
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const t=(v:any)=>String(v??'').trim();
const fmt=(v:any)=>Number(v||0).toLocaleString('en-US');
const pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:'—';
const money=(v:any)=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:'—';
const H={apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'};

async function call(url:string,body:any){const r=await fetch(url,{method:'POST',headers:H,body:JSON.stringify(body)}),raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{d=raw}if(!r.ok)throw Error(d?.error||d?.message||`${r.status}`);return d}
const rpc=(name:string,body:any)=>call(`${U}/rest/v1/rpc/${name}`,body);
function card(q:string){for(const p of[/^how\s+deep\s+is\s+(?:the\s+)?market\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^(?:what(?:'s| is)\s+)?(?:the\s+)?market\s+depth\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^how(?:'s| is)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity|depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^(?:what(?:'s| is)|show(?: me)?|give me)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity|depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/\b(?:stock|supply|inventory|liquidity|market\s+depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i]){const m=q.match(p);if(m?.[1])return m[1].trim()}return''}
function finish(v:any){const s=t(v).toUpperCase().replace(/[^A-Z]/g,'');return s.includes('FOIL')&&!s.includes('NONFOIL')?'FOIL':'NON FOIL'}
function prettyClass(v:any){const s=t(v).toUpperCase();if(s==='VERY_THIN')return'Very thin';if(s==='THIN')return'Thin';if(s==='MODERATE')return'Moderate';if(s==='DEEP')return'Deep';return'Unproven'}
function conclusionFor(name:string,v:any){const s=t(v).toUpperCase();if(s==='DEEP')return`${name} has deep family-wide supply; scarcity is treatment-specific.`;if(s==='MODERATE')return`${name} has healthy family-wide depth, with some tighter treatments.`;if(s==='THIN'||s==='VERY_THIN')return`${name} is genuinely tight across the measured family.`;return`${name} market-wide depth remains unproven.`}
function printingMarketPrice(productId:any,finishScope:any,marketContext:any){const candidates=(Array.isArray(marketContext?.by_sku)?marketContext.by_sku:[]).filter((r:any)=>t(r.product_id)===t(productId)&&finish(r.printing)===finishScope&&Number(r.market_price)>0);const nm=candidates.find((r:any)=>['NEAR MINT','NM'].includes(t(r.condition).toUpperCase()));return Number(nm?.market_price||candidates[0]?.market_price)||null}
function collectorNum(v:any){const m=t(v).match(/^(\d+)/);return m?Number(m[1]):null}
function rowKey(r:any){return`${t(r.set_code)}|${t(r.collector_number)}|${finish(r.finish)}`}
function compactSafe(rows:any[]){if(!rows.length||rows.some(r=>collectorNum(r.collector_number)==null))return false;const seen=new Set<string>();for(const r of rows){const k=rowKey(r);if(seen.has(k))return false;seen.add(k)}return true}
function rowPrice(r:any,marketContext:any){return printingMarketPrice(r.product_id,r.finish,marketContext)}
function compactRow(r:any,marketContext:any){const star=finish(r.finish)==='FOIL'?'★':'',p=rowPrice(r,marketContext);return`\`${star}${t(r.collector_number)}\`${p?` · **${money(p)}**`:''} · **${fmt(r.unit_count)}**`}
function explicitRow(r:any,marketContext:any){const p=rowPrice(r,marketContext),fl=finish(r.finish)==='FOIL'?'foil':'nonfoil';return`**${t(r.set_code)} #${t(r.collector_number)} ${fl}**${p?` · **${money(p)}**`:''} · ${fmt(r.unit_count)}`}
function ladderSections(rows:any[],marketContext:any){const sets=new Map<string,any[]>();for(const r of rows){const k=t(r.set_code)||'Unknown set';if(!sets.has(k))sets.set(k,[]);sets.get(k)!.push(r)}const sections:any[]=[];for(const [setCode,setRows] of sets){const safe=compactSafe(setRows);const ordered=[...setRows].sort((a,b)=>(collectorNum(a.collector_number)??1e9)-(collectorNum(b.collector_number)??1e9)||(finish(a.finish)==='FOIL'?1:0)-(finish(b.finish)==='FOIL'?1:0));if(safe){const nf=ordered.filter(r=>finish(r.finish)!=='FOIL'),fo=ordered.filter(r=>finish(r.finish)==='FOIL');const parts:string[]=[];if(nf.length)parts.push(`**Nonfoil**\n${nf.map(r=>compactRow(r,marketContext)).join('\n')}`);if(fo.length)parts.push(`**Foil · ★**\n${fo.map(r=>compactRow(r,marketContext)).join('\n')}`);sections.push({heading:`${setCode} supply ladder`,kind:'text',text:parts.join('\n')})}else{sections.push({heading:`${setCode} variants`,kind:'text',text:ordered.map(r=>explicitRow(r,marketContext)).join('\n')})}}return sections}
function expectedTailScarcity(row:any,setRows:any[]){if(!row||!compactSafe(setRows)||finish(row.finish)!=='FOIL')return false;const n=collectorNum(row.collector_number);if(n==null)return false;const nums=setRows.map(r=>collectorNum(r.collector_number)).filter((x):x is number=>x!=null);const max=Math.max(...nums);if(n!==max)return false;const peers=setRows.filter(r=>finish(r.finish)==='FOIL').sort((a,b)=>(collectorNum(a.collector_number)??0)-(collectorNum(b.collector_number)??0));const idx=peers.findIndex(r=>t(r.product_id)===t(row.product_id));if(idx<=0)return true;return Number(row.unit_count||0)<=Number(peers[idx-1].unit_count||0)}
function findUnexpectedBreak(rows:any[]){const sets=new Map<string,any[]>();for(const r of rows){const k=t(r.set_code);if(!sets.has(k))sets.set(k,[]);sets.get(k)!.push(r)}let best:any=null;for(const [setCode,setRows] of sets){if(!compactSafe(setRows))continue;for(const fl of ['NON FOIL','FOIL']){const peers=setRows.filter(r=>finish(r.finish)===fl).sort((a,b)=>(collectorNum(a.collector_number)??0)-(collectorNum(b.collector_number)??0));for(let i=1;i<peers.length;i++){const prev=Number(peers[i-1].unit_count||0),cur=Number(peers[i].unit_count||0);if(prev<=0)continue;const ratio=cur/prev;const isExpectedTail=fl==='FOIL'&&i===peers.length-1;if(ratio<0.2&&!isExpectedTail&&(!best||ratio<best.ratio))best={row:peers[i],previous:peers[i-1],ratio,setCode}}}}return best}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);const b=await req.json().catch(()=>({})),q=t(b.question||b.message),name=card(q);if(!name)return js({handled:false,reason:'not_supply_question'});
 try{
  const targets:any[]=await rpc('ask_collectish_supply_family_skus_v1',{p_card_name:name,p_scryfall_id:null}).catch(()=>[]);
  if(!targets.length)return js({handled:true,route:'card_family_supply',response:`I recognized the stock question, but Collectish has no canonical English NM/LP family mapping for “${name}”.`,presentation:{version:11,type:'card_family_supply',title:`${name} — Market depth`,summary:'Canonical family mapping unavailable.',badges:['UNPROVEN'],metrics:[],sections:[],footnote:'Printing clarification is only needed when the card name itself is ambiguous.',actions:[]},data:{reason:'canonical_family_not_found'}});
  let supply:any;try{supply=await call(`${U}/functions/v1/market-supply-sync`,{targets,scope:'CARD_FAMILY_NM_LP',max_pages:40})}catch{return js({handled:true,route:'card_family_supply',response:`${targets[0].card_name||name} resolved to ${targets.length} English NM/LP SKUs, but the market-depth refresh failed. Try again shortly.`,presentation:{version:11,type:'card_family_supply',title:`${targets[0].card_name||name} — Market depth`,summary:'Card family resolved; market refresh failed.',badges:['REFRESH FAILED'],metrics:[],sections:[],footnote:`${targets.length} English NM/LP SKUs resolved.`,actions:[]},data:{reason:'family_resolved_market_sync_failed'}})}
  const skus=[...new Set(targets.map(z=>t(z.sku_id)))],oracleId=t(targets[0]?.oracle_id);
  const [concentration,trend,marketContext]=await Promise.all([rpc('ask_collectish_family_supply_concentration_v1',{p_sku_ids:skus}).catch(()=>null),rpc('ask_collectish_family_supply_trend_v1',{p_sku_ids:skus,p_days:90}).catch(()=>null),oracleId?rpc('scout_oracle_family_market_context_v1',{p_oracle_id:oracleId}).catch(()=>null):Promise.resolve(null)]);
  const x=supply?.combined||{},ck=supply?.source_depth?.cardkingdom_retail||{},mp=supply?.source_depth?.manapool_retail||{},g=t(supply?.global_supply_classification||supply?.classification||'UNPROVEN').toUpperCase(),units=Number(x.unit_count||0),listings=Number(x.listing_count||0),direct=Number(x.direct_unit_count||0),non=Number(x.non_direct_unit_count||0),mpq=Number(mp.quantity??x.manapool_retail_quantity??0),n=targets[0].card_name||name,directShare=units>0?direct/units*100:null,conclusion=conclusionFor(n,g);
  const mpCovered=Number(mp.fresh_sku_count??mp.covered_sku_count??0),mpExpected=Number(mp.expected_sku_count??targets.length),mpComplete=mpExpected>0&&mpCovered>=mpExpected,mpCoverage=`${mpCovered}/${mpExpected} mapped SKUs${mpComplete?'':' · partial'}`;
  const rows=Array.isArray(concentration?.printing_rows)?concentration.printing_rows:[],tight=concentration?.tightest_printing||null,tightSet=rows.filter((r:any)=>t(r.set_code)===t(tight?.set_code)),expectedTail=expectedTailScarcity(tight,tightSet),anomaly=findUnexpectedBreak(rows);
  const trendLabel=t(trend?.trend||'UNPROVEN'),points=Number(trend?.complete_observation_points||0),trendText=trendLabel==='UNPROVEN'?`Trend not established yet (${points} complete family observation${points===1?'':'s'}).`:`${fmt(trend?.first_units)} → ${fmt(trend?.last_units)} TCG units (${Number(trend?.unit_change_pct)>=0?'+':''}${Number(trend?.unit_change_pct||0).toFixed(1)}%) over ${fmt(trend?.observed_span_days)} observed days · ${trendLabel.replaceAll('_',' ')}`;
  const scoutUrl=oracleId?`${WEB}?q=${encodeURIComponent(n)}&oracle=${encodeURIComponent(oracleId)}&marketDepth=1`:null;
  const patternText=anomaly?`⚠️ **Unexpected supply break:** ${t(anomaly.setCode)} #${t(anomaly.row.collector_number)} ${finish(anomaly.row.finish)==='FOIL'?'foil':'nonfoil'} has only ${fmt(anomaly.row.unit_count)} units versus ${fmt(anomaly.previous.unit_count)} for the preceding comparable treatment.`:expectedTail?'Supply follows the expected premium-treatment ladder; the scarcest printing is the premium tail, not an unusual market break.':'No clear treatment-ladder anomaly detected from the measured variants.';
  const response=[`**${n} — Market depth**`,`**${g} MARKET** · ${conclusion}`,'',`TCGplayer: **${fmt(units)}** NM/LP units · **${fmt(listings)}** listings`,`↳ Direct **${fmt(direct)}**${directShare!=null?` (${pct(directShare)} of TCG units)`:''} · Non-Direct **${fmt(non)}**`,`ManaPool: **${fmt(mpq)}+** observed · ${mpCoverage}`,`Card Kingdom: **${ck?.available?fmt(ck.quantity):'unavailable'}** NM/EX${ck?.available&&ck?.freshness_status?` · ${t(ck.freshness_status).toLowerCase()}`:''}`,'',patternText,scoutUrl?`[Open all printings in Collectish Scout](${scoutUrl})`:null,points>=2?`Trend: ${trendText}`:null].filter(x=>x!==null).join('\n');
  const sections:any[]=[...ladderSections(rows,marketContext),{heading:anomaly?'Supply anomaly':'Supply pattern',kind:'text',text:patternText}];if(scoutUrl)sections.push({heading:'Scout',kind:'text',text:`[Open all printings with market price + supply context](${scoutUrl})`});if(points>=2)sections.push({heading:'Supply trend',kind:'text',text:trendText});
  const footerParts=[`English NM/LP family`,`${supply?.coverage?.complete_sku_count||0}/${targets.length} TCG SKUs complete`,`ManaPool ${mpCovered}/${mpExpected} mapped`,`★ = foil`,`Direct ⊂ TCGplayer`];if(points<2)footerParts.push(trendText);
  const presentation={version:11,type:'card_family_supply',title:`${n} — Market depth`,summary:`${conclusion}${directShare!=null?` Direct represents ${pct(directShare)} of observed TCGplayer units.`:''}`,badges:[`${g} MARKET`,`${t(supply?.confidence||'LOW')} CONFIDENCE`],metrics:[{label:'TCGplayer',display:`${fmt(units)} units · ${fmt(listings)} listings`},{label:'TCG split',display:`Direct ${fmt(direct)} · Non-Direct ${fmt(non)}`},{label:mpComplete?'ManaPool NM/LP':'ManaPool observed',display:`${fmt(mpq)}+ · ${mpCoverage}`},{label:'Card Kingdom',display:ck?.available?`${fmt(ck.quantity)} NM/EX · ${t(ck.freshness_status||'').toLowerCase()}`:'unavailable'}],sections,footnote:footerParts.join(' · '),actions:scoutUrl?[{label:'Open in Scout',url:scoutUrl}]:[]};
  return js({handled:true,route:'card_family_supply',response,presentation,data:{card_name:n,oracle_id:oracleId,scout_url:scoutUrl,scope:'CARD_FAMILY_NM_LP',canonical_target_count:targets.length,market_context:marketContext,market_supply:supply,concentration,trend,printing_rows:rows,supply_pattern:{expected_tail:expectedTail,unexpected_break:anomaly},sku_ids:skus}})
 }catch(e){return js({handled:true,route:'card_family_supply',response:`I resolved “${name}” as a stock question, but the family-supply analysis failed. Try again shortly.`,presentation:{version:11,type:'card_family_supply',title:`${name} — Market depth`,summary:'Family-supply analysis failed.',badges:['ERROR'],metrics:[],sections:[],footnote:'This should not fall through to a set/SKU clarification.',actions:[]},data:{reason:'family_supply_error',error:String((e as Error)?.message||e)}})}
});
