import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:any)=>String(v??'').trim();
const sh=()=>({apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function rest(path:string,o:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:o.method||'GET',headers:{...sh(),...(o.prefer?{Prefer:o.prefer}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function rpc(name:string,body:any){return rest(`rpc/${name}`,{method:'POST',body})}
async function fn(name:string,body:any){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:sh(),body:JSON.stringify(body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.error||`${name} ${r.status}`);return d}
function alias(q:string){for(const p of[/^how\s+deep\s+is\s+(?:the\s+)?market\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^(?:what(?:'s| is)\s+)?(?:the\s+)?market\s+depth\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^how(?:'s| is)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity|depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/^(?:what(?:'s| is)|show(?: me)?|give me)\s+(?:the\s+)?(?:stock|supply|inventory|liquidity|depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i,/\b(?:stock|supply|inventory|liquidity|market\s+depth)\s+(?:on|for|of)\s+(.+?)(?:[?.!,]|$)/i]){const m=text(q).match(p);if(m?.[1])return m[1].trim()}return''}
const nfmt=(v:any)=>Number(v||0).toLocaleString('en-US');
const pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:'—';
function finish(v:any){const s=text(v).toUpperCase().replace(/[^A-Z]/g,'');return s.includes('FOIL')&&!s.includes('NONFOIL')?'FOIL':'NON FOIL'}
function labelFor(productId:any,finishScope:any,targets:any[]){const x=(targets||[]).find((r:any)=>text(r?.product_id)===text(productId)&&finish(r?.printing)===finishScope)||(targets||[]).find((r:any)=>text(r?.product_id)===text(productId));return [x?.set_code,x?.collector_number?`#${x.collector_number}`:null,finishScope==='FOIL'?'foil':'nonfoil'].filter(Boolean).join(' ')||`${productId} ${finishScope.toLowerCase()}`}
function summaryFor(v:any){const s=text(v).toUpperCase();if(s==='DEEP')return'Plenty available across the measured NM/LP family.';if(s==='MODERATE')return'Supply looks healthy overall, with some tighter variants.';if(s==='THIN'||s==='VERY_THIN')return'The measured NM/LP family is genuinely tight.';return'Current family depth is incomplete.'}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);
 const body=await req.json().catch(()=>({})),q=text(body?.question||body?.message),name=alias(q);if(!name)return js({handled:false,reason:'not_supply_question'});
 const targets:any[]=await rpc('ask_delvin_card_family_supply_targets_v1',{p_card_name:name,p_limit:80}).catch(()=>[]);if(!targets.length)return js({handled:false,reason:'no_exact_card_family'});
 const supply=await fn('market-supply-sync',{targets:targets.map(t=>({product_id:t.product_id,sku_id:t.sku_id,card_name:t.card_name,set_code:t.set_code,collector_number:t.collector_number,printing:t.printing,condition:t.condition,language:t.language,scryfall_id:t.scryfall_id})),scope:'CARD_FAMILY_NM_LP',max_pages:40});
 const skus=[...new Set(targets.map(t=>text(t.sku_id)))];const [concentration,trend]=await Promise.all([rpc('ask_collectish_family_supply_concentration_v1',{p_sku_ids:skus}).catch(()=>null),rpc('ask_collectish_family_supply_trend_v1',{p_sku_ids:skus,p_days:90}).catch(()=>null)]);
 const total=supply?.combined||{},ck=supply?.source_depth?.cardkingdom_retail||{},mp=supply?.source_depth?.manapool_retail||{},cardName=text(targets[0]?.card_name||name),classification=text(supply?.global_supply_classification||supply?.classification||'UNPROVEN').toUpperCase(),tcgClass=text(supply?.tcgplayer_supply_classification||total?.classification||'UNPROVEN').toUpperCase(),summaryBase=summaryFor(classification),tcg=Number(total.unit_count||0),listings=Number(total.listing_count||0),direct=Number(total.direct_unit_count||0),nonDirect=Number(total.non_direct_unit_count||0),mpQty=Number(mp.quantity??total.manapool_retail_quantity??0);
 const rows=Array.isArray(concentration?.printing_rows)?concentration.printing_rows:[],deep=concentration?.deepest_printing||null,tight=concentration?.tightest_printing||null,top1=Number(concentration?.top1_supply_share_pct),top3=Number(concentration?.top3_supply_share_pct),deepLabel=deep?labelFor(deep.product_id,deep.finish,targets):null,tightLabel=tight?labelFor(tight.product_id,tight.finish,targets):null;
 const trendLabel=text(trend?.trend||'UNPROVEN'),points=Number(trend?.complete_observation_points||0),trendText=trendLabel==='UNPROVEN'?`No historical direction yet — ${points} complete family observation${points===1?'':'s'}.`:`${nfmt(trend?.first_units)} → ${nfmt(trend?.last_units)} TCG units (${Number(trend?.unit_change_pct)>=0?'+':''}${Number(trend?.unit_change_pct||0).toFixed(1)}%) across ${nfmt(trend?.observed_span_days)} observed days · ${trendLabel.replaceAll('_',' ')}`;
 const response=`**${cardName} — Market depth**\n**${classification}** · ${summaryBase}\n\nTCGplayer (${tcgClass}): **${nfmt(tcg)}** units across **${nfmt(listings)}** listings\n↳ Direct **${nfmt(direct)}** · Non-Direct **${nfmt(nonDirect)}**\nManaPool NM/LP: **${nfmt(mpQty)}** copies\nCard Kingdom NM/EX: **${ck?.available?nfmt(ck.quantity):'unavailable'}**\n\n${deepLabel&&Number.isFinite(top1)?`Supply concentration: **${pct(top1)}** in ${deepLabel}; top 3 = **${pct(top3)}**.\n`:''}${tight&&tightLabel?`Tightest printing: **${tightLabel}** — ${text(tight.supply_classification)} (${nfmt(tight.unit_count)} units).\n`:''}History: ${trendText}`;
 const variantRows=rows.slice(0,10).map((r:any)=>({title:labelFor(r.product_id,r.finish,targets),subtitle:`${text(r.supply_classification).replaceAll('_',' ')} · ${pct(r.supply_share_pct)} of TCG family supply`,badges:[text(r.supply_classification)],metrics:[{label:'TCG',value:r.unit_count,display:nfmt(r.unit_count)},{label:'Listings',value:r.listing_count,display:nfmt(r.listing_count)},{label:'Direct',value:r.direct_unit_count,display:nfmt(r.direct_unit_count)}],raw:r}));
 const sections:any[]=[];if(concentration?.available)sections.push({heading:'Supply concentration',kind:'text',text:`Largest printing ${pct(top1)} · top 3 ${pct(top3)}. A scarce premium printing does not make the whole card family thin.`});if(variantRows.length)sections.push({heading:'Printing depth',kind:'ranked_rows',rows:variantRows});sections.push({heading:'Observed trend',kind:'text',text:trendText});
 const presentation={version:4,type:'card_family_supply',title:`${cardName} — Market depth`,summary:`${classification} · ${summaryBase}`,badges:[classification,`${text(supply?.confidence||'LOW')} CONFIDENCE`],metrics:[{label:'TCGplayer',value:tcg,display:`${nfmt(tcg)} units · ${nfmt(listings)} listings`},{label:'Direct',value:direct,display:nfmt(direct)},{label:'Non-Direct',value:nonDirect,display:nfmt(nonDirect)},{label:'ManaPool NM/LP',value:mpQty,display:nfmt(mpQty)},{label:'CK NM/EX',value:Number(ck.quantity||0),display:ck?.available?nfmt(ck.quantity):'unavailable'}],sections,footnote:`All resolved printings · English NM/LP · ${supply?.coverage?.complete_sku_count||0}/${targets.length} TCG SKUs complete · Direct is a subset of TCGplayer, not additive.`,actions:[]};
 return js({handled:true,route:'card_family_supply',response,presentation,data:{card_name:cardName,scope:'CARD_FAMILY_NM_LP',market_supply:supply,concentration,trend,sku_ids:skus}});
});
