import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const auth=(r:Request)=>r.headers.get('authorization')||'';
const token=(r:Request)=>{const h=auth(r);return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const text=(v:any)=>String(v??'').trim();
const norm=(v:any)=>text(v).toLowerCase().replace(/\s*\/\/\s*.*/,'').replace(/\([^)]*\)\s*$/,'').replace(/[^a-z0-9]+/g,' ').trim();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));

async function rpc(t:string,name:string,body:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:A,Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`${name} failed (${r.status})`);return d}
async function rest(t:string,path:string){const r=await fetch(`${U}/rest/v1/${path}`,{headers:{apikey:A,Authorization:`Bearer ${t}`}});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST failed (${r.status})`);return d}

function priceHistoryIntent(q:string){return /\b(?:price|market)\s+history\b|\b(?:graph|chart|plot|visuali[sz]e)\b.*\b(?:price|market)\b|\b(?:price|market)\b.*\b(?:graph|chart|plot|visuali[sz]e)\b/i.test(q)}
function requestedDays(q:string){const m=q.match(/\b(?:last|past)\s+(\d+)\s*(day|week|month|year)s?\b/i);if(m){const n=Math.max(1,Number(m[1])||1),u=m[2].toLowerCase();if(u==='day')return Math.min(730,n);if(u==='week')return Math.min(730,n*7);if(u==='month')return Math.min(730,n*30);if(u==='year')return Math.min(730,n*365)}if(/\b6\s*months?\b/i.test(q))return 180;if(/\b3\s*months?\b/i.test(q))return 90;if(/\b1\s*year\b|\b12\s*months?\b/i.test(q))return 365;return 180}
function cohortPhrase(q:string){for(const p of[/^why\s+are\s+(?:all\s+)?(.+?)(?:\s+cards?)?\s+(?:moving|spiking|rising|jumping|up)\??$/i,/^why\s+did\s+(?:all\s+)?(.+?)(?:\s+cards?)?\s+(?:move|spike|rise|jump)\??$/i,/^what(?:'s|\s+is)\s+driving\s+(?:all\s+)?(.+?)(?:\s+cards?)?\??$/i]){const m=q.match(p);if(m?.[1])return m[1].trim().replace(/[?.!,]+$/g,'')}return null}
function moveAlias(q:string){for(const p of[/^why\s+(?:did|has)\s+(.+?)\s+(?:spike|spiked|move|moved|jump|jumped|rise|rose|rally|rallied)\??$/i,/^why\s+is\s+(.+?)\s+(?:spiking|moving|rising|jumping|up)\??$/i]){const m=q.match(p);if(m?.[1])return m[1].trim().replace(/[?.!,]+$/g,'')}return null}
function sellerMapIntent(q:string){return /seller\s+(?:map|board)|opportunity\s+map|what should i (?:sell|reprice|watch)|act now|reprice now/i.test(q)||Boolean(cohortPhrase(q)||moveAlias(q))}

function money(v:any){const n=Number(v);return Number.isFinite(n)?`$${n.toFixed(2)}`:'—'}
function historySurface(h:any){const card=h?.card||{},prices=Array.isArray(h?.price_points)?h.price_points:[],sales=Array.isArray(h?.sales_points)?h.sales_points:[],days=Number(h?.days||180),first=prices[0]||null,last=prices.at(-1)||null;let change:null|number=null;if(Number(first?.market_price)>0&&Number.isFinite(Number(last?.market_price)))change=((Number(last.market_price)-Number(first.market_price))/Number(first.market_price))*100;return{type:'price_history',domain:'collectish',title:`${card.card_name||'Card'} · ${days}-day history`,card,days,price_points:prices,sales_points:sales,summary:{price_point_count:prices.length,sales_bucket_count:sales.length,market_start:first?.market_price??null,market_end:last?.market_price??null,market_change_pct:change,units:sales.reduce((s:number,r:any)=>s+Number(r.quantity_sold||0),0),transactions:sales.reduce((s:number,r:any)=>s+Number(r.transaction_count||0),0)}}}
function historyAnswer(h:any){const s=historySurface(h),x=s.summary;if(!x.price_point_count&&!x.sales_bucket_count)return `${s.card?.card_name||'That card'} resolved correctly, but Collectish does not currently have stored price or sales history for this exact SKU.`;const bits=[];if(x.price_point_count)bits.push(`Market ${money(x.market_start)} → ${money(x.market_end)}${x.market_change_pct==null?'':` (${x.market_change_pct>=0?'+':''}${x.market_change_pct.toFixed(1)}%)`}`);if(x.sales_bucket_count)bits.push(`${Number(x.units).toLocaleString()} copies across ${Number(x.transactions).toLocaleString()} transactions`);return `${s.card?.card_name||'Card'}: ${bits.join(' · ')} over the last ${s.days} days.`}
async function routePriceHistory(t:string,q:string){const rows=await rpc(t,'ask_resolve_card_context',{p_question:q}).catch(()=>[]),resolved=Array.isArray(rows)?rows[0]||null:rows;if(!resolved?.product_id&&!resolved?.sku_id)return null;const h=await rpc(t,'ask_card_price_history_v1',{p_product_id:resolved.product_id||null,p_sku_id:resolved.sku_id||null,p_days:requestedDays(q)});return{handled:true,route:'price_history',response:historyAnswer(h),surfaces:[historySurface(h)],tools:[{name:'ask_resolve_card_context',ok:true,classification:'READ'},{name:'ask_card_price_history_v1',ok:true,classification:'READ'}]}}

function parseMoveSignal(s:any){const title=text(s?.title),summary=text(s?.summary),tm=title.match(/^Interests\s*·\s*(average|market)\s*·\s*(foil|regular|nonfoil|non-foil)\s*·\s*\d+d\s*·\s*(.+)$/i),sm=summary.match(/MTGStocks Interests\s+(average|market)\s+(foil|regular|nonfoil|non-foil)\s+\d+d:\s*(.+?)\s+moved from \$([\d.]+) to \$([\d.]+) \(([+-]?[\d.]+)%\)/i);if(!tm&&!sm)return null;return{metric:text(sm?.[1]||tm?.[1]).toLowerCase(),finish:text(sm?.[2]||tm?.[2]).toLowerCase(),card_name:text(sm?.[3]||tm?.[3]),from:sm?Number(sm[4]):null,to:sm?Number(sm[5]):null,change:sm?Number(sm[6]):null,source_url:s?.source_url||null,observed_at:s?.observed_at||s?.published_at||null}}
function moveScore(m:any){return (m?.metric==='market'?10000:0)+Math.abs(Number(m?.change||0))}
function identityMatches(cardName:any,moveName:any){const a=norm(cardName),b=norm(moveName);return Boolean(a&&b&&(a===b||a.startsWith(`${b} `)||b.startsWith(`${a} `)))}
function rowWantsFoil(row:any){const p=text(row?.printing||row?.finish||row?.variant).toLowerCase();return p.includes('foil')&&!p.includes('non foil')&&!p.includes('non-foil')}
function moveIsFoil(move:any){return text(move?.finish).toLowerCase()==='foil'}
function matchMove(row:any,moves:any[]){let candidates=(moves||[]).filter(m=>identityMatches(row?.card_name||row?.product_name,m?.card_name));if(!candidates.length)return null;const wantFoil=rowWantsFoil(row),exact=candidates.filter(m=>moveIsFoil(m)===wantFoil);if(exact.length)candidates=exact;return [...candidates].sort((a,b)=>moveScore(a)-moveScore(b)).at(-1)||null}
function demandPressure(r:any){let s=0;const rank=Number(r?.edhrec_rank);if(rank>0)s+=clamp(38-Math.log10(rank)*8,0,30);const vel=Number(r?.avg_daily_qty_sold);if(Number.isFinite(vel))s+=clamp(vel*2.5,0,22);const qty=Number(r?.sales_qty_14d);if(Number.isFinite(qty))s+=clamp(qty/18,0,16);const scout=Number(r?.scout_score);if(Number.isFinite(scout))s+=clamp((scout-35)*0.4,0,15);s+=clamp(Number(r?.signal_count_14d||0)*3,0,9);s+=clamp(Number(r?.independent_sources_14d||0)*4,0,8);if(r?.buylist_backed)s+=5;const supply=text(r?.supply_type).toLowerCase();if(/thin|tight|low|shallow/.test(supply))s+=8;const direct=Number(r?.direct_available);if(Number.isFinite(direct)){if(direct<=15)s+=8;else if(direct<=40)s+=5;else if(direct<=80)s+=2}return clamp(Math.round(s),0,100)}
function classify(row:any,move:any){const demand=demandPressure(row),raw=Math.max(0,Number(move?.change||0)),priced=clamp(move?(move.metric==='market'?raw:raw*.42):0,0,180),catchup=clamp(Math.round(demand-priced*.42),0,100);let bucket='LOW PRIORITY';if(priced>=115)bucket='EXTENDED';else if(demand>=52&&priced<30)bucket='CATCH-UP';else if(demand>=48&&priced>=30)bucket='REPRICE NOW';else if(demand>=38&&priced<45)bucket='WATCH';return{...row,move:move||null,demand,priced,catchup,bucket}}
async function recentSignals(t:string,days=21){const cut=new Date(Date.now()-days*86400000).toISOString();return rest(t,`market_intel_items?observed_at=gte.${encodeURIComponent(cut)}&source_name=eq.MTGStocks&select=source_name,source_url,title,summary,published_at,observed_at&order=observed_at.desc&limit=1200`).catch(()=>[])}
async function lookup(t:string,q:string){const x=await rpc(t,'ask_collectish_public_card_lookup_v1',{p_query:q,p_limit:50}).catch(()=>[]);const rows=Array.isArray(x)?x:[],bySku=new Map();for(const r of rows){const k=text(r.sku_id||`${r.product_id}|${r.card_name}|${r.printing}`),old=bySku.get(k);if(!old||(!old.scryfall_id&&r.scryfall_id))bySku.set(k,r)}return[...bySku.values()]}
async function skuEvidence(t:string,ids:string[]){const v=[...new Set(ids.map(text).filter(Boolean))];return v.length?rpc(t,'ask_collectish_public_internal_sku_evidence_v1',{p_sku_ids:v}).catch(()=>[]):[]}
async function cardEvidence(t:string,names:string[]){const u=[...new Map(names.filter(Boolean).map(x=>[norm(x),x])).values()],out=[];for(let i=0;i<u.length;i+=50){const x=await rpc(t,'ask_collectish_public_internal_card_evidence_v1',{p_card_names:u.slice(i,i+50)}).catch(()=>[]);if(Array.isArray(x))out.push(...x)}return out}
function bestMoves(signals:any[],allowed:string[]){const names=new Map(allowed.map(n=>[norm(n),n])),best=new Map();for(const s of signals){const m=parseMoveSignal(s);if(!m||!Number.isFinite(m.change))continue;const n=norm(m.card_name);let canonical=names.get(n);if(!canonical){for(const[k,v]of names){if(n===k||n.startsWith(`${k} `)||k.startsWith(`${n} `)){canonical=v;break}}}if(!canonical)continue;const key=`${norm(canonical)}|${moveIsFoil(m)?'foil':'nonfoil'}`,old=best.get(key);if(!old||moveScore(m)>moveScore(old))best.set(key,{...m,card_name:canonical})}return[...best.values()]}
function sellerSurface(title:string,kind:string,rows:any[],meta:any={}){const buckets=['REPRICE NOW','CATCH-UP','WATCH','EXTENDED','LOW PRIORITY'],grouped:any={};for(const b of buckets)grouped[b]=rows.filter(r=>r.bucket===b).sort((a,b)=>b.catchup-a.catchup).slice(0,b==='LOW PRIORITY'?8:6);return{type:'seller_opportunity_map',domain:'collectish',title,kind,generated_at:new Date().toISOString(),groups:grouped,rows:rows.slice(0,80),meta}}
function sellerAnswer(title:string,rows:any[]){const count=(b:string)=>rows.filter(r=>r.bucket===b).length,parts=[];for(const b of['REPRICE NOW','CATCH-UP','WATCH','EXTENDED']){const n=count(b);if(n)parts.push(`${n} ${b.toLowerCase()}`)}return `${title}: ${parts.length?parts.join(' · '):'no high-priority seller actions from current evidence'}.`}
async function namedFamily(t:string,alias:string,signals:any[]){const found=await lookup(t,alias);if(!found.length)return null;const ev=await skuEvidence(t,found.map((r:any)=>r.sku_id));const emap=new Map((ev||[]).map((r:any)=>[text(r.sku_id),r])),moves=bestMoves(signals,found.map((r:any)=>r.card_name)),rows=found.map((r:any)=>{const merged={...r,...(emap.get(text(r.sku_id))||{})};return classify(merged,matchMove(merged,moves))});const title=`${alias} · seller opportunity map`;return{handled:true,route:'named_family_seller_map',response:sellerAnswer(title,rows),surfaces:[sellerSurface(title,'named_family',rows,{alias})],tools:[{name:'ask_collectish_public_card_lookup_v1',ok:true,classification:'READ'},{name:'ask_collectish_public_internal_sku_evidence_v1',ok:true,classification:'READ'}]}}
function subtypeCandidates(raw:string){const s=raw.trim().replace(/\s+tribal$/i,''),irr:any={elves:'Elf',wolves:'Wolf',dwarves:'Dwarf',mice:'Mouse',geese:'Goose',oxen:'Ox',bears:'Bear'};return[...new Set([irr[s.toLowerCase()],/ies$/i.test(s)?s.replace(/ies$/i,'y'):null,/s$/i.test(s)?s.replace(/s$/i,''):s,s].filter(Boolean).map((x:any)=>x[0].toUpperCase()+x.slice(1)))]}
async function subtypeCards(raw:string){for(const subtype of subtypeCandidates(raw)){let url=`https://api.scryfall.com/cards/search?q=${encodeURIComponent(`t:${subtype} game:paper`)}`,names=[] as string[];for(let page=0;page<5&&url;page++){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Collectish/1.0 shared Ask seller map'}});if(!r.ok){url='';break}const d=await r.json();for(const c of d?.data||[]){const n=text(c?.name);if(n&&!names.some(x=>norm(x)===norm(n)))names.push(n)}url=d?.has_more?d?.next_page:''}if(names.length)return{subtype,names}}return null}
async function cohort(t:string,phrase:string,signals:any[]){const resolved=await subtypeCards(phrase);if(!resolved)return null;const moves=bestMoves(signals,resolved.names),ev=await cardEvidence(t,resolved.names),emap=new Map((ev||[]).map((r:any)=>[norm(r.card_name),r])),names=[...new Set([...resolved.names,...moves.map((m:any)=>m.card_name)])],rows=names.map(name=>{const row={card_name:name,...(emap.get(norm(name))||{})};return classify(row,matchMove(row,moves))}).sort((a,b)=>b.catchup-a.catchup);const title=`${resolved.subtype} cards · seller opportunity map`;return{handled:true,route:'cohort_seller_map',response:sellerAnswer(title,rows),surfaces:[sellerSurface(title,'cohort',rows,{phrase,subtype:resolved.subtype})],tools:[{name:'scryfall_subtype_resolver',ok:true,classification:'READ'},{name:'ask_collectish_public_internal_card_evidence_v1',ok:true,classification:'READ'}]}}
async function routeSellerMap(t:string,q:string){if(!sellerMapIntent(q))return null;const signals=await recentSignals(t),cohortName=cohortPhrase(q);if(cohortName){const c=await cohort(t,cohortName,signals);if(c)return c}const alias=moveAlias(q)||q.replace(/seller\s+(?:map|board)|opportunity\s+map|show me|for/ig,' ').replace(/\s+/g,' ').trim();if(alias){const n=await namedFamily(t,alias,signals);if(n)return n}return null}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);const t=token(req);if(!t)return js({error:'Authentication required'},401);let body:any;try{body=await req.json()}catch{return js({error:'Invalid JSON'},400)}const action=text(body?.action||'chat').toLowerCase(),q=text(body?.message||body?.question);if(action!=='chat'||!q)return js({handled:false});try{if(priceHistoryIntent(q)){const r=await routePriceHistory(t,q);if(r)return js(r)}const s=await routeSellerMap(t,q);if(s)return js(s);return js({handled:false})}catch(error){return js({handled:false,error:String((error as Error)?.message||error)})}});
