import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});const text=(v:any)=>String(v??'').trim();
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function rpc(name:string,body:any={}){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.message||`${name} ${r.status}`);return d}
async function fn(name:string,body:any){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.error||`${name} ${r.status}`);return d}
async function cache(key:string){return rpc('get_delvin_query_cache_v1',{p_query_key:key})}
function rows(route:string,d:any){const p=d?.payload||d||{};if(route==='collectible_cohort_thesis')return Array.isArray(p.cards)?p.cards:[];if(route==='set_intelligence')return Array.isArray(p.leaders)?p.leaders:[];if(route==='printing_family'||route==='card_investigation')return Array.isArray(p.printings)?p.printings:[];return Array.isArray(p.rows)?p.rows:Array.isArray(p.raw)?p.raw:[]}
function identity(r:any){return{sku_id:r?.sku_id??null,product_id:r?.product_id??null,card_name:r?.card_name??r?.product_name??r?.name??null,set_code:r?.set_code??null,collector_number:r?.collector_number??null,printing:r?.printing??null,treatment:r?.treatment??null,evidence_tier:r?.evidence_tier??null,source_count:r?.source_count??null}}
function stable(v:any):string{if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;return JSON.stringify(v)}
async function fingerprint(route:string,d:any){const payload={route,rows:rows(route,d).map(identity)};const bytes=new TextEncoder().encode(stable(payload));const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,24)}
function answer(route:string,d:any){if(route==='collectible_cohort_thesis')return d?.assessment||'Collectible cohort analysis ready.';const n=rows(route,d).length;return n?`${String(route).replaceAll('_',' ')}: ${n} current result${n===1?'':'s'}.`:`${String(route).replaceAll('_',' ')}: no qualifying rows right now.`}
const owned=new Set(['mtgstocks_interests_both','tcgplayer_climbing','sales_acceleration','sales_acceleration_price_lag','direct_pressure_7d','direct_pressure_24h','cross_market_dislocations','syp_pressure_7d','market_radar','edh_demand_7d','creator_catalysts_7d','collectible_cohort_thesis','collectible_family_index','set_intelligence','treatment_intelligence','printing_family','card_investigation']);
async function execute(i:any){const route=String(i.route_key||i.query_key||'');if(i.capability_kind==='cached')return cache(route);if(route==='collectible_cohort_thesis')return rpc('ask_delvin_collectible_cohort_thesis_v1',{p_treatment:i.treatment,p_set_codes:i.set_codes,p_days:365});if(route==='collectible_family_index')return rpc('ask_delvin_collectible_family_index_v1',{p_treatment:i.treatment,p_limit:40});if(route==='set_intelligence')return rpc('ask_delvin_set_intelligence_v1',{p_set_code:i.set_code,p_limit:40});if(route==='treatment_intelligence')return rpc('ask_delvin_treatment_intelligence_v1',{p_set_code:i.set_code,p_treatment:i.treatment,p_limit:40});if(route==='printing_family')return rpc('ask_delvin_printing_family_v1',{p_card_name:i.card_name,p_limit:40});if(route==='card_investigation')return rpc('ask_delvin_card_investigation_v1',{p_card_name:i.card_name});return null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({handled:false},405);if(!S)return js({handled:false,error:'service role unavailable'},500);const b=await req.json().catch(()=>({})),q=text(b?.question||b?.message);if(!q)return js({handled:false});try{const intent=await rpc('resolve_delvin_registry_intent_v2',{p_question:q}).catch(()=>null),route=String(intent?.route_key||intent?.query_key||'');if(intent?.matched&&owned.has(route)){const data=await execute(intent);if(data!=null){const canonical_result_id=await fingerprint(route,data);return js({handled:true,route,response:answer(route,data),data,shared_query_key:intent.query_key||route,resolver_source:'delvin_query_registry',intent,canonical_result_id,canonical_row_count:rows(route,data).length,async_enrichment:intent.async_enrichment===true})}}return js(await fn('ask-collectish-delvin-route',b))}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});