import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});const text=(v:any)=>String(v??'').trim();
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function rpc(name:string,body:any={}){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.message||`${name} ${r.status}`);return d}
async function fn(name:string,body:any){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.error||`${name} ${r.status}`);return d}
async function cache(key:string){return rpc('get_delvin_query_cache_v1',{p_query_key:key})}
function rows(d:any){const p=d?.payload||{};return Array.isArray(p.rows)?p.rows:Array.isArray(p.raw)?p.raw:[]}
function answer(title:string,c:any){const r=rows(c);return r.length?`${title}: ${r.length} current result${r.length===1?'':'s'} from the shared Delvin cache.`:`${title}: no qualifying cached rows right now.`}
function keyFor(q:string){const s=q.toLowerCase().replace(/[’]/g,"'");if(/\bmtg\s*stocks?\b|\bmtgstocks\b/.test(s)&&/\binterests?|movers?|gainers?\b/.test(s))return'mtgstocks_interests_both';if(/\btcgplayer\b.*\b(?:climbing|price trends?)\b|\bclimbing in price\b/.test(s))return'tcgplayer_climbing';if(/\b(?:sales? acceleration|selling faster|started selling|sales? velocity)\b/.test(s))return/\b(?:before.*price|price.*(?:hasn['’]?t|has not|isn['’]?t|not).*mov|price lag)\b/.test(s)?'sales_acceleration_price_lag':'sales_acceleration';if(/\bdirect\b.*\b(?:tight|pressure|getting low|low inventory|inventory pressure)\b/.test(s))return/\b(?:today|24h|24 hours?)\b/.test(s)?'direct_pressure_24h':'direct_pressure_7d';if(/\b(?:cross[- ]?market|mispriced.*markets?|arbitrage|market dislocations?)\b/.test(s))return'cross_market_dislocations';if(/\bsyp\b.*\b(?:change|changes|pressure|meaningful|week|changed)\b|\bmeaningful syp\b/.test(s))return'syp_pressure_7d';return null}
const titles:any={mtgstocks_interests_both:'MTGStocks Interests',tcgplayer_climbing:'TCGplayer Climbing in Price',sales_acceleration:'Sales acceleration',sales_acceleration_price_lag:'Sales accelerating before price',direct_pressure_7d:'Direct inventory pressure',direct_pressure_24h:'Direct inventory pressure · 24h',cross_market_dislocations:'Cross-market dislocations',syp_pressure_7d:'Meaningful SYP changes'};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({handled:false},405);if(!S)return js({handled:false,error:'service role unavailable'},500);const b=await req.json().catch(()=>({})),q=text(b?.question||b?.message);if(!q)return js({handled:false});try{const key=keyFor(q);if(key){const c=await cache(key);return js({handled:true,route:key,response:answer(titles[key]||key,c),data:c,shared_query_key:key})}return js(await fn('ask-collectish-delvin-route',b))}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});