import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});const text=(v:any)=>String(v??'').trim();
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function rpc(name:string,body:any={}){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.message||`${name} ${r.status}`);return d}
async function fn(name:string,body:any){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await parse(r);if(!r.ok)throw Error((d as any)?.error||`${name} ${r.status}`);return d}
async function cache(key:string){return rpc('get_delvin_query_cache_v1',{p_query_key:key})}
function rows(d:any){const p=d?.payload||{};return Array.isArray(p.rows)?p.rows:Array.isArray(p.raw)?p.raw:[]}
function answer(title:string,c:any){const r=rows(c);return r.length?`${title}: ${r.length} current result${r.length===1?'':'s'} from the shared Delvin cache.`:`${title}: no qualifying cached rows right now.`}
const v2Cached=new Set(['mtgstocks_interests_both','tcgplayer_climbing','sales_acceleration','sales_acceleration_price_lag','direct_pressure_7d','direct_pressure_24h','cross_market_dislocations','syp_pressure_7d']);
async function keyFor(q:string){const d=await rpc('resolve_delvin_cached_query_v1',{p_question:q}).catch(()=>null);const key=String(d?.query_key||d?.route_key||'');return d?.matched&&v2Cached.has(key)?key:null}
const titles:any={mtgstocks_interests_both:'MTGStocks Interests',tcgplayer_climbing:'TCGplayer Climbing in Price',sales_acceleration:'Sales acceleration',sales_acceleration_price_lag:'Sales accelerating before price',direct_pressure_7d:'Direct inventory pressure',direct_pressure_24h:'Direct inventory pressure · 24h',cross_market_dislocations:'Cross-market dislocations',syp_pressure_7d:'Meaningful SYP changes'};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({handled:false},405);if(!S)return js({handled:false,error:'service role unavailable'},500);const b=await req.json().catch(()=>({})),q=text(b?.question||b?.message);if(!q)return js({handled:false});try{const key=await keyFor(q);if(key){const c=await cache(key);return js({handled:true,route:key,response:answer(titles[key]||key,c),data:c,shared_query_key:key,resolver_source:'delvin_query_registry'})}return js(await fn('ask-collectish-delvin-route',b))}catch(e){return js({handled:false,error:String((e as Error)?.message||e)})}});