import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const O=Deno.env.get('OPENAI_API_KEY')||'';
const MODEL=Deno.env.get('MARKET_INTEL_MODEL')||Deno.env.get('ASK_COLLECTISH_MODEL')||'gpt-5-mini';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const H=()=>({apikey:S||A,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
const bearer=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const trim=(x:any,n=2000)=>String(x??'').trim().slice(0,n);
const clamp=(x:any)=>Number.isFinite(Number(x))?Math.max(0,Math.min(1,Number(x))):.5;
const norm=(x:any)=>String(x||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const mmss=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
async function auth(t:string){if(!t)return false;if(S&&t===S)return true;try{const r=await fetch(`${U}/auth/v1/admin/users?page=1&per_page=1`,{headers:{apikey:t,Authorization:`Bearer ${t}`}});return r.ok}catch{return false}}
async function rest(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H(),...(opt.prefer?{Prefer:opt.prefer}:{})},body:opt.body===undefined?undefined:JSON.stringify(opt.body)});const raw=await r.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
const rpc=(n:string,a:any={})=>rest(`rpc/${n}`,{method:'POST',body:a});
function parse(raw:string){const s=String(raw||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),z=s.lastIndexOf('}');if(a>=0&&z>a){try{return JSON.parse(s.slice(a,z+1).replace(/,\s*([}\]])/g,'$1'))}catch{}}throw Error('invalid JSON')}
async function model(prompt:string,max=1800){if(!O)throw Error('OPENAI_API_KEY not configured');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${O}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,store:false,input:prompt,max_output_tokens:max})});const raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{d={error:{message:raw}}}if(!r.ok)throw Error(d?.error?.message||`OpenAI ${r.status}`);let out='';for(const x of d?.output||[])if(x.type==='message')for(const p of x.content||[])if(p.type==='output_text')out+=p.text;return out}
async function modelEvents(prompt:string){const raw=await model(prompt);try{return parse(raw)}catch{}try{return parse(await model(`Repair this into strict JSON with only {"events":[]}. Preserve complete events only. No prose. INPUT:\n${raw.slice(0,14000)}`,1500))}catch{return{events:[]}}}
async function card(name:string){for(const mode of ['exact','fuzzy']){try{const r=await fetch(`https://api.scryfall.com/cards/named?${mode}=${encodeURIComponent(name)}`,{headers:{'User-Agent':'MarketplaceScout/0.9 (+cedh reconcile)'}});if(!r.ok)continue;const c=await r.json();if(c?.id)return{name:String(c.name||name),scryfall_id:String(c.id),set_code:c.set?String(c.set):null}}catch{}}return null}
function cleanSegments(xs:any[]){return(xs||[]).map(x=>({text:trim(x?.text,1400),offset:Number(x?.offset)||0,duration:Number(x?.duration)||0})).filter(x=>x.text)}
function titleCandidate(title:string){const t=String(title||'');const pats=[/\bwith\s+(.+?)\s+in\s+cEDH\b/i,/\bRebuilding[^:]*:\s*(.+?)(?:\s+in\s+cEDH)?$/i,/\bBuilding\s+(.+?)(?:\s+in\s+cEDH)?$/i,/:\s*([^:]+?)\s+in\s+cEDH\b/i,/:[^:]*:\s*([^:]+)$/i];for(const p of pats){const m=t.match(p);if(m?.[1])return trim(m[1].replace(/\s+ft\.?\s*:.*$/i,''),200)}return''}
function evidenceSegment(xs:any[],re:RegExp){return xs.find(x=>re.test(x.text))||null}
async function deterministic(item:any,xs:any[]){const guess=titleCandidate(item.title);if(!guess)return[];const resolved=await card(guess);if(!resolved)return[];const out:any[]=[];const result=evidenceSegment(xs,/(top\s*(?:8|16|cut)|finish(?:ed)?\s+top\s*(?:8|16)|made\s+top\s*(?:8|16|cut))/i);const played=evidenceSegment(xs,/(played|tournament|event|swiss|top\s*16)/i);if(result&&played){out.push({canonical_name:resolved.name,event_type:'competitive_result',direction:'bullish',signal_stage:'confirming',confidence:.97,prominence:.95,start_ms:result.offset,end_ms:result.offset+result.duration,evidence:trim(result.text,900),summary:`${resolved.name} was tied to a reported cEDH tournament top-cut result.`})}const endorse=evidenceSegment(xs,/(busted|extremely impressive|very good|really good|deck played very well|well positioned|highly recommend|recommend trying|deck(?:'s| is) great|transformative)/i);if(endorse){out.push({canonical_name:resolved.name,event_type:'cedh_adoption',direction:'bullish',signal_stage:'leading',confidence:.96,prominence:.95,start_ms:endorse.offset,end_ms:endorse.offset+endorse.duration,evidence:trim(endorse.text,900),summary:`${resolved.name} received an explicit strong cEDH endorsement after real play/testing.`})}return out}
function selected(xs:any[]){const re=/(top\s*(?:8|16|cut)|tournament|won\b|winning|finish|busted|very good|recommend|well positioned|transformative|incredible|really good|very strong|added|cut\b|played|playing|testing|commander)/i;const m=new Map<number,any>();for(const x of xs.slice(0,8))m.set(x.offset,x);for(const x of xs)if(re.test(x.text))m.set(x.offset,x);for(const x of xs.slice(-8))m.set(x.offset,x);return[...m.values()].sort((a:any,b:any)=>a.offset-b.offset).slice(0,42)}
function prompt(item:any,xs:any[]){const tx=selected(xs).map((x:any)=>`[${mmss(x.offset)}] ${x.text}`).join('\n');return`Extract only strong CARD-LEVEL cEDH creator evidence missed by a generic extractor. Return ONLY JSON {"events":[{"canonical_name":string,"event_type":"competitive_result"|"cedh_adoption"|"deck_innovation"|"competitive_test","direction":"bullish"|"bearish"|"neutral","signal_stage":"leading"|"confirming"|"lagging"|"neutral","confidence":number,"prominence":number,"start_ms":integer,"end_ms":integer|null,"evidence":string,"summary":string}]}. Top 8/Top 16/top cut or meaningful tournament result tied to a card/commander => competitive_result. Personal testing/play plus very good/busted/incredible/transformative/well positioned/recommendation => cedh_adoption. Non-obvious tech with explicit rationale => deck_innovation. Routine decklist recitation, neutral rules text, opponent cards, and product/set facts are NOT signals. A result plus separate endorsement may produce two events for the same card. Prefer the card/commander central to the title. At most 5. No financial advice. Creator=${item.channel_name}. Title=${item.title}. Transcript:\n${tx}`}
async function saveEvent(item:any,cap:any,e:any,keys:Set<string>){const resolved=await card(trim(e?.canonical_name,300));if(!resolved)return null;const allowed=['competitive_result','cedh_adoption','deck_innovation','competitive_test'];const type=allowed.includes(String(e?.event_type))?String(e.event_type):'competitive_test';const start=Math.max(0,Math.round(Number(e?.start_ms)||0)),end=Number.isFinite(Number(e?.end_ms))?Math.max(start,Math.round(Number(e.end_ms))):null,confidence=clamp(e?.confidence),prominence=clamp(e?.prominence);if(confidence<.68||prominence<.62)return null;const key=`${item.video_id}|${type}|${start}|${norm(resolved.name)}`;if(keys.has(key))return null;const direction=['bullish','bearish','neutral'].includes(String(e?.direction))?String(e.direction):'neutral';const stage=['leading','confirming','lagging','neutral'].includes(String(e?.signal_stage))?String(e.signal_stage):(type==='competitive_result'?'confirming':'leading');const url=item.source_url||`https://www.youtube.com/watch?v=${item.video_id}`;const inserted=await rest('market_intel_items',{method:'POST',prefer:'return=representation',body:{user_id:cap.user_id,source_type:'youtube',source_name:item.channel_name||cap.source||'YouTube',source_url:url,title:item.title||resolved.name,author:item.channel_name||cap.source||null,summary:trim(e?.summary||e?.evidence,1200)||`${resolved.name}: ${type.replace(/_/g,' ')}`,claim_type:'competitive',direction,signal_stage:stage,confidence,published_at:item.published_at||null,source_profile:'creator_cedh',source_subtype:type,metadata_json:{platform:'youtube',video_id:item.video_id,channel_id:item.channel_id||null,creator_lane:'competitive',source_profile:'creator_cedh',reconciled:true,reconcile_policy:'cedh_strong_evidence_v2',video_event_key:key,event_type:type,start_ms:start,end_ms:end,prominence,raw_mention:e?.canonical_name||resolved.name,resolution_method:'cedh_reconcile_scryfall',resolution_confidence:confidence}}});const intel=Array.isArray(inserted)?inserted[0]:inserted;if(!intel?.intel_id)return null;await rest('market_intel_entities',{method:'POST',prefer:'return=minimal',body:{intel_id:intel.intel_id,user_id:cap.user_id,entity_type:'card',entity_name:resolved.name,scryfall_id:resolved.scryfall_id,set_code:resolved.set_code,confidence}});await rest('market_intel_video_events',{method:'POST',prefer:'resolution=ignore-duplicates,return=minimal',body:{intel_id:intel.intel_id,user_id:cap.user_id,video_id:item.video_id,channel_id:item.channel_id||null,channel_name:item.channel_name||cap.source||null,creator_lane:'competitive',event_type:type,start_ms:start,end_ms:end,prominence,evidence:trim(e?.evidence,900)||null,transcript_provider:'supadata',transcript_mode:'native'}}).catch(()=>null);keys.add(key);return{card:resolved.name,event_type:type,start_ms:start,confidence,prominence}}
async function reconcile(item:any){const sk=`youtube:${item.video_id}:transcript`;const caps=await rest(`source_captures?select=capture_id,user_id,source,payload_json,metadata_json&capture_type=eq.video_transcript&source_key=eq.${encodeURIComponent(sk)}&limit=1`);const cap=caps?.[0];if(!cap)return{video_id:item.video_id,events_saved:0,error:'transcript_missing'};const xs=cleanSegments(cap?.payload_json?.segments||[]);if(!xs.length)return{video_id:item.video_id,events_saved:0,error:'segments_missing'};const det=await deterministic(item,xs);let modeled:any[]=[];try{const p=await modelEvents(prompt(item,xs));modeled=Array.isArray(p?.events)?p.events.slice(0,5):[]}catch{}const candidates=[...det,...modeled];const url=item.source_url||`https://www.youtube.com/watch?v=${item.video_id}`;const existing=await rest(`market_intel_items?select=intel_id,metadata_json&user_id=eq.${encodeURIComponent(cap.user_id)}&source_url=eq.${encodeURIComponent(url)}&limit=100`).catch(()=>[]);const keys=new Set((existing||[]).map((x:any)=>String(x?.metadata_json?.video_event_key||'')));const details=[];for(const e of candidates){const d=await saveEvent(item,cap,e,keys);if(d)details.push(d)}await rpc('mark_youtube_cedh_reconciled',{p_user_id:cap.user_id,p_video_id:item.video_id,p_events:details.length}).catch(()=>null);if(details.length){await rpc('refresh_market_intel_entity_links',{}).catch(()=>null);await rpc('refresh_market_intel_evaluations',{}).catch(()=>null)}return{video_id:item.video_id,events_saved:details.length,deterministic_considered:det.length,model_considered:modeled.length,details}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return J({error:'POST required'},405);const t=bearer(req);if(!t||!(await auth(t)))return J({error:'Service authentication required'},401);if(!S)return J({error:'Service role unavailable'},500);let b:any={};try{b=await req.json()}catch{}const limit=Math.max(1,Math.min(Number(b?.limit)||2,5)),requested=trim(b?.video_id,100);try{let rows:any[];if(requested)rows=await rest(`market_intel_youtube_video_ledger?select=user_id,video_id,channel_id,channel_name,title,source_url,published_at,status,cards_detected,events_detected,cedh_reconciled_at&video_id=eq.${encodeURIComponent(requested)}&limit=1`);else rows=await rest(`market_intel_youtube_cedh_reconcile_pending?select=*&order=published_at.desc.nullslast&limit=${limit}`);const results=[];for(const row of rows.slice(0,limit))results.push(await reconcile(row));return J({ok:true,policy:'cedh_strong_evidence_v2',processed:results.length,events_saved:results.reduce((n:any,x:any)=>n+Number(x.events_saved||0),0),results})}catch(e){return J({error:(e as Error).message},502)}});