import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const O=Deno.env.get('OPENAI_API_KEY')||'';
const MODEL=Deno.env.get('ASK_WEB_MODEL')||'gpt-5.4-mini';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const tok=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const uh=(t:string)=>({apikey:A,Authorization:`Bearer ${t}`,'Content-Type':'application/json'});
const clean=(s:any)=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const clip=(v:any,n=12000)=>{const s=typeof v==='string'?v:JSON.stringify(v??{});return s.length>n?s.slice(0,n)+'…':s};
async function user(t:string){const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('Unauthorized');const x=await r.json();if(!x?.id)throw Error('Unauthorized');return x}
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function canonicalUrl(raw:string){try{const u=new URL(raw);['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].forEach(k=>u.searchParams.delete(k));u.hash='';return u.toString()}catch{return raw}}
function outputText(r:any){if(typeof r?.output_text==='string'&&r.output_text.trim())return r.output_text.trim();const a:string[]=[];for(const x of r?.output||[]){if(typeof x?.text==='string'&&x.text.trim())a.push(x.text);if(x?.type==='message')for(const c of x.content||[]){const v=c?.text||c?.value||c?.output_text;if(typeof v==='string'&&v.trim())a.push(v)}}return [...new Set(a)].join('\n').trim()}
function searchCalls(r:any){return (r?.output||[]).filter((x:any)=>x?.type==='web_search_call')}
function resultRows(r:any){const rows:any[]=[];for(const x of searchCalls(r)){for(const s of x?.action?.sources||[])rows.push({title:s?.title||null,url:s?.url||null,published_at:s?.published_at||s?.date||null,snippet:s?.snippet||null});for(const z of x?.results||x?.action?.results||[])rows.push({title:z?.title||z?.name||null,url:z?.url||z?.link||null,published_at:z?.published_at||z?.published_date||z?.date||null,snippet:z?.snippet||z?.text||z?.description||null})}return rows}
function cardSpecificity(title:string,snippet:string,card:any){const name=clean(card?.product_name||card?.name||''),set=clean(card?.set_name||''),t=clean(title),s=clean(snippet);if(name&&t.includes(name))return 1;if(name&&s.includes(name))return .8;if(set&&(t.includes(set)||s.includes(set)))return .4;return .15}
function mtgContextScore(url:string,title:string,snippet:string){const txt=clean(`${title} ${snippet||''} ${url}`);let score=0;if(/\bmagic\b|\bmtg\b|\bcommander\b|\bedh\b|tcgplayer|edhrec|scryfall|decklist|card game|mana|buyout|mtgfinance/.test(txt))score+=1;if(/\/r\/(?:edh|magictcg|mtg|mtgfinance|competitiveedh|budgetbrews)\b/i.test(url))score+=2;if(/\b5e\b|dungeons dragons|d d campaign|baldur s gate campaign/.test(txt))score-=2;return score}
function sourceKind(url:string){const h=host(url);if(/magic\.wizards\.com|wizards\.com/.test(h))return'Official';if(/edhrec\.com/.test(h))return'Commander';if(/tcgplayer\.com|mtgstocks\.com|cardmarket\.com|tcgstrat\.com/.test(h))return'Market';if(/mtgdecks\.net|mtgtop8\.com|melee\.gg|mtggoldfish\.com/.test(h))return'Decks';if(/reddit\.com|youtube\.com|youtu\.be/.test(h))return'Community';return'Web'}
function evidenceRole(url:string,kind:string,title:string,specificity:number,titleSpecific:boolean){let path='';try{path=new URL(url).pathname.toLowerCase()}catch{}const t=clean(title);if(kind==='Market')return'background';if(kind==='Official'&&(/\/sets\//.test(path)||!/card|deck|ban|announcement|rules|update|news|article|release|reprint|secret lair/.test(t)))return'background';if(kind==='Commander'&&(/^\/cards\//.test(path)||/\/articles\/tagged\//.test(path)||/tagged with/.test(t)))return'background';if(/price|prices|pricing|market page|card page|set page|search results|articles tagged|price tracking/.test(t))return'background';if((kind==='Community'||kind==='Decks')&&!titleSpecific)return'background';if(kind==='Commander'&&specificity<.8)return'background';if(kind==='Official'&&specificity<.8&&!/ban|announcement|rules|release|spoiler|reprint|secret lair/.test(t))return'background';return'event_evidence'}
function marketLinkage(kind:string,role:string,title:string,snippet:string,url:string,contextScore:number,specificity:number){if(role!=='event_evidence'||contextScore<=0)return false;const txt=clean(`${title} ${snippet} ${url}`);const marketAction=/buyout|buying|bought|sold out|sellout|spike|spiking|price jump|price increase|market move|finance|speculat|demand|copies|listings|inventory|tcgplayer|mtgstocks|cardmarket/.test(txt);const discussion=kind==='Community'||kind==='Decks'||kind==='Commander'||kind==='Official';return Boolean(marketAction&&discussion&&specificity>=.65)}
function rankSource(s:any,card:any){const url=canonicalUrl(s?.url||''),title=s?.title||host(url)||'Source',snippet=s?.snippet||'',txt=clean(`${title} ${url} ${snippet}`),name=clean(card?.product_name||card?.name||''),set=clean(card?.set_name||''),tokens=name.split(' ').filter((x:string)=>x.length>3),hits=tokens.filter((x:string)=>txt.includes(x)).length;let relevance=tokens.length?hits/tokens.length:0;if(name&&txt.includes(name))relevance=1;if(set&&txt.includes(set))relevance=Math.max(relevance,.45);const kind=sourceKind(url),specificity=cardSpecificity(title,snippet,card),titleSpecific=Boolean(name&&clean(title).includes(name)),contextScore=mtgContextScore(url,title,snippet),genericMarket=kind==='Market'&&relevance>=.25,keep=(kind!=='Community'||contextScore>0)&&(relevance>=.45||genericMarket||(kind==='Official'&&relevance>=.2));const role=evidenceRole(url,kind,title,specificity,titleSpecific),market_linkage=marketLinkage(kind,role,title,snippet,url,contextScore,specificity);const quality=kind==='Official'?6:kind==='Commander'?5:(kind==='Market'||kind==='Decks')?4:kind==='Community'?2:1;return{...s,title,url,kind,evidence_role:role,market_linkage,card_specificity:Number(specificity.toFixed(2)),mtg_context_score:contextScore,relevance_score:Number(relevance.toFixed(2)),keep,score:quality*10+Math.round(relevance*10)+Math.round(specificity*10)+(role==='event_evidence'?15:0)+(market_linkage?20:0)}}
function sources(r:any,card:any){const merged=new Map<string,any>();for(const row of resultRows(r)){if(!row?.url)continue;const url=canonicalUrl(row.url),old=merged.get(url)||{};merged.set(url,{...old,...row,url,title:row.title||old.title||null,published_at:row.published_at||old.published_at||null,snippet:row.snippet||old.snippet||null})}const seen=new Set<string>();return [...merged.values()].map(x=>rankSource(x,card)).filter(x=>x.keep&&x.url).sort((a,b)=>b.score-a.score).filter(x=>{const k=`${host(x.url)}|${clean(x.title).slice(0,90)}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,10).map(({keep,score,...x})=>x)}
function extractEvents(raw:string,src:any[]){const marker='COLLECTISH_EVENTS_JSON=',at=raw.lastIndexOf(marker);if(at<0)return{answer:raw.trim(),events:[]};const answer=raw.slice(0,at).trim(),j=raw.slice(at+marker.length).trim();let parsed:any[]=[];try{const x=JSON.parse(j);if(Array.isArray(x))parsed=x}catch{}const byUrl=new Map(src.map(s=>[canonicalUrl(s.url),s]));const events=parsed.slice(0,8).map(e=>{const url=canonicalUrl(String(e?.url||'')),source=byUrl.get(url),title=String(e?.title||source?.title||'External event').slice(0,180);let confidence=/^(low|medium|high)$/i.test(String(e?.evidence_confidence||e?.confidence||''))?String(e.evidence_confidence||e.confidence).toLowerCase():'medium';const specificity=Number(source?.card_specificity??.5);if(specificity<.65&&confidence==='high')confidence='medium';if(specificity<.35)confidence='low';return{date:/^\d{4}-\d{2}-\d{2}$/.test(String(e?.date||''))?String(e.date):null,title,kind:String(e?.kind||source?.kind||'Web').slice(0,40),url:source?.url||url||null,evidence_confidence:confidence,evidence_role:source?.evidence_role||'event_evidence',market_linkage:Boolean(source?.market_linkage),card_specificity:specificity}}).filter(e=>e.date&&e.title&&e.evidence_role!=='background'&&!/updated\/crawled|page refresh|current price|price tracking|pricing data|market page|card page update/i.test(e.title));return{answer,events}}
function day(v:any){const n=Date.parse(String(v||''));return Number.isFinite(n)?Math.floor(n/86400000):null}
function causalAssessment(events:any[],evidence:any){const anchor=day(evidence?.measured_acceleration_at),dated=events.map(e=>({...e,d:day(e.date)})).filter(e=>e.d!=null),linked=dated.filter(e=>e.market_linkage),hosts=new Set(linked.map(e=>host(e.url)).filter(Boolean));let closest:null|number=null;for(const e of dated){if(anchor==null)continue;const delta=e.d-anchor;if(closest==null||Math.abs(delta)<Math.abs(closest))closest=delta}const timing_strength=closest==null?'UNKNOWN':Math.abs(closest)<=3?'STRONG':Math.abs(closest)<=7?'MODERATE':'WEAK';let causal_confidence='LOW';if(linked.length&&timing_strength==='STRONG')causal_confidence=hosts.size>=2?'HIGH':'MEDIUM';else if(linked.length)causal_confidence='MEDIUM';const market_linking_source_count=linked.length;const conclusion=market_linking_source_count?`${market_linking_source_count} retained source${market_linking_source_count===1?'':'s'} explicitly link${market_linking_source_count===1?'s':''} an external event to MTG/card-market behavior.`:'No market-linking source found; dated external events are timing hypotheses, not established catalysts.';return{causal_confidence,timing_strength,market_linking_source_count,closest_event_days:closest,conclusion}}
async function openai(body:any){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${O}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{d={error:{message:raw.slice(0,800)}}}if(!r.ok)throw Error(d?.error?.message||`OpenAI ${r.status}`);return d}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);const t=tok(req);if(!t)return js({error:'Authentication required'},401);let u:any;try{u=await user(t)}catch{return js({error:'Authentication required'},401)}let b:any;try{b=await req.json()}catch{return js({error:'Invalid JSON'},400)}const q=String(b?.question||b?.message||'').trim();if(!q)return js({error:'question required'},400);if(!O)return js({error:'OPENAI_API_KEY not configured'},500);const card=b?.card||b?.context?.entity||{},evidence=b?.internal_evidence||{};
 const eventInstruction=`At the very end append exactly one machine-readable line beginning COLLECTISH_EVENTS_JSON= followed by a valid JSON array. Include at most 6 DATED external event candidates supported by event-specific sources, with date (YYYY-MM-DD), title, kind, url, evidence_confidence (low|medium|high). Evidence confidence means confidence the event/source exists and is card-relevant; it is NOT causal confidence. Never include card pages, price/listing/tracking pages, taxonomy/tag pages, routine crawls, or generic deck pages as events.`;
 const instructions=`You are Collectish external MTG market research. You MUST use web search. Search for dated evidence around the measured market acceleration. Keep three concepts separate: (1) event confidence = did the dated event happen; (2) timing strength = how close it was to measured acceleration; (3) causal confidence = is there evidence collectors/players/sellers actually reacted to that event. News/general event coverage verifies the event but is not market linkage. NEVER call an external event a likely/probable catalyst solely because dates line up. Before calling an event a likely catalyst, require at least one source explicitly connecting that event to MTG/card-market behavior such as buying, buyouts, sellouts, price movement, listings, collector demand, or finance discussion. Prefer MTGFinance/MTG community, seller/editorial, content creator, and marketplace commentary for that linkage. If no market-linking source is found, say exactly that it is a plausible timing hypothesis and direct card-market linkage was not found. Reject same-name non-MTG results. Start with a Quick read under 75 words, then External findings and Timing/causation. ${eventInstruction}`;
 const input=`Question: ${q}\nCard context: ${clip(card,1800)}\nInternal Collectish evidence: ${clip(evidence,8000)}\nFocus on evidence preceding or overlapping the first measured acceleration. Explicitly search for card-market discussion connecting candidate events to buying/demand, not just general news coverage.`;
 try{let d=await openai({model:MODEL,store:false,instructions,input,tools:[{type:'web_search_preview',search_context_size:'medium'}],tool_choice:'auto',include:['web_search_call.action.sources','web_search_call.results'],max_output_tokens:1800}),calls=searchCalls(d),src=sources(d,card),rawAnswer=outputText(d),synthesis_fallback=false;if(!src.length)throw Error('Web search completed without relevant source metadata');if(!rawAnswer){synthesis_fallback=true;const synth=await openai({model:MODEL,store:false,instructions:'You are a concise MTG market research synthesizer. Never infer causation from timing alone. General news verifies an event but is not market linkage.',input:`Question: ${q}\nCard: ${clip(card,1800)}\nInternal evidence: ${clip(evidence,6000)}\nSearch output: ${clip(calls,12000)}\nRetained sources: ${clip(src,6000)}\n${eventInstruction}`,tool_choice:'none',max_output_tokens:1400});rawAnswer=outputText(synth);if(!rawAnswer)throw Error('Search sources returned but synthesis was empty');d={...d,model:synth?.model||d?.model,usage:synth?.usage||d?.usage}}const parsed=extractEvents(rawAnswer,src),events=parsed.events,causal_assessment=causalAssessment(events,evidence);let answer=parsed.answer;if(causal_assessment.market_linking_source_count===0){answer=`Causal confidence: LOW — ${causal_assessment.conclusion}\n\n${answer}`};await fetch(`${U}/rest/v1/ask_collectish_research_runs`,{method:'POST',headers:{...uh(t),Prefer:'return=minimal'},body:JSON.stringify([{user_id:u.id,product_id:card?.product_id??null,sku_id:card?.sku_id??null,query_text:q,model:d?.model||MODEL,source_count:src.length}])}).catch(()=>{});return js({ok:true,answer,sources:src,events,causal_assessment,market_linking_source_count:causal_assessment.market_linking_source_count,model:d?.model||MODEL,usage:d?.usage||null,source_count:src.length,event_source_count:src.filter(x=>x.evidence_role==='event_evidence').length,web_search_used:true,synthesis_fallback})}catch(e){return js({ok:false,error:String((e as Error).message),web_search_used:false},502)}
});
