import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const A=Deno.env.get('SUPABASE_ANON_KEY')||'';
const O=Deno.env.get('OPENAI_API_KEY')||'';
const MODEL=Deno.env.get('ASK_WEB_MODEL')||'gpt-5.4-mini';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const tok=(r:Request)=>{const h=r.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7):''};
const uh=(t:string)=>({apikey:A,Authorization:`Bearer ${t}`,'Content-Type':'application/json'});
async function user(t:string){const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('Unauthorized');const x=await r.json();if(!x?.id)throw Error('Unauthorized');return x}
function clip(v:any,n=12000){const s=typeof v==='string'?v:JSON.stringify(v??{});return s.length>n?s.slice(0,n)+'…':s}
function outputText(r:any){const direct=r?.output_text;if(typeof direct==='string'&&direct.trim())return direct.trim();if(Array.isArray(direct)){const s=direct.map((x:any)=>typeof x==='string'?x:(x?.text||x?.value||'')).filter(Boolean).join('\n').trim();if(s)return s}const a:string[]=[];for(const x of r?.output||[]){if(typeof x?.text==='string'&&x.text.trim())a.push(x.text);if(x?.type==='message')for(const c of x.content||[]){if(typeof c?.text==='string'&&c.text.trim())a.push(c.text);else if(typeof c?.value==='string'&&c.value.trim())a.push(c.value);else if(typeof c?.output_text==='string'&&c.output_text.trim())a.push(c.output_text)}}return [...new Set(a)].join('\n').trim()}
function searchCalls(r:any){return (r?.output||[]).filter((x:any)=>x?.type==='web_search_call')}
const clean=(s:any)=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function canonicalUrl(raw:string){try{const u=new URL(raw);['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].forEach(k=>u.searchParams.delete(k));u.hash='';return u.toString()}catch{return raw}}
function prettyPath(raw:string,card:any){try{const u=new URL(raw),parts=u.pathname.split('/').filter(Boolean).map(x=>decodeURIComponent(x));const cardName=String(card?.product_name||card?.name||'').trim();if(/edhrec\.com$/.test(u.hostname)&&parts[0]==='cards'&&cardName)return `${cardName} — EDHREC`;const slug=(parts.at(-1)||'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).trim();if(slug&&slug.length>4&&!/^\d+$/.test(slug))return slug;return u.hostname.replace(/^www\./,'')}catch{return 'Source'}}
function resultRows(r:any){const rows:any[]=[];for(const x of searchCalls(r)){for(const s of x?.action?.sources||[])rows.push({title:s?.title||null,url:s?.url||null,type:s?.type||null,published_at:s?.published_at||s?.date||null,snippet:s?.snippet||null});for(const z of x?.results||x?.action?.results||[]){rows.push({title:z?.title||z?.name||null,url:z?.url||z?.link||null,type:z?.type||'search_result',published_at:z?.published_at||z?.published_date||z?.date||null,snippet:z?.snippet||z?.text||z?.description||null})}}return rows}
function rankSource(s:any,card:any){const url=canonicalUrl(s?.url||''),h=host(url),title=s?.title||prettyPath(url,card),txt=clean(`${title} ${url} ${s?.snippet||''}`),name=clean(card?.product_name||card?.name||''),set=clean(card?.set_name||'');const nameTokens=name.split(' ').filter((x:string)=>x.length>3),nameHits=nameTokens.filter((x:string)=>txt.includes(x)).length;let relevance=nameTokens.length?nameHits/nameTokens.length:0;if(name&&txt.includes(name))relevance=1;if(set&&txt.includes(set))relevance=Math.max(relevance,.45);let quality=1,kind='Web';if(/magic\.wizards\.com|wizards\.com/.test(h)){quality=6;kind='Official'}else if(/edhrec\.com/.test(h)){quality=5;kind='Commander'}else if(/tcgplayer\.com|mtgstocks\.com|cardmarket\.com/.test(h)){quality=4;kind='Market'}else if(/mtgdecks\.net|mtgtop8\.com|melee\.gg|mtggoldfish\.com/.test(h)){quality=4;kind='Decks'}else if(/reddit\.com|youtube\.com|youtu\.be/.test(h)){quality=2;kind='Community'}const genericMarket=kind==='Market'&&relevance>=.25;const keep=relevance>=.45||genericMarket||(kind==='Official'&&relevance>=.2);return {...s,title,url,kind,quality,relevance_score:Number(relevance.toFixed(2)),keep,score:quality*10+Math.round(relevance*10)}}
function sources(r:any,card:any){const merged=new Map<string,any>();for(const row of resultRows(r)){if(!row?.url)continue;const url=canonicalUrl(row.url),old=merged.get(url)||{};merged.set(url,{...old,...row,url,title:row.title||old.title||null,published_at:row.published_at||old.published_at||null,snippet:row.snippet||old.snippet||null})}const seenEvidence=new Set<string>();return [...merged.values()].map(x=>rankSource(x,card)).filter(x=>x.keep&&x.url).sort((a,b)=>b.score-a.score).filter(x=>{const evidenceKey=`${host(x.url)}|${clean(x.title).replace(clean(card?.product_name||''),'').slice(0,80)}`;if(seenEvidence.has(evidenceKey))return false;seenEvidence.add(evidenceKey);return true}).slice(0,8).map(({keep,score,...x})=>x)}
function extractEvents(raw:string,src:any[]){const marker='COLLECTISH_EVENTS_JSON=';const at=raw.lastIndexOf(marker);if(at<0)return {answer:raw.trim(),events:[]};const answer=raw.slice(0,at).trim();const jsonText=raw.slice(at+marker.length).trim();let parsed:any[]=[];try{const x=JSON.parse(jsonText);if(Array.isArray(x))parsed=x}catch{}const byUrl=new Map(src.map(s=>[canonicalUrl(s.url),s]));const events=parsed.slice(0,6).map(e=>{const url=canonicalUrl(String(e?.url||'')),source=byUrl.get(url);return {date:/^\d{4}-\d{2}-\d{2}$/.test(String(e?.date||''))?String(e.date):null,title:String(e?.title||source?.title||'External event').slice(0,180),kind:String(e?.kind||source?.kind||'Web').slice(0,40),url:source?.url||url||null,confidence:/^(low|medium|high)$/i.test(String(e?.confidence||''))?String(e.confidence).toLowerCase():'medium'}}).filter(e=>e.date&&e.title);return {answer,events}}
async function openai(body:any){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${O}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const raw=await r.text();let d:any;try{d=JSON.parse(raw)}catch{d={error:{message:raw.slice(0,800)}}}if(!r.ok)throw Error(d?.error?.message||`OpenAI ${r.status}`);return d}
Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);
  const t=tok(req);if(!t)return js({error:'Authentication required'},401);let u:any;try{u=await user(t)}catch{return js({error:'Authentication required'},401)}
  let b:any;try{b=await req.json()}catch{return js({error:'Invalid JSON'},400)}const q=String(b?.question||b?.message||'').trim();if(!q)return js({error:'question required'},400);if(!O)return js({error:'OPENAI_API_KEY not configured'},500);
  const card=b?.card||b?.context?.entity||{},evidence=b?.internal_evidence||{};
  const eventInstruction=`At the very end append exactly one machine-readable line beginning COLLECTISH_EVENTS_JSON= followed by a valid JSON array. Include at most 6 DATED external event candidates actually supported by the search, with fields date (YYYY-MM-DD), title, kind, url, confidence (low|medium|high). Do not include routine card/price page refreshes as events. If there are no dated catalyst candidates, append an empty array.`;
  const instructions=`You are Collectish external market research. You MUST use web search before answering. Search the public web only to explain or verify an MTG market move. Prefer primary/authoritative sources first, then established MTG market/deck sources, then community discussion. Separate internal Collectish observations from external evidence. Distinguish confirmed facts, timing correlation, and causation. Do not invent card-specific events. IMPORTANT: routine EDHREC card-page freshness, a price/listing page, or the mere existence of a card page is corroborating state evidence, NOT a catalyst. Treat an EDHREC editorial article, newly published deck result, announcement, creator feature, or dated community discussion as a possible catalyst only when timing and subject match. If no convincing catalyst is found, say so plainly. ALWAYS finish with a concise synthesized answer after searching. ${eventInstruction}`;
  const input=`Question: ${q}\nCard context: ${clip(card,1800)}\nInternal Collectish evidence: ${clip(evidence,7000)}\nSearch for external events, deck results, announcements, editorial/content, or discussion that plausibly overlap the timing in the internal evidence. Then give a final answer with: External findings; Timing/causation assessment; Bottom line. Explicitly label corroborating state evidence versus possible catalysts.`;
  try{let d=await openai({model:MODEL,store:false,instructions,input,tools:[{type:'web_search_preview',search_context_size:'medium'}],tool_choice:'auto',include:['web_search_call.action.sources','web_search_call.results'],max_output_tokens:2000});const calls=searchCalls(d);let src=sources(d,card),rawAnswer=outputText(d),synthesis_fallback=false;if(!src.length)throw Error('Web search completed without relevant source metadata');if(!rawAnswer){synthesis_fallback=true;const synthInput=`Question: ${q}\nCard context: ${clip(card,1800)}\nInternal Collectish evidence: ${clip(evidence,5000)}\nWeb search tool output: ${clip(calls,12000)}\nRetained relevant sources: ${clip(src,5000)}\nSynthesize a concise answer using only this material. Separate possible catalysts from corroborating state evidence. Routine page freshness is not a catalyst. State timing/causation confidence and a bottom line. ${eventInstruction}`;const s=await openai({model:MODEL,store:false,instructions:'You are a concise MTG market research synthesizer. Use only the supplied search output and internal evidence.',input:synthInput,tool_choice:'none',max_output_tokens:1600});rawAnswer=outputText(s);if(!rawAnswer)throw Error('Web search returned sources but synthesis fallback also returned no answer');d={...d,model:s?.model||d?.model,usage:s?.usage||d?.usage}}const parsed=extractEvents(rawAnswer,src),answer=parsed.answer,events=parsed.events;await fetch(`${U}/rest/v1/ask_collectish_research_runs`,{method:'POST',headers:{...uh(t),Prefer:'return=minimal'},body:JSON.stringify([{user_id:u.id,product_id:card?.product_id??null,sku_id:card?.sku_id??null,query_text:q,model:d?.model||MODEL,source_count:src.length}])}).catch(()=>{});return js({ok:true,answer,sources:src,events,model:d?.model||MODEL,usage:d?.usage||null,source_count:src.length,web_search_used:true,synthesis_fallback})}catch(e){return js({ok:false,error:String((e as Error).message),web_search_used:false},502)}
});
