import { rest } from '../../core/rest.js';

let parsedOrders=[];
let parseMeta=null;
let importing=false;
let browserSyncing=false;
let buyerSessionStatus='unknown';
let statusMessage='';
const BUYER_HISTORY='https://store.tcgplayer.com/myaccount/orderhistory';
const MAX_BUYER_PAGES=50;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>v==null?'—':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const host=()=>document.getElementById('cxSeller');
const normKey=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const asNum=v=>{if(v==null||v==='')return null;const n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null};
const asDate=v=>{if(v==null||v==='')return null;const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString():null};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const readBridge=()=>window.CollectishReadOnly||null;
const androidBridge=()=>window.CollectishAndroid||null;
function valueByAliases(obj,aliases){if(!obj||typeof obj!=='object'||Array.isArray(obj))return null;const wanted=new Set(aliases.map(normKey));for(const [k,v] of Object.entries(obj)){if(wanted.has(normKey(k))&&v!=null&&v!=='')return v}return null}
function arrayByAliases(obj,aliases){if(!obj||typeof obj!=='object'||Array.isArray(obj))return null;const wanted=new Set(aliases.map(normKey));for(const [k,v] of Object.entries(obj)){if(wanted.has(normKey(k))&&Array.isArray(v))return v}return null}
function endpointPath(raw){try{const u=new URL(raw);return `${u.pathname}${u.searchParams.has('PageNumber')?`?PageNumber=${u.searchParams.get('PageNumber')}`:''}`.slice(0,500)}catch{return null}}
function decodeContent(content){if(!content?.text)return null;try{return content.encoding==='base64'?atob(content.text):content.text}catch{return null}}
function normalizeItem(it,index){if(!it||typeof it!=='object'||Array.isArray(it))return null;const qty=Math.max(0,asNum(valueByAliases(it,['quantity','qty','count']))??1);const unit=asNum(valueByAliases(it,['unitPrice','price','itemPrice','salePrice','purchasePrice']));const line=asNum(valueByAliases(it,['lineTotal','extendedPrice','itemTotal','totalPrice','subtotal']))??(unit!=null?unit*qty:null);const pid=valueByAliases(it,['tcgplayerProductId','productId','productID','tcgProductId']);const sku=valueByAliases(it,['skuId','skuID','productConditionId']);const name=valueByAliases(it,['productName','name','title','cardName']);if(!pid&&!sku&&!name&&!unit&&!line)return null;return {line_key:String(valueByAliases(it,['lineId','lineItemId','itemId'])??index),product_id:pid==null?null:String(pid),sku_id:sku==null?null:String(sku),product_name:name==null?null:String(name),set_name:String(valueByAliases(it,['setName','expansionName','set'])??'')||null,condition:String(valueByAliases(it,['condition','conditionName'])??'')||null,printing:String(valueByAliases(it,['printing','printingName','finish','foil'])??'')||null,seller_name:String(valueByAliases(it,['sellerName','seller','storeName'])??'')||null,quantity:qty,unit_price:unit,line_total:line};}
function extractItems(obj){const direct=arrayByAliases(obj,['items','orderItems','lineItems','products','purchasedItems','orderLines']);if(direct)return direct.map(normalizeItem).filter(Boolean);const nested=arrayByAliases(obj,['packages','shipments','sellers','orders']);if(!nested)return[];const out=[];for(const x of nested){const arr=arrayByAliases(x,['items','orderItems','lineItems','products']);if(arr)for(const it of arr){const n=normalizeItem(it,out.length);if(n)out.push(n)}}return out}
function normalizeOrder(obj,path){if(!obj||typeof obj!=='object'||Array.isArray(obj))return null;const order=valueByAliases(obj,['orderNumber','orderNo','orderId','orderID','purchaseId','purchaseNumber']);const date=asDate(valueByAliases(obj,['orderDate','purchaseDate','createdAt','createdDate','datePlaced','date']));const total=asNum(valueByAliases(obj,['totalAmount','grandTotal','orderTotal','amountPaid','total','totalPrice']));if(order==null||!date||total==null)return null;return {order_number:String(order),order_date:date,subtotal:asNum(valueByAliases(obj,['subtotal','subTotal','itemSubtotal','productTotal'])),shipping_amount:asNum(valueByAliases(obj,['shippingAmount','shipping','shippingTotal'])),tax_amount:asNum(valueByAliases(obj,['taxAmount','tax','salesTax'])),total_amount:Math.max(0,total),status:String(valueByAliases(obj,['status','orderStatus','state'])??'')||null,payment_method:String(valueByAliases(obj,['paymentMethod','paymentType','tenderType'])??'')||null,source_path:path,items:extractItems(obj)};}
function walk(value,path,out,depth=0){if(depth>12||value==null)return;if(Array.isArray(value)){for(const v of value)walk(v,path,out,depth+1);return}if(typeof value!=='object')return;const o=normalizeOrder(value,path);if(o)out.push(o);for(const v of Object.values(value)){if(v&&typeof v==='object')walk(v,path,out,depth+1)}}
function text(el){return String(el?.textContent||'').replace(/\s+/g,' ').trim()}
function moneyFrom(s){const m=String(s||'').replace(/,/g,'').match(/-?\$?([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):null}
function summaryMap(wrap){const out={};wrap.querySelectorAll('[data-aid="tbl-sellerorderwidget-productsinorder"] tr').forEach(tr=>{const td=tr.querySelectorAll('td');if(td.length<2)return;const key=text(td[0]).replace(/:$/,'').toLowerCase();out[key]=text(td[1])});return out}
function htmlOrderNumber(wrap){for(const el of wrap.querySelectorAll('[id^="RateTransactionButton_"],[data-aid="btn-sellerorderwidget-contact"]')){const hay=`${el.id||''} ${el.getAttribute('onclick')||''}`;const m=hay.match(/([A-F0-9]{8}-[A-F0-9]{6}-[A-F0-9]{5})/i);if(m)return m[1].toUpperCase()}const m=text(wrap.querySelector('.orderHeader')).match(/([A-F0-9]{8}-[A-F0-9]{6}-[A-F0-9]{5})/i);return m?m[1].toUpperCase():null}
function htmlItem(tr,index,seller){const itemCell=tr.querySelector('.orderHistoryItems');if(!itemCell)return null;const a=itemCell.querySelector('a[title],a.nocontext');const name=(a?.getAttribute('title')||text(a)||'').trim()||null;const strings=Array.from(itemCell.querySelectorAll('span')).flatMap(s=>String(s.innerText||s.textContent||'').split(/\n+/).map(x=>x.trim()).filter(Boolean));const setName=strings.find(x=>x!==name)||null;const img=itemCell.querySelector('img');const src=img?.getAttribute('data-original')||img?.getAttribute('src')||'';const pm=src.match(/\/product\/(\d+)_/i);const detail=text(tr.querySelector('.orderHistoryDetail'));const cm=detail.match(/Condition:\s*(.+?)(?:\s+Rarity:|$)/i)||detail.match(/Condition:\s*(.+)$/i);const condition=cm?cm[1].trim():null;const unit=moneyFrom(text(tr.querySelector('.orderHistoryPrice')));const qty=asNum(text(tr.querySelector('.orderHistoryQuantity')))??1;return {line_key:`${pm?.[1]||index}:${index}`,product_id:pm?.[1]||null,sku_id:null,product_name:name,set_name:setName,condition,printing:condition&&/foil/i.test(condition)?'foil':'normal',seller_name:seller||null,quantity:qty,unit_price:unit,line_total:unit==null?null:unit*qty};}
function parseOrderHistoryHtml(html,path){let doc;try{doc=new DOMParser().parseFromString(html,'text/html')}catch{return[]}const out=[];doc.querySelectorAll('.orderWrap').forEach(wrap=>{const order=htmlOrderNumber(wrap),date=asDate(text(wrap.querySelector('[data-aid="spn-sellerorderwidget-orderdate"]'))),sum=summaryMap(wrap);if(!order||!date)return;const seller=text(wrap.querySelector('[data-aid="spn-sellerorderwidget-vendorname"]'))||null;const items=Array.from(wrap.querySelectorAll('table.orderTable tbody tr')).map((tr,i)=>htmlItem(tr,i,seller)).filter(Boolean);const taxKey=Object.keys(sum).find(k=>k.startsWith('sales tax')||k==='tax');const status=text(wrap.querySelector('[data-aid="spn-sellerorderwidget-trackingnumber"]'))||null;out.push({order_number:order,order_date:date,subtotal:moneyFrom(sum.subtotal),shipping_amount:moneyFrom(sum.shipping),tax_amount:moneyFrom(taxKey?sum[taxKey]:null),total_amount:Math.max(0,moneyFrom(sum.total)??items.reduce((a,x)=>a+Number(x.line_total||0),0)),status,payment_method:null,source_path:path,items})});return out}
function maxPageFromHtml(html){let doc;try{doc=new DOMParser().parseFromString(html,'text/html')}catch{return 1}let maxPage=1;for(const a of doc.querySelectorAll('a[href*="PageNumber"],a[href*="pagenumber"]')){try{const u=new URL(a.getAttribute('href')||'',BUYER_HISTORY),n=Number(u.searchParams.get('PageNumber')||u.searchParams.get('pagenumber'));if(Number.isFinite(n))maxPage=Math.max(maxPage,n)}catch{}}return Math.max(1,Math.min(MAX_BUYER_PAGES,maxPage))}
function mergeOrders(found){const map=new Map();for(const o of found){const prev=map.get(o.order_number);if(!prev){map.set(o.order_number,o);continue}const score=x=>(x.items?.length||0)+(x.subtotal!=null?1:0)+(x.shipping_amount!=null?1:0)+(x.tax_amount!=null?1:0)+(x.status?1:0);map.set(o.order_number,score(o)>score(prev)?{...prev,...o}:{...o,...prev})}return [...map.values()].sort((a,b)=>String(b.order_date).localeCompare(String(a.order_date)))}
function cookieNames(entry){const names=new Set((entry?.request?.cookies||[]).map(c=>c?.name).filter(Boolean));for(const h of entry?.request?.headers||[]){if(String(h?.name||'').toLowerCase()!=='cookie')continue;String(h.value||'').split(';').forEach(p=>{const n=p.split('=')[0]?.trim();if(n)names.add(n)})}return names}
function parseHar(har){const entries=har?.log?.entries;if(!Array.isArray(entries))throw new Error('This file does not look like a HAR capture.');const found=[];let tcgJsonEntries=0,orderHtmlEntries=0;const paths=new Set(),authNames=new Set();for(const e of entries){const raw=e?.request?.url||'';let url;try{url=new URL(raw)}catch{continue}if(!/(^|\.)tcgplayer\.com$/i.test(url.hostname))continue;const textBody=decodeContent(e?.response?.content);if(!textBody)continue;const path=endpointPath(raw),mime=String(e?.response?.content?.mimeType||'').toLowerCase();if(url.hostname==='store.tcgplayer.com'&&/orderhistory/i.test(url.pathname)&&mime.includes('html')){const parsed=parseOrderHistoryHtml(textBody,path);if(parsed.length){orderHtmlEntries++;found.push(...parsed);paths.add(path);for(const n of cookieNames(e))if(['TCGAuthTicket_Production','BuyerRevalidationKey','ASP.NET_SessionId','OAuthLoginSessionId','__RequestVerificationToken'].includes(n))authNames.add(n)}continue}if(!mime.includes('json')&&!/^[\s]*[\[{]/.test(textBody))continue;let json;try{json=JSON.parse(textBody)}catch{continue}tcgJsonEntries++;paths.add(path);walk(json,path,found)}const orders=mergeOrders(found);return {orders,meta:{har_entries:entries.length,tcg_json_entries:tcgJsonEntries,order_html_entries:orderHtmlEntries,recognized_orders:orders.length,recognized_items:orders.reduce((a,o)=>a+(o.items?.length||0),0),auth_session_detected:authNames.has('TCGAuthTicket_Production'),auth_cookie_names:[...authNames],paths:[...paths].slice(0,25)}}}
async function probeBuyerPage(page){const bridge=readBridge();if(!bridge?.startReadOnlyProbe)throw new Error('Buyer WebView sync requires the Android Collectish agent.');const url=page<=1?BUYER_HISTORY:`${BUYER_HISTORY}?PageNumber=${page}`;bridge.startReadOnlyProbe(JSON.stringify({mode:'fetch_html',method:'GET',url,waitMs:1500}));const deadline=Date.now()+25000;while(Date.now()<deadline){await sleep(250);const state=String(bridge.getReadOnlyProbeState?.()||'');if(state==='running'||state==='idle')continue;let result={};try{result=JSON.parse(String(bridge.getReadOnlyProbeResult?.()||'{}'))}catch{}if(state==='error'||result?.error){const e=new Error(result?.error||'Buyer session request failed.');e.code=/login|auth/i.test(e.message)?'BUYER_LOGIN_REQUIRED':'BUYER_SYNC_FAILED';throw e}if(state==='ready'){if(!result?.ok||typeof result?.body!=='string')throw new Error('Buyer history returned an unexpected response.');return {html:result.body,url:result.url||url}}}throw new Error('Buyer history request timed out.');}
async function persistOrders(orders){if(!orders.length)throw new Error('No buyer orders were found to import.');const data=await rest('rpc/import_tcg_buyer_orders',{method:'POST',body:{p_orders:orders}}),r=Array.isArray(data)?data[0]:data;document.dispatchEvent(new CustomEvent('collectish:buyer-orders-changed',{detail:{orders:Number(r?.imported_orders||orders.length),items:Number(r?.imported_items||0)}}));return r||{};}
async function syncBuyerSession(){if(browserSyncing||importing)return;browserSyncing=true;buyerSessionStatus='checking';statusMessage='Checking authenticated buyer session…';render();try{const first=await probeBuyerPage(1),found=[...parseOrderHistoryHtml(first.html,'/myaccount/orderhistory')],pages=maxPageFromHtml(first.html);buyerSessionStatus='authenticated';for(let page=2;page<=pages;page++){statusMessage=`Syncing buyer history page ${page} of ${pages}…`;render();const r=await probeBuyerPage(page),orders=parseOrderHistoryHtml(r.html,`/myaccount/orderhistory?PageNumber=${page}`);if(!orders.length)break;found.push(...orders)}parsedOrders=mergeOrders(found);parseMeta={recognized_orders:parsedOrders.length,recognized_items:parsedOrders.reduce((a,o)=>a+(o.items?.length||0),0),order_html_entries:pages,auth_session_detected:true,source:'authenticated_webview'};if(!parsedOrders.length)throw new Error('Authenticated buyer history loaded, but no orders were found.');statusMessage=`Importing ${parsedOrders.length} buyer orders…`;render();const imported=await persistOrders(parsedOrders);statusMessage=`Synced ${Number(imported?.imported_orders||parsedOrders.length)} buyer orders and ${Number(imported?.imported_items||0)} items.`;buyerSessionStatus='authenticated'}catch(err){if(err?.code==='BUYER_LOGIN_REQUIRED'){buyerSessionStatus='signed_out';statusMessage='Buyer sign-in required. Open the TCGplayer buyer session, sign in, then sync again.'}else{buyerSessionStatus='error';statusMessage=String(err?.message||'Buyer sync failed.')}}finally{browserSyncing=false;render()}}
function openBuyerSession(){const read=readBridge(),android=androidBridge();if(read?.startReadOnlyProbe){try{read.startReadOnlyProbe(JSON.stringify({mode:'navigate_capture',method:'GET',url:BUYER_HISTORY,waitMs:1200}))}catch{}}if(android?.showSellerPortal){setTimeout(()=>android.showSellerPortal(),80);buyerSessionStatus='interactive';statusMessage='TCGplayer buyer session opened. Sign in if needed, then return to Collectish and sync.'}else{window.open(BUYER_HISTORY,'_blank','noopener');statusMessage='Opened TCGplayer buyer history in a new tab.'}render()}
function ensurePanel(){const h=host();if(!h)return null;let p=document.getElementById('cxBuyerAccountImport');if(!p){p=document.createElement('section');p.id='cxBuyerAccountImport';p.className='cx-card';const cash=document.getElementById('cxSellerCashflowBudget');if(cash)cash.insertAdjacentElement('afterend',p);else h.prepend(p)}return p}
function summaryHtml(){if(!parseMeta)return `<div class="cx-empty">${readBridge()?'Android buyer sync is available. Sync directly from the authenticated TCGplayer WebView, or use a HAR as a fallback.':'Choose a HAR captured while viewing your TCGplayer buyer order history. On Android, the authenticated WebView can sync this automatically.'}</div>`;const dateMin=parsedOrders.length?parsedOrders[parsedOrders.length-1].order_date.slice(0,10):'—',dateMax=parsedOrders.length?parsedOrders[0].order_date.slice(0,10):'—',total=parsedOrders.reduce((a,o)=>a+Number(o.total_amount||0),0),auth=parseMeta.auth_session_detected?'Authenticated buyer session detected':'Buyer auth session not detected';return `<div class="cx-v5-grid"><div class="cx-v5-stat"><span>Recognized orders</span><strong>${parseMeta.recognized_orders}</strong></div><div class="cx-v5-stat"><span>Recognized items</span><strong>${parseMeta.recognized_items}</strong></div><div class="cx-v5-stat"><span>Order range</span><strong>${esc(dateMin)} → ${esc(dateMax)}</strong></div><div class="cx-v5-stat"><span>Captured spend</span><strong>${money(total)}</strong><small>${esc(auth)}</small></div></div>${!parsedOrders.length?'<div class="cx-empty">No buyer orders were recognized.</div>':''}`}
function render(){const p=ensurePanel();if(!p)return;const android=!!readBridge(),syncLabel=browserSyncing?'Syncing buyer history…':buyerSessionStatus==='signed_out'?'Retry buyer sync':'Sync buyer history';p.innerHTML=`<div class="cx-page-head"><div><div class="cx-section-title">TCGplayer buyer account</div><p class="cx-sub">Track buyer purchases automatically from TCGplayer’s authenticated legacy order-history pages. Only normalized order/item records are persisted.</p></div></div><div class="cx-scout-toolbar">${android?`<button type="button" class="cx-primary" id="cxBuyerWebSync" ${browserSyncing?'disabled':''}>${esc(syncLabel)}</button><button type="button" class="cx-refresh" id="cxBuyerOpenSession">${buyerSessionStatus==='signed_out'?'Open buyer sign-in':'Open buyer session'}</button>`:''}<label class="cx-refresh" for="cxBuyerHarFile">HAR fallback</label><input id="cxBuyerHarFile" type="file" accept=".har,.json,application/json" style="display:none"><button type="button" class="cx-refresh" id="cxBuyerImport" ${parsedOrders.length&&!importing&&!browserSyncing?'':'disabled'}>${importing?'Importing…':`Import ${parsedOrders.length||''} parsed order${parsedOrders.length===1?'':'s'}`}</button></div>${statusMessage?`<div class="cx-empty">${esc(statusMessage)}</div>`:''}${summaryHtml()}<small class="cx-sub">Security: browser cookies, request headers, authorization/session tokens, shipping/billing addresses, and raw page HTML are never sent to MarketplaceScout. The Android WebView retains the TCGplayer session locally; only normalized purchase data is imported.</small>`;document.getElementById('cxBuyerWebSync')?.addEventListener('click',syncBuyerSession);document.getElementById('cxBuyerOpenSession')?.addEventListener('click',openBuyerSession);document.getElementById('cxBuyerHarFile')?.addEventListener('change',onFile);document.getElementById('cxBuyerImport')?.addEventListener('click',importOrders)}
async function onFile(e){const file=e.target.files?.[0];if(!file)return;parsedOrders=[];parseMeta=null;statusMessage='';render();try{if(file.size>100*1024*1024)throw new Error('HAR is larger than 100 MB. Capture just the buyer order-history session if possible.');const raw=await file.text(),har=JSON.parse(raw),result=parseHar(har);parsedOrders=result.orders;parseMeta=result.meta;buyerSessionStatus=parseMeta.auth_session_detected?'authenticated':'unknown';statusMessage=`HAR parsed: ${parsedOrders.length} unique buyer orders.`;render()}catch(err){parseMeta={recognized_orders:0,recognized_items:0};statusMessage=String(err?.message||'Could not parse HAR.');render()}}
async function importOrders(){if(importing||browserSyncing||!parsedOrders.length)return;importing=true;statusMessage=`Importing ${parsedOrders.length} parsed buyer orders…`;render();try{const r=await persistOrders(parsedOrders);statusMessage=`Imported ${Number(r?.imported_orders??parsedOrders.length)} orders and ${Number(r?.imported_items??0)} items. Monthly buying budget refreshed.`}catch(err){statusMessage=`Import failed: ${String(err?.message||'Request failed')}`}finally{importing=false;render()}}
function ensure(){if(!host())return;render()}
document.addEventListener('collectish:seller-rendered',()=>setTimeout(ensure,0));
document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='seller')setTimeout(ensure,100)});
document.addEventListener('collectish:ready',()=>setTimeout(ensure,180));
setTimeout(ensure,250);
export {parseHar,parseOrderHistoryHtml,syncBuyerSession};
