import { rest } from '../../core/rest.js';

const BUYER_ROOT='https://www.tcgplayer.com/myaccount';
const BUYER_HISTORY='https://store.tcgplayer.com/myaccount/orderhistory';
const BUYER_LOGIN='https://www.tcgplayer.com/login?returnUrl=/myaccount/orderhistory';
const AUTO_SYNC_MS=6*60*60*1000;
const MAX_ORDER_PAGES=50;
const MAX_MESSAGE_THREADS=100;
let syncing=false,state=null,status='';
const host=()=>document.getElementById('cxSeller');
const bridge=()=>window.CollectishReadOnly||null;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const num=s=>{const m=String(s||'').replace(/,/g,'').match(/-?\$?([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):null};
const iso=s=>{const d=new Date(s);return Number.isFinite(d.getTime())?d.toISOString():null};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const key=s=>{let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(36)};
function doc(html){return new DOMParser().parseFromString(html,'text/html')}
function text(el){return clean(el?.textContent||'')}
function summaryMap(wrap){const out={};wrap.querySelectorAll('[data-aid="tbl-sellerorderwidget-productsinorder"] tr').forEach(tr=>{const td=tr.querySelectorAll('td');if(td.length>1)out[text(td[0]).replace(/:$/,'').toLowerCase()]=text(td[1])});return out}
function orderNumber(wrap){for(const el of wrap.querySelectorAll('[id^="RateTransactionButton_"],[data-aid="btn-sellerorderwidget-contact"]')){const m=`${el.id||''} ${el.getAttribute('onclick')||''}`.match(/([A-F0-9]{8}-[A-F0-9]{6}-[A-F0-9]{5})/i);if(m)return m[1].toUpperCase()}return text(wrap).match(/([A-F0-9]{8}-[A-F0-9]{6}-[A-F0-9]{5})/i)?.[1]?.toUpperCase()||null}
function item(tr,i,seller){const cell=tr.querySelector('.orderHistoryItems');if(!cell)return null;const a=cell.querySelector('a[title],a.nocontext'),name=(a?.getAttribute('title')||text(a)||'').trim()||null,spans=[...cell.querySelectorAll('span')].map(text).filter(Boolean),img=cell.querySelector('img'),src=img?.getAttribute('data-original')||img?.getAttribute('src')||'',pid=src.match(/\/product\/(\d+)_/i)?.[1]||null,detail=text(tr.querySelector('.orderHistoryDetail')),condition=detail.match(/Condition:\s*(.+?)(?:\s+Rarity:|$)/i)?.[1]?.trim()||null,unit=num(text(tr.querySelector('.orderHistoryPrice'))),qty=Number(text(tr.querySelector('.orderHistoryQuantity'))||1)||1;return {line_key:`${pid||i}:${i}`,product_id:pid,sku_id:null,product_name:name,set_name:spans.find(x=>x!==name)||null,condition,printing:condition&&/foil/i.test(condition)?'foil':'normal',seller_name:seller||null,quantity:qty,unit_price:unit,line_total:unit==null?null:unit*qty}}
export function parseOrderHistoryHtml(html,path='/myaccount/orderhistory'){const d=doc(html),out=[];d.querySelectorAll('.orderWrap').forEach(w=>{const order=orderNumber(w),date=iso(text(w.querySelector('[data-aid="spn-sellerorderwidget-orderdate"]'))),sum=summaryMap(w);if(!order||!date)return;const seller=text(w.querySelector('[data-aid="spn-sellerorderwidget-vendorname"]'))||null,items=[...w.querySelectorAll('table.orderTable tbody tr')].map((tr,i)=>item(tr,i,seller)).filter(Boolean),taxKey=Object.keys(sum).find(k=>k.startsWith('sales tax')||k==='tax'),refundKey=Object.keys(sum).find(k=>/refund/.test(k)),creditKey=Object.keys(sum).find(k=>/store credit|bonus bucks/.test(k)),total=Math.max(0,num(sum.total)??items.reduce((a,x)=>a+Number(x.line_total||0),0)),refund=Math.max(0,num(refundKey?sum[refundKey]:null)||0),credit=Math.max(0,num(creditKey?sum[creditKey]:null)||0);out.push({order_number:order,order_date:date,subtotal:num(sum.subtotal),shipping_amount:num(sum.shipping),tax_amount:num(taxKey?sum[taxKey]:null),total_amount:total,refund_amount:refund,store_credit_amount:credit,cash_paid_amount:Math.max(0,total-credit-refund),status:text(w.querySelector('[data-aid="spn-sellerorderwidget-trackingnumber"]'))||null,payment_method:null,source_path:path,items})});return out}
function maxPage(html){let m=1;for(const a of doc(html).querySelectorAll('a[href*="PageNumber" i]')){try{m=Math.max(m,Number(new URL(a.getAttribute('href'),BUYER_HISTORY).searchParams.get('PageNumber'))||1)}catch{}}return Math.min(MAX_ORDER_PAGES,m)}
function accountLinks(html){const out=new Map();for(const a of doc(html).querySelectorAll('a[href]')){const label=text(a).toLowerCase();let u;try{u=new URL(a.getAttribute('href'),BUYER_ROOT)}catch{continue}if(!['store.tcgplayer.com','www.tcgplayer.com'].includes(u.hostname)||!u.pathname.toLowerCase().startsWith('/myaccount'))continue;if(/store credit|credit balance/.test(label)||/credit/.test(u.pathname))out.set('credit',u.href);if(/message|inbox/.test(label)||/message|inbox/.test(u.pathname))out.set('messages',u.href)}return out}
function parseCredit(html,path){const d=doc(html),body=text(d.body),balance=num(body.match(/(?:store credit(?: balance)?|available credit)[^$]{0,40}(\$[\d,.]+)/i)?.[1]),entries=[];for(const tr of d.querySelectorAll('table tr')){const c=[...tr.querySelectorAll('th,td')].map(text).filter(Boolean);if(c.length<2)continue;const occurred=iso(c.find(x=>/\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|[A-Za-z]{3,9}\s+\d{1,2},\s+\d{4}/.test(x))||''),amount=c.map(num).find(x=>x!=null),desc=c.filter(x=>num(x)==null&&!iso(x)).join(' · ').slice(0,1000);if(!occurred&&amount==null)continue;entries.push({entry_key:key(c.join('|')),occurred_at:occurred,description:desc||null,amount,balance:null,source_path:new URL(path).pathname})}return {balance,entries}}
function messageLinks(html,base){const out=[];for(const a of doc(html).querySelectorAll('a[href]')){let u;try{u=new URL(a.getAttribute('href'),base)}catch{continue}if(['store.tcgplayer.com','www.tcgplayer.com'].includes(u.hostname)&&u.pathname.toLowerCase().startsWith('/myaccount')&&/message|contact|conversation|thread/.test(`${u.pathname}${u.search}`.toLowerCase()))out.push(u.href)}return [...new Set(out)].slice(0,MAX_MESSAGE_THREADS)}
function parseMessages(html,path){const d=doc(html),nodes=[...d.querySelectorAll('[data-aid*="message" i],.message,.messageRow,.message-row,.conversation-message,.thread-message,article')],fallback=nodes.length?nodes:[...d.querySelectorAll('table tbody tr')],out=[];fallback.forEach((n,i)=>{const body=text(n);if(body.length<2)return;const order=body.match(/([A-F0-9]{8}-[A-F0-9]{6}-[A-F0-9]{5})/i)?.[1]?.toUpperCase()||null,when=iso(body.match(/(?:\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|[A-Za-z]{3,9}\s+\d{1,2},\s+\d{4})(?:\s+\d{1,2}:\d{2}\s*(?:AM|PM)?)?/i)?.[0]||''),subject=text(n.querySelector('h1,h2,h3,h4,.subject,[data-aid*="subject" i]'))||null;out.push({message_key:key(`${path}|${i}|${body}`),thread_key:key(path),order_number:order,occurred_at:when,direction:/\bfrom you\b|\byou wrote\b/i.test(body)?'outbound':null,counterpart:null,subject,body:body.slice(0,20000),source_path:new URL(path).pathname})});return out}
async function fetchHtml(url){const b=bridge();if(!b?.startReadOnlyProbe)throw new Error('Buyer sync requires the Android Collectish agent.');if(b.isBuyerProfileIsolated&&!b.isBuyerProfileIsolated())throw new Error('This device WebView cannot isolate buyer credentials from Seller credentials.');b.startReadOnlyProbe(JSON.stringify({mode:'fetch_html',method:'GET',url,waitMs:1500}));const deadline=Date.now()+25000;while(Date.now()<deadline){await sleep(250);const s=String(b.getReadOnlyProbeState?.()||'');if(s==='running'||s==='idle')continue;let r={};try{r=JSON.parse(String(b.getReadOnlyProbeResult?.()||'{}'))}catch{}if(s==='error'||r.error){const e=new Error(r.error||'TCGplayer buyer request failed');e.code=/login|auth/i.test(e.message)?'LOGIN':'SYNC';throw e}if(s==='ready'&&r.ok&&typeof r.body==='string')return r.body}throw new Error('TCGplayer buyer request timed out')}
async function loadState(){try{const rows=await rest('tcg_buyer_account_state?select=last_sync_at,last_success_at,session_state,last_error,store_credit_balance,orders_synced,messages_synced,credit_entries_synced&limit=1');state=Array.isArray(rows)?rows[0]||null:null}catch{state=null}}
async function persist(orders,credit,messages,balance){const data=await rest('rpc/import_tcg_buyer_account',{method:'POST',body:{p_orders:orders,p_store_credit:credit,p_messages:messages,p_state:{success:true,session_state:'authenticated',store_credit_balance:balance}}});document.dispatchEvent(new CustomEvent('collectish:buyer-orders-changed',{detail:{orders:orders.length,messages:messages.length,credit:credit.length}}));return Array.isArray(data)?data[0]:data}
export async function syncBuyerAccount({automatic=false}={}){if(syncing)return;if(!bridge())return;syncing=true;status=automatic?'Refreshing buyer account…':'Syncing buyer account…';render();try{const first=await fetchHtml(BUYER_HISTORY),orders=[...parseOrderHistoryHtml(first)],pages=maxPage(first);for(let p=2;p<=pages;p++){status=`Orders ${p}/${pages}…`;render();orders.push(...parseOrderHistoryHtml(await fetchHtml(`${BUYER_HISTORY}?PageNumber=${p}`),`/myaccount/orderhistory?PageNumber=${p}`))}let links=accountLinks(first);if(!links.size){try{links=accountLinks(await fetchHtml(BUYER_ROOT))}catch{}}let credit={balance:null,entries:[]},messages=[];if(links.get('credit')){status='Syncing store credit…';render();credit=parseCredit(await fetchHtml(links.get('credit')),links.get('credit'))}if(links.get('messages')){status='Syncing buyer messages…';render();const inbox=await fetchHtml(links.get('messages'));messages.push(...parseMessages(inbox,links.get('messages')));for(const u of messageLinks(inbox,links.get('messages'))){try{messages.push(...parseMessages(await fetchHtml(u),u))}catch{}}}const uniqueOrders=[...new Map(orders.map(o=>[o.order_number,o])).values()],uniqueMessages=[...new Map(messages.map(m=>[m.message_key,m])).values()];await persist(uniqueOrders,credit.entries,uniqueMessages,credit.balance);localStorage.setItem('collectishBuyerLastAutoSync',String(Date.now()));status=`Synced ${uniqueOrders.length} orders · ${uniqueMessages.length} messages · ${credit.entries.length} credit entries.`;await loadState()}catch(e){status=e.code==='LOGIN'?'TCGplayer buyer sign-in required. Open the separate buyer session, sign in, then sync again.':String(e.message||'Buyer sync failed')}finally{syncing=false;render()}}
function openSession(){const b=bridge();if(b?.showBuyerSession){b.showBuyerSession();status='Opened the isolated TCGplayer buyer login. Sign in with the buyer-account credentials, then return and sync.';render();return}window.open(BUYER_LOGIN,'_blank','noopener')}
function ensurePanel(){const h=host();if(!h)return null;let p=document.getElementById('cxBuyerAccountImport');if(!p){p=document.createElement('section');p.id='cxBuyerAccountImport';p.className='cx-card';p.dataset.sellerPersistent='1';const cash=document.getElementById('cxSellerCashflowBudget');if(cash)cash.insertAdjacentElement('afterend',p);else h.prepend(p)}return p}
function render(){const p=ensurePanel();if(!p)return;const b=bridge(),native=!!b,isolated=native&&(!b.isBuyerProfileIsolated||b.isBuyerProfileIsolated()),nativeSession=native&&b.getBuyerSessionState?String(b.getBuyerSessionState()||'unknown'):null,last=state?.last_success_at?new Date(state.last_success_at).toLocaleString():'Never',session=nativeSession||state?.session_state||'Unknown';p.innerHTML=`<div class="cx-page-head"><div><div class="cx-section-title">TCGplayer buyer account</div><p class="cx-sub">Separate authenticated buyer-account connector for purchases, refunds/returns, messages and store credit. Buyer and Seller credentials use isolated browser profiles and are never shared.</p></div></div><div class="cx-scout-toolbar"><button type="button" class="cx-primary" id="cxBuyerSync" ${!native||!isolated||syncing?'disabled':''}>${syncing?'Syncing…':'Sync buyer account'}</button><button type="button" class="cx-refresh" id="cxBuyerSession">Open buyer login</button></div>${!isolated?'<div class="cx-empty">Buyer credential isolation is unavailable in this Android WebView. Buyer sync is disabled rather than sharing Seller credentials.</div>':''}${status?`<div class="cx-empty">${esc(status)}</div>`:''}<div class="cx-v5-grid"><div class="cx-v5-stat"><span>Last successful sync</span><strong>${esc(last)}</strong><small>Auto refresh every ~6h while Collectish is active</small></div><div class="cx-v5-stat"><span>Buyer session</span><strong>${esc(session)}</strong><small>Separate from Seller Portal</small></div><div class="cx-v5-stat"><span>Orders</span><strong>${Number(state?.orders_synced||0).toLocaleString()}</strong></div><div class="cx-v5-stat"><span>Messages</span><strong>${Number(state?.messages_synced||0).toLocaleString()}</strong></div><div class="cx-v5-stat"><span>Store credit</span><strong>${money(state?.store_credit_balance)}</strong><small>${Number(state?.credit_entries_synced||0).toLocaleString()} synced entries</small></div></div><small class="cx-sub">Buyer login: ${esc(BUYER_LOGIN)}. TCGplayer passwords are not stored in MarketplaceScout. Buyer cookies/storage remain in the isolated Android WebView profile; Seller Portal keeps its own separate session. Raw HTML, cookies, authorization headers and addresses are not persisted.</small>`;document.getElementById('cxBuyerSync')?.addEventListener('click',()=>syncBuyerAccount());document.getElementById('cxBuyerSession')?.addEventListener('click',openSession)}
async function ensure(){if(!host())return;await loadState();render();const last=Number(localStorage.getItem('collectishBuyerLastAutoSync')||0);if(bridge()&&(!bridge().isBuyerProfileIsolated||bridge().isBuyerProfileIsolated())&&Date.now()-last>AUTO_SYNC_MS)setTimeout(()=>syncBuyerAccount({automatic:true}),600)}
document.addEventListener('collectish:seller-rendered',()=>setTimeout(ensure,0));
document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='seller')setTimeout(ensure,80)});
document.addEventListener('collectish:ready',()=>setTimeout(ensure,800));
setTimeout(ensure,250);
