import { rest } from '../../core/rest.js';
import { syncBuyerAccount } from './buyer-account.js';

const host=()=>document.getElementById('cxSeller');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const fmtDate=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleDateString():String(v||'')};
const RANGE_KEY='collectishBuyerHistoryRange';
let range=localStorage.getItem(RANGE_KEY)||'90';
let query='';
let orders=[];
let itemsByOrder=new Map();
let expanded=null;
let loading=false;

function cutoff(){if(range==='all')return null;const d=new Date();d.setDate(d.getDate()-Number(range||90));return d}
function filtered(){const c=cutoff(),q=query.trim().toLowerCase();return orders.filter(o=>{if(c&&new Date(o.order_date)<c)return false;if(!q)return true;return `${o.order_number||''} ${o.status||''}`.toLowerCase().includes(q)});}
async function loadOrders(){loading=true;render();try{const rows=await rest('tcg_buyer_orders?select=order_number,order_date,subtotal,shipping_amount,tax_amount,total_amount,status,payment_method,source_path&order=order_date.desc&limit=1000');orders=Array.isArray(rows)?rows:[]}catch{orders=[]}finally{loading=false;render()}}
async function loadItems(order){if(itemsByOrder.has(order))return;try{const rows=await rest(`tcg_buyer_order_items?select=order_number,line_key,product_id,sku_id,product_name,set_name,condition,printing,seller_name,quantity,unit_price,line_total&order_number=eq.${encodeURIComponent(order)}&order=line_key.asc`);itemsByOrder.set(order,Array.isArray(rows)?rows:[])}catch{itemsByOrder.set(order,[])}render()}
function summary(rows){return {orders:rows.length,spent:rows.reduce((a,o)=>a+Number(o.total_amount||0),0),avg:rows.length?rows.reduce((a,o)=>a+Number(o.total_amount||0),0)/rows.length:0}}
function ensurePanel(){const h=host();if(!h)return null;let p=document.getElementById('cxBuyerHistory');if(!p){p=document.createElement('section');p.id='cxBuyerHistory';p.className='cx-card';p.dataset.sellerPersistent='1';const buyer=document.getElementById('cxBuyerAccountImport');if(buyer)buyer.insertAdjacentElement('afterend',p);else h.prepend(p)}return p}
function rowHtml(o){const open=expanded===o.order_number,items=itemsByOrder.get(o.order_number)||[];return `<div class="cx-v5-row" style="display:block;padding:12px 0;border-bottom:1px solid var(--cx-border,#25385f)"><button type="button" class="cx-refresh cxBuyerOrder" data-order="${esc(o.order_number)}" style="width:100%;text-align:left;display:grid;grid-template-columns:1fr auto;gap:8px"><span><strong>${fmtDate(o.order_date)}</strong><br><small>${esc(o.order_number)}${o.status?` · ${esc(o.status)}`:''}</small></span><strong>${money(o.total_amount)}</strong></button>${open?`<div style="padding:10px 4px 0">${items.length?items.map(i=>`<div style="display:grid;grid-template-columns:1fr auto;gap:8px;padding:8px 0"><span>${esc(i.product_name||'Item')}<br><small>${esc([i.set_name,i.condition,i.printing,i.seller_name].filter(Boolean).join(' · '))}</small></span><span>${Number(i.quantity||1)} × ${money(i.unit_price)}<br><small>${money(i.line_total)}</small></span></div>`).join(''):'<small>No line items stored for this order.</small>'}</div>`:''}</div>`}
function render(){const p=ensurePanel();if(!p)return;const rows=filtered(),s=summary(rows);p.innerHTML=`<div class="cx-page-head"><div><div class="cx-section-title">Buyer history</div><p class="cx-sub">Browse normalized TCGplayer purchases already synced into Collectish.</p></div></div><div class="cx-scout-toolbar" style="gap:8px;flex-wrap:wrap"><select id="cxBuyerRange" class="cx-refresh"><option value="30" ${range==='30'?'selected':''}>30 days</option><option value="90" ${range==='90'?'selected':''}>90 days</option><option value="365" ${range==='365'?'selected':''}>1 year</option><option value="all" ${range==='all'?'selected':''}>All synced</option></select><input id="cxBuyerSearch" class="cx-refresh" value="${esc(query)}" placeholder="Search order # / status" style="min-width:190px"><button type="button" class="cx-refresh" id="cxBuyerRefreshHistory">Refresh</button><button type="button" class="cx-primary" id="cxBuyerSyncHistory">Sync now</button></div><div class="cx-v5-grid"><div class="cx-v5-stat"><span>Orders in view</span><strong>${s.orders.toLocaleString()}</strong></div><div class="cx-v5-stat"><span>Spend in view</span><strong>${money(s.spent)}</strong></div><div class="cx-v5-stat"><span>Avg order</span><strong>${money(s.avg)}</strong></div></div>${loading?'<div class="cx-empty">Loading buyer history…</div>':rows.length?`<div>${rows.map(rowHtml).join('')}</div>`:'<div class="cx-empty">No synced buyer orders match this range.</div>'}<small class="cx-sub">Range filters what you view here. Historical sync depth still depends on what TCGplayer exposes through its order-history pages; the next backfill pass will make that explicit and controllable.</small>`;document.getElementById('cxBuyerRange')?.addEventListener('change',e=>{range=e.target.value;localStorage.setItem(RANGE_KEY,range);render()});document.getElementById('cxBuyerSearch')?.addEventListener('input',e=>{query=e.target.value;render()});document.getElementById('cxBuyerRefreshHistory')?.addEventListener('click',loadOrders);document.getElementById('cxBuyerSyncHistory')?.addEventListener('click',async()=>{await syncBuyerAccount();await loadOrders()});p.querySelectorAll('.cxBuyerOrder').forEach(btn=>btn.addEventListener('click',async()=>{const order=btn.dataset.order;expanded=expanded===order?null:order;if(expanded&&!itemsByOrder.has(order))await loadItems(order);else render()}));}
async function ensure(){if(!host())return;await loadOrders()}
document.addEventListener('collectish:buyer-orders-changed',()=>setTimeout(loadOrders,0));
document.addEventListener('collectish:seller-rendered',()=>setTimeout(ensure,120));
document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='seller')setTimeout(ensure,160)});
document.addEventListener('collectish:ready',()=>setTimeout(ensure,900));
setTimeout(ensure,400);
