import { rest } from '../../core/rest.js';

let row=null,loading=null,lastLoadedAt=0,error='';
const CACHE_MS=60*1000;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>v==null?'—':Number(v).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const pct=v=>v==null?'—':`${Number(v).toFixed(0)}%`;
const monthKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`};
const host=()=>document.getElementById('cxSeller');
function stat(label,value,sub=''){return `<div class="cx-v5-stat"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function ensurePanel(){const h=host();if(!h)return null;let p=document.getElementById('cxSellerCashflowBudget');if(!p){p=document.createElement('section');p.id='cxSellerCashflowBudget';p.className='cx-card';p.dataset.sellerPersistent='1';h.prepend(p)}return p}
const confirmed=()=>row?.input_status==='auto_plus_manual'||row?.input_status==='manual_only';
function render(){const p=ensurePanel();if(!p)return;if(loading){p.innerHTML='<div class="cx-section-title">Monthly buying budget</div><div class="cx-empty">Loading marketplace cash flow…</div>';return}if(error){p.innerHTML=`<div class="cx-section-title">Monthly buying budget</div><div class="cx-empty">Unavailable: ${esc(error)}</div>`;return}if(!row){p.innerHTML='<div class="cx-section-title">Monthly buying budget</div><div class="cx-empty">No cash-flow data yet.</div>';return}
 const safe=Number(row.safe_additional_buy_budget||0),netBuyer=Number(row.tcg_buyer_purchase_spend||0),gross=Number(row.tcg_buyer_gross_spend??netBuyer),refunds=Number(row.tcg_buyer_refunds||0),credit=Number(row.tcg_store_credit_used||0),manual=Number(row.manual_purchase_adjustment||0),orders=Number(row.buyer_orders_count||0),ready=confirmed(),last=row.buyer_last_sync_at?new Date(row.buyer_last_sync_at).toLocaleString():'never';
 const status=row.input_status==='auto_buyer_only'?'Buyer-account spend is automatic; confirm any off-platform/operating spend below.':row.input_status==='needs_spend_input'?'No buyer orders or monthly spend inputs yet.':'Monthly spend inputs confirmed.';
 p.innerHTML=`<div class="cx-page-head"><div><div class="cx-section-title">Monthly buying budget</div><p class="cx-sub">Combines seller payouts with the synced TCGplayer buyer ledger, refunds/returns, store credit, off-platform buys and operating spend.</p></div><button type="button" class="cx-refresh" id="cxCashflowRefresh">Refresh</button></div><div class="cx-v5-grid">${stat('Cash received',money(row.posted_marketplace_cash),`${money(row.pending_marketplace_cash)} pending`)}${stat('Net TCG buyer spend',money(netBuyer),`${orders} orders · ${money(gross)} gross`)}${stat('Buyer refunds',money(refunds),`${money(credit)} store credit used`)}${stat('Store credit balance',money(row.store_credit_balance),`buyer sync ${last}`)}${stat('Manual / off-platform',money(manual),`${money(row.operating_expense_spend)} external operating spend`)}${stat('Safe additional buys',money(safe),ready?'ready for Scout allocation':'provisional until month is confirmed')}</div><div class="cx-scout-toolbar"><label class="cx-sub">Off-platform / manual buys <input id="cxCashflowInventorySpend" inputmode="decimal" type="number" min="0" step="1" value="${esc(row.manual_purchase_adjustment||0)}"></label><label class="cx-sub">Other spend not netted from payouts <input id="cxCashflowOperatingSpend" inputmode="decimal" type="number" min="0" step="1" value="${esc(row.operating_expense_spend||0)}"></label><label class="cx-sub">Reserve % <input id="cxCashflowReserve" inputmode="decimal" type="number" min="0" max="100" step="1" value="${esc(row.reserve_pct||15)}"></label><label class="cx-sub">Buy target % <input id="cxCashflowTarget" inputmode="decimal" type="number" min="0" max="150" step="1" value="${esc(row.purchase_target_pct||70)}"></label><button type="button" class="cx-primary" id="cxCashflowSave">${ready?'Update month':'Confirm month'}</button></div><small class="cx-sub">${esc(status)} Buyer-account sync can revise prior orders when returns/refunds appear later. Marketplace fees and adjustments remain reflected in seller payout cash. Inventory spend used by the budget is ${money(row.inventory_purchase_spend)} total: ${money(netBuyer)} from the synced TCGplayer buyer ledger plus ${money(manual)} manual/off-platform. Current rule preserves ${pct(row.reserve_pct)} of cash received and targets inventory purchases near ${pct(row.purchase_target_pct)} of the stronger of current-month cash received or the trailing 3-month payout average.</small>`;
 document.getElementById('cxCashflowRefresh')?.addEventListener('click',()=>load({force:true}));document.getElementById('cxCashflowSave')?.addEventListener('click',save)}
async function save(){const inv=Number(document.getElementById('cxCashflowInventorySpend')?.value||0),op=Number(document.getElementById('cxCashflowOperatingSpend')?.value||0),reserve=Number(document.getElementById('cxCashflowReserve')?.value||15),target=Number(document.getElementById('cxCashflowTarget')?.value||70),btn=document.getElementById('cxCashflowSave');if(btn)btn.disabled=true;try{await rest('rpc/save_seller_cashflow_month',{method:'POST',body:{p_month_start:monthKey(),p_inventory_purchase_spend:Math.max(0,inv),p_operating_expense_spend:Math.max(0,op),p_reserve_pct:Math.max(0,Math.min(100,reserve)),p_purchase_target_pct:Math.max(0,Math.min(150,target)),p_note:null}});lastLoadedAt=0;await load({force:true});document.dispatchEvent(new CustomEvent('collectish:seller-cashflow-changed',{detail:{safeBudget:Number(row?.safe_additional_buy_budget||0),inputStatus:row?.input_status||null}}))}catch(e){error=String(e?.message||e||'Save failed');render()}finally{if(btn)btn.disabled=false}}
async function load({force=false}={}){if(loading)return loading;if(!force&&lastLoadedAt&&Date.now()-lastLoadedAt<CACHE_MS){render();return row}error='';loading=rest('rpc/seller_monthly_buying_budget',{method:'POST',body:{p_month_start:monthKey()}}).then(data=>{row=Array.isArray(data)?data[0]||null:data||null;lastLoadedAt=Date.now();if(row)document.dispatchEvent(new CustomEvent('collectish:seller-cashflow-changed',{detail:{safeBudget:Number(row.safe_additional_buy_budget||0),inputStatus:row.input_status||null}}));return row}).catch(e=>{row=null;error=String(e?.message||e||'Request failed');return null}).finally(()=>{loading=null;render()});render();return loading}
function ensure(){if(!host())return;render();void load()}
document.addEventListener('collectish:buyer-orders-changed',()=>{lastLoadedAt=0;void load({force:true})});document.addEventListener('collectish:seller-rendered',()=>setTimeout(ensure,0));document.addEventListener('collectish:page-change',e=>{if(e.detail?.page==='seller')setTimeout(ensure,80)});document.addEventListener('collectish:ready',()=>setTimeout(ensure,120));setTimeout(ensure,200);export {load as loadSellerCashflowBudget};
