import store from '../../state/store.js';

// Collectish Seller parity — server summaries + lazy detail tabs
(() => {
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'}),num=n=>Number(n||0).toLocaleString();
  const date=v=>v?new Date(v).toLocaleDateString():'—';
  let summary=null,recentOrders=[],reasons=[],tab=store.get().seller?.tab||'overview',installed=false,rendering=false,tabToken=0;
  const sync=patch=>store.update('seller',patch);

  function table(headers,rows){return `<div class="cx-table-wrap"><table class="cx-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td data-label="${esc(headers[i])}">${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function loading(text='Loading…'){return `<div class="cx-empty">${esc(text)}</div>`}
  function kpis(){const s=summary||{};return `<div class="cx-kpis"><div class="cx-kpi"><span>Orders</span><strong>${num(s.order_count)}</strong><small>${num(s.missing_detail_count)} details pending</small></div><div class="cx-kpi"><span>Gross sales</span><strong>${money(s.gross_sales)}</strong></div><div class="cx-kpi"><span>Fees</span><strong>${money(s.total_fees)}</strong><small>${Number(s.gross_sales||0)?(100*Number(s.total_fees||0)/Number(s.gross_sales)).toFixed(1):0}%</small></div><div class="cx-kpi"><span>Refunds</span><strong>${money(s.order_refund_total)}</strong><small>${num(s.refund_record_count)} records</small></div><div class="cx-kpi"><span>Net after refunds</span><strong>${money(s.net_after_refunds)}</strong></div><div class="cx-kpi"><span>Reviews</span><strong>${Number(s.average_rating||0).toFixed(2)}★</strong><small>${num(s.review_count)} reviews</small></div></div>`}
  function shell(host){
    host.innerHTML=`<div class="cx-page-head"><div><h2>Seller</h2><p>Complete sales, fees, refunds, feedback and reimbursement history.</p></div><button id="cxSellerParityRefresh" class="cx-refresh">Refresh</button></div><div class="cx-seller-tabs">${['overview','orders','products','refunds','reviews','payments','ris'].map(x=>`<button data-seller-tab="${x}" class="${x===tab?'active':''}">${x==='ris'?'RI / Direct':x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div id="cxSellerParityBody"></div>`;
    document.getElementById('cxSellerParityRefresh').onclick=load;
    host.querySelectorAll('[data-seller-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.sellerTab;sync({tab});host.querySelectorAll('[data-seller-tab]').forEach(x=>x.classList.toggle('active',x===b));renderTab()});
  }

  async function loadCore(){
    const [s,o,r]=await Promise.all([
      rest('seller_dashboard_summary?select=*&limit=1'),
      rest('seller_orders?select=order_number,order_date,order_status,order_channel,order_fulfillment,buyer_name,gross_amount,fee_amount,direct_fee_amount,net_amount,refund_total,review_rating,has_details&order=order_date.desc&limit=40'),
      rest('seller_refund_reason_summary?select=reason,refund_count,refund_amount,last_refund_at&order=refund_amount.desc&limit=10')
    ]);
    summary=s?.[0]||{};recentOrders=o||[];reasons=r||[];
    sync({summary,recentOrders,reasons,status:'ready'});
  }
  function overview(){const s=summary||{};return `${kpis()}<div class="cx-grid"><div class="cx-card cx-span-8"><div class="cx-section-title">Recent orders</div>${table(['Order','Date','Buyer','Gross','Fees','Refund','Net'],recentOrders.slice(0,25).map(o=>[o.order_number,date(o.order_date),o.buyer_name||'',money(o.gross_amount),money(Number(o.fee_amount||0)+Number(o.direct_fee_amount||0)),money(o.refund_total),money(Number(o.net_amount||0)-Number(o.refund_total||0))]))}</div><div class="cx-card cx-span-4"><div class="cx-section-title">Business exceptions</div><div class="cx-exception"><span>Missing order details</span><strong>${num(s.missing_detail_count)}</strong></div><div class="cx-exception"><span>Low reviews (≤3★)</span><strong>${num(s.low_review_count)}</strong></div><div class="cx-exception"><span>Pending payments</span><strong>${num(s.pending_payment_count)}</strong></div><div class="cx-exception"><span>RI discrepancy rows</span><strong>${num(s.ri_discrepancy_count)}</strong></div><div class="cx-exception"><span>RI replacement fees</span><strong>${money(s.ri_replacement_fees)}</strong></div><div class="cx-section-title" style="margin-top:16px">Top refund reasons</div>${reasons.slice(0,7).map(r=>`<div class="cx-exception"><span>${esc(r.reason)} <small>(${num(r.refund_count)})</small></span><strong>${money(r.refund_amount)}</strong></div>`).join('')}</div></div>`}

  async function ordersView(token){const body=document.getElementById('cxSellerParityBody');body.innerHTML=`<div class="cx-filters"><input id="cxSellerOrderSearch" placeholder="Search order or buyer…"><select id="cxSellerOrderRefund"><option value="">All orders</option><option value="refunded">Refunded only</option><option value="missing">Missing details</option></select></div><div id="cxSellerOrdersTable">${loading('Loading recent orders…')}</div>`;let timer;
    const run=async()=>{const q=document.getElementById('cxSellerOrderSearch')?.value.trim()||'',f=document.getElementById('cxSellerOrderRefund')?.value||'';let path='seller_orders?select=order_number,order_date,order_status,order_channel,order_fulfillment,buyer_name,gross_amount,fee_amount,direct_fee_amount,net_amount,refund_total,review_rating,has_details&order=order_date.desc&limit=1000';if(q){const like=encodeURIComponent(`*${q}*`);path+=`&or=(order_number.ilike.${like},buyer_name.ilike.${like})`}if(f==='refunded')path+='&refund_total=gt.0';if(f==='missing')path+='&has_details=eq.false';const rows=await rest(path);if(token!==tabToken)return;document.getElementById('cxSellerOrdersTable').innerHTML=table(['Order','Date','Fulfillment','Buyer','Status','Gross','Fees','Refund','Net','Review'],(rows||[]).map(o=>[o.order_number,date(o.order_date),o.order_fulfillment||'',o.buyer_name||'',o.order_status||'',money(o.gross_amount),money(Number(o.fee_amount||0)+Number(o.direct_fee_amount||0)),money(o.refund_total),money(Number(o.net_amount||0)-Number(o.refund_total||0)),o.review_rating?`${o.review_rating}★`:'' ]));sync({orderRows:rows||[]})};
    document.getElementById('cxSellerOrderSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(run,250)};document.getElementById('cxSellerOrderRefund').onchange=run;await run()}
  async function productsView(token){const body=document.getElementById('cxSellerParityBody');body.innerHTML=`<div class="cx-filters"><input id="cxSellerProductSearch" placeholder="Search product or SKU…"></div><div id="cxSellerProductsTable">${loading('Loading product sales…')}</div>`;let timer;const run=async()=>{const q=document.getElementById('cxSellerProductSearch')?.value.trim()||'';let path='seller_product_summary?select=product_name,sku_id,product_id,order_count,units_sold,revenue,last_sold_at&order=revenue.desc&limit=1000';if(q)path+=`&product_name=ilike.${encodeURIComponent(`*${q}*`)}`;const rows=await rest(path);if(token!==tabToken)return;document.getElementById('cxSellerProductsTable').innerHTML=table(['Product','SKU','Orders','Units','Revenue','Last sold'],(rows||[]).map(x=>[x.product_name,x.sku_id||x.product_id||'',num(x.order_count),num(x.units_sold),money(x.revenue),date(x.last_sold_at)]))};document.getElementById('cxSellerProductSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(run,250)};await run()}
  async function refundsView(token){const rows=await rest('seller_refunds?select=created_at_source,order_number,buyer_name,amount,shipping_amount,origin,reason,reason_text,type&order=created_at_source.desc&limit=1000');if(token!==tabToken)return;document.getElementById('cxSellerParityBody').innerHTML=`${reasons.length?`<div class="cx-card" style="margin-bottom:12px"><div class="cx-section-title">Refund reasons</div>${table(['Reason','Count','Amount','Last'],reasons.map(r=>[r.reason,num(r.refund_count),money(r.refund_amount),date(r.last_refund_at)]))}</div>`:''}<div class="cx-card"><div class="cx-section-title">Refund records</div>${table(['Date','Order','Buyer','Amount','Origin','Type','Reason'],(rows||[]).map(r=>[date(r.created_at_source),r.order_number,r.buyer_name||'',money(r.amount),r.origin||'',r.type||'',r.reason_text||r.reason||'']))}</div>`}
  async function reviewsView(token){const rows=await rest('seller_reviews?select=order_number,order_date,buyer_name,rating,review_text,created_at_source&order=created_at_source.desc&limit=1000');if(token!==tabToken)return;document.getElementById('cxSellerParityBody').innerHTML=`<div class="cx-card"><div class="cx-section-title">Latest reviews</div>${table(['Date','Order','Buyer','Rating','Review'],(rows||[]).map(r=>[date(r.created_at_source||r.order_date),r.order_number,r.buyer_name||'',`${Number(r.rating||0)}★`,r.review_text||'']))}</div>`}
  async function paymentsView(token){const [p,po,a]=await Promise.all([rest('seller_payments?select=*&order=arrival_date.desc&limit=1000'),rest('seller_payment_orders?select=payment_id,order_number,channel,buyer_name,order_date,total_sale,total_fees,refunded_orders,refunded_fees&order=order_date.desc&limit=300'),rest('seller_payment_adjustments?select=payment_id,amount,reason,order_number,ri_number,collected_at&order=collected_at.desc&limit=300')]);if(token!==tabToken)return;document.getElementById('cxSellerParityBody').innerHTML=`<div class="cx-card"><div class="cx-section-title">Payments</div>${table(['Arrival','Payment ID','Orders','Sales','Fees','Refunds','Adjustments','Payment'],(p||[]).map(x=>[date(x.arrival_date),x.payment_id,num(x.order_count),money(x.total_sales),money(x.total_fees),money(Number(x.refunded_orders||0)+Number(x.refunded_fees||0)),money(x.adjustments),money(x.payment)]))}</div><div class="cx-grid" style="margin-top:12px"><div class="cx-card cx-span-7"><div class="cx-section-title">Recent payment-linked orders</div>${table(['Order','Date','Buyer','Sale','Fees','Refunded'],(po||[]).map(x=>[x.order_number,date(x.order_date),x.buyer_name||'',money(x.total_sale),money(x.total_fees),money(Number(x.refunded_orders||0)+Number(x.refunded_fees||0))]))}</div><div class="cx-card cx-span-5"><div class="cx-section-title">Recent adjustments</div>${table(['Date','Reason','Amount','Order / RI'],(a||[]).map(x=>[date(x.collected_at),x.reason||'',money(x.amount),x.order_number||x.ri_number||'']))}</div></div>`}
  async function riView(token){const [ri,d]=await Promise.all([rest('reimbursement_invoices?select=*&order=created_date.desc&limit=500'),rest('ri_discrepancies?select=ri_number,set_name,product_name,expected_condition,received_condition,quantity,discrepancy,discrepancy_reason,market_price,sold_price,replacement_fee,collected_at&discrepancy=neq.0&order=replacement_fee.desc&limit=1000')]);if(token!==tabToken)return;document.getElementById('cxSellerParityBody').innerHTML=`${kpis()}<div class="cx-grid"><div class="cx-card cx-span-5"><div class="cx-section-title">Reimbursement invoices</div>${table(['RI','Date','Status','Product value','Replacement fees','Discrepancies'],(ri||[]).map(r=>[r.ri_number,date(r.created_date),r.status||'',money(r.total_product_value),money(r.total_replacement_fees),num(r.discrepancy_row_count)]))}</div><div class="cx-card cx-span-7"><div class="cx-section-title">Largest discrepancies</div>${table(['RI','Set','Product','Expected','Received','Qty Δ','Reason','Replacement'],(d||[]).map(r=>[r.ri_number,r.set_name,r.product_name,r.expected_condition||'',r.received_condition||'',num(r.discrepancy),r.discrepancy_reason||'',money(r.replacement_fee)]))}</div></div>`}

  function emitTab(){sync({tab,status:'ready'});document.dispatchEvent(new CustomEvent('collectish:seller-tab-rendered',{detail:{tab}}))}
  async function renderTab(){
    const body=document.getElementById('cxSellerParityBody');if(!body)return;
    const token=++tabToken;
    if(tab==='overview'){body.innerHTML=overview();emitTab();return}
    body.innerHTML=loading(`Loading ${tab==='ris'?'RI / Direct':tab}…`);
    try{if(tab==='orders')await ordersView(token);else if(tab==='products')await productsView(token);else if(tab==='refunds')await refundsView(token);else if(tab==='reviews')await reviewsView(token);else if(tab==='payments')await paymentsView(token);else await riView(token)}catch(e){if(token===tabToken)body.innerHTML=loading(e.message)}
    if(token===tabToken)emitTab();
  }
  async function load(){
    const host=document.getElementById('cxSeller');if(!host||rendering)return;
    rendering=true;sync({status:'loading'});host.dataset.sellerParity='loading';host.innerHTML='<div class="cx-page-head"><div><h2>Seller</h2><p>Complete sales, fees, refunds, feedback and reimbursement history.</p></div></div>'+loading('Loading Seller summary…');
    try{await loadCore();shell(host);await renderTab();host.dataset.sellerParity='ready';document.dispatchEvent(new CustomEvent('collectish:seller-rendered',{detail:{tab}}))}
    catch(e){sync({status:'error',error:String(e.message||e)});host.innerHTML=loading(e.message)}finally{rendering=false}
  }
  function install(){
    const h=document.getElementById('cxSeller');if(!h)return false;
    if(installed)return true;
    installed=true;load();return true;
  }
  if(!install())throw new Error('Seller renderer mounted without Seller host');
  window.CollectishSeller={load,renderTab};
})();