import store from '../../state/store.js';
import { renderSypScan } from './syp-scan-view.js';

// SYP route owner — decision scan plus server-paged workspace and changes.
(() => {
  const PAGE=100;
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const money=n=>n==null?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
  const num=n=>n==null?'—':Number(n||0).toLocaleString();
  const date=v=>v?new Date(v).toLocaleDateString():'—';
  const initial=store.get().syp||{};
  let tab=initial.tab||'products',page=initial.page||0,sort=initial.sort||{key:'last_seen',dir:'desc'},mode=initial.mode||'scan',scanFilter='all',scanQuery='';
  let stats=initial.stats||null,opts=initial.opts||{sets:[],conditions:[],event_types:[]},installed=false,loading=false,seq=0,debounce=0,scanEnrichment=new Map();
  const sync=patch=>store.update('syp',patch);
  const qp=(k,v)=>`${k}=${encodeURIComponent(v)}`;
  const sortOrder=()=>`${sort.key}.${sort.dir}`;
  const searchOr=(q,fields)=>q?`&or=(${fields.map(f=>`${f}.ilike.*${String(q).replace(/[,*()]/g,' ')}*`).join(',')})`:'';
  const host=()=>document.getElementById('cxSyp');
  const workspace=()=>document.getElementById('cxSypWorkspace');
  const scanRows=()=>tab==='products'&&Array.isArray(store.get().syp?.rows)?store.get().syp.rows:[];

  function shell(pageHost){
    pageHost.innerHTML=`<div class="cx-page-head"><div><h2>SYP</h2><p>Find the eligibility changes and capacity signals that matter, then inspect exact history as needed.</p></div><button id="cxSypParityRefresh" class="cx-refresh">Refresh</button></div><div class="cx-sv-nav cx-ui-tabs" id="cxSypRouteNav"><button type="button" data-syp-mode="scan" class="${mode==='scan'?'active':''}">Scan</button><button type="button" data-syp-mode="workspace" class="${mode==='workspace'?'active':''}">Workspace</button><button type="button" data-syp-changes>Changes</button><span>Eligibility · capacity · marketplace context</span></div><section id="cxSypScan"></section><section id="cxSypWorkspace"><div class="cx-kpis"><div class="cx-kpi"><span>Products</span><strong>${stats?num(stats.products):'—'}</strong></div><div class="cx-kpi"><span>Eligible</span><strong>${stats?num(stats.eligible):'—'}</strong></div><div class="cx-kpi"><span>Change events</span><strong>${stats?num(stats.events):'—'}</strong></div><div class="cx-kpi"><span>Added</span><strong>${stats?num(stats.added):'—'}</strong></div><div class="cx-kpi"><span>Removed</span><strong>${stats?num(stats.removed):'—'}</strong></div></div><div class="cx-seller-tabs cx-syp-tabs"><button data-syp-tab="products" class="${tab==='products'?'active':''}">Eligible products</button><button data-syp-tab="events" class="${tab==='events'?'active':''}">Changes</button></div><div id="cxSypParityBody"></div></section>`;
    document.getElementById('cxSypParityRefresh').onclick=()=>load(true);
    pageHost.addEventListener('click',routeClick,true);
    pageHost.addEventListener('input',routeInput,true);
    pageHost.querySelectorAll('[data-syp-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.sypTab));
    syncMode();renderScan();
  }

  function syncMode(){const scan=document.getElementById('cxSypScan'),work=workspace();if(scan)scan.hidden=mode!=='scan';if(work)work.hidden=mode!=='workspace';document.querySelectorAll('[data-syp-mode]').forEach(b=>b.classList.toggle('active',b.dataset.sypMode===mode));sync({mode})}
  function setMode(next){mode=next==='workspace'?'workspace':'scan';syncMode();if(mode==='scan')renderScan()}
  function setTab(next){tab=next==='events'?'events':'products';page=0;sort=tab==='products'?{key:'last_seen',dir:'desc'}:{key:'changed_at',dir:'desc'};sync({tab,page,sort});workspace()?.querySelectorAll('[data-syp-tab]').forEach(b=>b.classList.toggle('active',b.dataset.sypTab===tab));renderBody()}
  function renderScan(){const box=document.getElementById('cxSypScan');if(!box)return;if(tab!=='products'){box.innerHTML='<div class="cx-empty">Eligible-product scan is unavailable while the Changes workspace is selected.</div>';return}const rows=scanRows();box.innerHTML=rows.length?renderSypScan({rows,enrichment:scanEnrichment,filter:scanFilter,query:scanQuery}):'<div class="cx-empty">Loading eligible products for the decision scan…</div>'}
  function routeClick(e){const modeButton=e.target.closest?.('[data-syp-mode]');if(modeButton){e.preventDefault();setMode(modeButton.dataset.sypMode);return}if(e.target.closest?.('[data-syp-changes]')){e.preventDefault();setMode('workspace');setTab('events');return}const filterButton=e.target.closest?.('[data-syp-scan-filter]');if(filterButton){e.preventDefault();scanFilter=filterButton.dataset.sypScanFilter;renderScan();return}const row=e.target.closest?.('[data-syp-scan-sku]');if(row){e.preventDefault();openWorkspaceRow(row.dataset.sypScanSku)}}
  function routeInput(e){if(e.target?.id!=='cxSypScanSearch')return;scanQuery=e.target.value;const pos=e.target.selectionStart;renderScan();const input=document.getElementById('cxSypScanSearch');if(input){input.focus();try{input.setSelectionRange(pos,pos)}catch{}}}
  function openWorkspaceRow(sku){setMode('workspace');requestAnimationFrame(()=>{const row=document.querySelector(`#cxSypTable tr[data-sku="${CSS.escape(String(sku))}"]`);row?.scrollIntoView({block:'center',behavior:'smooth'});row?.querySelector('.cx-cardname')?.classList.add('cx-sypv-focus')})}

  const productFilters=()=>`<div class="cx-syp-filtergrid"><input id="cxSypSearch" placeholder="Search card, set or TCGplayer ID…"><select id="cxSypSet"><option value="">All sets</option>${(opts.sets||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="cxSypCondition"><option value="">All conditions</option>${(opts.conditions||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="cxSypMax"><option value="">Any max qty</option><option value="0">0</option><option value="1-4">1–4</option><option value="5-9">5–9</option><option value="10-24">10–24</option><option value="25-49">25–49</option><option value="50-99">50–99</option><option value="100+">100+</option></select><label>First seen since<input id="cxSypFirst" type="date"></label><label>Last seen since<input id="cxSypLast" type="date"></label><button id="cxSypExport" class="cx-refresh">Export filtered CSV</button></div><div id="cxSypCount" class="cx-syp-count"></div><div id="cxSypTable"></div><div id="cxSypPager" class="cx-syp-pager"></div>`;
  const eventFilters=()=>`<div class="cx-syp-filtergrid cx-syp-eventfilters"><input id="cxSypEventSearch" placeholder="Search card, set or TCGplayer ID…"><select id="cxSypEventType"><option value="">All change types</option>${(opts.event_types||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select><button id="cxSypExport" class="cx-refresh">Export filtered CSV</button></div><div id="cxSypCount" class="cx-syp-count"></div><div id="cxSypTable"></div><div id="cxSypPager" class="cx-syp-pager"></div>`;

  function productPath(limit=PAGE,offset=page*PAGE){const q=document.getElementById('cxSypSearch')?.value.trim()||'',set=document.getElementById('cxSypSet')?.value||'',cond=document.getElementById('cxSypCondition')?.value||'',mq=document.getElementById('cxSypMax')?.value||'',first=document.getElementById('cxSypFirst')?.value,last=document.getElementById('cxSypLast')?.value;let s=`syp_products?select=tcgplayer_id,product_name,set_name,number,condition,market_price,current_max_quantity,first_seen,last_seen,is_currently_eligible&is_currently_eligible=eq.true&order=${sortOrder()}&limit=${limit}&offset=${offset}`;s+=searchOr(q,['product_name','set_name','tcgplayer_id']);if(set)s+=`&${qp('set_name','eq.'+set)}`;if(cond)s+=`&${qp('condition','eq.'+cond)}`;if(mq==='0')s+='&current_max_quantity=eq.0';else if(mq==='100+')s+='&current_max_quantity=gte.100';else if(mq){const [a,b]=mq.split('-');s+=`&current_max_quantity=gte.${a}&current_max_quantity=lte.${b}`}if(first)s+=`&first_seen=gte.${encodeURIComponent(first+'T00:00:00Z')}`;if(last)s+=`&last_seen=gte.${encodeURIComponent(last+'T00:00:00Z')}`;return s}
  function eventPath(limit=PAGE,offset=page*PAGE){const q=document.getElementById('cxSypEventSearch')?.value.trim()||'',type=document.getElementById('cxSypEventType')?.value||'';let s=`syp_events?select=event_id,tcgplayer_id,product_name,set_name,event_type,old_value,new_value,difference,changed_at&order=${sortOrder()}&limit=${limit}&offset=${offset}`;s+=searchOr(q,['product_name','set_name','tcgplayer_id']);if(type)s+=`&${qp('event_type','eq.'+type)}`;return s}
  function header(label,key=''){return key?`<th data-syp-sort="${key}" class="${sort.key===key?'sorted '+sort.dir:''}">${esc(label)}${sort.key===key?(sort.dir==='asc'?' ↑':' ↓'):''}</th>`:`<th>${esc(label)}</th>`}
  function pager(rows){const h=document.getElementById('cxSypPager');if(!h)return;h.innerHTML=`<button class="cx-refresh" id="cxSypPrev" ${page===0?'disabled':''}>Previous</button><span>Page ${page+1}</span><button class="cx-refresh" id="cxSypNext" ${rows.length<PAGE?'disabled':''}>Next</button>`;h.querySelector('#cxSypPrev').onclick=()=>{if(page){page--;sync({page});loadPage()}};h.querySelector('#cxSypNext').onclick=()=>{if(rows.length===PAGE){page++;sync({page});loadPage()}}}
  function wireSort(){document.querySelectorAll('#cxSypTable [data-syp-sort]').forEach(th=>th.onclick=()=>{const k=th.dataset.sypSort;if(sort.key===k)sort.dir=sort.dir==='asc'?'desc':'asc';else sort={key:k,dir:['product_name','set_name','condition','event_type'].includes(k)?'asc':'desc'};page=0;sync({sort,page});loadPage()})}

  async function marketplaceEnrichment(skus){try{const r=await rest('rpc/syp_marketplace_enrichment',{method:'POST',body:{p_skus:skus}});return new Map((r||[]).map(x=>[String(x.sku_id),x]))}catch{return new Map()}}
  async function identityCache(skus){if(!skus.length)return new Map();try{const r=await rest(`card_identity_cache?select=sku_id,tcgplayer_url,image_url&sku_id=in.(${skus.map(encodeURIComponent).join(',')})`);return new Map((r||[]).map(x=>[String(x.sku_id),x]))}catch{return new Map()}}
  async function enrichProductPage(rows,my){const skus=rows.map(r=>String(r.tcgplayer_id)).filter(Boolean);if(!skus.length){scanEnrichment=new Map();renderScan();return}const [ids,market]=await Promise.all([identityCache(skus),marketplaceEnrichment(skus)]);if(my!==seq)return;scanEnrichment=market;for(const p of rows){const sku=String(p.tcgplayer_id),tr=document.querySelector(`#cxSypTable tr[data-sku="${CSS.escape(sku)}"]`);if(!tr)continue;const id=ids.get(sku),m=market.get(sku),cell=tr.querySelector('.cx-cardname');if(cell&&id?.tcgplayer_url){cell.dataset.tcgUrl=id.tcgplayer_url;cell.title='Open on TCGplayer'}const set=(role,val)=>{const n=tr.querySelector(`[data-role="${role}"]`);if(n)n.textContent=val};set('direct-low',money(m?.direct_low));set('direct-qty',num(m?.direct_available));set('direct-listings',num(m?.direct_listings));set('market-listings',num(m?.total_marketplace_listings))}sync({enrichment:{identities:ids.size,market:market.size}});renderScan();document.dispatchEvent(new CustomEvent('collectish:syp-enriched',{detail:{count:rows.length}}))}

  async function loadPage(){const my=++seq,table=document.getElementById('cxSypTable'),count=document.getElementById('cxSypCount');if(!table)return;table.innerHTML='<div class="cx-empty">Loading…</div>';sync({status:'loading-page',tab,page,sort});try{const rows=await rest(tab==='products'?productPath():eventPath());if(my!==seq)return;sync({status:'ready',tab,page,sort,rows});if(count)count.textContent=`${num(rows.length)} rows on this page • ${PAGE} per page`;if(tab==='products'){table.innerHTML=`<div class="cx-table-wrap"><table class="cx-table cx-syp-table"><thead><tr>${header('Product','product_name')}${header('Set','set_name')}${header('Condition','condition')}${header('Market','market_price')}${header('Direct')}${header('D qty')}${header('D listings')}${header('Mkt listings')}${header('SYP max','current_max_quantity')}${header('First seen','first_seen')}${header('Last seen','last_seen')}</tr></thead><tbody>${rows.map(p=>`<tr data-sku="${esc(p.tcgplayer_id)}"><td data-label="Product" class="cx-cardname">${esc(p.product_name)}<span class="cx-sub">TCG SKU ${esc(p.tcgplayer_id)}</span></td><td data-label="Set">${esc(p.set_name)}</td><td data-label="Condition">${esc(p.condition)}</td><td data-label="Market">${money(p.market_price)}</td><td data-label="Direct" data-role="direct-low">—</td><td data-label="D qty" data-role="direct-qty">—</td><td data-label="D listings" data-role="direct-listings">—</td><td data-label="Mkt listings" data-role="market-listings">—</td><td data-label="SYP max">${num(p.current_max_quantity)}</td><td data-label="First seen">${date(p.first_seen)}</td><td data-label="Last seen">${date(p.last_seen)}</td></tr>`).join('')}</tbody></table></div>`;renderScan();void enrichProductPage(rows,my)}else{scanEnrichment=new Map();table.innerHTML=`<div class="cx-table-wrap"><table class="cx-table cx-syp-table"><thead><tr>${header('Changed','changed_at')}${header('Type','event_type')}${header('Product','product_name')}${header('Set','set_name')}${header('Old','old_value')}${header('New','new_value')}${header('Δ','difference')}</tr></thead><tbody>${rows.map(e=>`<tr><td data-label="Changed">${date(e.changed_at)}</td><td data-label="Type"><span class="cx-syp-event cx-syp-${String(e.event_type||'').toLowerCase()}">${esc(e.event_type)}</span></td><td data-label="Product" class="cx-cardname">${esc(e.product_name)}<span class="cx-sub">TCG SKU ${esc(e.tcgplayer_id)}</span></td><td data-label="Set">${esc(e.set_name)}</td><td data-label="Old">${e.old_value==null?'—':num(e.old_value)}</td><td data-label="New">${e.new_value==null?'—':num(e.new_value)}</td><td data-label="Δ">${e.difference==null?'—':num(e.difference)}</td></tr>`).join('')}</tbody></table></div>`;renderScan()}wireSort();pager(rows);document.dispatchEvent(new CustomEvent('collectish:syp-page-rendered',{detail:{tab,page,count:rows.length}}))}catch(e){if(my===seq){sync({status:'error',error:String(e.message||e)});table.innerHTML=`<div class="cx-empty">${esc(e.message)}</div>`}}}
  function schedulePage(){clearTimeout(debounce);debounce=setTimeout(()=>{page=0;sync({page});loadPage()},250)}
  async function exportAll(){const btn=document.getElementById('cxSypExport');if(btn){btn.disabled=true;btn.textContent='Preparing…'}try{const out=[];for(let off=0;;off+=1000){const r=await rest(tab==='products'?productPath(1000,off):eventPath(1000,off));out.push(...r);if(r.length<1000)break}const fields=tab==='products'?[['TCGplayer SKU','tcgplayer_id'],['Product','product_name'],['Set','set_name'],['Condition','condition'],['Market Price','market_price'],['Max Quantity','current_max_quantity'],['First Seen','first_seen'],['Last Seen','last_seen']]:[['Changed At','changed_at'],['Event Type','event_type'],['TCGplayer SKU','tcgplayer_id'],['Product','product_name'],['Set','set_name'],['Old Value','old_value'],['New Value','new_value'],['Difference','difference']],quote=v=>`"${String(v??'').replace(/"/g,'""')}"`,text=[fields.map(x=>quote(x[0])).join(','),...out.map(r=>fields.map(x=>quote(r[x[1]])).join(','))].join('\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=tab==='products'?'TCGplayer_SYP_current_eligible_filtered.csv':'TCGplayer_SYP_latest_changes_filtered.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}finally{if(btn){btn.disabled=false;btn.textContent='Export filtered CSV'}}}
  function renderBody(){const body=document.getElementById('cxSypParityBody');if(!body)return;body.innerHTML=tab==='products'?productFilters():eventFilters();if(tab==='products'){['cxSypSet','cxSypCondition','cxSypMax','cxSypFirst','cxSypLast'].forEach(id=>document.getElementById(id).onchange=schedulePage);document.getElementById('cxSypSearch').oninput=schedulePage}else{document.getElementById('cxSypEventSearch').oninput=schedulePage;document.getElementById('cxSypEventType').onchange=schedulePage}document.getElementById('cxSypExport').onclick=exportAll;void loadPage()}

  async function load(){const pageHost=host();if(!pageHost||loading)return;loading=true;sync({status:'loading'});pageHost.dataset.sypParity='loading';pageHost.innerHTML='<div class="cx-page-head"><div><h2>SYP</h2><p>Loading eligibility and change data…</p></div></div><div class="cx-empty">Loading SYP…</div>';try{[stats,opts]=await Promise.all([rest('rpc/syp_dashboard_stats',{method:'POST',body:{}}),rest('rpc/syp_filter_options_rpc',{method:'POST',body:{}})]);sync({stats,opts,tab,page,sort,mode,status:'ready'});shell(pageHost);renderBody();pageHost.dataset.sypParity='ready';document.dispatchEvent(new CustomEvent('collectish:syp-rendered',{detail:{tab,mode}}))}catch(e){sync({status:'error',error:String(e.message||e)});pageHost.innerHTML=`<div class="cx-empty">${esc(e.message)}</div>`}finally{loading=false}}
  function install(){const h=host();if(!h)return false;if(installed)return true;installed=true;load();return true}

  const style=document.createElement('style');style.textContent=`.cx-syp-pager{display:flex;justify-content:center;align-items:center;gap:10px;margin:12px 0 4px}.cx-syp-pager button:disabled{opacity:.4}#cxSyp .cx-cardname{cursor:pointer}#cxSyp .cx-cardname:hover{text-decoration:underline;text-underline-offset:2px}`;document.head.appendChild(style);
  if(!install())throw new Error('SYP renderer mounted without SYP host');
  window.CollectishSyp={load,loadPage,renderBody,setMode};
})();
