import { readMetrics } from './rest.js';

const started=performance.now();
const KEY='collectishRuntimeHealth';

function writeMetrics(patch){
  const next={...readMetrics(),...patch};
  try{sessionStorage.setItem(KEY,JSON.stringify(next))}catch{}
  return next;
}

const fmtMs=value=>value==null?'—':value<1000?`${Math.round(value)} ms`:`${(Number(value)/1000).toFixed(2)} s`;
const clean=value=>String(value??'').replace(/[<>]/g,'');

export function renderRuntimeHealth(){
  const host=document.getElementById('cxAdmin');
  if(!host)return;
  let box=host.querySelector('.cx-runtime-health');
  if(!box){
    box=document.createElement('div');
    box.className='cx-card cx-span-12 cx-runtime-health';
    (host.querySelector('.cx-grid')||host).append(box);
  }
  const metrics=readMetrics();
  const retries=Number(metrics.statement_timeout_retries||0);
  const recoveries=Number(metrics.statement_timeout_recoveries||0);
  const failures=Number(metrics.statement_timeout_failures||0);
  const cache=metrics.scout_cache_used===true
    ?`Used · ${fmtMs(metrics.scout_cache_read_ms)}`
    :metrics.scout_cache_fallback
      ?`Fallback · ${fmtMs(metrics.scout_cache_read_ms)}`
      :'—';

  box.innerHTML=`<div class="cx-section-title">Runtime health</div><div class="cx-detail-list">
    <div class="cx-detail-stat"><span>Scout first load</span><strong>${fmtMs(metrics.scout_first_load_ms)}</strong></div>
    <div class="cx-detail-stat"><span>Scout ranking cache</span><strong>${cache}</strong></div>
    <div class="cx-detail-stat"><span>Timeout retries</span><strong>${retries}</strong></div>
    <div class="cx-detail-stat"><span>Recovered retries</span><strong>${recoveries}</strong></div>
    <div class="cx-detail-stat"><span>Retry failures</span><strong>${failures}</strong></div>
    <div class="cx-detail-stat"><span>Slow reads (&gt;4s)</span><strong>${Number(metrics.slow_reads||0)}</strong></div>
    <div class="cx-detail-stat"><span>Last lazy page</span><strong>${metrics.last_lazy_page?`${metrics.last_lazy_page} · ${fmtMs(metrics.last_lazy_page_ms)}`:'—'}</strong></div>
  </div><div class="cx-sub">Session-only diagnostics. No extra API calls are generated by this card.${metrics.last_retry_path?` Last timeout path: ${clean(metrics.last_retry_path)}`:''}</div>`;
}

export function installRuntimeHealth(){
  document.addEventListener('collectish:scout-v5-ready',()=>{
    const metrics=readMetrics();
    if(metrics.scout_first_load_ms==null){
      writeMetrics({scout_first_load_ms:Math.round(performance.now()-started),scout_ready_at:new Date().toISOString()});
    }
  });
  document.addEventListener('collectish:lazy-page-loaded',event=>{
    writeMetrics({last_lazy_page:event.detail?.page||null,last_lazy_page_ms:event.detail?.ms??null});
    if(document.getElementById('cxAdmin')?.classList.contains('active'))renderRuntimeHealth();
  });
  document.addEventListener('collectish:runtime-health',()=>{
    if(document.getElementById('cxAdmin')?.classList.contains('active'))renderRuntimeHealth();
  });
  document.addEventListener('collectish:admin-section-change',event=>{
    if(event.detail?.section==='system')setTimeout(renderRuntimeHealth,0);
  });
  document.addEventListener('click',event=>{
    if(event.target?.closest?.('[data-cx-page="admin"]'))setTimeout(renderRuntimeHealth,120);
  },true);

  window.CollectishRuntimeHealthCard={render:renderRuntimeHealth,get:readMetrics};
}

installRuntimeHealth();
