-- Production observability for Scout ranking refresh decisions.
-- Applied to Supabase on 2026-08-23.

create table if not exists public.scout_rankings_run_log (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  completed_at timestamptz not null default now(),
  source text not null check (source in ('five_minute_worker','hourly_reconciliation','manual_or_other')),
  status text not null check (status in ('complete','failed')),
  decision text not null,
  skipped boolean not null default false,
  newest_input_at timestamptz,
  watermarks jsonb not null default '{}'::jsonb,
  durations_ms jsonb not null default '{}'::jsonb,
  total_ms integer,
  failed_phase text,
  error text,
  created_at timestamptz not null default now()
);

alter table public.scout_rankings_run_log enable row level security;
revoke all on table public.scout_rankings_run_log from anon, authenticated;
grant select, insert on table public.scout_rankings_run_log to service_role;
grant usage, select on sequence public.scout_rankings_run_log_id_seq to service_role;

create index if not exists scout_rankings_run_log_started_at_idx
  on public.scout_rankings_run_log (started_at desc);
create index if not exists scout_rankings_run_log_source_started_idx
  on public.scout_rankings_run_log (source, started_at desc);
