-- Continuous catalyst calibration capture support.
-- The run ledger is private; authenticated clients only see its summary through
-- get_catalyst_calibration().

create table if not exists public.market_intel_catalyst_shadow_recorder_runs (
  run_id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  scout_rows integer not null default 0,
  recent_intel integer not null default 0,
  candidates integer not null default 0,
  inserted integer not null default 0,
  status text not null default 'running' check (status in ('running','ok','failed')),
  error text
);

revoke all on public.market_intel_catalyst_shadow_recorder_runs from anon, authenticated;

-- Treat placeholder author values as missing so a real source_name wins.
create or replace view public.market_intel_catalyst_shadow_source_backtest
with (security_invoker=true) as
with labeled as (
  select distinct
    b.snapshot_id,
    b.user_id,
    coalesce(
      nullif(nullif(lower(trim(i.author)),'unknown'),''),
      nullif(trim(i.source_name),''),
      nullif(trim(i.source_type),''),
      'Unknown'
    ) as source_label,
    coalesce(nullif(trim(i.source_type),''),'unknown') as source_type,
    b.shadow_modifier,
    b.future_release,
    b.matured_1d,b.matured_3d,b.matured_7d,b.matured_30d,
    b.market_change_1d_pct,b.market_change_3d_pct,b.market_change_7d_pct,b.market_change_30d_pct,
    b.transactions_1d,b.transactions_3d,b.transactions_7d,b.transactions_30d
  from public.market_intel_catalyst_shadow_backtest b
  cross join lateral unnest(b.intel_ids) as x(intel_id)
  join public.market_intel_items i on i.user_id=b.user_id and i.intel_id=x.intel_id
)
select
  user_id,
  source_label,
  max(source_type) as source_type,
  count(*)::bigint as snapshots,
  round(avg(shadow_modifier),2) as avg_modifier,
  count(*) filter(where matured_1d)::bigint as matured_1d,
  count(*) filter(where matured_3d)::bigint as matured_3d,
  count(*) filter(where matured_7d)::bigint as matured_7d,
  count(*) filter(where matured_30d)::bigint as matured_30d,
  round(avg(market_change_1d_pct) filter(where matured_1d),2) as avg_market_change_1d_pct,
  round(avg(market_change_3d_pct) filter(where matured_3d),2) as avg_market_change_3d_pct,
  round(avg(market_change_7d_pct) filter(where matured_7d),2) as avg_market_change_7d_pct,
  round(avg(market_change_30d_pct) filter(where matured_30d),2) as avg_market_change_30d_pct,
  round(avg(transactions_1d) filter(where matured_1d),2) as avg_transactions_1d,
  round(avg(transactions_3d) filter(where matured_3d),2) as avg_transactions_3d,
  round(avg(transactions_7d) filter(where matured_7d),2) as avg_transactions_7d,
  round(avg(transactions_30d) filter(where matured_30d),2) as avg_transactions_30d
from labeled
where not future_release
group by user_id,source_label;

revoke all on public.market_intel_catalyst_shadow_source_backtest from anon;
grant select on public.market_intel_catalyst_shadow_source_backtest to authenticated;

create or replace function public.get_catalyst_calibration()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_result jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'bands', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.scorer_version desc, x.modifier_band)
      from (select * from public.market_intel_catalyst_shadow_backtest_summary where user_id=v_user_id) x
    ), '[]'::jsonb),
    'proposals', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.matured_7d desc, x.snapshots desc, x.source_label)
      from (select * from public.market_intel_catalyst_shadow_weight_proposals where user_id=v_user_id) x
    ), '[]'::jsonb),
    'candidates', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.decided_at desc nulls last, x.source_label)
      from (select * from public.market_intel_catalyst_candidate_weights where user_id=v_user_id) x
    ), '[]'::jsonb),
    'shots', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.captured_at desc)
      from (
        select snapshot_id,future_release,captured_at
        from public.market_intel_catalyst_shadow_snapshots
        where user_id=v_user_id
        order by captured_at desc limit 500
      ) x
    ), '[]'::jsonb),
    'candidateMetrics', coalesce((
      select jsonb_agg(to_jsonb(x))
      from (select * from public.market_intel_catalyst_candidate_model_metrics where user_id=v_user_id) x
    ), '[]'::jsonb),
    'health', jsonb_build_object(
      'last_snapshot_at',(select max(captured_at) from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id),
      'first_snapshot_at',(select min(captured_at) from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id),
      'next_7d_at',(select min(captured_at + interval '7 days') from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id and captured_at + interval '7 days' > now()),
      'mature_1d',(select count(*) from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id and captured_at + interval '1 day' <= now()),
      'mature_3d',(select count(*) from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id and captured_at + interval '3 days' <= now()),
      'mature_7d',(select count(*) from public.market_intel_catalyst_shadow_snapshots where user_id=v_user_id and captured_at + interval '7 days' <= now()),
      'latest_signal_at',(select max(observed_at) from public.market_intel_items where user_id=v_user_id),
      'recorder',(select coalesce(to_jsonb(r),'{}'::jsonb) from (
        select started_at,completed_at,scout_rows,recent_intel,candidates,inserted,status,error
        from public.market_intel_catalyst_shadow_recorder_runs
        order by started_at desc limit 1
      ) r)
    )
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_catalyst_calibration() from public, anon;
grant execute on function public.get_catalyst_calibration() to authenticated;
