create table if not exists public.delvin_surface_parity_observations (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  surface text not null check (surface in ('web','discord')),
  question_hash text not null,
  route text not null,
  canonical_result_id text not null,
  canonical_row_count integer,
  presentation_version integer,
  resolver_source text
);

create index if not exists delvin_surface_parity_lookup_idx
  on public.delvin_surface_parity_observations(question_hash,route,surface,observed_at desc);
create index if not exists delvin_surface_parity_observed_idx
  on public.delvin_surface_parity_observations(observed_at desc);

alter table public.delvin_surface_parity_observations enable row level security;
revoke all on table public.delvin_surface_parity_observations from public,anon,authenticated;
grant select,insert,delete on table public.delvin_surface_parity_observations to service_role;

create or replace function public.record_delvin_surface_parity_v1(
  p_surface text,
  p_question text,
  p_route text,
  p_canonical_result_id text,
  p_canonical_row_count integer default null,
  p_presentation_version integer default null,
  p_resolver_source text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  normalized text;
  qhash text;
  rid bigint;
begin
  if lower(coalesce(p_surface,'')) not in ('web','discord') then
    return jsonb_build_object('recorded',false,'reason','unsupported_surface');
  end if;
  if nullif(trim(coalesce(p_question,'')),'') is null or nullif(trim(coalesce(p_route,'')),'') is null or nullif(trim(coalesce(p_canonical_result_id,'')),'') is null then
    return jsonb_build_object('recorded',false,'reason','missing_identity');
  end if;
  normalized:=lower(regexp_replace(trim(p_question),'\s+',' ','g'));
  qhash:=md5(normalized);

  delete from public.delvin_surface_parity_observations
   where observed_at < now()-interval '14 days';

  insert into public.delvin_surface_parity_observations(surface,question_hash,route,canonical_result_id,canonical_row_count,presentation_version,resolver_source)
  values(lower(p_surface),qhash,trim(p_route),trim(p_canonical_result_id),p_canonical_row_count,p_presentation_version,nullif(trim(coalesce(p_resolver_source,'')),''))
  returning id into rid;

  return jsonb_build_object('recorded',true,'id',rid,'question_hash',qhash);
end;
$$;
revoke all on function public.record_delvin_surface_parity_v1(text,text,text,text,integer,integer,text) from public,anon,authenticated;
grant execute on function public.record_delvin_surface_parity_v1(text,text,text,text,integer,integer,text) to service_role;

create or replace function public.ask_delvin_surface_parity_health_v1(
  p_minutes integer default 60,
  p_pair_window_seconds integer default 300
)
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
with recent as (
  select *
  from public.delvin_surface_parity_observations
  where observed_at >= now() - make_interval(mins=>greatest(1,least(coalesce(p_minutes,60),10080)))
), ranked as (
  select r.*,row_number() over(partition by question_hash,route,surface order by observed_at desc,id desc) rn
  from recent r
), web as (
  select * from ranked where surface='web' and rn=1
), discord as (
  select * from ranked where surface='discord' and rn=1
), paired as (
  select
    w.question_hash,w.route,
    w.canonical_result_id web_result_id,d.canonical_result_id discord_result_id,
    w.canonical_row_count web_row_count,d.canonical_row_count discord_row_count,
    w.observed_at web_observed_at,d.observed_at discord_observed_at,
    abs(extract(epoch from (w.observed_at-d.observed_at)))::integer separation_seconds,
    (w.canonical_result_id=d.canonical_result_id) matched
  from web w
  join discord d using(question_hash,route)
  where abs(extract(epoch from (w.observed_at-d.observed_at))) <= greatest(1,least(coalesce(p_pair_window_seconds,300),3600))
), stats as (
  select count(*)::integer paired_count,count(*) filter(where matched)::integer matched_count,count(*) filter(where not matched)::integer mismatch_count
  from paired
)
select jsonb_build_object(
  'window_minutes',greatest(1,least(coalesce(p_minutes,60),10080)),
  'pair_window_seconds',greatest(1,least(coalesce(p_pair_window_seconds,300),3600)),
  'paired_count',(select paired_count from stats),
  'matched_count',(select matched_count from stats),
  'mismatch_count',(select mismatch_count from stats),
  'status',case when (select mismatch_count from stats)>0 then 'MISMATCH' when (select paired_count from stats)>0 then 'HEALTHY' else 'NO_PAIRED_OBSERVATIONS' end,
  'mismatches',coalesce((select jsonb_agg(to_jsonb(p) order by greatest(p.web_observed_at,p.discord_observed_at) desc) from (select * from paired where not matched limit 50)p),'[]'::jsonb),
  'pairs',coalesce((select jsonb_agg(to_jsonb(p) order by greatest(p.web_observed_at,p.discord_observed_at) desc) from (select * from paired limit 50)p),'[]'::jsonb)
);
$$;
revoke all on function public.ask_delvin_surface_parity_health_v1(integer,integer) from public,anon,authenticated;
grant execute on function public.ask_delvin_surface_parity_health_v1(integer,integer) to service_role;
