create table if not exists public.market_intel_catalyst_shadow_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  sku_id bigint not null,
  product_id bigint,
  scryfall_id uuid,
  card_name text not null,
  official_score numeric not null,
  official_grade text,
  shadow_modifier numeric not null,
  shadow_score numeric not null,
  shadow_grade text,
  raw_modifier numeric,
  future_release boolean not null default false,
  future_thesis_modifier numeric,
  independent_sources integer not null default 0,
  unique_events integer not null default 0,
  source_keys text[] not null default '{}',
  intel_ids uuid[] not null default '{}',
  catalyst_key text not null,
  scorer_version text not null default 'catalyst-shadow-v1',
  signal_max_at timestamptz,
  captured_at timestamptz not null default now(),
  constraint market_intel_catalyst_shadow_modifier_bounds check (shadow_modifier between -8 and 12),
  constraint market_intel_catalyst_shadow_score_bounds check (shadow_score between 0 and 100),
  unique(user_id, sku_id, catalyst_key, official_score, scorer_version)
);

alter table public.market_intel_catalyst_shadow_snapshots enable row level security;

drop policy if exists catalyst_shadow_snapshots_select_own on public.market_intel_catalyst_shadow_snapshots;
create policy catalyst_shadow_snapshots_select_own on public.market_intel_catalyst_shadow_snapshots
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists catalyst_shadow_snapshots_insert_own on public.market_intel_catalyst_shadow_snapshots;
create policy catalyst_shadow_snapshots_insert_own on public.market_intel_catalyst_shadow_snapshots
for insert to authenticated with check ((select auth.uid()) = user_id);

grant select, insert on public.market_intel_catalyst_shadow_snapshots to authenticated;
grant usage, select on sequence public.market_intel_catalyst_shadow_snapshots_snapshot_id_seq to authenticated;

create index if not exists idx_catalyst_shadow_snapshots_user_captured on public.market_intel_catalyst_shadow_snapshots(user_id, captured_at desc);
create index if not exists idx_catalyst_shadow_snapshots_user_sku on public.market_intel_catalyst_shadow_snapshots(user_id, sku_id, captured_at desc);
create index if not exists idx_catalyst_shadow_snapshots_intel_ids on public.market_intel_catalyst_shadow_snapshots using gin(intel_ids);

create or replace view public.market_intel_catalyst_shadow_outcomes
with (security_invoker = true)
as
select
  s.snapshot_id,s.user_id,s.sku_id,s.product_id,s.scryfall_id,s.card_name,
  s.official_score,s.official_grade,s.shadow_modifier,s.shadow_score,s.shadow_grade,
  s.raw_modifier,s.future_release,s.future_thesis_modifier,s.independent_sources,s.unique_events,
  s.source_keys,s.intel_ids,s.scorer_version,s.signal_max_at,s.captured_at,
  o.intel_id as outcome_intel_id,o.source_name,o.author,o.signal_at,o.oracle_id,o.canonical_name,
  o.empirical_timing,o.pre7_vs_prior23_pct,o.post7_vs_pre7_pct,o.signal_market_price,
  o.post7_market_price,o.post7_market_price_change_pct,o.post7_transactions,o.post14_transactions,
  o.post7_quantity,o.post7_covered_days
from public.market_intel_catalyst_shadow_snapshots s
left join public.market_intel_signal_outcomes o
  on o.user_id=s.user_id and o.intel_id=any(s.intel_ids);

grant select on public.market_intel_catalyst_shadow_outcomes to authenticated;
