update public.delvin_query_registry set matcher_priority=200, matcher_patterns=array['(growth|upside|room (left|to grow)|growth left|still grow|more room|more upside|plateau|ceiling|run left|legs left|runway|long term|collectible thesis)']::text[] where query_key='collectible_cohort_thesis';
update public.delvin_query_registry set matcher_priority=210, matcher_patterns=array['(across sets|cross set|which sets|best sets|compare sets|treatment families|treatment family|how are .* foils? doing across sets)']::text[] where query_key='collectible_family_index';
update public.delvin_query_registry set matcher_priority=220, matcher_patterns=array['(show me|show|list|which|best|strongest).*foil','foils?.*(in|from).*']::text[] where query_key='treatment_intelligence';
update public.delvin_query_registry set matcher_priority=230, matcher_patterns=array['(what is|what s|whats|what).*moving in','(set intelligence|top cards in|collectibles in|what is moving in|what s moving in|whats moving in)']::text[] where query_key='set_intelligence';
update public.delvin_query_registry set matcher_priority=240, matcher_patterns=array['(compare )?(all )?printings of','which printing of','printing family']::text[] where query_key='printing_family';
update public.delvin_query_registry set matcher_priority=250, matcher_patterns=array['why is .* moving','why did .* move','is .* move real','analy[sz]e ','am i late on ','investigate ','deep dive ']::text[] where query_key='card_investigation';

create or replace function public.resolve_delvin_registry_intent_v2(p_question text)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare raw_q text:=trim(coalesce(p_question,''));q text:=trim(regexp_replace(lower(coalesce(p_question,'')),'[^a-zA-Z0-9]+',' ','g'));r public.delvin_query_registry%rowtype;treatment text;setcodes text[];card text;
begin
 q:=trim(regexp_replace(q,'\s+',' ','g'));if q='' then return jsonb_build_object('matched',false);end if;
 select d.* into r from public.delvin_query_registry d where d.enabled and coalesce(array_length(d.matcher_patterns,1),0)>0 and exists(select 1 from unnest(d.matcher_patterns) pat where q~pat) order by d.matcher_priority,d.sort_order,d.query_key limit 1;
 if not found then return jsonb_build_object('matched',false);end if;
 treatment:=case when q like '%oil slick%' then 'Oil Slick Raised Foil' when q like '%step and compleat%' then 'Step-and-Compleat Foil' when q like '%retro frame foil%' then 'Retro Frame Foil' when q like '%extended art foil%' then 'Extended Art Foil' when q like '%textured foil%' then 'Textured Foil' when q like '%raised foil%' then 'Raised Foil' when q like '%fracture foil%' then 'Fracture Foil' when q like '%confetti foil%' then 'Confetti Foil' when q like '%galaxy foil%' then 'Galaxy Foil' when q like '%surge foil%' then 'Surge Foil' when q like '%rainbow foil%' then 'Rainbow Foil' when q like '%halo foil%' then 'Halo Foil' when q like '%neon ink%' then 'Neon Ink' when q like '%serialized%' then 'Serialized' when q like '%gilded foil%' then 'Gilded Foil' when q like '%etched foil%' then 'Etched Foil' when q like '%borderless foil%' then 'Borderless Foil' when q like '%showcase foil%' then 'Showcase Foil' else null end;
 select array_agg(code order by ord) into setcodes from (select distinct on(upper(m[1])) upper(m[1]) code,min(ord) over(partition by upper(m[1])) ord from regexp_matches(upper(raw_q),'\m([A-Z0-9]{3,6})\M','g') with ordinality as x(m,ord) where exists(select 1 from public.scout_opportunities_v5_cache s where upper(s.set_code)=upper(m[1])) order by upper(m[1]),ord)z;
 if r.query_key in('collectible_cohort_thesis','collectible_family_index','treatment_intelligence') and treatment is null then return jsonb_build_object('matched',false);end if;
 if r.query_key in('set_intelligence','treatment_intelligence') and coalesce(array_length(setcodes,1),0)<>1 then return jsonb_build_object('matched',false);end if;
 if r.query_key='printing_family' then card:=regexp_replace(raw_q,'^(compare\s+)?(all\s+)?printings\s+of\s+','','i');card:=regexp_replace(card,'^which\s+printing\s+of\s+','','i');card:=regexp_replace(card,'^printing\s+family\s+','','i');card:=trim(regexp_replace(card,'[?]+$','','g'));if card='' then return jsonb_build_object('matched',false);end if;
 elsif r.query_key='card_investigation' then card:=regexp_replace(raw_q,'^(why\s+is|why\s+did|is|analy[sz]e|am\s+i\s+late\s+on|investigate|deep\s+dive)\s+','','i');card:=regexp_replace(card,'\s+(moving|spiking|move\s+real|real\s+or\s+noise|sustainable)\??$','','i');card:=trim(regexp_replace(card,'[?]+$','','g'));if card='' then return jsonb_build_object('matched',false);end if;end if;
 return jsonb_strip_nulls(jsonb_build_object('matched',true,'query_key',r.query_key,'route_key',coalesce(r.route_key,r.query_key),'capability_kind',r.capability_kind,'surface_type',r.surface_type,'async_enrichment',r.async_enrichment,'prompt',r.prompt,'treatment',treatment,'set_codes',setcodes,'set_code',case when coalesce(array_length(setcodes,1),0)=1 then setcodes[1] else null end,'card_name',card,'resolver_source','delvin_query_registry'));
end;$$;
revoke all on function public.resolve_delvin_registry_intent_v2(text) from public,anon;
grant execute on function public.resolve_delvin_registry_intent_v2(text) to authenticated,service_role;