create or replace view public.market_intel_catalyst_candidate_promotion_gate
with (security_invoker=true)
as
with active as (
  select * from public.market_intel_catalyst_candidate_backtest
  where candidate_model_active and not future_release
),
source_counts as (
  select c.user_id,count(*)::bigint approved_candidate_sources
  from public.market_intel_catalyst_candidate_weights c
  where c.candidate_weight is not null
  group by c.user_id
),
agg as (
  select a.user_id,
    count(*) filter(where a.matured_7d)::bigint matured_7d,
    count(*) filter(where a.matured_30d)::bigint matured_30d,
    count(*) filter(where a.matured_7d and a.candidate_weighted_signals>0)::bigint affected_matured_7d,
    count(*) filter(where a.matured_30d and a.candidate_weighted_signals>0)::bigint affected_matured_30d,
    round(avg(a.market_change_7d_pct) filter(where a.matured_7d and a.shadow_modifier>=4),2) current_high_avg_7d,
    round(avg(a.market_change_7d_pct) filter(where a.matured_7d and a.shadow_modifier<=0),2) current_low_avg_7d,
    round(avg(a.market_change_7d_pct) filter(where a.matured_7d and a.candidate_modifier>=4),2) candidate_high_avg_7d,
    round(avg(a.market_change_7d_pct) filter(where a.matured_7d and a.candidate_modifier<=0),2) candidate_low_avg_7d,
    round(avg(a.market_change_30d_pct) filter(where a.matured_30d and a.shadow_modifier>=4),2) current_high_avg_30d,
    round(avg(a.market_change_30d_pct) filter(where a.matured_30d and a.shadow_modifier<=0),2) current_low_avg_30d,
    round(avg(a.market_change_30d_pct) filter(where a.matured_30d and a.candidate_modifier>=4),2) candidate_high_avg_30d,
    round(avg(a.market_change_30d_pct) filter(where a.matured_30d and a.candidate_modifier<=0),2) candidate_low_avg_30d,
    round(100.0*count(*) filter(where a.matured_7d and a.shadow_modifier>0 and coalesce(a.market_change_7d_pct,0)<=0)/nullif(count(*) filter(where a.matured_7d and a.shadow_modifier>0),0),1) current_false_positive_pct_7d,
    round(100.0*count(*) filter(where a.matured_7d and a.candidate_modifier>0 and coalesce(a.market_change_7d_pct,0)<=0)/nullif(count(*) filter(where a.matured_7d and a.candidate_modifier>0),0),1) candidate_false_positive_pct_7d,
    count(*) filter(where a.candidate_shadow_grade is distinct from a.shadow_grade)::bigint grade_changed_snapshots,
    count(*) filter(where a.matured_7d and a.candidate_shadow_grade in ('A','B') and a.shadow_grade not in ('A','B'))::bigint promoted_to_ab_matured_7d,
    round(avg(a.market_change_7d_pct) filter(where a.matured_7d and a.candidate_shadow_grade in ('A','B') and a.shadow_grade not in ('A','B')),2) promoted_to_ab_avg_7d
  from active a group by a.user_id
),
calc as (
  select a.*,coalesce(s.approved_candidate_sources,0) approved_candidate_sources,
    round(coalesce(a.current_high_avg_7d,0)-coalesce(a.current_low_avg_7d,0),2) current_separation_7d,
    round(coalesce(a.candidate_high_avg_7d,0)-coalesce(a.candidate_low_avg_7d,0),2) candidate_separation_7d,
    round((coalesce(a.candidate_high_avg_7d,0)-coalesce(a.candidate_low_avg_7d,0))-(coalesce(a.current_high_avg_7d,0)-coalesce(a.current_low_avg_7d,0)),2) separation_lift_7d,
    round(coalesce(a.current_high_avg_30d,0)-coalesce(a.current_low_avg_30d,0),2) current_separation_30d,
    round(coalesce(a.candidate_high_avg_30d,0)-coalesce(a.candidate_low_avg_30d,0),2) candidate_separation_30d,
    round((coalesce(a.candidate_high_avg_30d,0)-coalesce(a.candidate_low_avg_30d,0))-(coalesce(a.current_high_avg_30d,0)-coalesce(a.current_low_avg_30d,0)),2) separation_lift_30d
  from agg a left join source_counts s using(user_id)
)
select c.*,
  (c.affected_matured_7d>=30) gate_sample_7d,
  (c.affected_matured_30d>=10) gate_sample_30d,
  (c.separation_lift_7d>=2.0) gate_lift_7d,
  (c.separation_lift_30d>=0) gate_lift_30d,
  (coalesce(c.candidate_false_positive_pct_7d,100)<=coalesce(c.current_false_positive_pct_7d,100)) gate_false_positives,
  (coalesce(c.candidate_low_avg_7d,0)<=coalesce(c.current_low_avg_7d,0)+1.0) gate_downside,
  (c.approved_candidate_sources>=3) gate_source_diversity,
  ((c.promoted_to_ab_matured_7d=0) or coalesce(c.promoted_to_ab_avg_7d,0)>0) gate_grade_crossings,
  (c.affected_matured_7d>=30 and c.affected_matured_30d>=10 and c.separation_lift_7d>=2.0 and c.separation_lift_30d>=0 and coalesce(c.candidate_false_positive_pct_7d,100)<=coalesce(c.current_false_positive_pct_7d,100) and coalesce(c.candidate_low_avg_7d,0)<=coalesce(c.current_low_avg_7d,0)+1.0 and c.approved_candidate_sources>=3 and ((c.promoted_to_ab_matured_7d=0) or coalesce(c.promoted_to_ab_avg_7d,0)>0)) eligible_for_production_review
from calc c;

revoke all on public.market_intel_catalyst_candidate_promotion_gate from anon;
grant select on public.market_intel_catalyst_candidate_promotion_gate to authenticated;

create table if not exists public.market_intel_catalyst_production_promotion_reviews(
  review_id bigint generated by default as identity primary key,
  user_id uuid not null,
  decision text not null check(decision in ('approved_for_production','rejected','revoked')),
  note text,
  affected_matured_7d integer not null,
  affected_matured_30d integer not null,
  approved_candidate_sources integer not null,
  separation_lift_7d numeric,
  separation_lift_30d numeric,
  current_false_positive_pct_7d numeric,
  candidate_false_positive_pct_7d numeric,
  promoted_to_ab_matured_7d integer not null default 0,
  promoted_to_ab_avg_7d numeric,
  decided_at timestamptz not null default now()
);
alter table public.market_intel_catalyst_production_promotion_reviews enable row level security;
drop policy if exists catalyst_production_reviews_owner_select on public.market_intel_catalyst_production_promotion_reviews;
create policy catalyst_production_reviews_owner_select on public.market_intel_catalyst_production_promotion_reviews for select to authenticated using((select auth.uid())=user_id);
revoke all on public.market_intel_catalyst_production_promotion_reviews from anon;
grant select on public.market_intel_catalyst_production_promotion_reviews to authenticated;

create or replace function public.review_catalyst_candidate_for_production(p_decision text,p_note text default null)
returns bigint language plpgsql security invoker set search_path=public as $$
declare uid uuid:=auth.uid();g public.market_intel_catalyst_candidate_promotion_gate%rowtype;rid bigint;
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if p_decision not in ('approved_for_production','rejected','revoked') then raise exception 'Invalid decision'; end if;
  select * into g from public.market_intel_catalyst_candidate_promotion_gate where user_id=uid limit 1;
  if not found then raise exception 'Candidate model has no active backtest'; end if;
  if p_decision='approved_for_production' and not g.eligible_for_production_review then raise exception 'Candidate model has not passed the production promotion gates'; end if;
  insert into public.market_intel_catalyst_production_promotion_reviews(user_id,decision,note,affected_matured_7d,affected_matured_30d,approved_candidate_sources,separation_lift_7d,separation_lift_30d,current_false_positive_pct_7d,candidate_false_positive_pct_7d,promoted_to_ab_matured_7d,promoted_to_ab_avg_7d)
  values(uid,p_decision,p_note,g.affected_matured_7d,g.affected_matured_30d,g.approved_candidate_sources,g.separation_lift_7d,g.separation_lift_30d,g.current_false_positive_pct_7d,g.candidate_false_positive_pct_7d,g.promoted_to_ab_matured_7d,g.promoted_to_ab_avg_7d)
  returning review_id into rid;
  return rid;
end;$$;
revoke all on function public.review_catalyst_candidate_for_production(text,text) from public,anon;
grant execute on function public.review_catalyst_candidate_for_production(text,text) to authenticated;

create or replace view public.market_intel_catalyst_production_promotion_state with (security_invoker=true) as
with latest as(select distinct on(user_id)* from public.market_intel_catalyst_production_promotion_reviews order by user_id,decided_at desc,review_id desc)
select l.user_id,l.review_id,l.decision,l.note,l.decided_at,(l.decision='approved_for_production') approved_for_production,l.affected_matured_7d,l.affected_matured_30d,l.approved_candidate_sources,l.separation_lift_7d,l.separation_lift_30d,l.current_false_positive_pct_7d,l.candidate_false_positive_pct_7d,l.promoted_to_ab_matured_7d,l.promoted_to_ab_avg_7d from latest l;
revoke all on public.market_intel_catalyst_production_promotion_state from anon;
grant select on public.market_intel_catalyst_production_promotion_state to authenticated;