create table if not exists public.market_intel_catalyst_weight_reviews (
  review_id bigint generated by default as identity primary key,
  user_id uuid not null,
  source_label text not null,
  source_type text not null default 'unknown',
  current_weight numeric not null,
  proposed_weight numeric,
  proposed_delta numeric,
  matured_7d integer not null default 0,
  proposal_confidence text,
  recommendation text,
  decision text not null check (decision in ('approved_candidate','rejected','revoked')),
  note text,
  proposal_snapshot jsonb not null default '{}'::jsonb,
  decided_at timestamptz not null default now()
);

alter table public.market_intel_catalyst_weight_reviews enable row level security;

drop policy if exists catalyst_weight_reviews_select_own on public.market_intel_catalyst_weight_reviews;
create policy catalyst_weight_reviews_select_own on public.market_intel_catalyst_weight_reviews
for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists catalyst_weight_reviews_insert_own on public.market_intel_catalyst_weight_reviews;
create policy catalyst_weight_reviews_insert_own on public.market_intel_catalyst_weight_reviews
for insert to authenticated with check ((select auth.uid()) = user_id);

revoke all on public.market_intel_catalyst_weight_reviews from anon;
grant select,insert on public.market_intel_catalyst_weight_reviews to authenticated;
grant usage,select on sequence public.market_intel_catalyst_weight_reviews_review_id_seq to authenticated;

create index if not exists idx_catalyst_weight_reviews_user_source_decided
on public.market_intel_catalyst_weight_reviews(user_id,source_label,decided_at desc);

create or replace function public.review_catalyst_weight_proposal(p_source_label text,p_decision text,p_note text default null)
returns public.market_intel_catalyst_weight_reviews
language plpgsql
security invoker
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  p public.market_intel_catalyst_shadow_weight_proposals%rowtype;
  r public.market_intel_catalyst_weight_reviews%rowtype;
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if p_decision not in ('approved_candidate','rejected','revoked') then raise exception 'Invalid decision'; end if;
  select * into p from public.market_intel_catalyst_shadow_weight_proposals
  where user_id=uid and lower(source_label)=lower(trim(p_source_label))
  order by matured_7d desc,snapshots desc limit 1;
  if not found then raise exception 'No weight proposal found for source'; end if;
  if p_decision='approved_candidate' and (p.matured_7d < 8 or p.proposed_weight is null) then
    raise exception 'Proposal has not met the candidate promotion gate';
  end if;
  insert into public.market_intel_catalyst_weight_reviews(
    user_id,source_label,source_type,current_weight,proposed_weight,proposed_delta,matured_7d,
    proposal_confidence,recommendation,decision,note,proposal_snapshot
  ) values (
    uid,p.source_label,p.source_type,p.current_weight,p.proposed_weight,p.proposed_delta,p.matured_7d,
    p.proposal_confidence,p.recommendation,p_decision,nullif(trim(p_note),''),to_jsonb(p)
  ) returning * into r;
  return r;
end;
$$;
revoke all on function public.review_catalyst_weight_proposal(text,text,text) from public,anon;
grant execute on function public.review_catalyst_weight_proposal(text,text,text) to authenticated;

create or replace view public.market_intel_catalyst_candidate_weights
with (security_invoker=true)
as
with latest as (
  select distinct on (user_id,lower(source_label)) *
  from public.market_intel_catalyst_weight_reviews
  order by user_id,lower(source_label),decided_at desc,review_id desc
)
select user_id,source_label,source_type,current_weight,
       case when decision='approved_candidate' then proposed_weight end as candidate_weight,
       proposed_delta,matured_7d,proposal_confidence,recommendation,decision,note,decided_at,review_id
from latest;

revoke all on public.market_intel_catalyst_candidate_weights from anon;
grant select on public.market_intel_catalyst_candidate_weights to authenticated;
