-- Delvin deterministic printing-family, set-level, and treatment-cohort intelligence.

create or replace function public.delvin_treatment_label_v1(p_product_name text,p_set_code text,p_collector_number text,p_printing text) returns text language sql immutable as $$
select case
 when p_product_name ilike '%(Raised Foil)%' then 'Raised Foil'
 when p_product_name ilike '%(Retro Frame)%' and lower(coalesce(p_printing,''))='foil' then 'Retro Frame Foil'
 when p_product_name ilike '%(Retro Frame)%' then 'Retro Frame'
 when p_product_name ilike '%Borderless%' and lower(coalesce(p_printing,''))='foil' then 'Borderless Foil'
 when p_product_name ilike '%Borderless%' then 'Borderless'
 when p_product_name ilike '%Extended Art%' and lower(coalesce(p_printing,''))='foil' then 'Extended Art Foil'
 when p_product_name ilike '%Extended Art%' then 'Extended Art'
 when p_product_name ilike '%Showcase%' and lower(coalesce(p_printing,''))='foil' then 'Showcase Foil'
 when p_product_name ilike '%Showcase%' then 'Showcase'
 when upper(coalesce(p_set_code,''))='3ED' and lower(regexp_replace(coalesce(p_product_name,''),'\s*\([^)]*\)\s*$','','g')) in ('badlands','bayou','plateau','savannah','scrubland','taiga','tropical island','tundra','underground sea','volcanic island') then 'Revised Dual Land'
 when upper(coalesce(p_set_code,''))='SLD' and lower(coalesce(p_product_name,'')) ~ '(yojimbo|ifrit|magus sisters|shiva|bahamut|ramuh|odin|leviathan|alexander)' then 'Final Fantasy Summon / Elemental'
 else case when lower(coalesce(p_printing,''))='foil' then 'Standard Foil' else 'Standard' end end
$$;

create or replace function public.delvin_base_card_name_v1(p_product_name text) returns text language sql immutable as $$ select trim(regexp_replace(coalesce(p_product_name,''),'\s*\([^)]*\)',' ','g')) $$;

create or replace function public.ask_delvin_printing_family_v1(p_card_name text,p_limit integer default 20) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_base text; v_rows jsonb; v_family jsonb;
begin
 select public.delvin_base_card_name_v1(product_name) into v_base from scout_opportunities_v5_cache where lower(public.delvin_base_card_name_v1(product_name))=lower(trim(p_card_name)) or lower(product_name)=lower(trim(p_card_name)) order by promoted_score desc nulls last limit 1;
 if v_base is null then select public.delvin_base_card_name_v1(product_name) into v_base from scout_opportunities_v5_cache where lower(product_name) like '%'||lower(trim(p_card_name))||'%' order by length(product_name),promoted_score desc nulls last limit 1; end if;
 if v_base is null then return jsonb_build_object('ok',false,'error','I could not resolve that card in Scout.'); end if;
 with rows as (
  select c.*,delvin_treatment_label_v1(c.product_name,c.set_code,c.collector_number,c.printing) treatment,case when c.avg_daily_qty_sold>0 and c.direct_available is not null then round(c.direct_available/c.avg_daily_qty_sold,1) end direct_cover_days,case when c.sku_market_price>0 and c.direct_low is not null then round((c.direct_low-c.sku_market_price)/c.sku_market_price*100,1) end direct_premium_pct
  from scout_opportunities_v5_cache c where lower(public.delvin_base_card_name_v1(c.product_name))=lower(v_base) and lower(coalesce(c.condition,'')) in ('near mint','nm') and lower(coalesce(c.language,''))='english'
 ), ranked as (select *,row_number() over(partition by set_code,collector_number,printing order by promoted_score desc nulls last) rn from rows), lim as (select * from ranked where rn=1 order by promoted_score desc nulls last,avg_daily_qty_sold desc nulls last limit greatest(1,least(coalesce(p_limit,20),50)))
 select coalesce(jsonb_agg(jsonb_build_object('card_name',product_name,'set_code',set_code,'set_name',set_name,'collector_number',collector_number,'printing',printing,'treatment',treatment,'sku_id',sku_id,'product_id',product_id,'market',sku_market_price,'tcg_low',tcg_low,'direct_low',direct_low,'direct_available',direct_available,'direct_listings',direct_listings,'direct_cover_days',direct_cover_days,'direct_premium_pct',direct_premium_pct,'sales_day',avg_daily_qty_sold,'cheapest_buy',cheapest_buy,'cheapest_source',cheapest_source,'ck_buylist',ck_buylist,'grade',promoted_grade,'score',promoted_score,'confidence',confidence_label) order by promoted_score desc nulls last,avg_daily_qty_sold desc nulls last),'[]'::jsonb) into v_rows from lim;
 with rows as (select c.*,delvin_treatment_label_v1(c.product_name,c.set_code,c.collector_number,c.printing) treatment,case when c.avg_daily_qty_sold>0 and c.direct_available is not null then round(c.direct_available/c.avg_daily_qty_sold,1) end direct_cover_days from scout_opportunities_v5_cache c where lower(public.delvin_base_card_name_v1(c.product_name))=lower(v_base) and lower(coalesce(c.condition,'')) in ('near mint','nm') and lower(coalesce(c.language,''))='english')
 select jsonb_build_object('printing_count',count(*),'set_count',count(distinct set_code),'treatment_count',count(distinct treatment),'total_sales_day',round(sum(coalesce(avg_daily_qty_sold,0)),2),'tight_direct_count',count(*) filter(where direct_cover_days is not null and direct_cover_days<2),'best_score',max(promoted_score)) into v_family from rows;
 return jsonb_build_object('ok',true,'card_name',v_base,'summary',v_family,'printings',v_rows,'generated_at',now());
end $$;

create or replace function public.ask_delvin_set_intelligence_v1(p_set_code text,p_limit integer default 20) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_set text:=upper(trim(coalesce(p_set_code,''))); v_rows jsonb; v_treatments jsonb; v_summary jsonb;
begin
 if v_set='' or not exists(select 1 from scout_opportunities_v5_cache where upper(set_code)=v_set) then return jsonb_build_object('ok',false,'error','I could not resolve that set code in Scout.'); end if;
 with rows as (select c.*,delvin_treatment_label_v1(c.product_name,c.set_code,c.collector_number,c.printing) treatment,case when c.avg_daily_qty_sold>0 and c.direct_available is not null then round(c.direct_available/c.avg_daily_qty_sold,1) end direct_cover_days,case when c.sku_market_price>0 and c.direct_low is not null then round((c.direct_low-c.sku_market_price)/c.sku_market_price*100,1) end direct_premium_pct from scout_opportunities_v5_cache c where upper(c.set_code)=v_set and lower(coalesce(c.condition,'')) in ('near mint','nm') and lower(coalesce(c.language,''))='english'), ranked as (select *,row_number() over(partition by sku_id order by promoted_score desc nulls last) rn from rows), lim as (select * from ranked where rn=1 order by promoted_score desc nulls last,avg_daily_qty_sold desc nulls last limit greatest(1,least(coalesce(p_limit,20),50)))
 select coalesce(jsonb_agg(jsonb_build_object('card_name',product_name,'collector_number',collector_number,'printing',printing,'treatment',treatment,'sku_id',sku_id,'product_id',product_id,'market',sku_market_price,'direct_low',direct_low,'direct_available',direct_available,'direct_cover_days',direct_cover_days,'direct_premium_pct',direct_premium_pct,'sales_day',avg_daily_qty_sold,'grade',promoted_grade,'score',promoted_score,'confidence',confidence_label,'cheapest_buy',cheapest_buy,'cheapest_source',cheapest_source) order by promoted_score desc nulls last,avg_daily_qty_sold desc nulls last),'[]'::jsonb) into v_rows from lim;
 with rows as (select c.*,delvin_treatment_label_v1(c.product_name,c.set_code,c.collector_number,c.printing) treatment from scout_opportunities_v5_cache c where upper(c.set_code)=v_set and lower(coalesce(c.condition,'')) in ('near mint','nm') and lower(coalesce(c.language,''))='english') select coalesce(jsonb_agg(jsonb_build_object('treatment',treatment,'printing_count',printing_count,'card_count',card_count,'market_value_sum',market_value_sum,'sales_day',sales_day,'avg_score',avg_score,'tight_direct_count',tight_direct_count) order by market_value_sum desc nulls last),'[]'::jsonb) into v_treatments from (select treatment,count(*) printing_count,count(distinct lower(public.delvin_base_card_name_v1(product_name))) card_count,round(sum(coalesce(sku_market_price,0)),2) market_value_sum,round(sum(coalesce(avg_daily_qty_sold,0)),2) sales_day,round(avg(promoted_score),1) avg_score,count(*) filter(where avg_daily_qty_sold>0 and direct_available/avg_daily_qty_sold<2) tight_direct_count from rows group by treatment) x;
 select jsonb_build_object('set_code',v_set,'set_name',max(set_name),'printing_count',count(*),'card_count',count(distinct lower(public.delvin_base_card_name_v1(product_name))),'sales_day',round(sum(coalesce(avg_daily_qty_sold,0)),2),'tight_direct_count',count(*) filter(where avg_daily_qty_sold>0 and direct_available/avg_daily_qty_sold<2),'high_grade_count',count(*) filter(where promoted_grade in ('A','B'))) into v_summary from scout_opportunities_v5_cache where upper(set_code)=v_set and lower(coalesce(condition,'')) in ('near mint','nm') and lower(coalesce(language,''))='english';
 return jsonb_build_object('ok',true,'summary',v_summary,'leaders',v_rows,'treatments',v_treatments,'generated_at',now());
end $$;

create or replace function public.ask_delvin_treatment_intelligence_v1(p_set_code text,p_treatment text default null,p_limit integer default 30) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_set text:=upper(trim(coalesce(p_set_code,''))); v_t text:=lower(trim(coalesce(p_treatment,''))); v_rows jsonb; v_label text; v_has_scout boolean;
begin
 if v_set='' then return jsonb_build_object('ok',false,'error','Set code is required.'); end if;
 if v_t like '%raised%' then v_label:='Raised Foil'; elsif v_t like '%retro%' and v_t like '%foil%' then v_label:='Retro Frame Foil'; elsif v_t like '%dual%' then v_label:='Revised Dual Land'; elsif v_t ~ '(final fantasy|elemental|summon|yojimbo|ifrit|magus)' then v_label:='Final Fantasy Summon / Elemental'; elsif v_t like '%borderless%' and v_t like '%foil%' then v_label:='Borderless Foil'; elsif v_t like '%borderless%' then v_label:='Borderless'; else v_label:=nullif(initcap(v_t),''); end if;
 select exists(select 1 from scout_opportunities_v5_cache where upper(set_code)=v_set) into v_has_scout;
 with scout_rows as (select c.product_name card_name,c.set_code,c.set_name,c.collector_number,c.printing,delvin_treatment_label_v1(c.product_name,c.set_code,c.collector_number,c.printing) treatment,c.sku_id,c.product_id,c.sku_market_price market,c.direct_low,c.direct_available,case when c.avg_daily_qty_sold>0 and c.direct_available is not null then round(c.direct_available/c.avg_daily_qty_sold,1) end direct_cover_days,case when c.sku_market_price>0 and c.direct_low is not null then round((c.direct_low-c.sku_market_price)/c.sku_market_price*100,1) end direct_premium_pct,c.avg_daily_qty_sold sales_day,c.promoted_grade grade,c.promoted_score score,c.confidence_label confidence,c.cheapest_buy,c.cheapest_source,c.ck_buylist,'scout'::text evidence_source from scout_opportunities_v5_cache c where upper(c.set_code)=v_set and lower(coalesce(c.condition,'')) in ('near mint','nm') and lower(coalesce(c.language,''))='english'), catalog_rows as (select m.name card_name,m.set_code,null::text set_name,m.collector_number,case when lower(coalesce(p.finish,'')) like '%foil%' then 'Foil' else 'Normal' end printing,delvin_treatment_label_v1(m.name,m.set_code,m.collector_number,case when lower(coalesce(p.finish,'')) like '%foil%' then 'Foil' else 'Normal' end) treatment,null::text sku_id,m.tcgplayer_product_id product_id,p.market_price market,nullif(p.direct_low_price,0) direct_low,null::integer direct_available,null::numeric direct_cover_days,case when p.market_price>0 and nullif(p.direct_low_price,0) is not null then round((p.direct_low_price-p.market_price)/p.market_price*100,1) end direct_premium_pct,null::numeric sales_day,null::text grade,null::integer score,'catalog_price_only'::text confidence,coalesce(p.lowest_listing_price,p.low_price) cheapest_buy,'TCGplayer'::text cheapest_source,null::numeric ck_buylist,'catalog_fallback'::text evidence_source from mtgjson_cards m left join tcgplayer_preferred_price_current_cache p on p.uuid=m.uuid where upper(m.set_code)=v_set and not v_has_scout), rows as (select * from scout_rows union all select * from catalog_rows), filt as (select * from rows where v_label is null or treatment=v_label), lim as (select * from filt order by score desc nulls last,market desc nulls last limit greatest(1,least(coalesce(p_limit,30),60)))
 select coalesce(jsonb_agg(jsonb_build_object('card_name',card_name,'set_code',set_code,'set_name',set_name,'collector_number',collector_number,'printing',printing,'treatment',treatment,'sku_id',sku_id,'product_id',product_id,'market',market,'direct_low',direct_low,'direct_available',direct_available,'direct_cover_days',direct_cover_days,'direct_premium_pct',direct_premium_pct,'sales_day',sales_day,'grade',grade,'score',score,'confidence',confidence,'cheapest_buy',cheapest_buy,'cheapest_source',cheapest_source,'ck_buylist',ck_buylist,'evidence_source',evidence_source) order by score desc nulls last,market desc nulls last),'[]'::jsonb) into v_rows from lim;
 return jsonb_build_object('ok',true,'set_code',v_set,'treatment',coalesce(v_label,'all treatments'),'rows',v_rows,'row_count',jsonb_array_length(v_rows),'generated_at',now(),'note',case when not v_has_scout then 'Scout economics unavailable for this set; using canonical MTGJSON identity + current TCGplayer pricing where available.' end);
end $$;

revoke all on function public.ask_delvin_printing_family_v1(text,integer) from public,anon,authenticated;
revoke all on function public.ask_delvin_set_intelligence_v1(text,integer) from public,anon,authenticated;
revoke all on function public.ask_delvin_treatment_intelligence_v1(text,text,integer) from public,anon,authenticated;
grant execute on function public.ask_delvin_printing_family_v1(text,integer),public.ask_delvin_set_intelligence_v1(text,integer),public.ask_delvin_treatment_intelligence_v1(text,text,integer) to service_role;
