-- Harden shared Ask identity resolution for natural-language card references and preserve Marketplace Scan identity in exact-SKU history.

create or replace function public.ask_collectish_public_card_lookup_v1(p_query text, p_limit integer default 20)
returns table(card_name text, product_id text, sku_id text, scryfall_id uuid, set_code text, collector_number text, printing text, condition text, language text, source text, match_rank integer)
language sql security definer set search_path to 'public'
as $function$
with raw as (select trim(regexp_replace(trim(coalesce(p_query,'')), '\s+cards?\s*$', '', 'i')) value),
conversational as (select trim(regexp_replace(value, '^(please\s+)?(show|give|find|get|open)\s+(me\s+)?', '', 'i')) value from raw),
parsed as (select value,(regexp_match(value,'\s+([A-Za-z0-9]{2,8})\s*#?\s*([A-Za-z0-9-]+)\s*$'))[1] maybe_set,(regexp_match(value,'\s+([A-Za-z0-9]{2,8})\s*#?\s*([A-Za-z0-9-]+)\s*$'))[2] maybe_collector from conversational),
scoped as (select p.*,exists(select 1 from public.scout_card_catalog c where upper(coalesce(c.set_code,''))=upper(coalesce(p.maybe_set,'')) and lower(coalesce(c.collector_number,''))=lower(coalesce(p.maybe_collector,'')) union all select 1 from public.marketplace_scan_rows m where upper(coalesce(m.set_code,''))=upper(coalesce(p.maybe_set,'')) and lower(coalesce(m.collector_number,''))=lower(coalesce(p.maybe_collector,'')) limit 1) valid_scope from parsed p),
q as (select trim(case when valid_scope then regexp_replace(value,'\s+[A-Za-z0-9]{2,8}\s*#?\s*[A-Za-z0-9-]+\s*$','','i') else value end) needle,case when valid_scope then maybe_set end set_code,case when valid_scope then maybe_collector end collector_number from scoped),
rows as (
select c.card_name,c.product_id,c.sku_id,c.scryfall_id,c.set_code,c.collector_number,c.printing,c.condition,c.language,'scout_card_catalog'::text source,case when lower(c.card_name)=lower(q.needle) then 0 when lower(split_part(c.card_name,' // ',1))=lower(q.needle) then 1 when c.card_name ilike q.needle||'%' then 2 else 3 end match_rank from public.scout_card_catalog c cross join q where q.needle<>'' and c.card_name ilike '%'||q.needle||'%' and (q.set_code is null or upper(coalesce(c.set_code,''))=upper(q.set_code)) and (q.collector_number is null or lower(coalesce(c.collector_number,''))=lower(q.collector_number))
union all
select m.product_name,m.product_id,m.sku_id,m.scryfall_id,m.set_code,m.collector_number,m.printing,m.condition,m.language,'marketplace_scan_rows'::text source,case when lower(m.product_name)=lower(q.needle) then 0 when m.product_name ilike q.needle||'%' then 2 else 3 end match_rank from public.marketplace_scan_rows m cross join q where q.needle<>'' and m.product_name ilike '%'||q.needle||'%' and (q.set_code is null or upper(coalesce(m.set_code,''))=upper(q.set_code)) and (q.collector_number is null or lower(coalesce(m.collector_number,''))=lower(q.collector_number))
),dedup as (select distinct on (product_id,sku_id,coalesce(scryfall_id::text,'')) * from rows order by product_id,sku_id,coalesce(scryfall_id::text,''),match_rank,source)
select card_name,product_id,sku_id,scryfall_id,set_code,collector_number,printing,condition,language,source,match_rank from dedup order by match_rank,case when upper(coalesce(condition,''))='NEAR MINT' then 0 else 1 end,case when upper(coalesce(language,''))='ENGLISH' then 0 else 1 end,case when upper(coalesce(printing,'')) in ('NON FOIL','NORMAL') then 0 else 1 end,card_name,set_code,collector_number,printing,sku_id limit greatest(1,least(coalesce(p_limit,20),50));
$function$;

create or replace function public.ask_card_price_history_v1(p_product_id bigint default null::bigint,p_sku_id bigint default null::bigint,p_days integer default 180)
returns jsonb language sql security definer set search_path to 'public'
as $function$
with candidates as (
select c.sku_id::bigint sku_id,c.product_id::bigint product_id,c.card_name,c.set_code,c.collector_number,c.printing,c.condition,c.language,0 source_rank from scout_card_catalog c where (p_sku_id is not null and c.sku_id::bigint=p_sku_id) or (p_sku_id is null and p_product_id is not null and c.product_id::bigint=p_product_id)
union all
select m.sku_id::bigint,m.product_id::bigint,m.product_name,m.set_code,m.collector_number,m.printing,m.condition,m.language,1 from marketplace_scan_rows m where (p_sku_id is not null and m.sku_id::bigint=p_sku_id) or (p_sku_id is null and p_product_id is not null and m.product_id::bigint=p_product_id)
),target as (select sku_id,product_id,card_name,set_code,collector_number,printing,condition,language from candidates order by case when p_sku_id is not null and sku_id=p_sku_id then 0 else 1 end,source_rank,case when upper(coalesce(condition,''))='NEAR MINT' then 0 else 1 end,case when upper(coalesce(language,''))='ENGLISH' then 0 else 1 end,case when upper(coalesce(printing,'')) in ('NON FOIL','NORMAL') then 0 else 1 end limit 1),
hist_ranked as (select h.sku_id::bigint,h.product_id::bigint,h.market_price,h.low_price,h.lowest_listing_price,h.direct_low_price,h.observed_at,row_number() over(partition by h.sku_id::bigint,date_trunc('hour',h.observed_at) order by h.observed_at desc) rn from tcgplayer_official_sku_price_history h join target t on t.sku_id=h.sku_id::bigint where h.observed_at>=now()-make_interval(days=>greatest(1,least(coalesce(p_days,180),730)))),
hist as (select sku_id,product_id,market_price,low_price,lowest_listing_price,direct_low_price,observed_at from hist_ranked where rn=1),
sales_ranked as (select b.sku_id::bigint,b.product_id::bigint,b.bucket_start_date,b.market_price,b.low_sale_price,b.high_sale_price,b.low_sale_price_with_shipping,b.high_sale_price_with_shipping,b.quantity_sold,b.transaction_count,b.source,b.observed_at,row_number() over(partition by b.sku_id::bigint,b.bucket_start_date order by b.observed_at desc) rn from marketplace_sku_sales_buckets b join target t on t.sku_id=b.sku_id::bigint where b.bucket_start_date>=current_date-greatest(1,least(coalesce(p_days,180),730))),
sales as (select sku_id,product_id,bucket_start_date,market_price,low_sale_price,high_sale_price,low_sale_price_with_shipping,high_sale_price_with_shipping,quantity_sold,transaction_count,source from sales_ranked where rn=1)
select jsonb_build_object('available',exists(select 1 from target),'days',greatest(1,least(coalesce(p_days,180),730)),'card',coalesce((select to_jsonb(t) from target t),'{}'::jsonb),'price_points',coalesce((select jsonb_agg(to_jsonb(h) order by h.observed_at) from hist h),'[]'::jsonb),'sales_points',coalesce((select jsonb_agg(to_jsonb(s) order by s.bucket_start_date) from sales s),'[]'::jsonb),'price_point_count',(select count(*) from hist),'sales_point_count',(select count(*) from sales),'sales_source',case when exists(select 1 from sales) then 'tcgplayer_marketplace' else null end);
$function$;
