import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:any)=>String(v??'').trim();
async function parse(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):null}catch{return raw}}
async function rpc(name:string,body:any={}){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.message||`${name} ${r.status}`);return d}
async function rest(path:string,method='GET',body?:any,prefer?:string){const r=await fetch(`${U}/rest/v1/${path}`,{method,headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function fn(name:string,body:any){const r=await fetch(`${U}/functions/v1/${name}`,{method:'POST',headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),d:any=await parse(r);if(!r.ok)throw Error(d?.error||`${name} ${r.status}`);return d}
async function authorized(req:Request){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'');if(!t)return false;if(t===S)return true;const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:S,Authorization:`Bearer ${t}`}});return r.ok}
const base=(v:string)=>v.replace(/\s*\([^)]*\)/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
async function mpTarget(t:any){try{return{ok:true,target:t,data:await fn('manapool-supply-sync',{product_id:t.product_id,sku_id:t.sku_id})}}catch(e){return{ok:false,target:t,error:String((e as Error)?.message||e).slice(0,300)}}}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);if(!(await authorized(req)))return js({error:'Signed-in user required'},401);
 const body=await req.json().catch(()=>({}));const card=text(body.card_name),setName=text(body.set_name),maxTargets=Math.max(1,Math.min(Number(body.max_targets||12)||12,20));if(!card||!setName)return js({error:'card_name and set_name required'},400);
 const targets:any[]=await rpc('ask_delvin_market_depth_targets_v1',{p_card_name:card,p_set_name:setName,p_limit:maxTargets});if(!targets.length)return js({handled:true,route:'market_depth_now',card_name:card,set_name:setName,target_count:0,response:'No NM/LP English TCGplayer SKU targets are currently resolved for this set/card family.',targets:[]});
 const tcg=await fn('market-supply-sync',{targets:targets.map(t=>({product_id:t.product_id,sku_id:t.sku_id,condition:t.condition,printing:t.printing,set_code:t.set_code,card_name:t.card_name,language:'ENGLISH'})),scope:'CARD_FAMILY_NM_LP',max_pages:40});
 const mp:any[]=[];for(let i=0;i<targets.length;i+=2)mp.push(...await Promise.all(targets.slice(i,i+2).map(mpTarget)));
 await rpc('refresh_delvin_query_cache_v1',{p_query_key:'velocity_price_supply_divergence',p_force:true}).catch(()=>null);const div=await rpc('ask_delvin_velocity_price_supply_divergence_v1',{p_limit:50}).catch(()=>({rows:[]}));const row=(Array.isArray(div?.rows)?div.rows:[]).find((r:any)=>base(text(r?.card_name))===base(card)&&text(r?.set_name).toLowerCase()===setName.toLowerCase())||null;
 const snapshots=Array.isArray(tcg?.snapshots)?tcg.snapshots:tcg?.snapshot?[tcg.snapshot]:[],snapBySku=new Map(snapshots.map((x:any)=>[text(x?.sku_id),x])),mpBySku=new Map(mp.map((x:any)=>[text(x?.target?.sku_id),x]));const results=targets.map(t=>({ok:Boolean(snapBySku.get(text(t.sku_id))),target:t,snapshot:snapBySku.get(text(t.sku_id))||null,manapool:mpBySku.get(text(t.sku_id))||null}));
 const lows=snapshots.map((x:any)=>Number(x?.lowest_price_with_shipping)).filter(Number.isFinite),combined=tcg?.combined||{};const summary:any={target_count:targets.length,scanned_count:Number(tcg?.coverage?.complete_sku_count??snapshots.length),failed_count:Math.max(0,targets.length-Number(tcg?.coverage?.complete_sku_count??snapshots.length)),tcgplayer_listing_count:Number(combined.listing_count||0),tcgplayer_unit_count:Number(combined.unit_count||0),tcgplayer_seller_count:Number(combined.unique_seller_count||0),direct_unit_count:Number(combined.direct_unit_count||0),non_direct_unit_count:Number(combined.non_direct_unit_count||0),lowest_with_shipping:lows.length?Math.min(...lows):null,tcgplayer_depth_classification:tcg?.classification||'UNPROVEN',manapool_successes:mp.filter(x=>x.ok&&x.data?.ok).length};
 await rest('delvin_market_depth_scans','POST',{card_name:card,set_name:setName,set_code:targets[0]?.set_code||null,target_count:targets.length,scanned_count:summary.scanned_count,failed_count:summary.failed_count,result:{summary,row,tcgplayer:tcg,manapool:mp}},'return=minimal').catch(()=>null);
 return js({handled:true,route:'market_depth_now',card_name:card,set_name:setName,summary,row,targets:results,tcgplayer:tcg,response:row?`Fresh NM/LP card-family depth captured for ${card}. Current TCGplayer depth: ${summary.tcgplayer_depth_classification}. ${row.signal_class||'WATCH'}; market-wide trend remains ${row.global_supply_state||'UNPROVEN'} until repeated history is sufficient.`:`Fresh NM/LP card-family depth captured for ${card}.`});
});