import { uiEvidenceMarker } from '../../core/ui-primitives.js';
import { signalLabelFromActionClass, signalKindFromActionClass, signalKindFromIntelStage, signalKindLabel, SIGNAL_KIND_RANK, SIGNAL_SCAN_STAGES } from './decision-taxonomy.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>v==null||v===''?'—':`$${Number(v).toFixed(2)}`;
const pct=v=>v==null||v===''?'—':`${Number(v).toFixed(1)}%`;
const age=value=>{if(!value)return'—';const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms))return'—';const h=Math.max(0,Math.round(ms/3600000));if(h<1)return'now';if(h<24)return`${h}h`;return`${Math.round(h/24)}d`};
const keyFor=({sku_id,product_id,scryfall_id,card_name})=>String(sku_id||product_id||scryfall_id||card_name||'').toLowerCase();
const salesFor=(salesResponse,card)=>salesResponse?.get?.(String(card||'').trim().toLowerCase())||null;

export function buildSignalScanRows({actionableRows=[],intelItems=[],salesResponse=new Map()}={}){
  const map=new Map();
  for(const r of actionableRows||[]){const row={key:keyFor(r),sku_id:r.sku_id||null,product_id:r.product_id||null,scryfall_id:r.scryfall_id||null,card_name:r.card_name||r.product_name||'Unknown card',set_name:r.set_name||'',printing:r.printing||'',kind:signalKindFromActionClass(r.action_class),signal:signalLabelFromActionClass(r.action_class),primary_signal:r.primary_signal||'Changing market signal',evidence:Number(r.signal_families||0),confidence:Math.max(0,Math.min(100,Number(r.actionability_score||0))),scout:Number(r.adjusted_scout_score??r.base_scout_score??0),roi:r.direct_roi_pct==null?null:Number(r.direct_roi_pct),buy:r.cheapest_buy==null?null:Number(r.cheapest_buy),direct_net:r.direct_net_est==null?null:Number(r.direct_net_est),liquidity:r.liquidity_label||'',updated_at:null,direction:'bullish',stage:r.action_class==='action_now'?'leading':'confirming'};row.sales_response=salesFor(salesResponse,row.card_name);map.set(row.key,row)}
  for(const item of intelItems||[]){const entities=Array.isArray(item.market_intel_entities)?item.market_intel_entities:[];for(const e of entities){if(e.entity_type!=='card'||!(e.scryfall_id||e.product_id))continue;const key=keyFor({product_id:e.product_id,scryfall_id:e.scryfall_id,card_name:e.entity_name}),existing=map.get(key),source=item.source_name||item.author||item.source_type||'Independent source';if(existing){existing.evidence=Math.max(existing.evidence,1);existing.intel_count=(existing.intel_count||0)+1;existing.source=existing.source||source;if(item.observed_at&&(!existing.updated_at||new Date(item.observed_at)>new Date(existing.updated_at)))existing.updated_at=item.observed_at;continue}const cardName=e.entity_name||'Unknown card',kind=signalKindFromIntelStage(item.signal_stage);map.set(key,{key,sku_id:null,product_id:e.product_id||null,scryfall_id:e.scryfall_id||null,card_name:cardName,set_name:e.set_code||'',printing:'',kind,signal:signalKindLabel(kind),primary_signal:item.summary||item.title||'External market intelligence',evidence:1,confidence:Math.round(Math.max(0,Math.min(1,Number(item.confidence??e.confidence??0.5)))*100),scout:null,roi:null,buy:null,direct_net:null,liquidity:'',source,updated_at:item.observed_at||item.published_at||item.created_at||null,direction:item.direction||'neutral',stage:item.signal_stage||'unclassified',intel_count:1,sales_response:salesFor(salesResponse,cardName)})}}
  const counts=new Map();for(const item of intelItems||[])for(const e of Array.isArray(item.market_intel_entities)?item.market_intel_entities:[]){if(e.entity_type==='card'&&(e.scryfall_id||e.product_id)){const k=keyFor({product_id:e.product_id,scryfall_id:e.scryfall_id,card_name:e.entity_name});counts.set(k,(counts.get(k)||0)+1)}}
  const rows=[...map.values()];for(const r of rows)r.evidence=Math.max(r.evidence||0,counts.get(r.key)||0);return rows.sort((a,b)=>(SIGNAL_KIND_RANK[b.kind]-SIGNAL_KIND_RANK[a.kind])||(b.confidence-a.confidence)||((b.scout||0)-(a.scout||0)))
}

function metric(label,value,sub=''){return `<div class="cx-sv-metric cx-ui-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function stageChip(r){const cls=r.kind==='action'?'cx-sv-action':r.kind==='emerging'?'cx-sv-emerging':r.kind==='confirming'?'cx-sv-confirming':'cx-sv-watch',semantic=r.kind==='action'?'success':r.kind==='emerging'?'warning':r.kind==='confirming'?'accent':'muted';return `<span class="cx-sv-chip cx-ui-status ${semantic} ${cls}">${esc(r.signal)}</span>`}
function direction(r){return r.direction==='bearish'?'↓':r.direction==='bullish'?'↑':'→'}
function salesConfirmation(r){const s=r.sales_response;if(!s)return'';const tx=Number(s.post_signal_transactions_to_date||0),days=Number(s.time_to_3_transactions_days||0),lift=Number(s.transaction_velocity_lift_30d_pct),coverage=Number(s.coverage_pct||0);if(s.evidence_status==='confirmed')return `<span class="cx-sv-sales-confirm">${uiEvidenceMarker('verified',`Card-level NM English marketplace sales confirmed: ${tx} post-signal transactions${days?` with 3 reached in ${days}d`:''}. Direct vs non-Direct is not identified.`)}<b>${Math.min(99,tx)}tx${days?`/${days}d`:''}</b>${Number.isFinite(lift)&&lift!==0?`<i>${lift>0?'+':''}${Math.round(lift)}%</i>`:''}</span>`;if(tx>=2)return `<span class="cx-sv-sales-confirm">${uiEvidenceMarker('inferred',`${tx} card-level NM English marketplace transactions observed after the signal; 3 are required for normal confirmation.`)}<b>${tx}tx</b></span>`;if(tx===1)return `<span class="cx-sv-sales-confirm">${uiEvidenceMarker('caution','One card-level NM English marketplace transaction observed after the signal; evidence is anecdotal.')}<b>1tx</b></span>`;if(s.evidence_status==='partial_coverage'&&coverage>0)return `<span class="cx-sv-sales-confirm">${uiEvidenceMarker('unmeasured',`Sales coverage is partial (${Math.round(coverage)}% of mapped NM English SKUs).`)}</span>`;return''}
function imageFor(r){if(r.scryfall_id)return `https://api.scryfall.com/cards/${encodeURIComponent(r.scryfall_id)}?format=image&version=small`;if(r.product_id)return `https://product-images.tcgplayer.com/fit-in/200x279/${encodeURIComponent(r.product_id)}.jpg`;return''}
function rowHtml(r){const edge=r.roi==null?'—':pct(r.roi),price=r.buy==null?'—':money(r.buy),evidenceText=r.evidence?String(r.evidence):'1',scout=r.scout==null?'—':Math.round(r.scout),confMarker=uiEvidenceMarker('inferred','Confidence is modeled/inferred, not a directly observed market fact.'),img=imageFor(r),source=r.source||'Scout + market',move=r.roi==null?direction(r):`${Number(r.roi)>=0?'+':''}${Number(r.roi).toFixed(0)}%`,art=img?`<span class="cx-sv-art-wrap"><img class="cx-sv-art" loading="lazy" src="${esc(img)}" alt="${esc(r.card_name)}" onerror="this.closest('.cx-sv-art-wrap').classList.add('failed');this.remove()"><span class="cx-sv-art-fallback">${esc(String(r.card_name||'?').charAt(0))}</span></span>`:`<span class="cx-sv-art-wrap failed"><span class="cx-sv-art-fallback">${esc(String(r.card_name||'?').charAt(0))}</span></span>`;return `<button type="button" class="cx-sv-row" data-sv-open data-sku="${esc(r.sku_id||'')}" data-product="${esc(r.product_id||'')}" data-scryfall="${esc(r.scryfall_id||'')}" data-card="${esc(r.card_name)}">${art}<span class="cx-sv-stage-line">${stageChip(r)}<small>${esc(age(r.updated_at))}</small></span><span class="cx-sv-card"><strong>${esc(r.card_name)}</strong><small>${esc(r.primary_signal)}</small></span><span class="cx-sv-source"><span>${esc(source)}</span><small>${esc(evidenceText)} source${evidenceText==='1'?'':'s'} · ${esc(price)} buy</small></span><span class="cx-sv-score cx-sv-confidence"><small>Confidence</small><strong>${esc(String(r.confidence))}%${confMarker}</strong></span><span class="cx-sv-score cx-sv-scout"><small>Scout</small><strong>${esc(String(scout))}</strong></span><span class="cx-sv-score cx-sv-market"><small>Market</small><strong>${esc(move)}</strong><em>${esc(edge)} edge</em></span><span class="cx-sv-chevron">›</span>${salesConfirmation(r)}</button>`}

export function renderSignalScan({actionableRows=[],intelItems=[],salesResponse=new Map(),filter='all',query='',sort='priority'}={}){const all=buildSignalScanRows({actionableRows,intelItems,salesResponse}),q=query.trim().toLowerCase(),filtered=all.filter(r=>(filter==='all'||r.kind===filter)&&(!q||`${r.card_name} ${r.set_name} ${r.primary_signal}`.toLowerCase().includes(q))),rows=[...filtered].sort((a,b)=>sort==='newest'?new Date(b.updated_at||0)-new Date(a.updated_at||0):sort==='market'?(Number(b.roi||-999)-Number(a.roi||-999)):(SIGNAL_KIND_RANK[b.kind]-SIGNAL_KIND_RANK[a.kind])||(b.confidence-a.confidence)),action=all.filter(r=>r.kind==='action').length,emerging=all.filter(r=>r.kind==='emerging').length,confirming=all.filter(r=>r.kind==='confirming').length,watch=all.filter(r=>r.kind==='watch').length;return `<div class="cx-sv-scan"><div class="cx-sv-metrics cx-ui-metrics">${metric('Action now',action,'ready')}${metric('Emerging',emerging,'early')}${metric('Confirming',confirming,'corroborated')}${metric('Watch',watch,'monitor only')}</div><div class="cx-sv-toolbar"><input id="cxSvSearch" type="search" value="${esc(query)}" placeholder="Search signals"><button type="button" data-sv-sheet="filter">Filters${filter==='all'?'':' · 1'}</button><button type="button" data-sv-sheet="sort">${sort==='priority'?'Priority ↓':sort==='newest'?'Newest ↓':'Market move ↓'}</button></div><div class="cx-sv-context"><strong>${rows.length} signals</strong><span>Independent sources + Scout market data</span></div><div class="cx-sv-list cx-ui-list">${rows.length?rows.slice(0,80).map(rowHtml).join(''):'<div class="cx-empty">No signals match this view.</div>'}</div><div class="cx-sv-sheet" data-sv-sheet-panel hidden><button type="button" class="cx-sv-sheet-scrim" data-sv-sheet-close aria-label="Close"></button><section role="dialog" aria-modal="true" aria-label="Signal controls"><div class="cx-sv-sheet-handle"></div><div data-sv-sheet-content></div></section></div></div>`}
