import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { classifyFamilySupply, manaPoolCoverage } from "../_shared/family-supply-classification.mjs";

const U=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const CACHE_MINUTES=30;
const js=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:any)=>String(v??'').trim();
const sh=()=>({apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json'});
async function rest(path:string,o:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{method:o.method||'GET',headers:{...sh(),...(o.prefer?{Prefer:o.prefer}:{})},body:o.body===undefined?undefined:JSON.stringify(o.body)});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.message||`REST ${r.status}`);return d}
async function authorized(req:Request){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'');if(!t)return false;if(t===S)return true;const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:S,Authorization:`Bearer ${t}`}});return r.ok}
function money(v:any){const n=Number(v);return Number.isFinite(n)?n:null}
function exactSku(row:any,sku:string){return text(row?.productConditionId||row?.sku)===sku}
function condition(v:any){const s=text(v).toUpperCase();if(s==='NM'||s==='NEAR MINT')return'NEAR MINT';if(s==='LP'||s==='LIGHTLY PLAYED')return'LIGHTLY PLAYED';return s}
function depth(units:number,sellers:number){if(units<=8||sellers<=3)return'VERY_THIN';if(units<=25&&sellers<=10)return'THIN';if(units>=100&&sellers>=20)return'DEEP';return'MODERATE'}
function ageMinutes(v:any){const t=Date.parse(text(v));return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):Infinity}
function manaPoolOutcome(row:any){if(row?.available)return'AVAILABLE';const message=text(row?.error).toLowerCase();if(message.includes('missing mtgjson_uuid')||message.includes('missing_printing_identity'))return'MISSING_PRINTING_IDENTITY';if(message.includes('no variant mapped'))return'CONDITION_OR_VARIANT_NOT_CARRIED';if(Number(row?.status)===429||message.includes('rate limit'))return'RATE_LIMITED';return row?.ok===false?'API_ERROR':'NO_OBSERVATION'}
function counts(values:string[]){return values.reduce((out:any,value:string)=>(out[value]=Number(out[value]||0)+1,out),{})}
const fresh=(r:any)=>r&&r.coverage_state==='COMPLETE'&&ageMinutes(r.observed_at)<CACHE_MINUTES;
const uniq=(xs:any[])=>[...new Set(xs.map(text).filter(Boolean))];
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T,i:number)=>Promise<R>){const out:R[]=new Array(items.length);let next=0;async function worker(){for(;;){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},()=>worker()));return out;}

async function fetchProductListings(productId:string,maxPages:number){const pageSize=50,listings:any[]=[];let sourceTotal=0,pages=0,coverage='COMPLETE',from=0;for(let page=0;page<maxPages;page++){const payload={filters:{term:{sellerStatus:'Live',channelId:0},range:{quantity:{gte:1}},exclude:{channelExclusion:0}},context:{shippingCountry:'US',cart:{}},sort:{field:'price+shipping',order:'asc'},from,size:pageSize,aggregations:['listingType','seller-key','condition','language','printing']};const r=await fetch(`https://mp-search-api.tcgplayer.com/v1/product/${productId}/listings`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','Origin':'https://www.tcgplayer.com','Referer':'https://www.tcgplayer.com/','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'},body:JSON.stringify(payload)});const d:any=await r.json().catch(()=>null);if(!r.ok)throw Error(`TCGplayer listings HTTP ${r.status}: ${text(d?.message||d?.errors?.[0]||'request failed')}`);const outer=d?.results?.[0]||{},rows=Array.isArray(outer?.results)?outer.results:[];sourceTotal=Number(outer?.totalResults||sourceTotal||0);pages++;listings.push(...rows);from+=rows.length;if(rows.length<pageSize||from>=sourceTotal)break;if(page===maxPages-1)coverage='PARTIAL_PAGE_CAP';}return{listings,sourceTotal,pages,coverage};}
async function currentTcg(skuIds:string[]){if(!skuIds.length)return new Map<string,any>();const rows=await rest(`market_supply_current?source=eq.tcgplayer_marketplace&sku_id=in.(${skuIds.join(',')})&select=*`).catch(()=>[]);return new Map((rows||[]).map((r:any)=>[text(r.sku_id),r]));}
async function latestManaPool(skuId:string){const ids=await rest(`vendor_item_identities?source=eq.manapool&tcgplayer_sku_id=eq.${encodeURIComponent(skuId)}&select=source_item_key&limit=20`).catch(()=>[]);const keys=uniq((ids||[]).map((x:any)=>x.source_item_key));if(!keys.length)return null;const rows=(await mapLimit(keys,6,async k=>{const d=await rest(`vendor_depth_current?source=eq.manapool&lane=eq.retail_supply&source_item_key=eq.${encodeURIComponent(k)}&select=source_item_key,quantity,listing_count,price,condition,finish,measurement_scope,count_quality,observed_at&order=observed_at.desc&limit=1`).catch(()=>[]);return d?.[0]||null;})).filter(Boolean) as any[];if(!rows.length)return null;const maxAge=Math.max(...rows.map((r:any)=>ageMinutes(r.observed_at))),prices=rows.map((r:any)=>Number(r.price)).filter(Number.isFinite);return{available:true,cached:true,cache_age_minutes:Math.round(maxAge*10)/10,cache_ttl_minutes:CACHE_MINUTES,quantity:rows.reduce((n:number,r:any)=>n+Number(r.quantity||0),0),listing_count:rows.every((r:any)=>r.listing_count!=null)?rows.reduce((n:number,r:any)=>n+Number(r.listing_count||0),0):null,lowest_price:prices.length?Math.min(...prices):null,observed_at:rows.reduce((a:any,r:any)=>!a||Date.parse(r.observed_at)<Date.parse(a)?r.observed_at:a,null),rows};}
async function syncManaPool(target:any){const productId=text(target?.product_id),skuId=text(target?.sku_id);try{const r=await fetch(`${U}/functions/v1/manapool-supply-sync`,{method:'POST',headers:sh(),body:JSON.stringify({product_id:productId,sku_id:skuId,known_identity:{scryfall_id:target?.scryfall_id||null,set_code:target?.set_code||null,collector_number:target?.collector_number||null,printing:target?.printing||null,condition:target?.condition||null}})});const raw=await r.text();let d:any=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)return{ok:false,status:r.status,error:text(d?.error||raw).slice(0,300)};const latest=await latestManaPool(skuId);return{ok:true,cached:false,...(latest||{}),sync:d};}catch(e:any){return{ok:false,error:String(e?.message||e).slice(0,300)}}}

function finish(v:any){const s=text(v).toUpperCase().replace(/[^A-Z]/g,'');return s.includes('FOIL')&&!s.includes('NONFOIL')?'foil':'nonfoil'}
function printingIdentity(t:any){return text(t?.scryfall_id)?`${text(t.scryfall_id).toLowerCase()}|${finish(t?.printing)}`:`${text(t?.set_code).toUpperCase()}|${text(t?.collector_number).toLowerCase()}|${finish(t?.printing)}`}
function freshness(observedAt:any,freshHours:number,expiredHours:number){const hours=ageMinutes(observedAt)/60;return hours<=freshHours?'FRESH':hours<=expiredHours?'STALE':'EXPIRED'}
async function cardKingdomFamily(targets:any[]){
  let scoped=targets;if(targets.some((t:any)=>!text(t.scryfall_id))){const ids=uniq(targets.map((t:any)=>t.sku_id)),catalog=await rest(`scout_card_catalog?sku_id=in.(${ids.join(',')})&select=sku_id,scryfall_id,printing`).catch(()=>[]),bySku=new Map((catalog||[]).map((x:any)=>[text(x.sku_id),x]));scoped=targets.map((t:any)=>({...bySku.get(text(t.sku_id)),...t,scryfall_id:text(t.scryfall_id)||bySku.get(text(t.sku_id))?.scryfall_id||null,printing:text(t.printing)||bySku.get(text(t.sku_id))?.printing||null}));}
  const expected=uniq(scoped.map((t:any)=>t.scryfall_id&&`${text(t.scryfall_id).toLowerCase()}|${finish(t.printing)}`)),scryfallIds=uniq(scoped.map((t:any)=>text(t.scryfall_id).toLowerCase()));if(!expected.length||!scryfallIds.length)return{available:false,quantity:0,nm_quantity:0,lp_quantity:0,listing_count:0,mapped_identity_count:0,expected_identity_count:expected.length,mapping_coverage_pct:0,freshness_status:'MISSING',usable_for_market_claim:false,note:'No Scryfall printing identities were available for Card Kingdom mapping.'};
  const identities=await rest(`vendor_item_identities?source=eq.cardkingdom&scryfall_id=in.(${scryfallIds.join(',')})&select=source_item_key,scryfall_id,finish,language`).catch(()=>[]),mapped=(identities||[]).filter((x:any)=>['','EN','ENGLISH'].includes(text(x.language).toUpperCase())&&expected.includes(`${text(x.scryfall_id).toLowerCase()}|${finish(x.finish)}`)),keys=uniq(mapped.map((x:any)=>x.source_item_key));if(!keys.length)return{available:false,quantity:0,nm_quantity:0,lp_quantity:0,listing_count:0,mapped_identity_count:0,expected_identity_count:expected.length,mapping_coverage_pct:0,freshness_status:'MISSING',usable_for_market_claim:false,note:'No English Card Kingdom printing/finish identities matched the family.'};
  const rows=await rest(`vendor_depth_current?source=eq.cardkingdom&lane=eq.retail_supply&source_item_key=in.(${keys.map(encodeURIComponent).join(',')})&select=source_item_key,quantity,listing_count,price,condition,finish,language,measurement_scope,count_quality,observed_at`).catch(()=>[]),eligible=(rows||[]).filter((r:any)=>['NM','EX'].includes(text(r.condition).toUpperCase())&&['','EN','ENGLISH'].includes(text(r.language).toUpperCase())),observedAt=eligible.reduce((a:any,r:any)=>!a||Date.parse(r.observed_at)<Date.parse(a)?r.observed_at:a,null),status=observedAt?freshness(observedAt,36,72):'MISSING',mappedKeys=new Set(mapped.map((x:any)=>`${text(x.scryfall_id).toLowerCase()}|${finish(x.finish)}`)),coverage=expected.length?mappedKeys.size/expected.length:0,exact=eligible.every((r:any)=>['exact','aggregate'].includes(text(r.count_quality).toLowerCase()));
  return{available:eligible.length>0,quantity:eligible.reduce((n:number,r:any)=>n+Number(r.quantity||0),0),nm_quantity:eligible.filter((r:any)=>text(r.condition).toUpperCase()==='NM').reduce((n:number,r:any)=>n+Number(r.quantity||0),0),lp_quantity:eligible.filter((r:any)=>text(r.condition).toUpperCase()==='EX').reduce((n:number,r:any)=>n+Number(r.quantity||0),0),listing_count:eligible.every((r:any)=>r.listing_count!=null)?eligible.reduce((n:number,r:any)=>n+Number(r.listing_count||0),0):null,mapped_identity_count:mappedKeys.size,expected_identity_count:expected.length,mapping_coverage_pct:Math.round(coverage*1000)/10,observed_at:observedAt,freshness_status:status,count_quality:exact?'exact_or_aggregate':'mixed',usable_for_market_claim:status==='FRESH'&&coverage>=.75&&exact,condition_mapping:{NM:'NEAR MINT',EX:'LIGHTLY PLAYED'},rows:eligible,note:'Card Kingdom EX is treated as the LP analogue. VG/G and buylist demand are excluded.'};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return js({error:'POST required'},405);if(!S)return js({error:'Service role unavailable'},500);if(!(await authorized(req)))return js({error:'Signed-in user required'},401);const body=await req.json().catch(()=>({})),force=body?.force_refresh===true,requestedScope=text(body?.scope||'EXACT_SKU').toUpperCase();const rawTargets=Array.isArray(body?.targets)?body.targets:[{product_id:body?.product_id||body?.productId,sku_id:body?.sku_id||body?.skuId,condition:body?.condition}];const targets=rawTargets.map((x:any)=>({...x,product_id:text(x?.product_id||x?.productId),sku_id:text(x?.sku_id||x?.skuId),condition:condition(x?.condition)})).filter((x:any)=>/^\d+$/.test(x.product_id)&&/^\d+$/.test(x.sku_id));if(!targets.length)return js({error:'at least one numeric product_id and sku_id target is required'},400);const identityCount=new Set(targets.map(printingIdentity)).size;if(requestedScope==='CARD_FAMILY_NM_LP'&&identityCount>10)return js({error:'Large card families require a bounded printing cohort or explicit set scope.',reason:'SUPPLY_SCOPE_REQUIRED',printing_identity_count:identityCount,maximum_automatic_printing_identities:10,allowed_scopes:['PRINTING_COHORT_NM_LP','EXACT_SKU']},422);if(targets.length>80)return js({error:'at most 80 exact-SKU targets per request'},400);
  const skuIds=uniq(targets.map((x:any)=>x.sku_id)),productIds=uniq(targets.map((x:any)=>x.product_id)),maxPages=Math.max(1,Math.min(Number(body?.max_pages||40)||40,80));
  const [cachedTcg,shared,mpBefore]=await Promise.all([currentTcg(skuIds),rest('rpc/ask_collectish_public_internal_sku_evidence_v1',{method:'POST',body:{p_sku_ids:skuIds}}).catch(()=>[]),mapLimit(targets,8,t=>latestManaPool(t.sku_id))]);
  const evidence=new Map((shared||[]).map((x:any)=>[text(x?.sku_id),x]));
  const refreshProducts=new Set<string>();for(const p of productIds){const group=targets.filter((t:any)=>t.product_id===p);if(force||group.some((t:any)=>!fresh(cachedTcg.get(t.sku_id))))refreshProducts.add(p);}
  const fetched=new Map<string,any>(await Promise.all([...refreshProducts].map(async productId=>[productId,await fetchProductListings(productId,maxPages)] as [string,any])));
  const rowsToInsert:any[]=[],snapshots=new Map<string,any>();
  for(const target of targets){const productId=target.product_id,skuId=target.sku_id;if(!refreshProducts.has(productId)){snapshots.set(skuId,cachedTcg.get(skuId));continue;}const {listings,sourceTotal,pages,coverage}=fetched.get(productId),exact=listings.filter((x:any)=>exactSku(x,skuId)&&Number(x?.quantity||0)>0),sellerKeys=uniq(exact.map((x:any)=>x?.sellerKey||x?.sellerId)),direct=exact.filter((x:any)=>x?.directListing===true),nonDirect=exact.filter((x:any)=>x?.directListing!==true),directSellerKeys=uniq(direct.map((x:any)=>x?.sellerKey||x?.sellerId)),nonDirectSellerKeys=uniq(nonDirect.map((x:any)=>x?.sellerKey||x?.sellerId)),sum=(xs:any[])=>xs.reduce((n,x)=>n+Math.max(0,Number(x?.quantity||0)||0),0),prices=exact.map((x:any)=>money(x?.price)).filter((x:any)=>x!=null).sort((a:number,b:number)=>a-b),ship=exact.map((x:any)=>{const p=money(x?.price),s=money(x?.shippingPrice);return p==null?null:p+(s||0)}).filter((x:any)=>x!=null).sort((a:number,b:number)=>a-b),e=evidence.get(skuId)||{};const row={source:'tcgplayer_marketplace',product_id:productId,sku_id:skuId,observed_at:new Date().toISOString(),coverage_state:coverage,listing_count:exact.length,seller_count:sellerKeys.length,unit_count:sum(exact),direct_listing_count:direct.length,direct_seller_count:directSellerKeys.length,direct_unit_count:sum(direct),non_direct_listing_count:nonDirect.length,non_direct_seller_count:nonDirectSellerKeys.length,non_direct_unit_count:sum(nonDirect),custom_listing_count:exact.filter((x:any)=>text(x?.listingType).toLowerCase()==='custom').length,lowest_price:prices[0]??null,lowest_price_with_shipping:ship[0]??null,source_query_total_results:sourceTotal,pages_fetched:pages,source_method:'tcgplayer_site_listings_search',metadata:{card_name:target.card_name||null,set_code:target.set_code||null,collector_number:target.collector_number||null,condition:target.condition||null,language:target.language||'ENGLISH',printing:target.printing||null,query_rows_fetched:listings.length,exact_sku_rows:exact.length,seller_keys:sellerKeys,direct_seller_keys:directSellerKeys,non_direct_seller_keys:nonDirectSellerKeys,collectish_direct_available:e?.direct_available??null,collectish_direct_listings:e?.direct_listings??null,family_scope:body?.scope||'EXACT_SKU',cache_ttl_minutes:CACHE_MINUTES,methodology:'TCGplayer.com listings search; live channel-0 listings; exact productConditionId/SKU; banned/suspended channel exclusions applied.'}};rowsToInsert.push(row);snapshots.set(skuId,row);}
  if(rowsToInsert.length){const inserted=await rest('market_supply_snapshots',{method:'POST',prefer:'return=representation',body:rowsToInsert});for(const r of inserted||[])snapshots.set(text(r.sku_id),r);}
  const mpResults=await mapLimit(targets,4,async(t,i)=>{const before=mpBefore[i];if(!force&&before&&Number(before.cache_age_minutes)<CACHE_MINUTES)return{...before,cached:true};return syncManaPool(t);});
  const detail=targets.map((t:any,i)=>{const r=snapshots.get(t.sku_id)||{},m=mpResults[i]||null;return{product_id:t.product_id,sku_id:t.sku_id,card_name:t.card_name||r?.metadata?.card_name||null,set_code:t.set_code||r?.metadata?.set_code||null,collector_number:t.collector_number||r?.metadata?.collector_number||null,printing:t.printing||r?.metadata?.printing||null,condition:t.condition||r?.metadata?.condition||null,language:t.language||r?.metadata?.language||'ENGLISH',coverage_state:r.coverage_state||'MISSING',observed_at:r.observed_at||null,cache_hit:!refreshProducts.has(t.product_id),listing_count:Number(r.listing_count||0),unit_count:Number(r.unit_count||0),seller_count:Number(r.seller_count||0),direct_listing_count:Number(r.direct_listing_count||0),direct_unit_count:Number(r.direct_unit_count||0),non_direct_listing_count:Number(r.non_direct_listing_count||0),non_direct_unit_count:Number(r.non_direct_unit_count||0),classification:r.coverage_state==='COMPLETE'?depth(Number(r.unit_count||0),Number(r.seller_count||0)):'UNPROVEN',manapool:m};});
  const aggregate=(wanted:string|null)=>{const xs=detail.filter((x:any)=>!wanted||x.condition===wanted),rows=xs.map((x:any)=>snapshots.get(x.sku_id)).filter(Boolean),allKeys=rows.every((r:any)=>Array.isArray(r?.metadata?.seller_keys)),sellerKeys=allKeys?uniq(rows.flatMap((r:any)=>r.metadata.seller_keys)):[],sellerLowerBound=rows.length?Math.max(...rows.map((r:any)=>Number(r.seller_count||0))):0,sellers=allKeys?sellerKeys.length:sellerLowerBound,units=xs.reduce((n:number,x:any)=>n+x.unit_count,0);return{sku_count:xs.length,listing_count:xs.reduce((n:number,x:any)=>n+x.listing_count,0),unit_count:units,unique_seller_count:allKeys?sellerKeys.length:null,seller_lower_bound:sellerLowerBound,seller_count_quality:allKeys?'deduplicated_exact':'conservative_lower_bound',direct_listing_count:xs.reduce((n:number,x:any)=>n+x.direct_listing_count,0),direct_unit_count:xs.reduce((n:number,x:any)=>n+x.direct_unit_count,0),non_direct_listing_count:xs.reduce((n:number,x:any)=>n+x.non_direct_listing_count,0),non_direct_unit_count:xs.reduce((n:number,x:any)=>n+x.non_direct_unit_count,0),classification:depth(units,sellers),manapool_retail_quantity:xs.reduce((n:number,x:any)=>n+Number(x.manapool?.quantity||0),0)};};
  const complete=detail.filter((x:any)=>x.coverage_state==='COMPLETE').length,combined=aggregate(null),tcgHits=detail.filter((x:any)=>x.cache_hit).length,mpHits=mpResults.filter((x:any)=>x?.cached===true).length,cache={ttl_minutes:CACHE_MINUTES,force_refresh:force,tcgplayer:{hits:tcgHits,misses:detail.length-tcgHits,refreshed_products:refreshProducts.size},manapool:{hits:mpHits,misses:mpResults.length-mpHits}};
  if(targets.length===1)return js({ok:true,cached:tcgHits===1&&mpHits===1,cache,snapshot:snapshots.get(targets[0].sku_id)||null,identity:detail[0],manapool:mpResults[0]||null});
  const tcgOldestAt=detail.reduce((a:any,r:any)=>!r.observed_at?a:!a||Date.parse(r.observed_at)<Date.parse(a)?r.observed_at:a,null),tcgAgeMinutes=ageMinutes(tcgOldestAt),tcgComplete=complete===targets.length,tcgFresh=tcgComplete&&tcgAgeMinutes<=CACHE_MINUTES;
  const ck=await cardKingdomFamily(targets),tcgClassification=tcgComplete?combined.classification:'UNPROVEN',mpCoverage=manaPoolCoverage(mpResults,targets.length),market=classifyFamilySupply({tcgClassification,tcgComplete,tcgFresh,cardKingdom:ck,manaPoolRows:mpResults,expectedSkuCount:targets.length}),cohort=requestedScope==='PRINTING_COHORT_NM_LP',classification=market.global_supply_classification;
  const sourceDepth={tcgplayer:{...combined,coverage_state:tcgComplete?'COMPLETE':'PARTIAL',observed_at:tcgOldestAt,age_minutes:Number.isFinite(tcgAgeMinutes)?Math.round(tcgAgeMinutes*10)/10:null,freshness_status:tcgFresh?'FRESH':tcgComplete?'STALE':'INCOMPLETE',confidence:tcgFresh?'HIGH':'LOW',usable_for_market_claim:tcgFresh},manapool_retail:{quantity:combined.manapool_retail_quantity,covered_sku_count:mpResults.filter((x:any)=>x?.available).length,fresh_sku_count:mpCoverage.usable.length,expected_sku_count:targets.length,coverage_ratio:mpCoverage.coverage_ratio,mapping_coverage_pct:mpCoverage.coverage_pct,oldest_age_minutes:mpCoverage.oldest_age_minutes,freshness_status:mpCoverage.usable.length===targets.length?'FRESH':mpCoverage.usable.length?'PARTIAL':'MISSING',confidence:mpCoverage.adequate?'HIGH':mpCoverage.usable.length?'LOW':'UNPROVEN',usable_for_market_claim:mpCoverage.adequate,outcome_counts:counts(mpResults.map(manaPoolOutcome))},cardkingdom_retail:{...ck,confidence:ck.usable_for_market_claim?'HIGH':ck.available?'LOW':'UNPROVEN'}};
  return js({ok:true,scope:cohort?'PRINTING_COHORT_NM_LP':'CARD_FAMILY_NM_LP',supply_scope:cohort?'BOUNDED_PRINTING_COHORT_NM_LP':market.retailer_sources_usable>0?'MULTI_SOURCE_CARD_FAMILY_NM_LP':'TCGPLAYER_CARD_FAMILY_NM_LP',conditions:['NEAR MINT','LIGHTLY PLAYED'],language:'ENGLISH',source_method:'tcgplayer_site_listings_search',cache,coverage:{target_sku_count:targets.length,complete_sku_count:complete,product_count:productIds.length,printing_identity_count:identityCount,state:tcgComplete?'COMPLETE':'PARTIAL'},classification,cohort_supply_classification:cohort?classification:null,global_supply_classification:cohort?'UNPROVEN':classification,tcgplayer_supply_classification:tcgClassification,...market,...(cohort?{global_supply_classification:'UNPROVEN',market_wide_thinness_proven:false,claim_basis:'BOUNDED_PRINTING_COHORT'}:{}),source_depth:sourceDepth,freshness_policy:{tcgplayer_cache_minutes:CACHE_MINUTES,manapool_fresh_hours:2,manapool_minimum_sku_coverage_pct:75,cardkingdom_fresh_hours:36,cardkingdom_expired_hours:72},combined,nm:aggregate('NEAR MINT'),lp:aggregate('LIGHTLY PLAYED'),exact_skus:detail,note:cohort?'English NM/LP depth for a bounded printing cohort. This cohort must not be described as total card-family or market-wide supply. Source inventories are reported independently and are never summed across venues. Direct is a subset of TCGplayer.':'English NM/LP family depth. A market-wide classification requires complete TCGplayer family coverage plus adequate retailer corroboration. Source inventories are reported independently and are never summed across venues. Card Kingdom EX is the LP analogue; VG/G and buylist demand are excluded. Direct is a subset of TCGplayer, never additive.'});
});
