import { rest } from '../../core/rest.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const age=d=>{if(!d)return'—';const ms=Math.max(0,Date.now()-new Date(d).getTime()),m=Math.round(ms/6e4);if(m<60)return m<=1?'just now':`${m}m ago`;const h=Math.round(m/60);return h<24?`${h}h ago`:`${Math.round(h/24)}d ago`};
let loading=false,loadedAt=0,last=null;

function ensure(){const page=document.getElementById('cxSealed');if(!page)return null;let box=document.getElementById('cxCt0Summary');if(!box){box=document.createElement('div');box.id='cxCt0Summary';box.className='cx-card cx-ct0-summary';const toolbar=page.querySelector('.cx-sealed-toolbar');if(toolbar)toolbar.before(box);else page.querySelector('.cx-page-head')?.after(box)}return box}
function render(data){const box=ensure();if(!box)return;const {rows,opps,strong,tight,stocked,lastCaptured,shadowChanges}=data;box.innerHTML=`<div class="cx-section-title">CardTrader Zero</div><div class="cx-sealed-grid"><div class="cx-sealed-stat"><span>CT0 opportunities</span><strong>${opps}</strong><small>${strong} strong · ≥10% landed spread</small></div><div class="cx-sealed-stat"><span>CT0 stocked</span><strong>${stocked}</strong><small>${rows} mapped observations</small></div><div class="cx-sealed-stat"><span>Supply tightening</span><strong>${tight}</strong><small>${tight?'trend-confirmed candidates':'history building / stable'}</small></div><div class="cx-sealed-stat"><span>Shadow grade moves</span><strong>${shadowChanges}</strong><small>official Scout grades unchanged</small></div></div><div class="cx-sealed-summary"><strong>CT0 feed:</strong> updated ${esc(age(lastCaptured))}. <button type="button" class="cx-refresh" data-ct0-view>View opportunities</button></div>`;box.querySelector('[data-ct0-view]')?.addEventListener('click',()=>{const s=document.getElementById('cxSealedFilter');if(!s)return;s.value='ct0opps';s.dispatchEvent(new Event('change',{bubbles:true}));s.scrollIntoView({behavior:'smooth',block:'center'})})}
async function load(force=false){if(loading)return;if(!force&&last&&Date.now()-loadedAt<60000){render(last);return}loading=true;try{const rows=await rest('sealed_product_price_current?select=captured_at,raw_json&source=eq.cardtrader&limit=1000').catch(()=>[]);const xs=rows||[],opps=xs.filter(x=>x.raw_json?.ct_zero_opportunity?.eligible===true).length,strong=xs.filter(x=>x.raw_json?.ct_zero_opportunity?.tier==='strong').length,tight=xs.filter(x=>['tightening','strong_tightening'].includes(x.raw_json?.ct_zero_trend?.signal)).length,stocked=xs.filter(x=>Number(x.raw_json?.ct_zero?.quantity||0)>0).length,shadowChanges=xs.filter(x=>{const s=x.raw_json?.ct_zero_shadow_score;return s?.official_grade&&s?.shadow_grade&&s.official_grade!==s.shadow_grade}).length,lastCaptured=xs.map(x=>x.captured_at).filter(Boolean).sort().at(-1)||null;last={rows:xs.length,opps,strong,tight,stocked,lastCaptured,shadowChanges};loadedAt=Date.now();render(last)}finally{loading=false}}
document.addEventListener('collectish:sealed-rendered',()=>{load().catch(()=>{})});window.addEventListener('focus',()=>{if(Date.now()-loadedAt>60000)load(true).catch(()=>{})});
