import { rest } from '../../core/rest.js';

let installed=false,seq=0;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const pct=n=>n==null||!Number.isFinite(Number(n))?'—':`${Number(n).toFixed(1)}%`;
const num=n=>n==null||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString();

function style(){if(document.getElementById('cxInventoryFitStyle'))return;const s=document.createElement('style');s.id='cxInventoryFitStyle';s.textContent=`
.cx-inventory-fit{margin:16px 0;padding:14px;border:1px solid var(--cx-border,#2a3441);border-radius:14px;background:var(--cx-card,#151b22)}.cx-inventory-fit-head{display:flex;align-items:start;justify-content:space-between;gap:12px}.cx-inventory-fit h4{margin:0;font-size:15px}.cx-inventory-fit-sub{margin:4px 0 10px;font-size:11px;opacity:.7}.cx-fit-labels{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.cx-fit-label{padding:4px 7px;border-radius:999px;background:rgba(90,162,255,.12);border:1px solid rgba(90,162,255,.3);font-size:9px;font-weight:800}.cx-fit-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.cx-fit-stat{padding:9px;border:1px solid var(--cx-border,#2a3441);border-radius:10px}.cx-fit-stat span{display:block;font-size:9px;text-transform:uppercase;opacity:.62}.cx-fit-stat b{display:block;font-size:15px;margin-top:2px}.cx-fit-stat small{display:block;font-size:9px;opacity:.64;margin-top:2px;line-height:1.25}.cx-fit-sections{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.cx-fit-section{border:1px solid var(--cx-border,#2a3441);border-radius:10px;overflow:hidden}.cx-fit-section h5{margin:0;padding:8px 10px;font-size:11px;border-bottom:1px solid var(--cx-border,#2a3441)}.cx-fit-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:7px 10px;border-bottom:1px solid var(--cx-border,#2a3441);font-size:10px}.cx-fit-row:last-child{border-bottom:0}.cx-fit-row b{white-space:nowrap}.cx-fit-row small{display:block;opacity:.62;margin-top:2px}.cx-fit-note{font-size:9px;opacity:.64;line-height:1.4;margin:9px 0 0}.cx-fit-coverage-warn{color:#8a5b00}@media(max-width:760px){.cx-fit-grid{grid-template-columns:1fr 1fr}.cx-fit-sections{grid-template-columns:1fr}.cx-inventory-fit-head{display:block}.cx-fit-labels{justify-content:flex-start;margin-top:8px}}
`;document.head.appendChild(s)}
function stat(label,value,sub=''){return `<div class="cx-fit-stat"><span>${esc(label)}</span><b>${value}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function valueRows(rows){return (rows||[]).slice(0,6).map(r=>`<div class="cx-fit-row"><div><strong>${esc(r.name)}</strong><small>${esc(r.set_code)} #${esc(r.collector_number)} · ${esc(r.finish)} · Direct ${r.direct_available==null?'unresolved':num(r.direct_available)}${r.syp_eligible?' · SYP':''}</small></div><b>${money(r.practical_value)} · ${pct(r.share_pct)}</b></div>`).join('')}
function growthRows(rows){return (rows||[]).slice(0,6).map(r=>`<div class="cx-fit-row"><div><strong>${esc(r.name)}</strong><small>${money(r.market_90d)} → ${money(r.market_now)}</small></div><b>${Number(r.growth_dollars)>=0?'+':''}${money(r.growth_dollars)} · ${Number(r.growth_pct)>=0?'+':''}${pct(r.growth_pct)}</b></div>`).join('')}

async function render(event){const run=++seq,id=event?.detail?.id;if(!id)return;const detail=document.getElementById('cxSealedDetail');if(!detail)return;detail.querySelector('.cx-inventory-fit')?.remove();try{const p=await rest('rpc/ask_sealed_inventory_fit_v1',{method:'POST',body:{p_sealed_uuid:id}});if(run!==seq||!p?.summary?.content_lines)return;const m=p.summary,labels=(p.classifications||[]).map(x=>`<span class="cx-fit-label">${esc(x)}</span>`).join('');const lowIdentity=Number(m.identity_coverage_pct)<70,lowDirect=Number(m.direct_observation_coverage_pct)<70;const growth=(p.top_growth_cards||[]).length?growthRows(p.top_growth_cards):`<div class="cx-fit-row"><div><strong>Not enough matched history yet</strong><small>${num(m.growth_history_cards)} of ${num(m.cards_2_plus)} current $2+ contents have a valid 90-day baseline.</small></div></div>`;const html=`<section class="cx-inventory-fit" data-no-detail-swipe><div class="cx-inventory-fit-head"><div><h4>Inventory Fit</h4><p class="cx-inventory-fit-sub">Value concentration, Direct depth, SYP gaps, and 90-day component momentum.</p></div><div class="cx-fit-labels">${labels}</div></div><div class="cx-fit-grid">${stat('Value concentration',pct(m.top_10_share_pct),`Top 10 · ${num(m.cards_to_50_pct)} cards make 50%`)}${stat('Direct observed',`${num(m.direct_observed)} / ${num(m.content_lines)}`,`${num(m.direct_in_stock)} in stock · ${num(m.direct_depth_10)} have 10+ copies`)}${stat('SYP fit',num(m.syp_listed),`${num(m.syp_no_direct)} confirmed no Direct · ${num(m.syp_direct_unobserved)} not observed`)}${stat('$2+ contents',num(m.cards_2_plus),`${num(m.cards_5_plus)} at $5+ · ${num(m.cards_10_plus)} at $10+`)}</div><div class="cx-fit-sections"><div class="cx-fit-section"><h5>Largest practical value contributors</h5>${valueRows(p.top_value_cards)}</div><div class="cx-fit-section"><h5>Largest 3-month movers</h5>${growth}</div></div><p class="cx-fit-note ${lowIdentity||lowDirect?'cx-fit-coverage-warn':''}">Exact-SKU identity: ${num(m.resolved_skus)} of ${num(m.content_lines)} (${pct(m.identity_coverage_pct)}). Direct inventory observed: ${num(m.direct_observed)} (${pct(m.direct_observation_coverage_pct)}). Growth baselines: ${num(m.growth_history_cards)} of ${num(m.cards_2_plus)} current $2+ contents. Missing Direct/history observations are excluded—not treated as zero.</p></section>`;const source=detail.querySelector('.cx-source-compare'),out=detail.querySelector('.cx-out-opt'),econ=detail.querySelector('.cx-section-title.cx-sealed-econ-title');if(source)source.insertAdjacentHTML('afterend',html);else if(out)out.insertAdjacentHTML('beforebegin',html);else if(econ)econ.insertAdjacentHTML('beforebegin',html);else detail.insertAdjacentHTML('beforeend',html)}catch(e){console.warn('[sealed inventory fit]',e)}}

export function installInventoryFit(){if(installed)return;installed=true;style();document.addEventListener('collectish:sealed-detail-rendered',render)}
