import { rest } from '../../core/rest.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
const pct=n=>n==null||!Number.isFinite(Number(n))?'—':`${(Number(n)*100).toFixed(0)}%`;
const primaryCategories=new Set(['booster_box','booster_pack','bundle','limited_aid_tool','box_set']);

function style(){if(document.getElementById('cxSealedFamilyStyle'))return;const s=document.createElement('style');s.id='cxSealedFamilyStyle';s.textContent=`
.cx-sealed-family{margin:0 0 12px;border:1px solid var(--color-border);border-radius:12px;background:var(--color-bg-surface);overflow:hidden}.cx-sealed-family-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:10px 12px;border-bottom:1px solid var(--color-border)}.cx-sealed-family-head strong{font-size:12px}.cx-sealed-family-head span{display:block;font-size:8px;color:var(--color-text-secondary);margin-top:2px}.cx-sealed-family-head button{font-size:8px;border:1px solid var(--color-border);background:var(--color-bg-primary);border-radius:999px;padding:4px 7px;color:var(--color-text-secondary)}.cx-sealed-family-scroll{overflow:auto}.cx-sealed-family-table{width:100%;border-collapse:collapse;min-width:820px;font-size:8px}.cx-sealed-family-table th,.cx-sealed-family-table td{padding:6px 7px;border-top:1px solid var(--color-border);text-align:right;white-space:nowrap}.cx-sealed-family-table th{font-size:7px;text-transform:uppercase;letter-spacing:.04em;color:var(--color-text-secondary)}.cx-sealed-family-table th:first-child,.cx-sealed-family-table td:first-child{text-align:left;white-space:normal;min-width:200px}.cx-sealed-family-name b{display:block;font-size:9px}.cx-sealed-family-name small{font-size:7px;color:var(--color-text-secondary)}.cx-sealed-family-action{font-size:7px;font-weight:900;border:1px solid var(--color-border);border-radius:999px;padding:3px 6px}.cx-sealed-family-action.positive{color:var(--color-accent)}.cx-sealed-family-note{padding:7px 12px;font-size:7.5px;color:var(--color-text-secondary);border-top:1px solid var(--color-border)}
@media(max-width:700px){.cx-sealed-family{border-radius:10px}.cx-sealed-family-head{padding:9px}.cx-sealed-family-note{padding:7px 9px}}
`;document.head.appendChild(s)}

function action(r){const market=Number(r.sealed_market_price),gross=Number(r.crack_gross_mean_ev),net=Number(r.crack_net_mean_ev);if(!(market>0))return[r.crack_value_complete?'VALUE MODELED':'PRICE PENDING',''];if(r.crack_value_basis==='not_modeled')return['MODEL PENDING',''];if(r.crack_value_basis==='modeled_components'&&!r.crack_value_complete)return['COMPONENT FLOOR',''];if(Number.isFinite(net)&&net>=market*1.10)return['BUY & CRACK','positive'];if(Number.isFinite(net)&&net>=market)return['MARGINAL CRACK','positive'];if(Number.isFinite(gross)&&gross>market)return['GROSS EV ONLY',''];return['KEEP SEALED',''];}
function basis(r){if(r.crack_value_basis==='direct_backtest')return 'full distribution';if(r.crack_value_basis==='modeled_components'){const d=Number(r.deterministic_deck_components||0),u=Number(r.unresolved_pack_components||0)+Number(r.unresolved_other_components||0)+Number(r.unresolved_deck_components||0);return r.crack_value_complete?`${d?'exact MTGJSON components':'modeled components'}`:`component floor · ${u} extras pending`;}return r.model_status?.replaceAll('_',' ')||'pending';}

let showAll=false,loading=false;
async function render(){if(loading)return;const host=document.getElementById('cxSealed');if(!host)return;loading=true;try{
  const rows=await rest('sealed_product_family_economics?select=sealed_uuid,product_name,category,subtype,release_date,sealed_market_price,sealed_low_price,crack_gross_mean_ev,crack_gross_median_ev,crack_p10_ev,crack_p90_ev,crack_net_mean_ev,crack_break_even_probability,crack_net_break_even_probability,crack_value_basis,crack_value_complete,model_status,modeled_child_components,unmodeled_child_components,deterministic_deck_components,deterministic_tcg_market_ev,deterministic_ck_buylist_ev,unresolved_deck_components,unresolved_pack_components,unresolved_other_components&set_code=eq.HOB&order=category.asc,product_name.asc');
  let box=document.getElementById('cxSealedFamily');if(!box){box=document.createElement('section');box.id='cxSealedFamily';box.className='cx-sealed-family';const toolbar=host.querySelector('.cx-sealed-toolbar');if(toolbar)host.insertBefore(box,toolbar);else host.appendChild(box)}
  const all=rows||[],visible=all.filter(r=>showAll||primaryCategories.has(r.category));
  box.innerHTML=`<div class="cx-sealed-family-head"><div><strong>The Hobbit · sealed product family</strong><span>${all.length} MTGJSON products · ${all.filter(x=>x.crack_value_basis==='direct_backtest').length} distribution models · exact deterministic decks layered where MTGJSON provides them</span></div><button type="button" id="cxSealedFamilyToggle">${showAll?'Primary retail only':'Show cases / decks'}</button></div><div class="cx-sealed-family-scroll"><table class="cx-sealed-family-table"><thead><tr><th>Product</th><th>Sealed market</th><th>Gross crack EV</th><th>Median</th><th>Net / realizable</th><th>CK floor</th><th>Gross BE</th><th>Net BE</th><th>Action</th></tr></thead><tbody>${visible.map(r=>{const [a,cls]=action(r);return `<tr><td class="cx-sealed-family-name"><b>${esc(r.product_name)}</b><small>${esc(r.subtype||r.category)} · ${esc(basis(r))}</small></td><td>${money(r.sealed_market_price)}</td><td>${money(r.crack_gross_mean_ev)}</td><td>${money(r.crack_gross_median_ev)}</td><td>${money(r.crack_net_mean_ev)}</td><td>${money(r.deterministic_ck_buylist_ev)}</td><td>${pct(r.crack_break_even_probability)}</td><td>${pct(r.crack_net_break_even_probability)}</td><td><span class="cx-sealed-family-action ${cls}">${a}</span></td></tr>`}).join('')}</tbody></table></div><div class="cx-sealed-family-note">Distribution models use probabilistic collation. Component floors now include modeled child sealed products plus exact MTGJSON deck contents (for example Bundle lands). Products with unresolved promo packs, scene cards or accessories remain ungraded until those components are identified or modeled.</div>`;
  box.querySelector('#cxSealedFamilyToggle')?.addEventListener('click',()=>{showAll=!showAll;void render()});
}catch(e){console.warn('sealed family load failed',e)}finally{loading=false}}

export function install(){style();document.addEventListener('collectish:sealed-rendered',()=>void render());if(document.getElementById('cxSealed'))void render()}
