import { registerComponent } from '../../core/lifecycle.js';
import { rest } from '../../core/rest.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
const when=d=>{if(!d)return'—';const ms=Math.max(0,Date.now()-new Date(d).getTime()),h=Math.round(ms/36e5);return h<24?`${Math.max(1,h)}h ago`:`${Math.round(h/24)}d ago`};
let seq=0;

function ensureStyle(){if(document.getElementById('cxProductHistoryStyle'))return;const s=document.createElement('style');s.id='cxProductHistoryStyle';s.textContent='.cx-product-history{margin-top:16px;padding:14px;border:1px solid var(--cx-border,#2a2f3a);border-radius:12px}.cx-product-history h3{margin:0 0 4px}.cx-product-history-note{opacity:.72;font-size:12px;margin-bottom:10px}.cx-product-history-list{display:grid;gap:8px}.cx-product-history-row{display:grid;grid-template-columns:auto 1fr;gap:10px;align-items:start;padding:9px 0;border-top:1px solid color-mix(in srgb,currentColor 12%,transparent)}.cx-product-history-row:first-child{border-top:0}.cx-product-history-dot{width:8px;height:8px;border-radius:999px;margin-top:7px;background:currentColor;opacity:.7}.cx-product-history-row[data-kind="video_signal"] .cx-product-history-dot{opacity:1}.cx-product-history-main{min-width:0}.cx-product-history-head{display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}.cx-product-history-head strong{font-size:13px}.cx-product-history-head small{opacity:.65}.cx-product-history-body{font-size:13px;margin-top:2px}.cx-product-history-meta{font-size:11px;opacity:.68;margin-top:3px}.cx-product-history-link{color:inherit;text-decoration:underline;text-underline-offset:2px}.cx-product-history-empty{opacity:.7;font-size:13px}';document.head.appendChild(s)}

function compact(rows=[]){const out=[],seen=new Set();for(const r of rows){if(r.kind==='video_signal'){out.push(r);continue}const d=r.detail||{},key=`${r.source}|${r.kind}|${r.new_value??''}|${d.low_price??''}|${d.total_listings??''}`;if(seen.has(key))continue;seen.add(key);out.push(r)}return out.slice(0,10)}
function rowHtml(r){const d=r.detail||{},isSignal=r.kind==='video_signal';const head=isSignal?(r.source||'Signal'):(r.source||'Market');const body=isSignal?(r.summary||r.evidence||r.title||r.event_type):`${r.new_value!=null?`Market ${money(r.new_value)}`:''}${d.low_price!=null?`${r.new_value!=null?' · ':''}Low ${money(d.low_price)}`:''}${d.total_listings!=null?` · ${d.total_listings} listings`:''}`;const meta=[isSignal?r.event_type:null,isSignal?r.direction:null,isSignal?r.signal_stage:null,when(r.event_at)].filter(Boolean).join(' · ');return `<div class="cx-product-history-row" data-kind="${esc(r.kind)}"><span class="cx-product-history-dot"></span><div class="cx-product-history-main"><div class="cx-product-history-head"><strong>${esc(head)}</strong>${r.source_url?`<a class="cx-product-history-link" href="${esc(r.source_url)}" target="_blank" rel="noopener"><small>source</small></a>`:''}</div><div class="cx-product-history-body">${esc(body||'Observed')}</div><div class="cx-product-history-meta">${esc(meta)}</div></div></div>`}

async function render(row){const detail=document.getElementById('cxSealedDetail');if(!detail||!row)return;ensureStyle();detail.querySelector('.cx-product-history')?.remove();const host=document.createElement('section');host.className='cx-product-history';host.innerHTML='<h3>Product history</h3><div class="cx-product-history-note">Creator/official product Signals and market observations for this sealed product.</div><div class="cx-product-history-empty">Loading history…</div>';detail.appendChild(host);const current=++seq;const productId=String(row.tcgplayer_product_id||row.product_id||'').trim(),setCode=String(row.set_code||'').trim();const args=productId?{p_entity_type:'sealed_product',p_product_id:productId,p_set_code:null,p_entity_name:null,p_days:90,p_limit:60}:{p_entity_type:'set',p_product_id:null,p_set_code:setCode||null,p_entity_name:null,p_days:90,p_limit:60};try{const rows=await rest('rpc/ask_collectish_product_timeline_v1',{method:'POST',body:args});if(current!==seq||!host.isConnected)return;const items=compact(rows||[]);host.innerHTML=`<h3>Product history</h3><div class="cx-product-history-note">Creator/official product Signals and market observations. Signal direction is context, not proof of causation.</div>${items.length?`<div class="cx-product-history-list">${items.map(rowHtml).join('')}</div>`:'<div class="cx-product-history-empty">No product-level history captured yet.</div>'}`}catch{if(current!==seq||!host.isConnected)return;host.innerHTML='<h3>Product history</h3><div class="cx-product-history-empty">Product history unavailable.</div>'}}

function onRendered(event){void render(event.detail?.row||null)}
export function installProductHistory(){registerComponent('sealed-product-history',{mount(){document.addEventListener('collectish:sealed-detail-rendered',onRendered)},unmount(){document.removeEventListener('collectish:sealed-detail-rendered',onRendered);seq++}})}
