import { rest } from '../../core/rest.js';

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD'});
const pct=n=>n==null||!Number.isFinite(Number(n))?'—':`${(Number(n)*100).toFixed(0)}%`;
const primaryCategories=new Set(['booster_box','booster_pack','bundle','limited_aid_tool','box_set']);
const knownCk=r=>{const a=Number(r.deterministic_ck_buylist_ev||0),b=Number(r.fixed_ck_buylist_ev||0),v=a+b;return v>0?v:null};
let showAll=false,loading=false,selectedSet='';

function style(){if(document.getElementById('cxSealedFamilyStyle'))return;const s=document.createElement('style');s.id='cxSealedFamilyStyle';s.textContent=`
.cx-sealed-family{margin:0 0 12px;border:1px solid var(--color-border);border-radius:12px;background:var(--color-bg-surface);overflow:hidden}.cx-sealed-family-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:10px 12px;border-bottom:1px solid var(--color-border)}.cx-sealed-family-head strong{font-size:12px}.cx-sealed-family-head span{display:block;font-size:8px;color:var(--color-text-secondary);margin-top:2px}.cx-sealed-family-controls{display:flex;gap:6px;align-items:center}.cx-sealed-family-head button,.cx-sealed-family-head select{font-size:8px;border:1px solid var(--color-border);background:var(--color-bg-primary);border-radius:999px;padding:4px 7px;color:var(--color-text-secondary)}.cx-sealed-family-scroll{overflow:auto}.cx-sealed-family-table{width:100%;border-collapse:collapse;min-width:900px;font-size:8px}.cx-sealed-family-table th,.cx-sealed-family-table td{padding:6px 7px;border-top:1px solid var(--color-border);text-align:right;white-space:nowrap}.cx-sealed-family-table th{font-size:7px;text-transform:uppercase;letter-spacing:.04em;color:var(--color-text-secondary)}.cx-sealed-family-table th:first-child,.cx-sealed-family-table td:first-child{text-align:left;white-space:normal;min-width:220px}.cx-sealed-family-name b{display:block;font-size:9px}.cx-sealed-family-name small{font-size:7px;color:var(--color-text-secondary)}.cx-sealed-family-action,.cx-sealed-family-coverage{font-size:7px;font-weight:900;border:1px solid var(--color-border);border-radius:999px;padding:3px 6px}.cx-sealed-family-action.positive,.cx-sealed-family-coverage.full{color:var(--color-accent)}.cx-sealed-family-note{padding:7px 12px;font-size:7.5px;color:var(--color-text-secondary);border-top:1px solid var(--color-border)}
@media(max-width:700px){.cx-sealed-family{border-radius:10px}.cx-sealed-family-head{padding:9px;display:block}.cx-sealed-family-controls{margin-top:8px}.cx-sealed-family-note{padding:7px 9px}}
`;document.head.appendChild(s)}

function action(r){const market=Number(r.sealed_market_price),gross=Number(r.crack_gross_mean_ev),net=Number(r.crack_net_mean_ev),coverage=String(r.coverage_state||'UNMODELED');if(!r.recommendation_eligible){if(coverage==='COLLATION PARTIAL')return['COLLATION PARTIAL',''];if(coverage==='COMPONENT FLOOR')return['COMPONENT FLOOR',''];if(coverage==='DETERMINISTIC')return['VALUE MODELED',''];return['MODEL PENDING',''];}if(!(market>0))return['VALUE MODELED',''];if(Number.isFinite(net)&&net>=market*1.10)return['BUY & CRACK','positive'];if(Number.isFinite(net)&&net>=market)return['MARGINAL CRACK','positive'];if(Number.isFinite(gross)&&gross>market)return['GROSS EV ONLY',''];return['KEEP SEALED',''];}
function coverageClass(r){return r.coverage_state==='FULL MODEL'||r.coverage_state==='DETERMINISTIC'?'full':''}
function basis(r){const adapter=r.adapter_name||r.adapter_key||'No adapter',reason=r.coverage_reason||'';return `${r.coverage_state||'UNMODELED'} · ${adapter}${reason?` · ${reason}`:''}`}

async function render(){if(loading)return;const host=document.getElementById('cxSealed');if(!host)return;loading=true;try{
  const rows=await rest('sealed_product_model_coverage?select=sealed_uuid,set_code,product_name,category,subtype,release_date,adapter_key,adapter_name,profile_status,coverage_state,recommendation_eligible,coverage_reason,sealed_market_price,sealed_low_price,crack_gross_mean_ev,crack_gross_median_ev,crack_p10_ev,crack_p90_ev,crack_net_mean_ev,crack_break_even_probability,crack_net_break_even_probability,crack_value_basis,crack_value_complete,model_status,modeled_child_components,unmodeled_child_components,deterministic_deck_components,deterministic_ck_buylist_ev,fixed_ck_buylist_ev,unresolved_deck_components,unresolved_pack_components,unresolved_other_components,noncard_extras_excluded&adapter_key=not.is.null&order=set_code.asc,category.asc,product_name.asc');
  let box=document.getElementById('cxSealedFamily');if(!box){box=document.createElement('section');box.id='cxSealedFamily';box.className='cx-sealed-family';const toolbar=host.querySelector('.cx-sealed-toolbar');if(toolbar)host.insertBefore(box,toolbar);else host.appendChild(box)}
  const all=rows||[],sets=[...new Set(all.map(r=>r.set_code).filter(Boolean))];if(!selectedSet||!sets.includes(selectedSet))selectedSet=sets.includes('HOB')?'HOB':sets[0]||'';const family=all.filter(r=>r.set_code===selectedSet),visible=family.filter(r=>showAll||primaryCategories.has(r.category)),eligible=family.filter(r=>r.recommendation_eligible).length,full=family.filter(r=>r.coverage_state==='FULL MODEL'||r.coverage_state==='DETERMINISTIC').length;
  box.innerHTML=`<div class="cx-sealed-family-head"><div><strong>Modeled sealed families · ${esc(selectedSet||'—')}</strong><span>${family.length} products · ${full} complete/deterministic · ${eligible} recommendation eligible · adapter-backed coverage</span></div><div class="cx-sealed-family-controls"><select id="cxSealedFamilySet" aria-label="Sealed set">${sets.map(s=>`<option value="${esc(s)}" ${s===selectedSet?'selected':''}>${esc(s)}</option>`).join('')}</select><button type="button" id="cxSealedFamilyToggle">${showAll?'Primary retail only':'Show cases / decks'}</button></div></div><div class="cx-sealed-family-scroll"><table class="cx-sealed-family-table"><thead><tr><th>Product</th><th>Coverage</th><th>Sealed market</th><th>Gross crack EV</th><th>Median</th><th>Net / realizable</th><th>Known CK buylist</th><th>Gross BE</th><th>Net BE</th><th>Action</th></tr></thead><tbody>${visible.map(r=>{const [a,cls]=action(r);return `<tr><td class="cx-sealed-family-name"><b>${esc(r.product_name)}</b><small>${esc(r.subtype||r.category)} · ${esc(basis(r))}${r.noncard_extras_excluded?' · accessories excluded':''}</small></td><td><span class="cx-sealed-family-coverage ${coverageClass(r)}">${esc(r.coverage_state||'UNMODELED')}</span></td><td>${money(r.sealed_market_price)}</td><td>${money(r.crack_gross_mean_ev)}</td><td>${money(r.crack_gross_median_ev)}</td><td>${money(r.crack_net_mean_ev)}</td><td>${money(knownCk(r))}</td><td>${pct(r.crack_break_even_probability)}</td><td>${pct(r.crack_net_break_even_probability)}</td><td><span class="cx-sealed-family-action ${cls}">${a}</span></td></tr>`}).join('')}</tbody></table></div><div class="cx-sealed-family-note">Coverage is adapter-backed and conservative: FULL MODEL/DETERMINISTIC products may receive recommendations; COLLATION PARTIAL, COMPONENT FLOOR and UNMODELED products do not. Adding a new set now means binding its products to reusable collation adapters plus set-specific slot/pool data rather than adding a new UI or product table.</div>`;
  box.querySelector('#cxSealedFamilyToggle')?.addEventListener('click',()=>{showAll=!showAll;void render()});box.querySelector('#cxSealedFamilySet')?.addEventListener('change',e=>{selectedSet=e.target.value;showAll=false;void render()});
}catch(e){console.warn('sealed family load failed',e)}finally{loading=false}}

export function install(){style();document.addEventListener('collectish:sealed-rendered',()=>void render());if(document.getElementById('cxSealed'))void render()}
