import { rest } from '../../core/rest.js';

let installed=false,seq=0;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const dec=(n,d=3)=>n==null||!Number.isFinite(Number(n))?'—':Number(n).toFixed(d);
const pct=n=>n==null||!Number.isFinite(Number(n))?'—':`${Number(n)>=0?'+':''}${Number(n).toFixed(0)}%`;

function style(){if(document.getElementById('cxSealedSourceCompareStyle'))return;const s=document.createElement('style');s.id='cxSealedSourceCompareStyle';s.textContent=`
.cx-source-compare{margin:16px 0;padding:14px;border:1px solid var(--cx-border,#2a3441);border-radius:14px;background:var(--cx-card,#151b22)}.cx-source-compare h4{margin:0;font-size:15px}.cx-source-compare>p{margin:4px 0 10px;font-size:11px;opacity:.7}.cx-source-product{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:10px}.cx-source-stat{padding:9px;border:1px solid var(--cx-border,#2a3441);border-radius:10px}.cx-source-stat span{display:block;font-size:9px;text-transform:uppercase;opacity:.62}.cx-source-stat b{display:block;font-size:15px;margin-top:2px}.cx-source-scenario{display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin:10px 0;padding:9px;border:1px dashed var(--cx-border,#2a3441);border-radius:10px}.cx-source-scenario label{font-size:9px;text-transform:uppercase;opacity:.7}.cx-source-scenario input{display:block;margin-top:3px;width:120px;padding:7px 8px;border:1px solid var(--cx-border,#2a3441);border-radius:8px;background:var(--cx-bg,#0f151b);color:inherit}.cx-source-scenario strong{font-size:12px}.cx-source-children{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0 11px}.cx-source-child{font-size:10px;border:1px solid var(--cx-border,#2a3441);border-radius:999px;padding:4px 7px}.cx-source-table-wrap{overflow:auto;max-height:520px;border:1px solid var(--cx-border,#2a3441);border-radius:10px}.cx-source-table{border-collapse:collapse;width:100%;min-width:930px;font-size:10px}.cx-source-table th,.cx-source-table td{padding:8px;border-bottom:1px solid var(--cx-border,#2a3441);text-align:right;vertical-align:top}.cx-source-table th:first-child,.cx-source-table td:first-child{text-align:left}.cx-source-table th{position:sticky;top:0;background:var(--cx-card,#151b22);z-index:2;font-size:8px;text-transform:uppercase;letter-spacing:.04em;opacity:.75}.cx-source-card b,.cx-source-lane b{display:block}.cx-source-card small,.cx-source-lane small{display:block;opacity:.62;margin-top:2px;white-space:normal}.cx-source-open{display:inline-block;border:1px solid var(--cx-border,#2a3441);border-radius:8px;padding:5px 7px;text-decoration:none;color:var(--cx-accent,#5aa2ff);font-weight:800;white-space:nowrap}.cx-source-positive{color:#16713a}.cx-source-caveat{font-size:9px;opacity:.64;margin-top:8px;line-height:1.4}.cx-mixed-route-warning{margin:8px 0;padding:8px 10px;border:1px solid rgba(235,171,50,.32);background:rgba(235,171,50,.09);border-radius:9px;font-size:10px;line-height:1.35}@media(max-width:760px){.cx-source-product{grid-template-columns:1fr 1fr}.cx-source-compare{padding:11px}}
`;document.head.appendChild(s)}
function scoutHref(r){const u=new URL(location.href);['sealed','q','status','settype','lang','buylist_backed'].forEach(k=>u.searchParams.delete(k));u.searchParams.set('tab','scout');if(r.sku_id)u.searchParams.set('sku',r.sku_id);else{u.searchParams.set('card',r.card_name||'');u.searchParams.set('set',r.card_set_code||'');u.searchParams.set('finish',r.finish||'')}return `${u.pathname}?${u.searchParams.toString()}${u.hash}`}
function stat(label,value,sub=''){return `<div class="cx-source-stat"><span>${esc(label)}</span><b>${value}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function rowsHtml(rows){return rows.slice(0,80).map(r=>`<tr data-source-row data-base-alloc="${Number(r.ev_allocated_acquisition_per_copy||0)}" data-direct="${Number(r.direct_buy_price||r.buy_direct_reference||0)}"><td class="cx-source-card"><b>${esc(r.card_name)}</b><small>${esc(r.card_set_code||'')} #${esc(r.collector_number||'—')} · ${esc(r.finish||'')}</small></td><td class="cx-source-lane"><b>${money(r.direct_buy_price||r.buy_direct_reference)}</b><small>best observed single acquisition</small></td><td class="cx-source-lane"><b data-scenario-alloc>${money(r.ev_allocated_acquisition_per_copy)}</b><small>${dec(r.expected_copies,4)} expected copies · EV-allocated cost / copy</small></td><td class="cx-source-lane"><b>${money(r.best_modeled_exit_net||r.market_exit_net_reference)}</b><small>${money(r.expected_exit_contribution)} expected product contribution</small></td><td class="cx-source-lane ${Number(r.crack_advantage_vs_direct_pct||0)>0?'cx-source-positive':''}" data-scenario-adv-cell><b data-scenario-adv>${pct(r.crack_advantage_vs_direct_pct)}</b><small>${money(r.crack_allocated_profit_per_copy)} base allocated profit / copy</small></td><td><a class="cx-source-open" href="${esc(scoutHref(r))}">Open in Scout</a></td></tr>`).join('')}
function applyScenario(box,market){const input=box.querySelector('[data-source-acquisition]'),price=Number(input?.value);const acquisition=Number.isFinite(price)&&price>0?price:market,ratio=market>0?acquisition/market:1;box.querySelectorAll('[data-source-row]').forEach(tr=>{const base=Number(tr.dataset.baseAlloc||0),direct=Number(tr.dataset.direct||0),alloc=base*ratio,adv=direct>0&&alloc>0?100*(direct-alloc)/direct:null;tr.querySelector('[data-scenario-alloc]').textContent=money(alloc);tr.querySelector('[data-scenario-adv]').textContent=pct(adv);tr.querySelector('[data-scenario-adv-cell]')?.classList.toggle('cx-source-positive',Number(adv)>0)});const net=Number(box.dataset.netEv||0),gross=Number(box.dataset.grossEv||0),roi=acquisition>0&&net>0?100*(net-acquisition)/acquisition:null,grossRoi=acquisition>0&&gross>0?100*(gross-acquisition)/acquisition:null;const out=box.querySelector('[data-source-scenario-summary]');if(out)out.textContent=`Net ${pct(roi)} · Gross ${pct(grossRoi)} vs ${money(acquisition)}`}
function guardMixed(children){if(!children?.length)return;const apply=()=>{const out=document.querySelector('#cxSealedDetail .cx-out-opt');if(!out)return false;const h=out.querySelector('h4');if(h)h.textContent='Fixed-card Out Optimization';let w=out.querySelector('.cx-mixed-route-warning');if(!w){w=document.createElement('div');w.className='cx-mixed-route-warning';w.innerHTML='<strong>Mixed sealed product:</strong> this routing table covers fixed cards only. Booster EV and booster-derived Singles are included in Source Compare above.';out.querySelector('.cx-out-opt-head')?.insertAdjacentElement('afterend',w)}return true};if(apply())return;[60,180,420].forEach(ms=>setTimeout(apply,ms))}
async function render(event){const run=++seq,id=event?.detail?.id;if(!id)return;const detail=document.getElementById('cxSealedDetail');if(!detail)return;detail.querySelector('.cx-source-compare')?.remove();try{
  const [family,children,cards]=await Promise.all([
    rest(`sealed_product_family_economics?select=sealed_market_price,crack_gross_mean_ev,crack_gross_median_ev,crack_net_mean_ev,crack_value_complete&sealed_uuid=eq.${encodeURIComponent(id)}&limit=1`),
    rest(`sealed_product_child_components?select=child_product_name,quantity,component_type&parent_sealed_uuid=eq.${encodeURIComponent(id)}&order=child_product_name.asc`),
    rest(`sealed_single_source_compare_current?select=card_name,card_set_code,collector_number,finish,tcgplayer_product_id,sku_id,expected_copies,buy_direct_reference,direct_buy_price,sealed_market_price,naive_sealed_spend_per_expected_copy,ev_allocated_acquisition_per_copy,market_exit_net_reference,best_modeled_exit_net,expected_exit_contribution,crack_advantage_vs_direct_pct,crack_allocated_profit_per_copy,source_kind&sealed_uuid=eq.${encodeURIComponent(id)}&order=expected_exit_contribution.desc&limit=80`)
  ]);if(run!==seq)return;const f=family?.[0];if(!f&&!cards?.length)return;const market=Number(f?.sealed_market_price||cards?.[0]?.sealed_market_price||0),childHtml=(children||[]).map(c=>`<span class="cx-source-child">${Number(c.quantity||0).toLocaleString()} × ${esc(c.child_product_name)}</span>`).join('');
  const html=`<section class="cx-source-compare" data-no-detail-swipe data-gross-ev="${Number(f?.crack_gross_mean_ev||0)}" data-net-ev="${Number(f?.crack_net_mean_ev||0)}"><h4>Source Compare</h4><p>Buy the printing directly vs source it through this sealed product vs take the best modeled market exit.</p>${f?`<div class="cx-source-product">${stat('Sealed market',money(f.sealed_market_price))}${stat('Gross crack EV',money(f.crack_gross_mean_ev))}${stat('Net modeled EV',money(f.crack_net_mean_ev),f.crack_value_complete?'card model complete':'partial card model')}${stat('Median',money(f.crack_gross_median_ev),'distribution models only')}</div>`:''}<div class="cx-source-scenario"><label>Your acquisition price<input type="number" min="0" step="0.01" value="${market||''}" data-source-acquisition></label><strong data-source-scenario-summary></strong></div>${childHtml?`<div class="cx-source-children">${childHtml}</div>`:''}${cards?.length?`<div class="cx-source-table-wrap"><table class="cx-source-table"><thead><tr><th>Single</th><th>Buy direct</th><th>Crack sealed</th><th>Best exit</th><th>Crack advantage</th><th></th></tr></thead><tbody>${rowsHtml(cards)}</tbody></table></div>`:'<div class="cx-source-caveat">No derived Singles are modeled for this product yet.</div>'}<div class="cx-source-caveat">Change acquisition price to model a store deal, distributor price or overseas landed cost. Allocated card cost scales with the sealed acquisition price; pull probabilities and expected contents do not change.</div></section>`;
  const out=detail.querySelector('.cx-out-opt'),econ=detail.querySelector('.cx-section-title.cx-sealed-econ-title');if(out)out.insertAdjacentHTML('beforebegin',html);else if(econ)econ.insertAdjacentHTML('beforebegin',html);else detail.insertAdjacentHTML('beforeend',html);const box=detail.querySelector('.cx-source-compare');box?.querySelector('[data-source-acquisition]')?.addEventListener('input',()=>applyScenario(box,market));if(box)applyScenario(box,market);guardMixed(children);
}catch(e){console.warn('[sealed source compare]',e)}}
export function installSourceCompare(){if(installed)return;installed=true;style();document.addEventListener('collectish:sealed-detail-rendered',render)}
