import { rest } from '../../core/rest.js';

let installed=false,seq=0;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>n==null||n===''||!Number.isFinite(Number(n))?'—':Number(n).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const dec=(n,d=3)=>n==null||!Number.isFinite(Number(n))?'—':Number(n).toFixed(d);

function style(){if(document.getElementById('cxSealedSourceCompareStyle'))return;const s=document.createElement('style');s.id='cxSealedSourceCompareStyle';s.textContent=`
.cx-source-compare{margin:16px 0;padding:14px;border:1px solid var(--cx-border,#2a3441);border-radius:14px;background:var(--cx-card,#151b22)}.cx-source-compare h4{margin:0;font-size:15px}.cx-source-compare>p{margin:4px 0 10px;font-size:11px;opacity:.7}.cx-source-product{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:10px}.cx-source-stat{padding:9px;border:1px solid var(--cx-border,#2a3441);border-radius:10px}.cx-source-stat span{display:block;font-size:9px;text-transform:uppercase;opacity:.62}.cx-source-stat b{display:block;font-size:15px;margin-top:2px}.cx-source-children{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0 11px}.cx-source-child{font-size:10px;border:1px solid var(--cx-border,#2a3441);border-radius:999px;padding:4px 7px}.cx-source-table-wrap{overflow:auto;max-height:520px;border:1px solid var(--cx-border,#2a3441);border-radius:10px}.cx-source-table{border-collapse:collapse;width:100%;min-width:820px;font-size:10px}.cx-source-table th,.cx-source-table td{padding:8px;border-bottom:1px solid var(--cx-border,#2a3441);text-align:right;vertical-align:top}.cx-source-table th:first-child,.cx-source-table td:first-child{text-align:left}.cx-source-table th{position:sticky;top:0;background:var(--cx-card,#151b22);z-index:2;font-size:8px;text-transform:uppercase;letter-spacing:.04em;opacity:.75}.cx-source-card b{display:block;font-size:11px}.cx-source-card small{display:block;opacity:.62;margin-top:2px}.cx-source-lane b{display:block}.cx-source-lane small{display:block;opacity:.62;margin-top:2px;white-space:normal}.cx-source-open{display:inline-block;border:1px solid var(--cx-border,#2a3441);border-radius:8px;padding:5px 7px;text-decoration:none;color:var(--cx-accent,#5aa2ff);font-weight:800;white-space:nowrap}.cx-source-caveat{font-size:9px;opacity:.62;margin-top:8px;line-height:1.4}@media(max-width:760px){.cx-source-product{grid-template-columns:1fr 1fr}.cx-source-compare{padding:11px}}
`;document.head.appendChild(s)}
function scoutHref(r){const u=new URL(location.href);['tab','sealed','q','status','settype','lang','buylist_backed'].forEach(k=>u.searchParams.delete(k));u.searchParams.set('product',r.tcgplayer_product_id||'');u.searchParams.set('card',r.card_name||'');u.searchParams.set('set',r.card_set_code||'');u.searchParams.set('finish',r.finish||'');return `${u.pathname}?${u.searchParams.toString()}${u.hash}`}
function stat(label,value,sub=''){return `<div class="cx-source-stat"><span>${esc(label)}</span><b>${value}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function rowsHtml(rows){return rows.map(r=>`<tr><td class="cx-source-card"><b>${esc(r.card_name)}</b><small>${esc(r.card_set_code||'')} #${esc(r.collector_number||'—')} · ${esc(r.finish||'')}</small></td><td class="cx-source-lane"><b>${money(r.buy_direct_reference)}</b><small>single-card market reference</small></td><td class="cx-source-lane"><b>${dec(r.expected_copies,4)} exp.</b><small>${money(r.naive_sealed_spend_per_expected_copy)} naive spend / expected copy</small></td><td class="cx-source-lane"><b>${money(r.market_exit_net_reference)}</b><small>${money(r.expected_exit_contribution)} expected product contribution</small></td><td><a class="cx-source-open" href="${esc(scoutHref(r))}">Open in Singles</a></td></tr>`).join('')}
async function render(event){const run=++seq,id=event?.detail?.id;if(!id)return;const detail=document.getElementById('cxSealedDetail');if(!detail)return;detail.querySelector('.cx-source-compare')?.remove();try{
  const [family,children,cards]=await Promise.all([
    rest(`sealed_product_family_economics?select=sealed_market_price,crack_gross_mean_ev,crack_gross_median_ev,crack_net_mean_ev,crack_value_complete&sealed_uuid=eq.${encodeURIComponent(id)}&limit=1`),
    rest(`sealed_product_child_components?select=child_product_name,quantity,component_type&parent_sealed_uuid=eq.${encodeURIComponent(id)}&order=child_product_name.asc`),
    rest(`sealed_single_source_compare_current?select=card_name,card_set_code,collector_number,finish,tcgplayer_product_id,expected_copies,buy_direct_reference,sealed_market_price,naive_sealed_spend_per_expected_copy,market_exit_net_reference,expected_exit_contribution,source_kind&sealed_uuid=eq.${encodeURIComponent(id)}&order=expected_exit_contribution.desc&limit=60`)
  ]);if(run!==seq)return;const f=family?.[0];if(!f&&!cards?.length)return;
  const childHtml=(children||[]).map(c=>`<span class="cx-source-child">${Number(c.quantity||0).toLocaleString()} × ${esc(c.child_product_name)}</span>`).join('');
  const html=`<section class="cx-source-compare" data-no-detail-swipe><h4>Source Compare</h4><p>Compare buying a single directly, acquiring it probabilistically by cracking this sealed product, and the modeled market exit.</p>${f?`<div class="cx-source-product">${stat('Sealed market',money(f.sealed_market_price))}${stat('Gross crack EV',money(f.crack_gross_mean_ev))}${stat('Net modeled EV',money(f.crack_net_mean_ev),f.crack_value_complete?'card model complete':'partial card model')}${stat('Median',money(f.crack_gross_median_ev),'distribution models only')}</div>`:''}${childHtml?`<div class="cx-source-children">${childHtml}</div>`:''}${cards?.length?`<div class="cx-source-table-wrap"><table class="cx-source-table"><thead><tr><th>Single</th><th>Buy directly</th><th>Crack sealed</th><th>Market exit</th><th></th></tr></thead><tbody>${rowsHtml(cards)}</tbody></table></div>`:'<div class="cx-source-caveat">No probabilistic single-card compare rows are cached for this product yet.</div>'}<div class="cx-source-caveat">“Naive spend / expected copy” is sealed acquisition divided by expected copies of that target printing. It deliberately does not call that the card's effective cost because every crack also produces other cards. Expected product contribution is the better portfolio-level comparison. Market exit is currently a conservative 75% of the stored single-card market reference; the next layer will replace this with the full outlet optimizer.</div></section>`;
  const out=detail.querySelector('.cx-out-opt'),econ=detail.querySelector('.cx-section-title.cx-sealed-econ-title');if(out)out.insertAdjacentHTML('beforebegin',html);else if(econ)econ.insertAdjacentHTML('beforebegin',html);else detail.insertAdjacentHTML('beforeend',html);
}catch(e){console.warn('[sealed source compare]',e)}}
export function installSourceCompare(){if(installed)return;installed=true;style();document.addEventListener('collectish:sealed-detail-rendered',render)}
